### ISSUE TITLE
Typescript returned type for Element.width() and Element.height() incorrect

### ISSUE THREAD

**Issue by maxailloud** [svgdotjs/svg.js#1001]
# Bug report

## Fiddle

On the last tagged version, 3.0.12, the Typescript definition file is stating that `Element.width()` and `Element.height` are suppose to return a number. In practice it's returning a string, so for example `400px` instead of `400`.

## Explanation

No matter the type of the value we get, the Typescript definition should match it.

**Comment by maxailloud** [comment]
The issue is still present.

**Comment by Fuzzyma** [comment]
Its on the list

**Comment by maxailloud** [comment]
Perfect thank you.
