### ISSUE TITLE
Typescript parameter type for event method should be optional to accept null/undefined

### ISSUE THREAD

**Issue by maxailloud** [svgdotjs/svg.js#1002]
# Bug report

## Explanation

Adding or removing an event on an Element uses the same method, just with or without the callback Function.
When removing the event we pass null (or undefined) to this method. The Typescript typings doesn't allow us to do it as it's typed as `mousemove(cb: Function): this;` as it should be `mousemove(cb?: Function): this;`.
And that for all events.

**Comment by Fuzzyma** [comment]
Mh, not really optional but explicitely null should be added here. Feel free to create a PR!

**Comment by maxailloud** [comment]
Yes you are right. It's null and not optional.
It is planned it is planned.

Typescript definition file is not auto-generated right?

**Comment by Fuzzyma** [comment]
> It is planned it is planned.

Wut? :D

No the d.ts file is made by hand so feel free to change it!

**Comment by maxailloud** [comment]
It is planned to do a PR i meant^^.

Ok perfect. I think I will do today, and if not will be next week.
