### ISSUE TITLE
New tag to include last fixes

### ISSUE THREAD

**Issue by maxailloud** [svgdotjs/svg.js#1005]
Is it possible to get a new tag of the package to include the last fixes?
Better than using master branch.

**Comment by maxailloud** [comment]
I think that it's why I have an issue with the draggable function not being available in my build prod https://github.com/svgdotjs/svg.draggable.js/issues/109.

**Comment by Fuzzyma** [comment]
It's planned but blocked by failing tests due to the last pr. At that time the tests were passing and I am not sure why that happened. However we have to fix that first

**Comment by maxailloud** [comment]
https://travis-ci.org/svgdotjs/svg.js Looks good to me.
Is there other tests somewhere else?

**Comment by Fuzzyma** [comment]
It failed locally on my pc when I last tested and that cannot happen... See the last (non typescript related) pr for more Infos

**Comment by maxailloud** [comment]
If you are talking about this one https://travis-ci.org/svgdotjs/svg.js/builds/518939947 It looks like the issue was on github side, or something like this, but not code related as it was a change on the CHANGELOG file.

**Comment by Fuzzyma** [comment]
This one: https://github.com/svgdotjs/svg.js/pull/992

**Comment by maxailloud** [comment]
Ok I see.

**Comment by Fuzzyma** [comment]
finally done in 3.0.13
