### ISSUE TITLE
Subtracting shapes

### ISSUE THREAD

**Issue by natew** [svgdotjs/svg.js#1006]
# Feature request

## **Example**

I'm looking to replicate this:

![image](https://user-images.githubusercontent.com/12100/58821034-00466b80-85e9-11e9-9c1b-9fc04b39e862.png)

But where the "+" is actually cut out from the background shape. I looked at paper.js and while it has "intersect" and "subtract", they don't seem to actually merge the shapes into a single path (at least in my early attempts). Instead it seemed to just draw the "above" path in whatever color the canvas background is, and when I exported to SVG, it was still two shapes with colors.

### Benefits

You could generate nice svg icons that actually have "see through" aspects.

It would be a lot like clipping I imagine, but instead be something like `subtract`.

https://jsfiddle.net/scdvjuka/13/

**Comment by natew** [comment]
After googling, I do see that this is really quite simple to achieve:

https://stackoverflow.com/questions/3742479/how-to-cut-a-hole-in-an-svg-rectangle

https://jsfiddle.net/scdvjuka/14/

Though I guess with svg.js you can take advantage of centering more easily.

**Comment by saivan** [comment]
This is something I've wanted for a while too, but the calculations are not trivial at all. Hopefully we will get to this someday :P But we'd accept prs if you'd like to try your hand. This would definitely be a plugin rather than a core feature though.

**Comment by Fuzzyma** [comment]
Isnt this just clockwise and anticlockwise drawing of shapes?

**Comment by saivan** [comment]
I was hoping to actually implement boolean operations on a path level at some point. So given two svg paths (or their d strings), produce the sum, subtraction, etc... We've had that request a few times I believe.

**Comment by saivan** [comment]
Closing in favor of #654 since it will be implemented there eventually
