### ISSUE TITLE
Perf Question on draw.text() function

### ISSUE THREAD

**Issue by besstiolle** [svgdotjs/svg.js#1008]
During perf test on my project i found something weird

8000 draw.rect().fill().move().stroke().radius() +  16000 draw.polyline().[...]() => 647ms

If you add 8000 draw.text("some random data") => 47 874ms
If you add instead 8000 draw.text("some random data").move(randomX, randomY) => 74 280ms

It's quite a huge difference. 

Did i miss something ?
Is it possible that there is some perf killer in the code of draw.text() ?
Are you already aware of this state and nothing can be made currently ?

Thank you by advance for your answer and your amazing work on this project !

**Comment by Fuzzyma** [comment]
Creating a rectangle or polygon just creates a node and sets a few attributes.
Creating text creates a text node and tspan nodes for every line. It might as well be true that rendering text is more expensive for the browser. Beside that, its still a huge difference.
When you move text around, a bbox call is made which is expensive. Also every tspan must be moved to reflect the new x. So that is more reasonable

**Comment by besstiolle** [comment]
Thank you Fuzzyma.

If there is no possibility to gain some perf in svg.js, have you any idea to reduce the impact of my own code ? (i imagined some cloning tricks)

**Comment by Fuzzyma** [comment]
Sure cloning should make a difference. Beside that you can use plain() which only creates a single line and no multi-line.
You can also try to pass a builder function to text which gives you more control about how the text is created and might speed it up - but that's just a guess

**Comment by besstiolle** [comment]
I'll take a look at all yours ideas. I'll give you a feedback as soon as possible.

**Comment by besstiolle** [comment]
After some tests, here my conclusion.

plain() is much more accurate for my need and is really quick.

As i have A LOT of elements to render in my svg i also put some "real time" rendering in my process instead of waiting the end of rendering.

At this point i didn't made any test on your advices : cloning & passing a builder function.

Thank you for your help, i'll close this ticket :)
