### ISSUE TITLE
anyone wanna build opensource https://www.image-map.net/ because it's on point but the js there is obfuscated.

### ISSUE THREAD

**Issue by ladoc** [svgdotjs/svg.js#1013]

**Comment by ladoc** [comment]
sorry, cant do that? why?

**Comment by Fuzzyma** [comment]
Your post is neither a bug report nor a feature request. This is an issue tracker and no platform for seeking personnel. For this purpose try a freelancing platform or ask per Mail/Chat/etc

**Comment by ladoc** [comment]
Understood, might you know someone or someplace I can find collaborators?
