### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by radman0x** [svgdotjs/svg.js#1014]
Just tried to start using svg.js today for a project and got caught up in a spiral of incorrect versions due to inconsistencies in the official documentation / websites / npm / github.

The [official installation steps](https://svgjs.com/docs/2.7/installation/), say to do `npm install svg.js` this appears to be an old (deprecated?) [package](https://www.npmjs.com/package/svg.js). This is at v2.7 which corresponds with the official documentation on `svgjs.com`.  There is also a straight svgjs npm package which was last published 2 years ago.

I was all good following the documentation until I tried to install and use the svgjs.draggable plugin which uses this project and version and my spiral began... So it looks like the official version is still 2.7 but 3 is under active development?

Thought I'd post this to give an outsiders view to using the library for the first time. I'd recommend you put deprecation warnings on either of the mentioned npm packages explaining the situation so time isn't wasted (or probably a good percentage of devs just giving up). 

Do with this what you will. I've got v3 working and it's really nice with TypeScript, imports work etc so good work on that front :+1:

**Comment by saivan** [comment]
Thanks for the notice. You're right. We are way too busy to add documentation these days. v3 is done but the documentation is totally out of date. We would love any help getting the documentation up to date. But we recommend looking at the changelog for most of the changes. We will get to it once our schedules are a little more free

**Comment by Fuzzyma** [comment]
docs are updated now
