### ISSUE TITLE
support registerWindow for typescript  in svg.js.d.ts

### ISSUE THREAD

**Issue by seuliang** [svgdotjs/svg.js#1015]
miss function registerWindow  in  svg.js.d.ts for typescript

**Comment by Fuzzyma** [comment]
feel free to add it :)

**Comment by larshp** [comment]
I have the same problem with latest 3.0.16 published a year ago

https://github.com/svgdotjs/svg.js/blob/master/svg.js.d.ts looks okay, only thing missing is to publish a new version?
