### ISSUE TITLE
svg.js 3 doesn't work 

### ISSUE THREAD

**Issue by feixiang001** [svgdotjs/svg.js#1018]
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title></title>
		<script type="text/javascript" src="svg.js" ></script>
	</head>
	<body>
		<div id="drawing"></div>
		<script>
               var rect = SVG().addTo('#drawing')
		</script>
	</body>
</html>

"Uncaught TypeError: undefined is not a function"

**Comment by Fuzzyma** [comment]
Create a jsfiddle that shows the problem

**Comment by feixiang001** [comment]
it's ok!  my Chrome version is too low;
