### ISSUE TITLE
Function `SVG` is null

### ISSUE THREAD

**Issue by torkleyy** [svgdotjs/svg.js#1021]
# Bug report

In the 3.0 version, it seems that `SVG("some-id")` no longer works (it's `null`). This can be reproduced by using the example on the website: https://svgjs.com/docs/3.0/getting-started/#create-an-svg-document

## Fiddle

https://jsfiddle.net/torkleyy/m2kLyzxw/2/

## Explanation

- What is the behaviour you expect?

The `SVG` function creates a new `Svg`, and injects it into the HTML.

- What is happening instead?

The function is `null`, and cannot be used.

- What error message are you getting?

```
TypeError: SVG(...) is null
```

**Comment by Fuzzyma** [comment]
Use `SVG('#id')` instead to get an element and `SVG().addTo('#id')` to create a new document and attach it to an element in the dom

**Comment by torkleyy** [comment]
Thank you!

**Comment by torkleyy** [comment]
I've created a PR to fix this in the guide: https://github.com/svgdotjs/svgdotjs.github.io/pull/78

**Comment by Fuzzyma** [comment]
Thanks! Not sure if I can easily merge it though... One could say it's... Complicated 😅

**Comment by frozar** [comment]
As I'm discovering SVG.js, this issue is really relevant for me ^^'

**Comment by Fuzzyma** [comment]
done
