### ISSUE TITLE
draw.image(...).loaded is not a function

### ISSUE THREAD

**Issue by notchris** [svgdotjs/svg.js#1024]
# Bug report

## Fiddle
[Fiddle Example](https://jsfiddle.net/notchris/s4vkqnfu/21/)

## Info
- Error on using 'loaded' function for draw.image(...).loaded()
- Using @svgdotjs/svg.js v3.0.13
- Other elements work

**Comment by notchris** [comment]
This issue is still occurring.

**Comment by notchris** [comment]
Note: In some cases, the image does load and is visible, the error persists.

**Comment by Fuzzyma** [comment]
Sorry for the long delay. Currenty writing on my diploma.
The syntax changed from what it was in 2.x. You now pass the callback as second parameter to the image function:

```js
canvas.images(url, function () {

})
```

More info (well not really) is here: https://github.com/svgdotjs/svgdotjs.github.io/issues/41

**Comment by notchris** [comment]
Thank you @Fuzzyma I really do appreciate your work and let me know if I can support this project in any way. Currently working on some plugins for v3 myself :)

**Comment by notchris** [comment]
Oh also @Fuzzyma to evade confusion in your response, the fix was (there was an extra 's' above):

`canvas.image(url,  () => {

})`

**Comment by Fuzzyma** [comment]
Thanks :). I will let you know when I am back on track and have stuff to do :). Actually there is always something to do but it's hard to a new contributer to deep dive into these issues
