### ISSUE TITLE
Svg.defs() can fail to attach the <defs> node to the DOM when using addTo

### ISSUE THREAD

**Issue by Lange** [svgdotjs/svg.js#1028]
# Bug report

When using `.addTo` to add the SVG root to the DOM, `Svg.defs()` can fail to attach the resulting `<defs>` node to the DOM, preventing anything it from working.

## Fiddle

https://jsfiddle.net/nk8w640x/

## Explanation

- What is the behaviour you expect?
  - Using `.addTo` should not change the behavior of other instance methods such as `.defs()`
- What is happening instead?
  - `.defs()` seems to stop working when using `.addTo()`
- What error message are you getting?
  - Usually, there's no error message, the `<defs>` node simply doesn't get added to the DOM.

As far as I can tell, the root issue is at this call to `.put()`: https://github.com/svgdotjs/svg.js/blob/b1c31462b498ee50e8ed3a88b07ad4a302431d32/src/elements/Svg.js#L46

This call omits the second argument, making it `undefined`. However, it seems that `put` is expecting `null` for this scenario. As a result, it does nothing with the `Defs` instance passed in. A potential fix may be to amend this call site to pass `null` as the second argument.

## Closing
I'm not sure that my explanation and understanding of this problem is fully correct, as Svg.js is a complex codebase and I could only spend about 30 minutes trying to understand this problem. However, it seems very likely that the `.put()` callsite linked under `Explanation` is indeed the problem.

**Comment by Fuzzyma** [comment]
Sorry for coming back to this so late. I actually cannot see the problem. The defs note is properly added to the dom. However, in your fiddle the call to `filter()` fails because the filter plugin wasnt added.

**Comment by Lange** [comment]
Oh sorry, totally forgot I filed this. The issue was actually just this: https://github.com/svgdotjs/svg.filter.js/issues/41

It's fixed when using that new release of `svg.filter.js`.
