### ISSUE TITLE
how to use these plugins(svg.js 3.0.13 , svg.select.js 3.0.1 , svg.resize.js1.4.3) to select and resize

### ISSUE THREAD

**Issue by guerxingGit** [svgdotjs/svg.js#1031]
It works fine before using svg.js v2.7.1
demo:
var draw = SVG('myDrawing').size(600, 600)
var rect = draw.rect(100, 100).attr({ fill: '#f06' })
rect.selectize().resize();

but using svg.js v3.0.13,this has issue( this.rectSelection.set = this.rectSelection.set || this.parent.set();)
demo:
var drawing = SVG().addTo('#myDrawing').size(500, 500);
var r1 = drawing.rect(50, 50);
//var r2 = drawing.group();          
//r2.add(r1);
r1.selectize().resize();
 
I'm looking forward to your help. Thank you.

**Comment by guerxingGit** [comment]
These plugins work well together
svg.js 2.7, svg.select.js 3.0.1 , svg.resize.js1.4.3,svg.draggy.js（not svg.draggable.js） svg.connectable.js

**Comment by valentinbourqui** [comment]
So svg.select.js isn't compatible with svg.js 3.x ?

**Comment by Fuzzyma** [comment]
correct. there is a branch with recent development but its not released yet

**Comment by valentinbourqui** [comment]
I think you should update your plugins list inside your documentation 3.0 because he is specified as avaliable for this version and that's not true. May be there are others plugins with the same problem.

**Comment by Fuzzyma** [comment]
docs were updated for 3.0 today
