### ISSUE TITLE
Position isn't correct from element in imported svg

### ISSUE THREAD

**Issue by chrille112** [svgdotjs/svg.js#1033]
version 3.0.13

I'm importing svg markup to my canvas. In this markup I have red rectangle. I get the red rectangle by id and I'm drawing a blue rectangle at it's position. Problem is that the position isn't matching, see this fiddle: https://jsfiddle.net/4p1u3gar/

**Comment by chrille112** [comment]
If I change the size of the canvas to be the same as my SVG code, it works as expected;

`const draw = SVG().addTo("#canvas").size(423, 247);`

How can I find the scaling factor used to recalculate the position? Or is this a bug?

**Comment by Fuzzyma** [comment]
Its not a bug. You are creating a new svg document and add a rectangle and move it to the coordinates you got from a different svg (which has a viewbox applied to it).
The new svg does not have that viewbox. Viewboxes scale and translate the contents of an svg. So whatever coordinates you get from the original svg do not match the new ones.
You can try to use `myArea.rbox(newSVG)` to get the coordinates transformed into the newSVG. rbox will give you a box with x, y, width and height

**Comment by chrille112** [comment]
@Fuzzyma  Thanks, `rbox` fixed it :) 
https://jsfiddle.net/aoqvt7se/
