### ISSUE TITLE
Runnerj.js -> Module parse failed: Unexpected Token

### ISSUE THREAD

**Issue by nashfx** [svgdotjs/svg.js#1034]
### Angular 8.0

This only happens when I make a build for production (ng build --prod).

This is the error itself:
```
ERROR in ./node_modules/@svgdotjs/svg.js/src/animation/Runner.js 16:15
Module parse failed: Unexpected token (16:15)
You may need an appropriate loader to handle this file type.
| import SVGNumber from '../types/SVGNumber.js';
| import Timeline from './Timeline.js';
> export default const Runner = /*@__PURE__*/ (() => {
|     class Runner extends EventTarget {
|         constructor(options) {
```

Weird thing is that Runner.js does not have anything in line 16:

Runner.js

```
import Point from '../types/Point.js'
import SVGNumber from '../types/SVGNumber.js'
import Timeline from './Timeline.js'

export default class Runner extends EventTarget {
  constructor (options) {
    super()
... 
```

I don't know what to do or how to continue in this case

regards

**Comment by saivan** [comment]
So I can't be sure what kind of steps you're using for the build, but this looks like the problem has occured after you've run Runner through babel (or a similar tool). If this is still a problem, just check your build :)

**Comment by Fuzzyma** [comment]
I added a transpiled esm bundle in the recent version. That shoud fix the problem. It should be used by the bundler automatically
