### ISSUE TITLE
Unable to load tutorials for 3.0 version

### ISSUE THREAD

**Issue by Dmitrijsmok** [svgdotjs/svg.js#1035]
# Bug report
3.0 version does not support tutorial samples

## Fiddle

https://jsfiddle.net/dotnetCarpenter/vceakozz/?utm_source=website&utm_medium=embed&utm_campaign=vceakozz

## Explanation

- it works only for version 2.5.0
- after changing the version graphics disappear

**Comment by saivan** [comment]
Yep the api has changed sufficiently that many of our examples no longer work.
The upside is that it's generally easier to do most of these things now,
The downside is that all of the maintainers barely have enough time to update the docs.
Sorry about the inconvenience

**Comment by Fuzzyma** [comment]
Docs are updated now. I also added some examples. Feel free to have a look!
