### ISSUE TITLE
Answer on TODO in color.js

### ISSUE THREAD

**Issue by renevanderlende** [svgdotjs/svg.js#1037]
In 'color.js', row 180 you say 'TODO I have no idea what this does :D If you figure it out, tell me!'

Well, I don't have a definitive answer for you, but near the end of document [wikipedia: Comparison of color models in computer graphics](https://en.wikipedia.org/wiki/Comparison_of_color_models_in_computer_graphics) paragraph 'HSL' you will find an explanantion of, what I think, the 0.5 value you (and B. Grinstead) use in your JS at line 181. Read [wikipedia: HSL and HSV](https://en.wikipedia.org/wiki/HSL_and_HSV) paragraphs 'Hue and chroma', 'Lightness' and 'Saturation' for the used HSL/V math.

I hope this will shed some light on the matter.

Finally, I found [Color FAQ](http://poynton.ca/notes/colour_and_gamma/ColorFAQ.html) very enlightning on the subject of color in general.

Cheers,
Rene

P.S.: [CSS Color Module Level 4, Editor’s Draft, 9 August 2019](https://drafts.csswg.org/css-color/) [paragraph 16 Sample code for color conversions](https://drafts.csswg.org/css-color/#color-conversion-code) has a nice bundle of extra color conversion JS ready to use. Make sure to check it out.

**Comment by saivan** [comment]
Wow, I really appreciate you taking the time to actually respond to me :P 
I didn't spend too much time looking into it at the time,
but it looks like we have some weekend reading.

Thanks for that :)
Feel free to make a pr with an explanatory comment if you want.

**Comment by saivan** [comment]
Awesome, so I've read up. I'll go ahead and close the issue but leave it as reference for anybody who might come across it in the future. Thanks again @renevanderlende
