### ISSUE TITLE
IE 10 draw.text('test') error

### ISSUE THREAD

**Issue by sammiewy** [svgdotjs/svg.js#1038]
I use the latest version 3.0.13.
run the following code:
`
 draw.text('test')；
`
in IE brower. it shows  a error.

I try to find  the cause is these code:
`
children () {
    return new List(map(this.node.children, function (node) {
      return adopt(node)
    }))
  }
`
in Dom.js file. 

IE brower "this.node.children" return "undefined"
in other brower  return  a array.

I'm looking forward to your help. Thank you.

**Comment by Shrumpf** [comment]
I got the same problem and included the polyfill from MDN

https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/children

after I included it I got the next error, so I had to add another polyfill from here: 

https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/CustomEvent

Probably not a good solutions but it works.

**Comment by Fuzzyma** [comment]
@sammiewy sorry for not coming back on that for so long. There are actually polyfills in every release and on npm. Just include `dist/polyfills.js` and `dist/polyfillsIE.js` in your application
