### ISSUE TITLE
SVG.supported is undefined.

### ISSUE THREAD

**Issue by sesky4** [svgdotjs/svg.js#1039]
# Bug report

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

Modify [this fiddle](https://jsfiddle.net/Fuzzy/s06mfv5u/) to demonstrate the problem clearly, just fork it and paste the resulting fiddle in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behaviour you expect?
  Include the lastest release of svg.js/svg.min.js(3.0.13)
  console.log(SVG.supported);
  SVG.supported exists.
- What is happening instead?
  SVG.supported is undefined.
- What error message are you getting?
  :D

**Comment by sesky4** [comment]
Oh i see, problem solved when I switched to v2.7.1
Seems that the official doc is not updated yet?

**Comment by Fuzzyma** [comment]
Official docs were updated today. The SVG.supported attribute does not exist anymore anyway

**Comment by ctlaux** [comment]
So is there any alternative available in v3?

**Comment by Fuzzyma** [comment]
Nope, sorry. Also there is a fair chance that the lib won't even load in older browsers due to new syntax
