### ISSUE TITLE
Can not adopt a correct element when element create by dynamic.

### ISSUE THREAD

**Issue by vellengs** [svgdotjs/svg.js#1040]
# Bug report

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

Modify [this fiddle](https://jsfiddle.net/Fuzzy/s06mfv5u/) to demonstrate the problem clearly, just fork it and paste the resulting fiddle in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behaviour you expect?
```
const body = document.body || document.documentElement;
const div = document.createElement("svg");
div.id = "graph";
body.append(div);
console.log(SVG('#graph'));  // expect Svg 
```

- What is happening instead?
it's Dom

- What error message are you getting?

**Comment by vellengs** [comment]
the problem is div.tagName is "SVG" instead of "svg";

**Comment by Fuzzyma** [comment]
Use `SVG().id('graph').addTo('body')`

**Comment by vellengs** [comment]
But it's different behavior, right?
it will create new tag instead of reuse exist one.

**Comment by vellengs** [comment]
https://github.com/svgdotjs/svg.js/blob/master/src/utils/adopter.js , line 54
```
export function adopt (node) {
  // check for presence of node
  if (!node) return null

  // make sure a node isn't already adopted
  if (node.instance instanceof Base) return node.instance

  // initialize variables
  var className = capitalize(node.nodeName || 'Dom')  // should have bugs here SVG won't equal Svg

  // Make sure that gradients are adopted correctly
  if (className === 'LinearGradient' || className === 'RadialGradient') {
    className = 'Gradient'

  // Fallback to Dom if element is not known
  } else if (!elements[className]) {
    className = 'Dom'
  }

  return new elements[className](node)
}

```

```

**Comment by vellengs** [comment]
should be create use 

```
const body = document.body || document.documentElement;
const div = document.createElementNS("http://www.w3.org/2000/svg", "svg");
div.id = "graph";
body.append(div);
console.log(SVG('#graph'));  // expect Svg 

```
