### ISSUE TITLE
Problem using build system to bundle svg.js

### ISSUE THREAD

**Issue by ctlaux** [svgdotjs/svg.js#1042]
# Feature request

As the title says, I would like to code up a global pause switch (per SVG object), and possibly also a speed regulator, which let's users globally change the speed at which an animation is running.

The idea behind the pause switch is to stop all animations on a drawing at once, and resume at the users convenience.

I have some questions before starting:
* has this been done before somewhere, if so where? Something similar?
* does anyone have recommendations about where and how to best do this?
* would this even be desirable to merge back into the main project?

**Comment by Fuzzyma** [comment]
With Version 3.0 you have the possibility to run all simulations on one timeline which you can pause, seek, speed up, reverse - and so on.

On our Twitter we posted an example on how to do that :)

**Comment by ctlaux** [comment]
Ok, thanks, I must have been looking at outdated documentation.

**Comment by ctlaux** [comment]
Could you please point me to the specific documentation entry or tweet? Grepping for 'timeline' doesn't yield much...

**Comment by Fuzzyma** [comment]
There is only an outdated documentation - unfortunately... Until now nobody had time to update. However here is the link to the tweet: https://twitter.com/svg_js/status/1070405081340764160?s=19

**Comment by ctlaux** [comment]
Thanks. Is the installation documentation also not up to date? I seem to not be able to load the newest version of svg.js the way I loaded version 2.7...

```
require('@svgdotjs/svg.js');
```
```
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by Fuzzyma** [comment]
Just npm i @svgdotjs/svg.js and then import {SVG} from 'svg.js'

**Comment by ctlaux** [comment]
That yields:

```
Uncaught TypeError: (0 , _svg.SVG) is not a function
```

Do I need to further unpack the SVG object?

**Comment by Fuzzyma** [comment]
If you need to use functions which were former on the svg object Iu need to import them separately. But the code i wrote should work as a starter

**Comment by ctlaux** [comment]
For others who have such problems in the future, this worked like the old svg.js:
```
import SVG from 'svg.js';
```
I need to update my JS knowledge to the year 2019...

**Comment by Fuzzyma** [comment]
When you do that you import the old 2.7 version. 3.0 is only available under the @svgdotjs namespace

**Comment by ctlaux** [comment]
So my problems (see error message above) seem to stem from using a build system (I tried both browserify and gulp.js), instead of just linking the svg.js file as recommended. Is there a recommended way to bundle one's own code with svg.js?

I just keep getting

```
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

during the build process...

**Comment by Fuzzyma** [comment]
You can just use the prebundled version and include it via script tag.
It looks like your bundle picks up the wrong source file. That should not happen!

**Comment by ctlaux** [comment]
It looks like it is picking up the right version from the full error message:

```
node_modules/@svgdotjs/svg.js/src/main.js:2
import './modules/optional/arrange.js'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by Fuzzyma** [comment]
Is this parse error coming up in your browser? Because this type of error shows when you use import in a script which wasnt loaded with `type="module"`

**Comment by ctlaux** [comment]
No, the build system reports it in the terminal. I have taken care to use `type="module"`

**Comment by Fuzzyma** [comment]
Try the newest version. I bundled a transpiled esm version with it which should be picked up by the bundlers (svg.esm.js)

**Comment by ctlaux** [comment]
Ok, I tried the newest version, still get a similar error, this time referring to your `.esm` file:

```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (9745:0) while parsing
 /Users/.../node_modules/@svgdotjs/svg.js/dist/svg.esm.js while parsing file:
 /Users/.../node_modules/@svgdotjs/svg.js/dist/svg.esm.js
```
This error is produced by watchify in the terminal, and not by the browser.

Thanks for ongoing help.

**Comment by Fuzzyma** [comment]
Hm at this point this is really only a module with exports only. So there is nothing special about this file at all! 

I assume this has to be some mistake in your configuration of your build system. Does it work with other esm dependencies?

**Comment by ctlaux** [comment]
Well the error message does speak of imports **and** exports! The mentioned line 9745 contains the export statement:

```
export { Morphable, registerMorphableType, ...
```

But yes, it is probably a problem with my build setup. I think though that the setup documentation for svg.js needs expanding...

**Comment by Fuzzyma** [comment]
I honestly don't think this is a problem related to svg.js. Just create your own file with an export and import it in your app. You should get the same error. Ofc you are importing a module. Obviously your configuration is not setup for that. I never had any problems with just using a standard esm import with any build system so far. Therefore my question if you have the same problem with any other Dependency.
