### ISSUE TITLE
Why the Y coordinate values obtained by the two methods are inconsistent, y() and attr('y'),svg.js3.0.13

### ISSUE THREAD

**Issue by feixiang001** [svgdotjs/svg.js#1043]
The two methods get y coordinate differently, which is right

**Comment by Fuzzyma** [comment]
This is only the case for text elements where this behavior is wanted.
The y-attribute of text specifies the baseline of the text. However, the y-method specifies the upper left edge. When you call y() it will give you the upper left edge and not the baseline (which is what you get when you pull the y-attribute directly with attr())
