### ISSUE TITLE
What's the different between @svgdotjs/svg.js and svg.js?

### ISSUE THREAD

**Issue by ibcLee** [svgdotjs/svg.js#1055]

**Comment by acenturyandabit** [comment]
They're literally the same.

**Comment by Fuzzyma** [comment]
`@svgdotjs` is the org we created to publish all svg.js related plugins and the lib itself. We did that with the release of version 3. So you can say, that installing `svg.js` gives you version 2 and installing `@svgdotjs/svg.js` gives you version 3. Also, all plugins available under `@svgdotjs` will be compatible to version 3
