### ISSUE TITLE
Question: Calculate similarity between shapes?

### ISSUE THREAD

**Issue by JoaoFGuiomar** [svgdotjs/svg.js#1057]
First of all congrats for such a great work.

Question: Would it be possible to calculate the similarity of 2 shapes?

Example: hand drawn rect vs a rect shape and see how close the hand drawn shape is to the rect shape?

**Comment by Fuzzyma** [comment]
Thanks! :)

Thats a question which is REALLY unrelated to svg.js. Not even really related to svg or javascript at all. I bet what you want breaks down to a mathematical problem so you might want to post it on https://math.stackexchange.com/

**Comment by JoaoFGuiomar** [comment]
Makes sense! 

I was planning on using methods from this lib to grab points, calculate angles, and so on, and do the math problem afterwards to calculate similarity.

Thank Fuzzy!
