### ISSUE TITLE
drag pattern - solved - please document

### ISSUE THREAD

**Issue by milahu** [svgdotjs/svg.js#1059]
this took me some hours to get it right
and i guess its worth to document

situation:
we have a rect, filled with a pattern
and we want to drag the rect

problem:
the pattern will not move with the rect

solution:
put the rect inside a "nested SVG document"
and make that draggable

why:
cos the pattern position is relative 
to its first parent SVG document

[fiddle](http://jsfiddle.net/59qtm1cn/4/) / [stackoverflow](https://stackoverflow.com/questions/14407240/how-to-make-svg-image-pattern-fill-move-with-object)

```js
// create canvas
var draw = SVG().size(200, 200).addTo('#canvas')

// pattern of checkerboard
var patt = draw.pattern(20, 20)
patt.rect(20, 20).fill({color: '#fff'})
patt.rect(10, 10)
patt.rect(10, 10).move(10, 10)

// nested svg document
var nested = draw.nested()

// rect + pattern
nested.rect(80, 80).fill(patt)

// drag on
nested.draggable()
```

bad solution:
use the dragmove handler, to update the pattern origin

```js
// this works too, but its slow:

// group + draggable
var group = draw.group().draggable()

// move handler
group.on('dragmove', (e) => {
  const {x, y} = e.detail.box
  patt.move(x, y)
})

// rect with pattern
var r = group.rect(80, 80).fill(patt)

// not helping:
patt.attr({
  //patternContentUnits: 'objectBoundingBox',
  //patternUnits: 'objectBoundingBox',
})
```

**Comment by Fuzzyma** [comment]
Nice solution! Feel free to create an FAQ in the readme and it this
