### ISSUE TITLE
svg.use of svg.symbol: center behaves like move --> wrong position

### ISSUE THREAD

**Issue by milahu** [svgdotjs/svg.js#1060]
# Bug report

svg.use.center() will set the wrong position

## Fiddle

[fiddle here](http://jsfiddle.net/wvL1gbc9/2/) with svg.js 3.0.16

the two symbols (blue squares) should be at the same position

## Explanation

situation:
we define a svg.symbol
we svg.use that symbol
we svg.use.center() the symbol-use

problem 1:
use.center() behaves like use.move()
and svg.use ends up at the wrong position

speculation:
use has no bbox or size
and symbol size dont propagate to symbol-use size

problem 2:
use.bbox() (red squares) is wrong
the bounding-box has a wrong x/y position

## Notes

move() should be used when possible (faster)
center() should be used only when necessary (slower)

**Comment by Fuzzyma** [comment]
When use's bbox is wrong, center will fail because its calculated from the bbox. The behavior of bbox regarding use changed from SVG1 to SVG2 and its possible that it is implemented inconsistenly across browsers. You are better off not relying on that.
