### ISSUE TITLE
Not possible to move mask? Unable to get bbox of mask element

### ISSUE THREAD

**Issue by brewh0use** [svgdotjs/svg.js#1061]
I've exported an SVG image from Sketch and wanted to animate it via svg.js. When trying to move parts of the image, svg.js throws an error:

> Getting bbox of element "mask" is not possible.

See screenshot below.

https://i.stack.imgur.com/9D5i4.png

Anything wrong with the SVG markup? Or does svg.js need additional input for moving masks?

https://i.stack.imgur.com/ppfFN.png

**Comment by Fuzzyma** [comment]
A mask is not visible and therefore simply has no bbox. If you need the bbox, use the contents of the mask and put it somewhere where it is visible and delete it after. Unfortunately there is no easier way to do this
