### ISSUE TITLE
scale() documentation arguments

### ISSUE THREAD

**Issue by edemaine** [svgdotjs/svg.js#1062]
`scale()`'s documentation looks like this:

> `scale()`
> returns itself
> animate yes
>
> The `scale()` method will take an `x` and `y` value:
>
> ```
> // scale(x, y)
> element.scale(0.5, -1)
> ```

[Looking at the code](https://github.com/svgdotjs/svg.js/blob/4ffb59abe80ff6815866a37447db62933b064813/src/modules/optional/sugar.js#L72-L77), `scale()` in fact takes an optional two-coordinate center of scaling (vanishing point).  It can be called in these ways:

* `scale(factor)`
* `scale(xFactor, yFactor)`
* `scale(factor, centerX, centerY)`
* `scale(xFactor, yFactor, centerX, centerY)`

`rotate()`'s documentation mentions the center argument, so `scale()`'s should too.

I personally find it confusing that `scale()` scales relative to the center of the object by default (different from a raw SVG transform), so I'd suggest also mentioning that the default is relative to the center of the element, like `rotate()`'s documentation does.

Happy to submit a PR if you can remind me where the documentation lives.

**Comment by Fuzzyma** [comment]
true. The current docs are here: https://github.com/svgdotjs/svgdotjs.github.io/tree/source-3.0

The compiled files go into the master so that are 2 PRs actually. A bit confusing the whole thing
