### ISSUE TITLE
Is it possible to load an existing svg object from the DOM?

### ISSUE THREAD

**Issue by stoffpalette** [svgdotjs/svg.js#1063]
I read the documentation but did not find an appropriate solution.
I tried it like that after i read https://svgjs.com/docs/3.0/getting-started/#the-svg-function

HTML:
`<svg id="svg"></svg>`
JS:
`var svg = SVG('#svg')`

But this does not seem to be the intended way to use it. The problem of the documentation is, that i can't follow the  "// get rect from dom" example without the related HTML code.

**Comment by Fuzzyma** [comment]
Thats exactly how it is supposed to work. Similar to jquerys `$('#svg')` you do `SVG('#svg')`.

**Comment by stoffpalette** [comment]
Thanks for your immediate answer! Sometimes you just need that input to be sure you are doing the right thing to find the cause for the non-working code. I am using you library within Vue.js and executed the JavaScript within the created-hook instead of the monted-hook. So the DOM was not ready at all. It is working now. I will amend my Vue example - maybe it helps some others.

Install svgdotjs: `npm install --save-prod @svgdotjs/svg.js`

add `./plugins/svg.js` file and paste:
`import { SVG } from '@svgdotjs/svg.js'

export default {
  install: Vue => {
      Vue.prototype.$SVG = SVG
  }
}
`
edit `main.js` file and add these lines before the `new Vue(...)` instantiation:

`import svgjs from "./plugins/svg.js";`
`Vue.use(svgjs);`

now you can access _svgdotjs_ inside your vue-components via `this.$SVG`
