### ISSUE TITLE
Easing support in v3 svg.easing.js !

### ISSUE THREAD

**Issue by priska42** [svgdotjs/svg.js#1066]
How the heck do we use svg.easing.js with the v3 of svg.js??

I'm searching everywhere that answer, the doc is not clear at all about that, the svg.easing.js is 4 years old now...

Any help would be much appreciated.

Thanks

**Comment by Fuzzyma** [comment]
That plugin isnt really updated for 3.0 but you can try the following: create a global object named `SVG` with a property `easing`, load the plugin, access the easing functions through `SVG.easing[name]`
