### ISSUE TITLE
Runner.persist and Timeline.persist type definition not defined in 3.0

### ISSUE THREAD

**Issue by mradcliffe** [svgdotjs/svg.js#1067]
# Bug report

There is no type definition for the Runner.persist method, which prevents a Typescript project from building when using that method. A persist method also exists on the Timeline class with slightly different comment about what the value should be though the function declarations are the same.

Runner

    // Stores how long a runner is stored after beeing [sic] done
    this._persist = this._isDeclarative ? true : null

Timeline

    // Determines how long a runner is hold in memory. Can be a dt or true/false
    this._persist = 0

## Fiddle

https://jsfiddle.net/5voqcz46/

(Uncomment the persist usage line)

## Explanation

- Expect: [Persist method exists that takes an optional boolean](https://svgjs.com/docs/3.0/animating/#svg-runner) on Runner and Timeline classes in svg.js.d.ts.
- Actual: Typescript compile fails to compile a typescript file that has Runner.persist usage.
- Error: `error TS2339: Property 'persist' does not exist on type 'Runner'.`

**Comment by mradcliffe** [comment]
I hope that small bug reports on these are okay. I'm creating these as I run into them. Unfortunately I have to use TypeScript on some projects.

I think that the resolution for this would be

```
    class Runner {
         persist(dtOrForever?: number | bool): this
```

```
    class Timeline extends EventTarget {
         persist(dtOrForever?: number | bool): this
```

**Comment by Fuzzyma** [comment]
Yes, ofc it is ok to post this small bug reports. Its actually easier to track everything and tick off.
Unfortunately I am traveling for the next time and wont be able to do any fixes myself. However, PRs are easy enough to merge whenever I habe Internet.
