### ISSUE TITLE
Viewbox doesn't have zoom property in 3.0

### ISSUE THREAD

**Issue by marekjedrzejewski** [svgdotjs/svg.js#1070]
2.7 had zoom property when viewbox() was called. Really useful feature for scalling things. Even the [docs for 2.7 said](https://svgjs.com/docs/2.7/geometry/#viewbox-as-getter):
> But the best thing about the viewbox() method is that you can get the zoom of the viewbox

3.0 doesn't have it, or it's somehow hidden, 3.0 docs don't give any result when I search for 'zoom'.

**Comment by Fuzzyma** [comment]
There should be a zoom() method on any element which supports viewbox. You can get and set the zoom with this method. Seems like we forgot it in the 3.0 docs

**Comment by marekjedrzejewski** [comment]
That works, thanks :)
