### ISSUE TITLE
feature request: scale but keep thickess or change thickness but keep bounding box size

### ISSUE THREAD

**Issue by creatxrgithub** [svgdotjs/svg.js#1071]
# Feature request: scale but keep thickness or change thickness but keep bounding box size

the gif below is close to my intent. thanks

![intent](https://user-images.githubusercontent.com/27437178/72209930-2935b580-3482-11ea-901b-34be033da0c4.gif)

**Comment by Fuzzyma** [comment]
I am not sure how this feature would serve as a core feature of svg.js. You can certainly add this functionality as a plugin though. Just animate the strokewidth together with the scale or use the non-scaling stroke vector effect: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/vector-effect

**Comment by creatxrgithub** [comment]
i know that (non-scaling stroke) , it is similar but that is not what i really need. 

![Untitled gif](https://user-images.githubusercontent.com/27437178/72223083-6741e080-3539-11ea-9971-75c7418af7ea.png)

i wish to keep the thickness while scaling the path

**Comment by Fuzzyma** [comment]
Feel free to implement. I dont see the use for a broader audience and I also dont have the time for that. But it would server well as a plugin.
