### ISSUE TITLE
improve docs: transform options

### ISSUE THREAD

**Issue by voxspox** [svgdotjs/svg.js#1073]
https://svgjs.com/docs/2.7/manipulating/#transforming
at text phrase *Available transformations are:*

I think it has to be `tx` and `ty` instead of `x` and `y`. Please check the whole list to be complete and correct. In `formatTransforms` it seams to me there are some more options like `px`, `translateX`, `around` ...

**Comment by Fuzzyma** [comment]
You are looking at the docs for 2.7, not 3.0:
https://svgjs.com/docs/3.0/manipulating/#transforming

**Comment by voxspox** [comment]
You are right :scream: thx
I'm currently migrating my project to 3...
