### ISSUE TITLE
css() typescript definition is missing object

### ISSUE THREAD

**Issue by Shrumpf** [svgdotjs/svg.js#1076]
The docs telling that you can use `element.css({ cursor: 'pointer', fill: '#f03' })` but the typescript definiton doesn't contain the definition for object.

My solution is to add
```javascript
css(style: object): this
```

to svg.js.d.ts on line 1036 but I'm not sure if this is the right solution.

**Comment by Fuzzyma** [comment]
Found this bug myself like a week ago and already fixed it locally. Will push as soon as I have other errors fixed as well!
