### ISSUE TITLE
Can't fill in variables as gradient

### ISSUE THREAD

**Issue by laurensgeerts** [svgdotjs/svg.js#1083]
Is it inpossible to fill in a variable as gradient applied to a SVG element. I try to change the gradient of a polygon with a select menu. But seems that I can't fill in a variable into the fill method. Like this: rect.fill(variable)

My code looks like this right now:

```
var linear2 = draw.gradient('linear', function (add) {
    add.stop(0, '#0f0')
    add.stop(1, 'f00')
})
var linear3 = draw.gradient('linear', function (add) {
    add.stop(0, '#d4f475')
    add.stop(1, '#EEE')
})

function colorFunction() {
    var fill1 = document.getElementById("square1").value;
    rect1.fill(fill1)
}
```

```
        <select id="square1">
            <option value="'linear1'">linear1</option>
            <option value="linear2">linear2</option>
            <option value="linear3">linear3</option>
            <option value="linear4">linear4</option>
        </select>
        <button onclick="colorFunction()">Kleuren</button>
```

Thanks in advance!

**Comment by Fuzzyma** [comment]
Why do you think "linear2" or "linear3" would be suitable names for a fill color? Did you try green and yellow?

**Comment by laurensgeerts** [comment]
> Why do you think "linear2" or "linear3" would be suitable names for a fill color? Did you try green and yellow?
Accidentally deleted 2 of the variables, my bad! Linear2 and Linear3 are 2 variables that should both represent a gradient.

**Comment by Fuzzyma** [comment]
Please show your full example code

**Comment by Fuzzyma** [comment]
closing this due to no feedback
