### ISSUE TITLE
wrap circle with a tag

### ISSUE THREAD

**Issue by necrojan** [svgdotjs/svg.js#1084]
Hi guys, this library is amazing, just a question, on how to wrap 
a circle with a tag? basically add a link on it.

I created the circle like this 
```javascript
let circle = draw.circle(radius);

// for the text
draw.plain(ele.ticket_id).attr({
                x: posX,
                y: posY,
                fill: '#fff',
                'alignment-baseline': 'central',
                'text-anchor': 'middle'
              })
// and the circle
draw.plain(ele.ticket_id).attr({
                x: posX,
                y: posY,
                fill: '#fff',
                'alignment-baseline': 'central',
                'text-anchor': 'middle'
              })

```

I am just wondering how can I wrap the circle with a tag so it's clickable. 
Thanks

**Comment by Fuzzyma** [comment]
There is a `linkTo` method on every element which basically does that. Just do `circle.linkTo(url)` and you are done

**Comment by necrojan** [comment]
awesome @Fuzzyma I missed that one. Thank!
