### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by martinhartmann** [svgdotjs/svg.js#1089]
# Bug report

How do I run the latest version? Using sample code from the documentation results in an error. Are the docs outdated?

## Fiddle

https://jsfiddle.net/2bok3t4v/

## Explanation

- What is the behaviour you expect?

Something happening

- What is happening instead?

Nothing

- What error message are you getting?

See console
```
Uncaught TypeError: Cannot read property 'rect' of null
```

**Comment by Fuzzyma** [comment]
https://svgjs.com/docs/3.0/
