### ISSUE TITLE
Save as .svg file

### ISSUE THREAD

**Issue by drlztn** [svgdotjs/svg.js#1098]
Hello, I'm sorry to open this but I don't know what else to do. I tried asking [in stackoverflow](https://stackoverflow.com/questions/60921718/save-generated-svg-with-svg-js-as-svg-file).

I want to save the drawing I'm generating with svg.js as a .svg file. I read [this issue
](https://github.com/svgdotjs/svg.js/issues/131) but I think svg.export.js is obsolete. I also read the [Import/Export page](https://svgjs.com/docs/3.0/importing-exporting/) in the docs but I'm not sure how to use the svg() method to export the generated SVG, neither did I find any examples of how to use it for this purpose.

**Comment by Fuzzyma** [comment]
I posted an answer on stackoverflow. You were right to post it there!
