### ISSUE TITLE
The SVG A element not move according its parent

### ISSUE THREAD

**Issue by amanfrinati** [svgdotjs/svg.js#1110]
# Bug report

I need to create an SVG A element into a group element and move the group according another coordinate system, but this feature seems like not work on svg.js version 3.0.16.

## Fiddle

This code running in version 2.7.0 [https://jsfiddle.net/amanfrinati/oj26zm9b/9/](https://jsfiddle.net/amanfrinati/oj26zm9b/9/): in this snippet, the red square was move on (200, 200) moving the granfather `g1`.

Here [https://jsfiddle.net/amanfrinati/n953op7u/6/](https://jsfiddle.net/amanfrinati/n953op7u/6/) the same snippet running in svg.js@3.0.16 not working.

## Explanation

- I expected that the red square was move to point (200, 200)
- The red square stay on the same position

**Comment by Fuzzyma** [comment]
Good catch. `<a>` should behave the same as `<g>`. The reason it worked in 2.x is because groups got translated when you used `move()`. This is handled differently in 3.x. You can use the old behavior by explicitely translating the group:

```js
grp.translate(200, 200)
```

**Comment by amanfrinati** [comment]
Ok! This solve it!
