### ISSUE TITLE
Small syntax error in documentation. attr() example

### ISSUE THREAD

**Issue by VitaliyAT** [svgdotjs/svg.js#1112]
Better 1 time look at picture then say lot of words.
![Screenshot_102](https://user-images.githubusercontent.com/1639608/82409014-414bc000-9a86-11ea-92ee-69b85fdf681c.png)

**Comment by Fuzzyma** [comment]
This is not a syntax error. Just copy and paste it into your editor.

But yes, we changed our code style guidelines and need to change this. Thank you!
