### ISSUE TITLE
Documentation doesnt show how to create id for various elements

### ISSUE THREAD

**Issue by saurabhgayali** [svgdotjs/svg.js#1115]
Documentation has only information about manipulating items with an ID.
https://svgjs.dev/docs/3.0/faq/#how-can-i-modify-an-element-that-already-exists-in-the-dom

no information on how to assign to id while creating elements.

**Comment by Fuzzyma** [comment]
You even linked to the very page which shows what you want.

**Comment by saurabhgayali** [comment]
> You even linked to the very page which shows what you want.

It only shows how to call for an element by ID that already exists.
I used svg.js and the created svg elements dont have any id. I hope you understand, I am using svg.js to create elements first and then call them by Id and hence, clueless.
Please enlighten if otherwise.

**Comment by Fuzzyma** [comment]
clicking on the link you posted gives this:

>How can I modify an element that already exists in the dom?
>
>There are many ways of referencing existing elements. Take a look at the referencing section to get >elements by id, using CSS selectors, using Zepto or jQuery, ...

Clicking on the link here gives this at the very top: 

>Referencing using CSS selectors
>SVG()
>
>returns SVG.Dom (or the most relevant subclass of SVG.Element)
>
>This function will get the first element matching the passed selector
>
>`var rect = SVG('rect.my-class').fill('#f06')`

And multiple other possibilities right after that. I dont even know WHERE you see ONLY an id

**Comment by ereckwerdt** [comment]
I think the real issue is that Dom.id() is not documented, and that setting the id is not used as an example in the .attr() docs.
If you don't realize that id is just an attribute that can be set with attr(), it is puzzling how to set the id after creating an element using svg.js.

**Comment by Fuzzyma** [comment]
@ereckwerdt thank you for pointing that out. Guess that sliped through. Will add it
