### ISSUE TITLE
Broken plugin links in docs

### ISSUE THREAD

**Issue by unre4l** [svgdotjs/svg.js#1121]
Found some broken links in the documentation. 
All plugin links under https://svgjs.com/docs/3.1/plugins/ point to a false url.

Is:
`https://svgjs.com/plugins/svg-colorat-js/` --> 404

Should: 
`https://svgjs.com/docs/3.1/plugins/svg-draggable-js/` --> works

**Comment by Fuzzyma** [comment]
Thanks! As a similar issue was already reported yesterday (yes yesterday lol) I will close this one and reference the other one: https://github.com/svgdotjs/svgdotjs.github.io/issues/91
