### ISSUE TITLE
SVG.js logo in SVG format

### ISSUE THREAD

**Issue by karol-depka** [svgdotjs/svg.js#1125]
Hi. Is there an SVG-format logo of SVG.js available?

I couldn't find it on the website and e.g. in
https://github.com/svgdotjs/svgdotjs.github.io/tree/source-3.0/assets/images

Isn't that a bit ironic that a bit ironic, for an SVG lib? ;)

**Comment by Fuzzyma** [comment]
Its not because we have it :P

Have a look here: https://github.com/svgdotjs/svg.logo

**Comment by service-paradis** [comment]
The SVG version looks really different than the original logo at https://github.com/svgdotjs/svg.logo
Am I missing something?
