### ISSUE TITLE
amove() cannot be animated

### ISSUE THREAD

**Issue by pragdave** [svgdotjs/svg.js#1131]
# Bug report

Although `amove()` works fine when setting up text, it doesn't seem to be an animatable property.

## Fiddle

https://codepen.io/pragdave/pen/bGEgVpd

## Explanation

I tried just adding it to Runner, but there's clearly some other plumbing that's needed, as it isn't being found

Dave

**Comment by Fuzzyma** [comment]
Mh jeah they seem to be missing on the Runner prototype. But in the end its as easy as adding them to the runner (with a bit of plumbing ;)  ): 

https://codepen.io/fuzzyma/pen/wvMgWjG

**Comment by Fuzzyma** [comment]
I am sorry, I somehow forgot to publish all the fixes I made. I just released it:
https://github.com/svgdotjs/svg.js/releases/tag/3.2.1
