### ISSUE TITLE
Is it possible to create a path from a group ?

### ISSUE THREAD

**Issue by gilles6** [svgdotjs/svg.js#1135]
Is it possible to create a path from a group, in order to have a group border ?

I asked a similar question [here](https://stackoverflow.com/questions/62751611/how-to-set-a-color-to-a-group-border-in-svg-file?noredirect=1#comment110969497_62751611) with an example.

**Comment by Fuzzyma** [comment]
Its certainly possible but svg.js has no method to do it for you ;)
