### ISSUE TITLE
Dead links on the documentation pages

### ISSUE THREAD

**Issue by crystalfp** [svgdotjs/svg.js#1136]
# Bug report (documentation web pages)

On the Plugin page https://svgjs.com/docs/3.1/plugins/ and also https://svgjs.com/docs/3.0/plugins/ all links on the right side pointing to the plugins do not point to anything.

On the Other Elements page https://svgjs.com/docs/3.1/shape-elements the links to Style and ForeignObject are wrong:
For Style the anchor should be `#svg-style` and not `#style`

For ForeignObject the anchor should be `#svg-foreignobject` and not `#foreignobject` as currently is.

Thanks for considering!
mario

**Comment by Fuzzyma** [comment]
Thanks for catching that!

**Comment by crystalfp** [comment]
The plugin page links have been fixed. Thanks!
Instead  Style and ForeignObject links are still wrong.

**Comment by Fuzzyma** [comment]
fixed
