### ISSUE TITLE
ForeignObject missing in Typescript definitions

### ISSUE THREAD

**Issue by crystalfp** [svgdotjs/svg.js#1139]
# Bug report
The definition for typescript of `foreignObject()` is missing from `svg.js.d.ts`
Adding the line:
```
foreignObject(width: number, height: number): Svg
```
inside `class Container extends Element {`
solves the problem.

Thanks for considering!
mario

**Comment by crystalfp** [comment]
I should add that I haven't found a way to add it, so I edited `node_modules\@svgdotjs\svg.js\svg.js.d.ts`
It is an ugly workaround, but I don't know other ways.
Any suggestion?

**Comment by crystalfp** [comment]
I'm speaking of the last version available on npm. In the git the the problem seems solved.

**Comment by Fuzzyma** [comment]
Yes this problem is solved in the current master which you can pull and build if you are in need of the fixes. I am waiting for a devdependency to be released before I release the new version
