### ISSUE TITLE
How to use existing SVG-element with SVGjs ?

### ISSUE THREAD

**Issue by mchapliuk** [svgdotjs/svg.js#114]

**Comment by jpgamaral** [comment]
I can't find any adopt plugin, is the absorb plugin the same? I have an element inline in my SVG and I want to manipulate it with svg.js, I can't seem be to able to do it either with SVG.wrap or the adopt plugin.

**Comment by Fuzzyma** [comment]
Use the refererence-branch for this task. SVG 2 is only waiting for be realeased there.
You can use it without problems and it can adopt existing SVGs.
Just call `SVG('id_of_svg')`
