### ISSUE TITLE
Missing width or height in foreignObject is taken as zero and not as missing

### ISSUE THREAD

**Issue by crystalfp** [svgdotjs/svg.js#1140]
# Bug report
If in a call to `foreignObject()` I leave undefined the height parameter, the resulting svg object has `height="0"`. Instead I expect `height` attribute to be missing.
# Explanation
If height is not present, the foreignObject is taking it from the object inside.

Thanks for considering!
mario

**Comment by Fuzzyma** [comment]
You are not supposed to leave the height out. If you do so, you have to expect unwanted behavior. However in this case the behavior is completely fine. If you need to remove the height attr you can follow up with `el.attr('height', null)`
