### ISSUE TITLE
Relative positioning of text elements broken

### ISSUE THREAD

**Issue by Thomas1664** [svgdotjs/svg.js#1141]
# Bug report
When I try to apply relative positioning (e.g. 50%) to a text element, the position is gets reset to 0.

## Fiddle
[My fiddle](https://jsfiddle.net/mwseb04h/5/)

## Explanation

- What is the behaviour you expect?
Correct position of the text e.g. for x=50% horizontally centered
- What is happening instead?
Position of the text at beginning of the line
- What error message are you getting?
None

**Comment by Fuzzyma** [comment]
Since text gets placed by its bounding box (upper left corner) rather by its base line, svg.js can only handle numbers as parameters and no percentage values. However, you can use `ax(), ay(), amove()` to do that or just set the x and y attrs yourself with `attr('x', '50%')`
