### ISSUE TITLE
Something wrong with relative transform

### ISSUE THREAD

**Issue by moayuisuda** [svgdotjs/svg.js#1142]
I'm following the code example below to transform relatively:
```js
element.transform({ rotate: 125 }).transform({ rotate: 37.5, relative: true })
// or
element.transform({ rotate: 125 }).transform({ rotate: 37.5 }, true)
```

But the code only work with `element.transform({ rotate: 125 }).transform({ rotate: 37.5 }, true)`
`element.transform({ rotate: 125 }).transform({ rotate: 37.5, relative: true })` will transform absolutely
[codepen](https://codepen.io/moayuisuda/pen/ExPJexR)

**Comment by Fuzzyma** [comment]
If this is true, this is a bug. However, your codepen is not working for me!

**Comment by edemaine** [comment]
I just noticed this bug while reading the source code. Specifically, the following line looks at the second argument (`relative`) but does not look at `o.relative` as claimed in the documentation:

https://github.com/svgdotjs/svg.js/blob/4524c20b48abe08e69c25a7382a289592d147496/src/modules/optional/transform.js#L67-L68

Actually, [the documentation for `transform()` as setter](https://svgjs.dev/docs/3.1/manipulating/#transform-as-setter) also mentions that `relative` can be a point-like object, and `new Matrix` follows this claim:

https://github.com/svgdotjs/svg.js/blob/4524c20b48abe08e69c25a7382a289592d147496/src/types/Matrix.js#L61-L63

Given this conflict, I wonder if the documentation should be changed, to remove the claim that `relative: true` works, and instead encourage use of the second argument...

**Comment by Fuzzyma** [comment]
Good catch. Yes, we introduced a different relative-thing for transforms without noticing the overlap. I will remove it from the docs since it just doesn't work
