### ISSUE TITLE
element.flip('x') still doesn't seem to work in svg.js 3.0.16 (element disappears); however, element.transform({flip: 'x'}, true) does

### ISSUE THREAD

**Issue by jpgm317** [svgdotjs/svg.js#1144]
https://jsfiddle.net/aezLwt0r/8/
The ellipse disappears
**HTML body:**
`
<div id="drawing"></div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/3.0.16/svg.min.js"></script>
<script src="main.js"></script>`

**main.js:**

`const draw = SVG().addTo('#drawing').size(1000, 1000)

let ellipse1 = draw.ellipse(40, 30).fill('orange').move(0, 400)
ellipse1.rotate(-25)

// this causes ellipse1 to disappear
ellipse1.flip('x') 

//The following code works...
//ellipse1.transform({flip: 'x'}, true)`

**Comment by Fuzzyma** [comment]
yes, this is fixed in the current master.
