### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by mroloux** [svgdotjs/svg.js#1152]
Hi,

I noticed the latest release is about one year old. Are there any plans to release a new version?

I'm hoping to take advantage of bug fixes and performance enhancements that happened the last couple of months ;-)

Thanks

**Comment by Bernix01** [comment]
Hoping to see a new release too!

**Comment by mroloux** [comment]
Any news on this?

**Comment by UnvirtualHH** [comment]
New release would be great, in cause of some resolved bugfixes.

**Comment by BrianHanechak** [comment]
I am hitting a bug with the existing release in importing SVG. When I call:

`const otherSvg = SVG().svg(svgString);`

I get a null reference exception in the parent function:

```javascript
  parent (type) {
    if (this.isRoot()) {
      return this.node.parentNode.nodeName === '#document'
        ? null
        : adopt(this.node.parentNode)
    }
```

This function is called from the `svg` function which imports the svg data from a string.

I tested building my own and it appears this issue has already been fixed (and the relevant functions are fairly different.). Can anyone suggest a workaround to this in the meantime? Am I creating the SVG object incorrectly?

**Comment by mkatanski** [comment]
I also want to ask when we can expect new release? There are still missing some TS definitions in latest build which were already added to the project.

**Comment by jdelaune** [comment]
Would be nice to see a new release

**Comment by jnt0r** [comment]
I would also like to see a new release. I think bugfixes should be released as soon as possible.

**Comment by BrianHanechak** [comment]
> I am hitting a bug with the existing release in importing SVG. When I call:
> 
> `const otherSvg = SVG().svg(svgString);`
> 
> I get a null reference exception in the parent function:
> 
> ```js
>   parent (type) {
>     if (this.isRoot()) {
>       return this.node.parentNode.nodeName === '#document'
>         ? null
>         : adopt(this.node.parentNode)
>     }
> ```
> 
> This function is called from the `svg` function which imports the svg data from a string.
> 
> I tested building my own and it appears this issue has already been fixed (and the relevant functions are fairly different.). Can anyone suggest a workaround to this in the meantime? Am I creating the SVG object incorrectly?

By the way, I eventually figured out that the solution is to use:

`const otherSvg = SVG(svgString);`
