### ISSUE TITLE
When cloned, a custom element looses it's constructor class and it's custom methods

### ISSUE THREAD

**Issue by Laurent-Chouinard** [svgdotjs/svg.js#1154]
# Bug report

## Fiddle
https://jsfiddle.net/say37z8m/2/

## Explanation

- What is the behaviour you expect?
I expect the clone method applied on a CustomElement to produce a CustomElement with the same constructor and same available custom methods (on the prototype) as the source element.

Should I write a custom clone method then? I don't know how to write one that works. my custom cloning introduces a problem with the tree model in the parent/children relationship

- What is happening instead?
the clone method returns an instance of the mother class and I loose access to my custom methods. The clone is not an instance of CustomElement anymore

- What error message are you getting?
When calling a custom method I get the behavior of the mother method of the same name or a TypeError "not a function" if the mother class doesn't have a method of that name.

Thank you so much for this great library.

**Comment by Fuzzyma** [comment]
Wow good catch! I fixed it in master :) 

Also: Great fiddle!
