### ISSUE TITLE
ease() method not working with during()

### ISSUE THREAD

**Issue by lucafaggianelli** [svgdotjs/svg.js#1156]
# Bug report

I need to animate an object along a path, as explained here: https://svgjs.com/docs/3.0/tutorials/ (which by the way is using SVG.js v2 and it doesn't work with v3). I was able to migrate the demo to v3, but the easing function doesn't work. it defaults to linear, whereas I try to use easeInOut

## Fiddle

https://codepen.io/lucafaggianelli/pen/abZoBxB

## Explanation

- What is the behaviour you expect?
When animating an object with `.during()` I expect to use `.ease()` to modify the animation easing function

- What is happening instead?
Easing is ignored and linear easing is used

- What error message are you getting?
No errors in console

**Comment by Fuzzyma** [comment]
The position which is passed to the during function is not the eased position. This is by design because if allows for more freedom. If you need the eased position just run it through the easing function (`SVG.easing['<>'](pos)`)

**Comment by lucafaggianelli** [comment]
cool! thanks, I updated the codepen and it's now working
