### ISSUE TITLE
Has it measure angle and distance?

### ISSUE THREAD

**Issue by Muslum6300** [svgdotjs/svg.js#1169]
Hi,
Firstly, thank you for your sharing.
Has it measure angle of between two lines same origin and measure distance between two dot?
if no, can your add this features please?

thank your again.

**Comment by Fuzzyma** [comment]
The angle between 2 lines and distance between 2 dots is simple math and you can look it up everywhere on the internet. This feature is not useful to us and won't get added. Every vector library has it though
