### ISSUE TITLE
svg render show 1000+

### ISSUE THREAD

**Issue by Feboboo** [svgdotjs/svg.js#1174]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
I have a lot of nodes. There are 4000 when there are more than 500+. At this time, the page will be very lagging. I want to ask whether svg.js can be rendered into canvas or any good suggestions? Can improve performance. Our project is considering replacing svg.js with g6, but this is a huge project!

**Comment by Fuzzyma** [comment]
see https://github.com/svgdotjs/svg.js/issues/1170#issuecomment-740612735
