### ISSUE TITLE
I used requestAnimationFrame to achieve smooth rendering, but I have a problem.

### ISSUE THREAD

**Issue by Feboboo** [svgdotjs/svg.js#1176]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
![image](https://user-images.githubusercontent.com/54396390/102181531-b6308c80-3ee5-11eb-9f9c-8972b24a6326.png)
![image](https://user-images.githubusercontent.com/54396390/102181591-d4968800-3ee5-11eb-9083-c732159f5e00.png)
![image](https://user-images.githubusercontent.com/54396390/102181887-48d12b80-3ee6-11eb-8c0c-eb0ca866bd1c.png)

I am looping through the addNode SVG.G above to render my node.
For the first rendering, the performance is improved a lot, so there is no need to wait for loading... But I may have a question, how is the svg rendered to add nodes?
_eg: The first time is **a1**, the second time is **a2** or **a1 + a2**?_
_q: If it is the second rendering, it may have a great impact on performance_

**Comment by Fuzzyma** [comment]
I am not sure I understand what you want. svg.js just manipulates the dom by calling appendChild or insertBefore

**Comment by Feboboo** [comment]
> I am not sure I understand what you want. svg.js just manipulates the dom by calling appendChild or insertBefore

thank you this is what i want
