### ISSUE TITLE
Fill mode freeze?

### ISSUE THREAD

**Issue by nikkisingh111333** [svgdotjs/svg.js#1182]
Hey i want to know how to use fill='freeze' in svg.js ...i m trying this  not working as i guessed it:
` patterns[c].stroke({
                    dasharray: 10000,
                    dashoffset: 10000
                }).animate({
                    duration: 6000,
                    when: 'now',
                    swing: false,
                    delay: 1000,
                    times: 1,
                    _**fill:'freeze'**_
                    }).stroke({
                    dasharray: 10000,
                    dashoffset: 0
                })`

**Comment by Fuzzyma** [comment]
There is nothing like a freeze option on svg.js' animations. Any fill you animate will stay at its last value anyway.
