### ISSUE TITLE
Linear gradient problem

### ISSUE THREAD

**Issue by qzoushi** [svgdotjs/svg.js#1184]
After I created the linear gradient in svg.js, it didn't work on the element, and I configured the color cutoff for the linear gradient, but I didn't find the stop in the code

**Comment by Fuzzyma** [comment]
Try this: https://svgjs.com/docs/3.0/shape-elements/#gradient-constructor

**Comment by qzoushi** [comment]
> 试试这个：[https](https://svgjs.com/docs/3.0/shape-elements/#gradient-constructor) : [//svgjs.com/docs/3.0/shape-elements/#gradient-constructor](https://svgjs.com/docs/3.0/shape-elements/#gradient-constructor)
Using the official API (add) will not work, while using at to add linear gradients will work

**Comment by Fuzzyma** [comment]
What does not work? Example please!

**Comment by qzoushi** [comment]
> 什么不起作用？请举个例子！

this  is not  work
var gradient = draw.gradient('linear', function(add) {
  add.stop(0, '#333')
  add.stop(1, '#fff')
})

this is work
var gradient = draw.gradient('linear', function(add) {
  add.at(0, '#333')
  add.at(1, '#fff')
})

**Comment by Fuzzyma** [comment]
are you using the latest version svg.js v3?
