### ISSUE TITLE
I instantiate the element object in svg.js and store it in an array. The properties of the object of this element will not be set.

### ISSUE THREAD

**Issue by qzoushi** [svgdotjs/svg.js#1185]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
I instantiate the element object in svg.js and store it in an array. The properties of the object of this element will not be set.

**Comment by Fuzzyma** [comment]
Please add an example. Otherwise, I am not able to understand your issue
