### ISSUE TITLE
After using the animation many times, the trajectory of the animation is not correct

### ISSUE THREAD

**Issue by heianqishizhisuiyuan** [svgdotjs/svg.js#1187]
Here's a chunk of code that animates a polygon:

https://codepen.io/heianqishizhisuiyuan/pen/GRjzeGq?editors=1111

when i first click the small polygon, the trajectory of the animation is right,  when i second click the small polygon， t the trajectory of the animation is not correct

**Comment by Fuzzyma** [comment]
cant reproduce. looks beatiful to me!
