### ISSUE TITLE
There are some problems with SVG3.0 used in micro front-end and non-micro front-end projects

### ISSUE THREAD

**Issue by Feboboo** [svgdotjs/svg.js#1189]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
1.Under non-micro front end:
![image](https://user-images.githubusercontent.com/54396390/106121981-255ef900-6193-11eb-9153-a28ee746cdde.png)
2.Micro front end: 
![image](https://user-images.githubusercontent.com/54396390/106122121-49223f00-6193-11eb-9ba0-1f5e7b64007f.png)

Description: In both cases, the code is the same, and my text is no longer displayed. Ask for help

**Comment by Feboboo** [comment]
code: 
![image](https://user-images.githubusercontent.com/54396390/106123025-60adf780-6194-11eb-9ee9-9c2823bec1fd.png)

**Comment by Feboboo** [comment]
code: 
![image](https://user-images.githubusercontent.com/54396390/106123116-7b806c00-6194-11eb-81ce-80888e217f6e.png)

**Comment by Feboboo** [comment]
How is tspan generated? I noticed that their labels were different. <tspan> and <text>

**Comment by Fuzzyma** [comment]
The first example has a tspan (which is allowed) and the second has text in text (which is not allowed). Dont know how you managed to do that

When you call `.text` a text element with one tspan per line is generated. If you dont want these tspans you can also use `plain` instead of `text` which will give you a text element without the tspan.

**Comment by Feboboo** [comment]
> The first example has a tspan (which is allowed) and the second has text in text (which is not allowed). Dont know how you managed to do that
> 
> When you call `.text` a text element with one tspan per line is generated. If you dont want these tspans you can also use `plain` instead of `text` which will give you a text element without the tspan.
I am also very surprised, the code is above, but
Is rendered, one is tspan and one text

**Comment by Feboboo** [comment]
> The first example has a tspan (which is allowed) and the second has text in text (which is not allowed). Dont know how you managed to do that
> 
> When you call `.text` a text element with one tspan per line is generated. If you dont want these tspans you can also use `plain` instead of `text` which will give you a text element without the tspan.



I am also very surprised, the code is above, but Is rendered, one is tspan and one text

**Comment by Feboboo** [comment]
> The first example has a tspan (which is allowed) and the second has text in text (which is not allowed). Dont know how you managed to do that
> 
> When you call `.text` a text element with one tspan per line is generated. If you dont want these tspans you can also use `plain` instead of `text` which will give you a text element without the tspan.



I am also very surprised, the code is above, but Is rendered, one is `tspan` and one `text`

**Comment by Feboboo** [comment]
It looks like `.text` under the micro front end project and it will not generate `tspan`. 
I am also very confused

**Comment by Feboboo** [comment]
great!  I can render text under the micro front end with `.plain.` `.text` still does not generate `tspan`

**Comment by Feboboo** [comment]
firefox is displayed, I guess it may be a problem with chrome

**Comment by Fuzzyma** [comment]
What on earth is the micro front end? Is this some other library? In this case, you have to report the issue there and not here!

**Comment by Feboboo** [comment]
> What on earth is the micro front end? Is this some other library? In this case, you have to report the issue there and not here!

Aha, he is this [(https://github.com/aliyun/alibabacloud-alfa)]

**Comment by Feboboo** [comment]
> > What on earth is the micro front end? Is this some other library? In this case, you have to report the issue there and not here!
> 
> Aha, he is this [(https://github.com/aliyun/alibabacloud-alfa)]
