### ISSUE TITLE
ungroup() reorders nodes

### ISSUE THREAD

**Issue by samhocevar** [svgdotjs/svg.js#1192]
# Bug report

## Fiddle

https://jsfiddle.net/3rof824w/

```js
var canvas = SVG().addTo('#canvas').size('100%', '100%')
g = canvas.group()
g.add(canvas.rect(100, 100).move(50,50).fill('red'))
canvas.rect(100, 100).move(100, 100).fill('blue')
g.ungroup()
```
## Explanation

Ungrouping `g` brings the red square to the front, because it is inserted after the blue square. I would expect ungrouped nodes to be inserted at the position of the original group.

**Comment by samhocevar** [comment]
FYI here is my implementation:

```js
function ungroup_in_place(g) {
    for (let e of g.children())
        g.before(e);
    g.remove();
}
```

**Comment by Fuzzyma** [comment]
good catch

**Comment by Fuzzyma** [comment]
seems like this was fixed long time ago
