### ISSUE TITLE
It's not lightweight enough...

### ISSUE THREAD

**Issue by YaoKaiLun** [svgdotjs/svg.js#1194]
![image](https://user-images.githubusercontent.com/11460856/111064415-e55b9780-84ee-11eb-90e4-57c1297177df.png)

**Comment by Fuzzyma** [comment]
true, once we added transpiling into the mix and all the polyfills, the size really grew. Hoping to solve this once only required polyfills are loaded

**Comment by Fuzzyma** [comment]
With the new release we are back at 75.57 KB. This was due to a transpiling mistake in the config
