### ISSUE TITLE
How to import and use .svg file

### ISSUE THREAD

**Issue by pyuyu** [svgdotjs/svg.js#1195]
How to import and manipulate and svg file ?
I tried the following code to use an .svg file
```js
 let use  = draw.use('shape1', '/public/svg/test.svg').move(0,0).size(100, 100)
```
and the `/public/svg/test.svg` is  accessible
however, it didn't work
What if i want to import svg file and use it?

**Comment by Fuzzyma** [comment]
For questions please refer to stackoverflow. This is an issue tracker. To manipulate svgs you have to load them into the accessible dom somehow. The use element doesn't do that

**Comment by pyuyu** [comment]
> For questions please refer to stackoverflow. This is an issue tracker. To manipulate svgs you have to load them into the accessible dom somehow. The use element doesn't do that

thanks!
