### ISSUE TITLE
Ignoring tspan element in .each()

### ISSUE THREAD

**Issue by standbyoneself** [svgdotjs/svg.js#1196]
svg.js@^2.7.1

I don't understand why svg.js ignores tspan while deep looping.

I'm trying to import raw svg and loop it. Text element that by default contains tspan is looped, but no text children (tspan's).

jsfiddle: https://jsfiddle.net/zxd2q1eu/1/

What is it?

**Comment by standbyoneself** [comment]
It seems to me that parser skips tspan, but what for?

Why I need to manually loop text.node.children and call SVG.adopt() on tspan to create an instance?

**Comment by Fuzzyma** [comment]
I think you are better off just using v3 for your needs
https://jsfiddle.net/nu6zcbwh/
