### ISSUE TITLE
3 and 3.1 seem broken

### ISSUE THREAD

**Issue by sethborg** [svgdotjs/svg.js#1197]
3 and 3.1 do not work. Go to your example page and change the framework from 2.5.0 to 3.0.5 and open the beta console to see the error https://jsfiddle.net/dotnetCarpenter/vceakozz/

Also, at the top of the page of svgjs.com if you change the dropdown from 2.7 to 3.0 or 3.1 none of doc links work, for example https://svgjs.com/docs/3.1/elements/#svg-clippath

**Comment by Fuzzyma** [comment]
Major version jumps mean breaking changes. That mean you cannot just run your old code with the new version. And the docs work pretty nicely

**Comment by sethborg** [comment]
But it's the exact same example code on jsfiddle for animating shapes along a path, the embedded jsfiddle uses svg.js 2.7 so the 3.1 page makes it seem like it is working when it's not. If you click Edit in jsfiddle and then at the top of the javascript frame, change the frameworks and extensions from 2.7 to 3.0.5 and hit Run you'll see this error in the console: "TypeError: SVG(...) is null"
https://svgjs.com/docs/3.1/tutorials/ vs https://svgjs.com/docs/2.7/tutorials/

Also, I don't think you clicked the other link I posted because if you had you'd see it gives a 404 
https://svgjs.com/docs/3.1/elements/ vs https://svgjs.com/docs/2.7/elements/

**Comment by Fuzzyma** [comment]
And where did you get that nonworking link from? I also can just give you a link which is a 404. 
About the tutorials: They are not up to date for 3.1

**Comment by sethborg** [comment]
There's a dropdown on the top left of svg.js with the different versions. Change it to 3 or 3.1 and then scroll down to "There is more..." where the links are. also if you duckduckgo svg.js the first link is https://svgjs.com/docs/3.0/ and the second is https://svgjs.com/docs/3.0/

I'd update the examples for you but I'm still not sure how to get the eased position.
