### ISSUE TITLE
set leading separately for tspan

### ISSUE THREAD

**Issue by pyuyu** [svgdotjs/svg.js#1198]
I want to set a separate leading for each tspan in the text, but only the leading of the text takes effect, so I try to set dy and x instead of newLine().
But after maintaining dy and x by myself, when I drag the text element, the x of tspan does not change (when using newLine(), while rebuild, x of tspan will be updated with the x of text).
Is there any way to set leading separately for tspan?

**Comment by Fuzzyma** [comment]
No unfortunetaly there is not. You have to roll your own solution. You can bind to the dragmove event and update what you need to update accordingly
