### ISSUE TITLE
TypeScript typings out of date but fixed in commit from 2019 - can we get a new release?

### ISSUE THREAD

**Issue by LaXiS96** [svgdotjs/svg.js#1199]
Hello,
I was trying to get this snippet of code working in my project (TypeScript 4.2.4 and `@svgdotjs/svg.js@3.0.16`):
```js
var timeline = new SVG.Timeline()

var rect1 = draw.rect(100, 200)
var rect2 = draw.rect(200, 100)

rect1.timeline(timeline)
rect2.timeline(timeline)

rect1.animate(300, 0, 'absolute').move(300, 300) // start at time 0 of timeline
rect2.animate(400, 200, 'absolute').move(500, 500) // start at time 200 of timeline
```
(taken from https://svgjs.com/docs/3.0/animating/#orchestrate-animations)

VSCode kept complaining that the documented usage of `Element.animate(...)` was incompatible with the included `svg.js.d.ts` typing.
I noticed that the particular issue was fixed in commit [be7ae4c2f6077af9363a266e59eba36dbface813](https://github.com/svgdotjs/svg.js/commit/be7ae4c2f6077af9363a266e59eba36dbface813), which is from December 2019.

Is there any particular reason why a new version hasn't yet been released, to include this and hopefully more fixes?

Thank you for your work, this library is awesome!

**Comment by vladdeSV** [comment]
This is an issue for me as well, but with #1015.

I would very much appreciate a new release as well.

**Comment by Shiuyin** [comment]
We very much need a new release as well. ForeignObject is missing typings which has been fixed a long time ago, without creating a new version.

**Comment by keyone2693z** [comment]
ForeignObject is missing typings

**Comment by Fuzzyma** [comment]
finally out

**Comment by vladdeSV** [comment]
Thank you so much! 🎉
