### ISSUE TITLE
www.svgjs.com not reachable

### ISSUE THREAD

**Issue by CetinOzdil** [svgdotjs/svg.js#1202]
Hi, 

Just wanted to inform you about www.svgjs.com is not reachable at the moment and looks like it's a DNS problem.

**Comment by MSDimos** [comment]
Same. 
Without docs, I even don't know how to use it. lol
Is there anybody can fix this problem, please.

**Comment by Fuzzyma** [comment]
We are not the owner of the domain. That makes it... complicated. I reached out and am waiting for a response. 

For now, I will try to remove the cname file so that the docs are available under:

https://svgdotjs.github.io

**Comment by microvn** [comment]
The Link from the search box still points to the old domain. I'm replacing the url manually. Please update it

**Comment by Fuzzyma** [comment]
This is only a temporary solution. Please bear with me. I don't have much time to handle this atm

**Comment by jonenst** [comment]
svgjs.com now has an invalid certificate and redirects to a chinese website saying "The Domain is for sale!" and displaying erotic images..

**Comment by phbernard** [comment]
@Fuzzyma Sorry you have to handle this difficult situation. Good luck!

**Comment by Z4P0** [comment]
Should updating the link in the sidebar too. Sorry about the domain stuff! Thank you

**Comment by akblissweb** [comment]
> We are not the owner of the domain. That makes it... complicated. I reached out and am waiting for a response.
> 
> For now, I will try to remove the cname file so that the docs are available under:
> 
> https://svgdotjs.github.io
> 
> You might need to clear your browsercache for this to work

Thanks for that... Yay... I can continue working

**Comment by edemaine** [comment]
You might want to edit the webpage link in the About section of https://github.com/svgdotjs/svg.js

**Comment by Nogbit** [comment]
It's now a gambling site, linking to https://svgdotjs.github.io/docs/3.0/ would be good.

**Comment by The4thLaw** [comment]
Also, searching on https://svgdotjs.github.io/docs/3.0/ redirects to the https://svgjs.com/ website. Perhaps that's something to change in the Algolia configuration?

**Comment by wout** [comment]
Shall I just buy a new domain? I was thinking about **svgjs.dev**.

Or is everyone fine with the GitHub address?

**Comment by edemaine** [comment]
svgjs.dev sounds reasonable. Alternatively, you could get svg.js.org via [js.org](https://js.org/). (See [exceptions in naming](https://github.com/js-org/js.org/wiki/Subdomain-Determination#exceptions).)

**Comment by Fuzzyma** [comment]
svgdotjs.com would be also free. I am fine with the github pages but maybe svgjs.dev is easier to communicate

**Comment by wout** [comment]
Both svg.js.org and svgjs.dev are fine with me, but I lean a bit towards the latter because it's closest to the original name.

Final call is with your guys. I want to fix this asap so let me know. :)

**Comment by Fuzzyma** [comment]
Lets go with .dev then. Its also faster to setup since we don't have to talk to the .js people (even though its a really nice project I must say!)

**Comment by wout** [comment]
> even though its a really nice project I must say!
I Agree!

I'll buy svgjs.dev now.

**Comment by wout** [comment]
It's on the way. Takes some time for Github to generate the new certificates.

**Comment by wout** [comment]
Ok, everything is looking fine (from the UK). In the meantime, I went through stackoverflow and updated all the links to point to svgjs.dev. That way, search engines will pick up the change quicker. I've also updated all references to svgjs.com to svgjs.dev on the master branch.

What else do we need to get changed?

**Comment by Fuzzyma** [comment]
@wout you have to add back the cname file to the svgdotjs repo also we need to generate new static sides. That I can do once its running

**Comment by Fuzzyma** [comment]
ok, than we need to check if all references in the svgdotjs repo are up to date and need to change the agnolia search config (I think)

**Comment by wout** [comment]
Ok, so this file needs to be changed: https://github.com/svgdotjs/svgdotjs.github.io/blob/source-3.0/statify.php
Can you regenerate the docs?

What needs to happen for Algolia?

**Comment by Fuzzyma** [comment]
Someone said, that searching produces the wrong links in the result. So I guess there is that. Maybe its solved by changing the statify. I will have a look

**Comment by Fuzzyma** [comment]
Ok, regenerating didn't do much. It actually only changed the copyright :D
I talked to the algolia guy years ago and he told me I can update the config somewhere on my own. But I cant find a mail. As of now, all searchresults still point to svgjs.com and I guess that needs to be changed. Seems like I have to contact him again

**Comment by wout** [comment]
> It actually only changed the copyright.
😂

> I can update the config somewhere on my own.
Wasn't that on an Algolia repo somewhere?

**Comment by wout** [comment]
Done!

https://github.com/algolia/docsearch-configs/pull/4179

**Comment by wout** [comment]
@Fuzzyma 
Here is another link that needs changing:

<img width="654" alt="image" src="https://user-images.githubusercontent.com/107324/121527256-1e25e280-c9f2-11eb-81e7-fd71daf68b11.png">

I tried logging in with the old credentials but they have changed. :)

**Comment by Fuzzyma** [comment]
I changed it. Also the algolia support was outstanding as always and changed their config. I think we are done now :)

**Comment by phbernard** [comment]
SVGs contain `xmlns:svgjs="http://svgjs.com/svgjs"`. Maybe you want to change that too?

**Comment by wout** [comment]
@Fuzzyma I've updated the package.json as well. Should we do a patch release to propagate the changes to the registries as well? Like npm for example:

https://www.npmjs.com/package/@svgdotjs/svg.js

**Comment by Fuzzyma** [comment]
v3.1 is ready to be released for month now. I just waited for the polyfill landscape to develop because I didn't want such a huge build again. Maybe it's better now. Will look into it :)

**Comment by wout** [comment]
> SVGs contain `xmlns:svgjs="http://svgjs.com/svgjs"`. Maybe you want to change that too?

@phbernard That's done already :)
https://github.com/svgdotjs/svg.js/blob/17d5f8ae58720f61094ee5221d16c89dbe66d98a/src/modules/core/namespaces.js

> Maybe it's better now. Will look into it :)

@Fuzzyma Brilliant! :D
