### ISSUE TITLE
textPath.first().x(0) give not x="0" in release 3.2.0

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.js#1207]
# Bug report

## Fiddle

Release 3.0.16 give  `<tspan x="0">` [https://jsfiddle.net/Piotrf/xfamqp1e/3/](https://jsfiddle.net/Piotrf/xfamqp1e/3/)
Release 3.1.0 give   `<tspan x="2.96875">` [https://jsfiddle.net/Piotrf/arnbd0v5/1/](https://jsfiddle.net/Piotrf/arnbd0v5/1/)
## Explanation

- What is the behaviour you expect?
I expect 0 and the same behavior as in release 3.0.16
- What is happening instead?
It is not 0
- What error message are you getting?
No error message

**Comment by Fuzzyma** [comment]
Were you able to figure out where things go wrong?

**Comment by PiotrFr** [comment]
Release 3.0.16
![image](https://user-images.githubusercontent.com/13883511/123380388-aaf2a380-d58f-11eb-8821-184d63946d33.png)

Release 3.1.0
![image](https://user-images.githubusercontent.com/13883511/123380436-ba71ec80-d58f-11eb-9e00-975b9abfa199.png)

**Comment by PiotrFr** [comment]
Maybe it will help
[Fiddle](https://jsfiddle.net/Piotrf/wsfnjhmr/8/)
![image](https://user-images.githubusercontent.com/13883511/123797879-f0dc9e00-d8e6-11eb-9c1d-f73377ceea13.png)
![image](https://user-images.githubusercontent.com/13883511/123798088-25e8f080-d8e7-11eb-9634-4b3782ab5b6f.png)

**Comment by PiotrFr** [comment]
Release 3.0.16
https://jsfiddle.net/Piotrf/wsfnjhmr/37
![image](https://user-images.githubusercontent.com/13883511/154858777-d7b58ec5-415a-41fd-9559-ec2e17295fce.png)

Release 3.1.2
https://jsfiddle.net/Piotrf/wsfnjhmr/41
![image](https://user-images.githubusercontent.com/13883511/154858913-bfc22ba1-d0db-4aca-bbb5-964ba2ae199f.png)

**Comment by Fuzzyma** [comment]
The reason this is happning is, that `x()` moves the bounding box of the element. The bbox x value of the tspan is 12 in your fiddle. Calling `x(0)` will attempt to move the bounding box to 0 (which means the tspan -12). However, this ofc fails on a tspan.

To do what you want, use `ax()` instead which does not do any magic and instead just moves the anchor:

https://jsfiddle.net/96uz7tnh/
