### ISSUE TITLE
select an exsisting group as SVG.Container

### ISSUE THREAD

**Issue by keyone2693z** [svgdotjs/svg.js#1210]
I have an existing SVG with the g tag which include everything in the SVG (g acts as a global thing to transfer everything in one)

so what I'm doing is this

I need to be able to select that outer g then i can append my stuff to it

`   this.svg = SVG('svg').style('cursor: crosshair');
    this.drawingLayer = this.svg.group().id(`draw`);

    this.updatePageSize(width, height);

    this.rect = this.drawingLayer.rect(0, 0).hide();
    this.icon = this.drawingLayer.image('.svg', 30).style('cursor: pointer').hide();

    this.svg.on('mousedown', this.mouseDown.bind(this));
    this.rect.on('mousedown', this.rectMouseDown.bind(this));`

in this line 
` this.drawingLayer = this.svg.group().id(`draw`);`

I'm adding a new g tag
but I want to first select my outer g then add this one to it

how can I do that

**Comment by Fuzzyma** [comment]
Just use `SVG(selector)` or `this.svg.findOne(selector)` to find your group
