### ISSUE TITLE
3.1.1: moving a group() changes use() elements

### ISSUE THREAD

**Issue by tdindorf** [svgdotjs/svg.js#1211]
Please have a look at the example https://codepen.io/tdindorf/pen/OJmBjZO

The one-but-last action, **groupM.dx**(-rS/2, 0) is the issue.

The result looks fine in 2.7.1, but not in 3.1.1: _use()_ elements previously added to group _groupM_ are drawn incorrectly (in 3.1.1) when the group is moved, be it using x(), dx(), cx(), move(), or dmove().

**Comment by tdindorf** [comment]
I see a solution is to _translate()_, not _move()_, as described in issue #1110... I wonder why the change?

**Comment by Fuzzyma** [comment]
This was done to separate transforms from simple movement. Now you can rely on the fact that a move command will move the bounding box of the object as well (which is not the case if you transform an object).
You can always explicitly use transform if you need to without any magic involved.

It's still a bug though so let's have a look.

**Comment by Fuzzyma** [comment]
This is fixed in master

**Comment by Fuzzyma** [comment]
So I attempted a fix but use-elements are just too much between groups and real element with how they behave.
One important thing does not hold true for them: If you move them, their bounding box is not where you just moved.
The current code abstraction however expects that.
I will label this as wontfix for now and close it. Maybe we can figure something our for the next major version
