### ISSUE TITLE
The method "elment.previous()" doesn't work.

### ISSUE THREAD

**Issue by qingyun1988** [svgdotjs/svg.js#1216]
```
var canvas = SVG().addTo('#canvas').size('100%', '100%')

var rect0 = canvas.rect(100, 100).move(100, 100).fill('blue');
var rect1 = canvas.rect(100,100);
var rect2 = canvas.rect(100, 100).move(100, 100).fill('red');

var test = rect1.previous();
```

**get error:**
Uncaught TypeError: rect1.previous is not a functio

**Comment by qingyun1988** [comment]
I  already know the answer that the method 'previous()' needs to be modified to 'prev()'. But the description of the method in svgjs.dev's doc is ‘previous()’ instead of 'prev()'.

Please modify it to make the description clear.

**Comment by Fuzzyma** [comment]
Feel free to make the change in the doc repository. We always welcome pull requests :)
