### ISSUE TITLE
documentation doesn't document shape?

### ISSUE THREAD

**Issue by nicferrier** [svgdotjs/svg.js#1218]
It seems like quite a lot of functionality is embedded in Shape but there doesn't seem to be any docs for it!

I've looked in Container elements... it's not in there.

I've looked in Other Elements... not in there either.

Looking further, in the Manipulating section it seems things like move are documented there... but perhaps some documentation for Shape would at least avoid some confusion?

**Comment by Fuzzyma** [comment]
Our docs don't follow the class hierarchy.  If you miss certain methods in the docs they might have been forgotten.
The docs are ordered around different funktionalities. The classes are just interna
