### ISSUE TITLE
The editing and adjustment function of path is required

### ISSUE THREAD

**Issue by lky5230** [svgdotjs/svg.js#1224]
We need svg.js to have the adjustment and editing function of path。
example website： https://yqnn.github.io/svg-path-editor/
![image](https://user-images.githubusercontent.com/21300963/137440214-e70204db-93b9-4c70-b902-99d5d5d3faaf.png)。
Is there a similar plug-in for  #svg.js？

**Comment by Fuzzyma** [comment]
There is a plug in called path handles but it's really old and it most likely will not work with svg.js v3. But you can get some inspiration there
