### ISSUE TITLE
animate() with duration 0 impossible

### ISSUE THREAD

**Issue by edemaine** [svgdotjs/svg.js#1225]
# Bug report

For complex multi-operation animations, I'd like to be able to write something like:
```js
circle.animate(0, 0, 'after').attr('cx', 5)
```
to make something happen instantaneously (here, set `cx` attribute to 0) after a sequence of animations in a timeline.  (I've already assigned a shared timeline via `elt.timeline(timeline)`.)

Unfortunately, the following code causes the first `0` to turn into a `400`:

https://github.com/svgdotjs/svg.js/blob/361d241c802ae144493a3f222b03c826d0e74b63/src/animation/Runner.js#L79-L80

## Explanation

The behaviour I expected was for `0` to be treated like a time, and only `undefined` (or `null`) to trigger a default value.

Assuming you agree (and this wouldn't break too many things), I'd be happy to write a PR.

I believe `Timeline.schedule` already behaves this way (it lacks a sanitization process.)

A workaround is to use a very small time, like `0.1`, in place of `0`.

**Comment by Fuzzyma** [comment]
I am sorry, I somehow forgot to publish all the fixes I made. I just released it:
https://github.com/svgdotjs/svg.js/releases/tag/3.2.1

**Comment by edemaine** [comment]
Thanks! Sorry, I forgot to make a PR as well. 😅

**Comment by Fuzzyma** [comment]
btw: for you actual problem: You can queue up functions that are immediately executed in a timeline.
You can use `queue(runOnceFn, runStepFn)` for that. If you only pass the runOnceFn, it will execute right away when its time :)

**Comment by edemaine** [comment]
Thanks! I didn't know about the `queue` interface. I'll probably find applications for that.

I found [the repo](https://github.com/edemaine/talk-token-swapping-robot-pivoting/blob/bd221796cce9dacf055c8d7b3bcb86d470e67733/robotpivot.coffee#L96-L99) where I originally ran into this issue. (The 0.1 is an approximation of zero.) This could be rewritten with `queue`, but it's maybe a little nicer to use `.attr` directly on the result of `animate` instead of wrapping in a function. (To see some of the generated animations, go [here](https://edemaine.github.io/talk-token-swapping-robot-pivoting/#/14/0/0) and press the right arrow key.

Another application I can imagine is an interactive speed slider where the maximum speed is instantaneous, though I've never built that. (For fun: [an example with a speed slider](https://erikdemaine.org/fonts/tetris/?text=svgjs&speed=5). [This code](https://github.com/edemaine/font-tetris/blob/f435dd76e47111d255cfc83142f1de746dfe85f5/index.coffee#L95-L168) uses svg.js but doesn't actually use `animate` for some reason I don't recall. Also the maximum speed isn't instantaneous.)
