### ISSUE TITLE
Path animation

### ISSUE THREAD

**Issue by antonioaltamura** [svgdotjs/svg.js#1229]
I'm not clear if and how you can animate paths.
It seems https://github.com/otm/svg.path.js is not totally compatible with the svg.js v3.

https://jsfiddle.net/alfredopacino/6qgjv39L/6/

**Comment by Fuzzyma** [comment]
This plug in is not maintained by us

**Comment by antonioaltamura** [comment]
There is no way to animate path then?

**Comment by Fuzzyma** [comment]
There is. But that plugin you mentioned doenst have anything to do with animation.
For path animation to work, you have to align the paths in a way that they both contain the same path commands. Only then it can be animated.

```js
const path = canvas.path('M 0 0 10 10').animate().plot('M 0 0 20 20')
```

**Comment by antonioaltamura** [comment]
Thanks. You should put that in your documentation.

**Comment by Fuzzyma** [comment]
https://svgjs.dev/docs/3.1/shape-elements/#path-plot
