### ISSUE TITLE
Possibility to add links to SVG Objects

### ISSUE THREAD

**Issue by otm** [svgdotjs/svg.js#123]
It would be nice to see the possibility to add links to SVG objects. 

That is:

```
<a xlink:href= "http://example.com/link/" xlink:title="A Title" '''xlink:show="new"'''>
     <rect x="0" y="0" width="100" height="100"/> 
</a>
```

One way to implement it would be to an API like:
    draw.rect(100, 100).attr({ fill: '#f06' }).link({href: 'http://example.com/link/'});

Or manually create the link and then add elements to it, like it is done with a group.
     var link = draw.link({href: 'http://example.com/link/'})
     link.rect(100, 100)

Any input would be great, I will try to get some time to implement this as a plugin.

**Comment by k-j-kleist** [comment]
Note that the documentation for v3.0 (https://svgjs.com/docs/3.0/parents/#svg-a) specifies the method name as `link()`, but the new method name seems to be `linkTo()` (see https://github.com/svgdotjs/svg.js/blob/master/src/elements/A.js).

**Comment by Fuzzyma** [comment]
Nope - both is possible but different. Link is called on a container to create a new link element. Linkto ist called on an object and wraps it into a link element so that it works as link

**Comment by k-j-kleist** [comment]
Ah - thanks for your clarification. And for an excellent library!
