### ISSUE TITLE
Set CSS variables with the css setter

### ISSUE THREAD

**Issue by Glandos** [svgdotjs/svg.js#1230]
# Feature request

Currently the following code doesn't work as expected:
```js
const draw = SVG()

draw.rect(10, 10).css({ '--myVar': 'black' })
```

There are 2 issues:

1. The setter will call [`camelCase`](https://github.com/svgdotjs/svg.js/blob/4524c20b48abe08e69c25a7382a289592d147496/src/utils/utils.js#L40) and remove the first dash, leading to an invalid CSS value declaration.
2. The Typescript definition doesn't allow this because (obviously) `--myVar` is not a part of `CSSStyleDeclaration`.

I don't think that 2. is concerning this project, but 1. is :)

I don't see this as a bug report, because in the meantime, we can use `attr({ 'style': '--myVar: black'})`.

**Comment by Fuzzyma** [comment]
This ended up being a bit more tricky. However, after 2 years its fair that I finally do it :D

**Comment by Glandos** [comment]
I think some Typescript part were not possible 2 years ago. I'm not 100% sure…
Anyway, thanks a lot!
