### ISSUE TITLE
SvgjsSvg1001 in body and link to svgjs.dev

### ISSUE THREAD

**Issue by jojozg7** [svgdotjs/svg.js#1239]
A node is created in the body with the ID SvgjsSvg1001. Does this node actually have to exist? Is there no other way to solve the purpose of this node so that it is not created in the body?

If this is not possible, then it would be great if the link to svgjs.dev is removed, so that it does not happen again in the future that the page is terminated and then replaced by Scam, as it happened before with the domain svgjs.com.

**Comment by Fuzzyma** [comment]
svgjs.com wasnt our domain svgjs.dev is. If you are talking about the extra svg that's added beside the actual svg, yes that's needed. However, its only inserted if a function is used that required ist. The namespace is needed as well because that's how XML works.
