### ISSUE TITLE
Querying nodes by ID appears to be case INsensitive

### ISSUE THREAD

**Issue by Perlkonig** [svgdotjs/svg.js#1242]
# Bug report

Querying nodes by ID appears to be case INsensitive, but that does not appear to be documented.

## Fiddle

I tried creating a fiddle (https://jsfiddle.net/e7cx43to/5/), but it works fine there. But the following HTML file does NOT work in Chrome or Firefox:

```html
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <script src="https://cdn.jsdelivr.net/npm/@svgdotjs/svg.js@3.0/dist/svg.min.js"></script>
        <script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function(event) {
                var draw = SVG().addTo("#drawing").size(200, 200).id("_scratch");
                var group1 = draw.defs().symbol().id("A").viewbox(-1, -1, 102, 102);
                group1.circle(100).fill("red").stroke({width: 2, color: "black"});
                var group2 = draw.defs().symbol().id("a").viewbox(-1, -1, 102, 102);
                group2.circle(100).fill("green").stroke({width: 2, color: "black"});
                var got1 = draw.findOne("#A");
                draw.use(got1);
                var got2 = draw.findOne("#a");
                draw.use(got2).dmove(50,50);

                var textdiv = document.getElementById("textdiv");
                var p = document.createElement("p");
                p.appendChild(document.createTextNode(draw.svg()));
                textdiv.appendChild(p);
            });
        </script>
    </head>
    <body>
        <div id="drawing"></div>
        <div id="textdiv"></div>
    </body>
</html>
```

## Explanation

What I expect to see is a red circle with a green circle overlapping it. What I get are two red circles. Order of definition matters. If I declare the green circle first, then I get two green circles. Using `SVG()` instead of `findOne` does not fix the problem.

Is this expected behaviour that is just not documented? Or am I the only one seeing this behaviour? Thanks for your time.

**Comment by Fuzzyma** [comment]
So I copied your example into a jsfiddle and it works. I am on Firefox. 

https://jsfiddle.net/Fuzzy/9ewq7xbs/

**Comment by Perlkonig** [comment]
I *said* it worked in Fiddle. It doesn't work as a plain HTML file. I don't know why it works in fiddle but not in the browser natively.

**Comment by Perlkonig** [comment]
I just posted it on my website if you want to see it served live: https://www.perlkonig.com/ap-renderer/scratch.html.

**Comment by Fuzzyma** [comment]
If it works in the fiddle, than it HAS to be a problem with how you setup the file and not with the library. e.g. try putting the script tag at the end of the body.

**Comment by Perlkonig** [comment]
That didn't work either. Updated the posted version: https://www.perlkonig.com/ap-renderer/scratch.html.

**Comment by Perlkonig** [comment]
The problem is clearly with `document.querySelector("#A")`. It is pulling `#a`, even though `querySelector` is supposed to be case sensitive. Even with the following HTML, it's logging "lowercase" in all my browsers, but it works in JSFiddle:

```html
<html lang="en">
    <head>
        <meta charset="UTF-8">
    </head>
    <body>
        <div id="drawing">lowercase</div>
        <div id="Drawing">uppercase</div>
        <script type="text/javascript">
            var qs = document.querySelector("#Drawing");
            console.log(qs.innerHTML);
        </script>
    </body>
</html>
```

I understand this isn't a problem with SVG.js. I will have to keep digging elsewhere.
