### ISSUE TITLE
A bug appears when dragging after rotation and then rotating

### ISSUE THREAD

**Issue by rfw** [svgdotjs/svg.js#1244]
# Bug report

A bug appears when dragging after rotation and then rotating

## Fiddle

https://codepen.io/rfw-the-bold/pen/yLzEypa

## Explanation

Drag and then rotate. The center point is in the center of the text

**Comment by capogreco** [comment]
yes - I am having a similar issue trying to animate a rotating object.

we need a way to move not just the object but the axis of rotation as well
