### ISSUE TITLE
EventTarget.off is missing argument options

### ISSUE THREAD

**Issue by Mscht** [svgdotjs/svg.js#1248]
# Bug report
EventTarget.off is missing argument options. So it is not possible to unbind an event handler that uses the options when calling EventTarget.on. Workaround: Using the top level function off().

Also note: the interface of the top level method off() is missing the argument options

## Fiddle

https://jsfiddle.net/swd4h7g5/

## Explanation

- EventTarget.off should pass options to top level function off()
- Behaviour should be se same like using the top level function off() directly
- Please add argument options to function off in svg.js.d.ts.

**Comment by Fuzzyma** [comment]
Feel free to create a PR to fix this issue :)
