### ISSUE TITLE
Tspan doesnt move when added to text

### ISSUE THREAD

**Issue by csae7255** [svgdotjs/svg.js#1250]
When creating a tspan via new SVG.Tspan().text('...') there are problems adding it to a text:
- newLine has no effect
- changing dy and x value fixes the tspan and it is no longer movable

https://jsfiddle.net/csae7255/2jz30hbk/3/

**Comment by csae7255** [comment]
I solved the problem.

Instead of using text.add(tspan) one has to use text.put(tspan). This also fixes the problem with newLines: text.put(tspan).newLine() works as expected.

https://jsfiddle.net/csae7255/qvpkzj1e/1/

**Comment by Fuzzyma** [comment]
The reason why put is working, is because put returns the element you pass to it. Since you have to call newLine on the tspan and not the text, you have to make sure that your newLine call is actually on the tspan (with put()) and not on the text (with add())
