### ISSUE TITLE
scalling problem with origin

### ISSUE THREAD

**Issue by patson12** [svgdotjs/svg.js#1255]
i want to scale svg scalling is working fine.. but i want my top origin fixed .. but after applyying scalling , its happen with centre,, 
i dont want the position of top changed.. same  i want from bottom.. rightnow its working fine with centre..

thanks in advance ...

here is my code 

 element.transform({

      scaleY: perc ,  
      translate: [0 , 0],
      origin : [0 , 0]
    })

**Comment by Fuzzyma** [comment]
Try `origin: 'top left'`. But `[0,0]` should work as well if your element is positioned at 0,0

**Comment by patson12** [comment]
thank you ok got it..and now its working fine.. but can i apply animation with scale?
 i want it like scale work with animation slow or fast..

thanks

**Comment by Fuzzyma** [comment]
just use `animate().transform()`. Please post such questions on stackoverflow where more people can easily answer your questions. This is an issue tracker and not meant for support questions. We also have a great documentation svgjs.dev :)
