### ISSUE TITLE
Create SVG

### ISSUE THREAD

**Issue by logrox** [svgdotjs/svg.js#1259]
Hi.

After upgrading from 3.1.1 to 3.1.2 I get a bug from SVG (). I include working code for version 3.1.1.
After changing to 3.1.2, an error appears in the nodeOrNew () method.

[codesandbox](https://codesandbox.io/s/svg-icon-uqj2r7)

**Comment by Fuzzyma** [comment]
Wow the usage of svg.js gets weirder every day :D. yeah there was a change in nodeOrNew to allow manipulating svgs that are loaded in an object tag. Object creates its own window (and therefore Node class) and we need to make sure that the correct one is used. Try to import the nodes into your document first: https://developer.mozilla.org/de/docs/Web/API/Document/importNode

**Comment by logrox** [comment]
It works, thanks.

**Comment by Fuzzyma** [comment]
It does? Awesome!! That was totally a shot into the blue :D
