### ISSUE TITLE
NPM page - documentation site is broken

### ISSUE THREAD

**Issue by arthurtyukayev** [svgdotjs/svg.js#1260]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.

The website that is listed in the NPM page as documentation leads to some sort of poker website.
https://www.npmjs.com/package/svg.js#documentation

This is the site listed on the NPM page for the package:
`https://svgjs.com/`

**Comment by Fuzzyma** [comment]
Cant really change that without releasing a new (very old) version :/
