### ISSUE TITLE
Save and Import (2.7)

### ISSUE THREAD

**Issue by SilverGaucho** [svgdotjs/svg.js#1261]
hei there

I've implemented svg.js (2.7) with several plugins (resize,select,drag) in an application of mine.
I've added several different events and behaviour around the "primitives" such as lines,images and so on.
Is there a fast way to save and import back the whole stuff?

At th emoment I save every object property and rebuild everything from scratch

Many thanks

**Comment by Fuzzyma** [comment]
You should probably move to version 3 which has very good import/export capabilities. I didn't touch the v2 code for years so I don't really have an idea whats going on there

**Comment by SilverGaucho** [comment]
Mmmmhhhh are there the following plugin compatible with 3 ? :
- draw
- select
- resize
- draggable


thx

**Comment by Fuzzyma** [comment]
nope unfortunately not. only draggable works

**Comment by SilverGaucho** [comment]
thanks bro, let us updated on that
