### ISSUE TITLE
Symbol use elements contained in group move wrong when moving its container group

### ISSUE THREAD

**Issue by DarSim2** [svgdotjs/svg.js#1263]
# Bug report

When moving a group that contains symbol use elements those elements behave inconsistently.

## Fiddle
[Fiddle](https://jsfiddle.net/cprvjLt2/2/)

## Explanation

_- What is the behaviour you expect?_
When moving a group `group.move(x, y)` all its children should move accordingly.

_- What is happening instead?_
The Text and Rect inside the group move as expected. The blue symbol use moves also as expected. The red symbol use moves slightly too much in x direction (to the right). And the gree symbol use moves slightly too much in y direction (down).

_- What error message are you getting?_
None.

**Comment by DarSim2** [comment]
I found out that the error is connected to the width/height ratio of the symbols. If it's 1:1 then it is moved normally. If height > width then it moves to the right and if width > heigth then it moves down. 
Here I added a yellow 16x16 rect to the red symbol and it is moving normally as expected: [Fiddle](https://jsfiddle.net/mq18ah2n/)

**Comment by Fuzzyma** [comment]
seems to be related to #1208. marking it as wontfix for now
