### ISSUE TITLE
Non working plugins

### ISSUE THREAD

**Issue by DwayneDibley** [svgdotjs/svg.js#1264]
I am currently trying out svg.js, the basic package seems great with the simple things I have done so far. I was attracted because of the plugins for dragging and resizing, they looked great on paper. The problem is that they don't work, apparently because of modifications to svg.py. 

Can you please mark the not working plugins as such, to save others from spending lots of time struggling as I have.

Thanks.

**Comment by Fuzzyma** [comment]
all plugins that live under the `@svgdotjs` namespace are compatible with v3

**Comment by DwayneDibley** [comment]
Please supply an example of how to do this for us who are not JavaScript experts.
