### ISSUE TITLE
svg.js.d.ts declear error 

### ISSUE THREAD

**Issue by mfdefs** [svgdotjs/svg.js#1266]
https://svgjs.dev/docs/3.1/shape-elements/#svg-foreignobject
var foreignObject = draw.foreignObject(width, height)
// Pass true as second parameter to SVG() to create an html in the html-namespace
foreignObject.add(SVG('<input type="text">', true))

"SVG('<input type="text">', true)" appear warning message: Expected 0-1 arguments, but got 2.ts(2554)

**Comment by Fuzzyma** [comment]
Good catch. Use the HTML function in the meantime

**Comment by Fuzzyma** [comment]
I didnt realize there is no HTML function. That was wrong in my mind. I fixed the types now. 
Sorry for the long wait
