### ISSUE TITLE
Can't use HTML color names when animating

### ISSUE THREAD

**Issue by OrIOg** [svgdotjs/svg.js#1269]
## Fiddle

https://jsfiddle.net/fwd3bgks/9/

## Explanation

- What is the behaviour you expect?
SVG.js should be able to map HTML color names to hex value for the interpolation in animation
ex: "green" -> "#00F000"
Maybe using the hex value during interpolation, and setting as the wanted named color when the animation is done.

- What is happening instead?
It seems that the color are not detected(instead detected as object). Then the svg's attributes become invalid(ie [object Object]), 
making the parser crash.

- What error message are you getting?
<details>
  <summary>Error Message</summary>
  
`Uncaught TypeError: lastCommand is undefined
    startNewSegment pathParser.js:96
    pathParser pathParser.js:160
    parse PathArray.js:97
    init SVGArray.js:17
    SVGArray SVGArray.js:6
    PathArray PathArray.js:43
    init Morphable.js:265
    ObjectBag Morphable.js:215
    _set Morphable.js:106
    from Morphable.js:71
    styleAttr Runner.js:682
    _initialise Runner.js:414
    step Runner.js:354
    _stepFn Timeline.js:293
    _draw Animator.js:86
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    _draw Animator.js:96
    frame Animator.js:18
    _continue Timeline.js:217
    play Timeline.js:92
    animate Runner.js:612
pathParser.js:96:18
`
</details>

**Comment by Fuzzyma** [comment]
svg.js wil not do that for you. A mapping would just add a lot of code for almost no benefit. So this is a wontfix unfortunately
