### ISSUE TITLE
Color-names are not applied after animation

### ISSUE THREAD

**Issue by chaitanyasunkara** [svgdotjs/svg.js#1270]
# Bug report

## Fiddle

[this fiddle](https://jsfiddle.net/dtoxepju/)

<img width="687" alt="Screen Shot 2022-04-12 at 2 48 40 AM" src="https://user-images.githubusercontent.com/48030253/162908931-138f92ac-b4c5-46fa-ac53-96b553e7cb7d.png">

## Explanation

- I expect the attributes like fill and stroke to be changed to their respective color names like "red", and "blue" after the animation.
- Default color "black" is being rendered.
- When I inspect the element seems like it's getting an object from somewhere.

**Comment by saivan** [comment]
This is definitely not a bug. The [css colors](https://www.w3schools.com/cssref/css_colors.asp) are supported by modern browsers, but not natively supported in SVGjs. You can certainly write a plugin to add support for them if you'd like to but it shouldn't be included in the core.

For starters, you can't animate between the strings 'red' and 'green' in any reasonable way. We would need to maintain a mapping with all of those names in them. Instead you should use:

`canvas.rect(100, 100).attr({ fill: 'rgb(255, 0, 0)' })`

Or you can use our awesome color module to define your colours however you'd like. But internally, to be able to animate the string 'red', we'd need to convert it to an rgb tuple. 

If you really want this functionality, you can just use this 

> https://stackoverflow.com/questions/1573053/javascript-function-to-convert-color-names-to-hex-codes

But I think that native support for these colors isn't something we'd add to the library
