### ISSUE TITLE
3.0.0 import not working

### ISSUE THREAD

**Issue by noah-seltzer** [svgdotjs/svg.js#1272]
I've been happily using SVGJS 3.0.0 with svgdom in nodejs with no issues for years. Today I tried to move some of my SVGJS code into the browser, but I can't seem to import it with the standard `import { SVG } from '@svgdotjs/svg.js'`

Is there anything I'm doing wrong here?

My front end stack is nuxt 3 + vue 2

**Comment by Fuzzyma** [comment]
Please look into how esm modules are loaded in the browser. node knows what npm is and that it can find its modules on node_modules. The browser doesn't. You have to give it the correct path to the javascript files

**Comment by noah-seltzer** [comment]
its been too long since the original comment for me to remember what I did, but I just checked my repo and `import { SVG } from '@svgdotjs/svg.js'` is working just fine. Must have been a webpack issue

**Comment by noah-seltzer** [comment]
thanks everyone who commented :)
