### ISSUE TITLE
Missing second parameter of ```addTo()``` in d.ts

### ISSUE THREAD

**Issue by dhckdaks** [svgdotjs/svg.js#1279]
# Bug report
```addTo()``` function of SVG() has second parameter .js. But addTo() doesn't have second parameter in .d.ts.

#### svg.js.d.ts
```ts
class Dom extends EventTarget {
    ...
    addTo(parent: Dom | HTMLElement | string): this // no second parameter
    ...
}
```

#### src/elements/Dom.js
```js
addTo (parent, i) { // there is second parameter
  return makeInstance(parent).put(this, i)
}
```

**Comment by Fuzzyma** [comment]
Feel free to create a pr to add it to the definition :)
