### ISSUE TITLE
rotate is not working with transform 

### ISSUE THREAD

**Issue by patson12** [svgdotjs/svg.js#1286]
Hello,

i am working on rotate element with left top corner and right left corner likewise all.. and i have added following code .. its working on if rotate angle less than 180.. its working fine if i make  rotate: 90 or  rotate: 120 but if i increase value like 360 , 720.. its not working.. 
plz have a look on my code 

regards
harshad
```
 scaleele.animate(2000).transform({
    rotate: 320,
    origin: "top left",
  });
```

**Comment by kelvinsekx** [comment]
This should have worked.
But an alternative approach is to rotate like in the example below
```js
scaleele.animate(2000).rotate(320)
```

**Comment by Fuzzyma** [comment]
as  @kelvinsekx your code works as intended. If you think you found a bug, please provide a minimal example which showcases the bug
