### ISSUE TITLE
Feature request: `group(id)` constructor for SVG.G

### ISSUE THREAD

**Issue by jango-fx** [svgdotjs/svg.js#1288]
# Feature request: `group(id)` constructor for SVG.G

to my mind a `<g>` tag's main attribute is its `id` (just like the `width` and `height` of a `rect`) and I would expect it to be set similarly intuitively during construction. Without a cumbersome additional call of `.attr('id', 'ID')`.

so instead of
```js
let theGroup = draw.group()
theGroup.attr('id', 'myGroupID')
```
simply
```js
let theGroup = draw.group("myGroupID")
```
to get
```xml
<svg>
  <g id="myGroupID">
  </g>
</svg>
```

(love your lib though ❤️ )

**Comment by Fuzzyma** [comment]
The constructor always takes the dimensions of the object. Since g don't have dimensions itself they don't take an argument.

But you can always pass an object with attributes: `canvas.group({ id })`

**Comment by jango-fx** [comment]
arr, I still don't find that very intuitive, but I might bow to your consistency 😜

**Comment by Fuzzyma** [comment]
haha, and I thought intuity comes from consistency :D

**Comment by jango-fx** [comment]
> The constructor always takes the dimensions of the object

not true for `SVG.text()` though 🤨

**Comment by Fuzzyma** [comment]
@jango-fx text doesnt have a dimension!! At least not until SVG 2 which isnt broadly supported and a whole other beast
