### ISSUE TITLE
Mouseover and mouseout events won't trigger when mouse moves too fast

### ISSUE THREAD

**Issue by chaoyifei** [svgdotjs/svg.js#1289]
Mouseover and mouseout events won't trigger when mouse moves too fast

When I slide my mouse between different rect,Mouseover and mouseout events won't trigger when mouse moves too fast

**Comment by Fuzzyma** [comment]
That sounds more like a limitation of the browser than the library. We use native events. No magic. So there is nothing we can do about it. You are better off asking on stackoverflow and providing an example that shows your issue
