### ISSUE TITLE
Animate color stops working after first call to animate

### ISSUE THREAD

**Issue by mrname5** [svgdotjs/svg.js#1290]
[# Bug report]

## Fiddle

https://jsfiddle.net/Mrname5/3tqsoekz/1/

## Explanation

- What is the behaviour you expect?
I expect the color of circle1 to continue animating each time I call the animate function. For example, I expect to be able to animate the color of circle1 from blue to black then back to blue with two function calls.
- What is happening instead?
It performs correctly the first time but after that, it does not animate anymore. It does not produce an error it just does not animate.
- What error message are you getting?
There is not error message it just does not respond.

**Comment by renickbell** [comment]
Using this code, I have observed the same problem. Is this method for animating color incorrect, or is this a bug?

**Comment by mrname5** [comment]
thanks
