### ISSUE TITLE
Can't set 'pointer-events'

### ISSUE THREAD

**Issue by byrakham** [svgdotjs/svg.js#1292]
When I use 'pointerEvents' as CSSStyleDeclaration  in the Dom.css<T extends CSSStyleName>(style: T) method, it translates it to 'pointerevents ' instead of 'pointer-events' value.  Could you please check the camelCase() method in the css.js file?

**Comment by byrakham** [comment]
The temporary solution is:  
const style = { "pointer-events": 'none' };
someElement.css(style);

**Comment by Fuzzyma** [comment]
fixed in master
