### ISSUE TITLE
Update website on node package README

### ISSUE THREAD

**Issue by raphaelsiz** [svgdotjs/svg.js#1293]
The website on the GitHub, svgjs.dev, leads to the documentation. The website on npmjs, svgjs.com, leads to "hereisyourwinner.com" which I think is a scammy gambling site? If you want people to be able to find your documentation instead of assuming the package is some sort of spam, this should probably be updated

**Comment by Fuzzyma** [comment]
You are probably looking at the old 2.7 version which wasnt updated for a while. Therefore the readme isnt updated as well. I probably have to release a new version to update the readme
