### ISSUE TITLE
It would be nice if we can destroy timeline gracefully.

### ISSUE THREAD

**Issue by PVirie** [svgdotjs/svg.js#1295]
# Timeline.terminate()

I am using svg.js to create a math tutorial web blog. It does the job nicely. Just one thing though..

Suppose that we have a script that uses svg.js, consider these conditions:
1. The script uses a lot of persisting Runners (to make animations revertible).
2. The script needs to replace and re-populate Timelines with those Runners.

For some reasons, javascript does not clean up Timelines properly and leaves a lot of occupying memory footprints.
I have been cleaning up Runners in Timelines manually. But it would be nice if you make an official support for this feature.

So instead of using this:
```js
timeline._runners = [];
```
It would be nice if we can
```js
timeline.terminate();
```
I will be happy if you could consider my request. Thank you in advance.

**Comment by Fuzzyma** [comment]
see https://github.com/svgdotjs/svg.js/commit/29b2bd7f811584380b35434d5bf29913ffe93459 for implementation

sorry that it took so long

**Comment by oliverschenk** [comment]
Will there be a release version for this?

**Comment by Fuzzyma** [comment]
I am sorry, I somehow forgot to publish all the fixes I made. I just released it:
https://github.com/svgdotjs/svg.js/releases/tag/3.2.1
