### ISSUE TITLE
npm install for nodejs

### ISSUE THREAD

**Issue by maxwowpow** [svgdotjs/svg.js#1299]
# Bug report

- no release/dist on npm install `npm install @svgdotjs/svg.js`.
- currently package.json refers /dist folder for release/compiled version.
- currently only release section and cdns have a compiled version.

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'XXX\node_modules\@svgdotjs\svg.js\' imported from app.js
    at new NodeError (node:internal/errors:399:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:202:9)
```

## Explanation

- What is the behaviour you expect?
as advertised to setup a library version 3 run npm install @svgdotjs/svg.js,
expected a package usable from nodejs.

- What is happening instead?
only sources are pulled on npm install

- What error message are you getting?
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'XXX\node_modules\@svgdotjs\svg.js\' imported from app.js
    at new NodeError (node:internal/errors:399:5)
    at legacyMainResolve (node:internal/modules/esm/resolve:202:9)
```

**Comment by Fuzzyma** [comment]
Cant reproduce.
My package.json has 
```json
{
  "devDependencies": {
    "@svgdotjs/svg.js": "^3.2.0"
  }
}
```

and i simply write

```js
const { SVG, registerWindow } = require('@svgdotjs/svg.js')
```

and it works. Closing this as not reproducible
