### ISSUE TITLE
(documentation) animating shapes along a path example needs rewrite 

### ISSUE THREAD

**Issue by opheliagame** [svgdotjs/svg.js#1303]
https://svgjs.dev/docs/3.0/tutorials/ 
The 'Animating shapes along a path' on this page doesn't work anymore I think. I would be willing to write the current version of this if required. lmk :) 
referencing #1134 as well

**Comment by Fuzzyma** [comment]
nice! feel free to create a PR to update the docs with a new example :)

**Comment by Fuzzyma** [comment]
You can just fork them and save a new link
