### ISSUE TITLE
Migrating SVG window events

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#1305]
Migrating to 3.x and running into error with:
```
 SVG.on(window, 'mousemove.drag', (e: any) => {
      this.drag(e)
    })
```
I see now that the events only exist on SVG elements but not clear how the window object would be used in this case. Not seeing much in the docs regarding this? Would I need to define an outer full page container and make that an SVG element?

**Comment by cyberwombat** [comment]
Oh interesting. Well let's see if perhaps you can tell from this. I import like this:

```
import {
  SVG,
  extend as SVGextend,
  Element as SVGElement,
  Text,
  Point,
  PathArray,
} from '@svgdotjs/svg.js'

```
And TS gives me this:
<img width="803" alt="Screenshot 2023-07-24 at 11 59 59 AM" src="https://github.com/svgdotjs/svg.js/assets/777498/841acbd1-097d-445a-9b11-2826f02f67c5">

**Comment by cyberwombat** [comment]
Oh I see the issue...
```
import SVG, {
  extend as SVGextend,
  Element as SVGElement,
  Text,
  Point,
  PathArray,
} from '@svgdotjs/svg.js'
```
duh...

**Comment by Fuzzyma** [comment]
`SVG.on` is the syntax if you import the WHOLE thing. 

This is only available if you do `import * as SVG from '@svgdotjs/svg.js'`.
Instead import `on` directly: `import { on } from  '@svgdotjs/svg.js'`.

**Comment by cyberwombat** [comment]
Thank you. Works like a charm. I appreciate your work and your quick response!
