### ISSUE TITLE
No Fragment declaration in svg.js.d.ts

### ISSUE THREAD

**Issue by we125182** [svgdotjs/svg.js#1307]
![image](https://github.com/svgdotjs/svg.js/assets/17947588/3db455eb-611f-4554-bc8d-1150889665ee)

`svg.js.d.ts` don't export Fragment

**expect**
add `Fragment` class declaration

**Comment by Fuzzyma** [comment]
Are you open to create a PR?

**Comment by we125182** [comment]
OK，I’d like try that.
