### ISSUE TITLE
Custom Bezier Function

### ISSUE THREAD

**Issue by JustinSteinberg** [svgdotjs/svg.js#1308]
# Bug report

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

Modify [this fiddle](https://jsfiddle.net/Fuzzy/s06mfv5u/) to demonstrate the problem clearly, just fork it and paste the resulting fiddle in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

When trying to use the custom bezier timing funciton for the animation, runner.ease(SVG.easing.beziere(x1,y1,x2,y2))... the console states that the easing function is not defined. 

- What is the behaviour you expect?
 Implementing custom timing funciton
- What is happening instead?
- What error message are you getting?

(As seen below, svgText.js is my own file)

svgText.js:38 Uncaught TypeError: SVG.easing.beziere is not a function
    at SVGGElement.<anonymous> (svgText.js:38:127)
    at SVGGElement.handle (jquery-3.7.0.min.js:2:44360)
    at SVGGElement.dispatch (jquery-3.7.0.min.js:2:39997)
    at v.handle (jquery-3.7.0.min.js:2:37968)

**Comment by Fuzzyma** [comment]
What bundle are you using? If you use npm you probably want to import easing instead of using SVG.easing

**Comment by Fuzzyma** [comment]
cant reproduce and will therefore close.
