### ISSUE TITLE
svgjs.com redirect to 'gacor.poker' scammy site

### ISSUE THREAD

**Issue by 3xploiton3** [svgdotjs/svg.js#1312]
svgjs.com redirect to 'gacor.poker' scammy site

please take down, or report abuse

> Domain Name: gacor.poker
Registry Domain ID: 145c055afa3f4a758b9e54b487e9eddb-DONUTS
Registrar WHOIS Server: whois.namecheap.com
Registrar URL: https://www.namecheap.com/
Updated Date: 2022-09-22T07:34:54Z
Creation Date: 2022-09-17T07:34:43Z
Registry Expiry Date: 2023-09-17T07:34:43Z
Registrar: NameCheap, Inc.
Registrar IANA ID: 1068
Registrar Abuse Contact Email: abuse@namecheap.com

**Comment by Fuzzyma** [comment]
It's not our domain. There is nothing we can do

**Comment by HongZeTao** [comment]
Please remove references to the website:http://svgjs.com/svgjs
