### ISSUE TITLE
Foreign object won't render in Firefox

### ISSUE THREAD

**Issue by DesantBucie** [svgdotjs/svg.js#1318]
# Bug report

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

https://jsfiddle.net/qau8cs9g/12/

## Explanation

- What is the behaviour you expect?
Render a text(open jsfiddle with safari or chrome, firefox won't work).
- What is happening instead?
Doesn't work on firefox.
- What error message are you getting?
None. Although if I open web inspector and change the name of the container(like div to xhtml:div or vice versa), the text starts to render.

**Comment by Fuzzyma** [comment]
svg.js by default creates elements in the svg namespace. Browser dont render divs in svg namespace. In order to create an element in html namespace, you can pass `true` to the SVG function:

```js
 canvas.foreignObject(100, 100).add(SVG(`<div contenteditable="true" style="color:black;">Text</div>`, true))
```


Here is your fixed example: https://jsfiddle.net/jd0x6mos/

**Comment by DesantBucie** [comment]
Thanks a lot.
