### ISSUE TITLE
[Bug Report] Invalid click event in Firefox

### ISSUE THREAD

**Issue by ALI1416** [svgdotjs/svg.js#1319]
# Bug report

Invalid click event in Firefox

Chrome is ok

## Code

svg.js version : 3.2.4

```js
let svg = SVG().addTo('body').size(300, 300)
let rect = svg.defs().rect(100, 100).attr({fill: '#6cf'}).click(() => {
  console.log('click')
})
svg.use(rect)
```

**Comment by Fuzzyma** [comment]
I run this in FF and dont get any error: https://jsfiddle.net/bf7yp4Lc/

I am also not sure what you expect this code to do. The rect lifes in the `<devs>` and therefore is only rendered through your `<use>` tag. I dont think events bound to the `<use>`d element are suppoed to fire.
If so, that is rather a bug in FF and not in svg.js

**Comment by Fuzzyma** [comment]
Closing due to no response

**Comment by ALI1416** [comment]
Thanks
