### ISSUE TITLE
animate keyTimes

### ISSUE THREAD

**Issue by skyunBoss** [svgdotjs/svg.js#1329]
`<animate attributeName="opacity" values="0;1;0;0" keyTimes="0;.154;.41;1" calcMode="linear" begin="0s" dur="2.04s" rotate="auto" repeatCount="indefinite" fill="freeze"></animate>`

`ellipse().animate(2040).ease('-').opacity(1)`

values??? keyTimes ???

**Comment by Fuzzyma** [comment]
I cannot work with that. Please formulate a proper bug report that I can work with.

**Comment by skyunBoss** [comment]
### How to convert the following code into svgjs
```
<ellipse stroke-width="0" rx="36" ry="26" opacity="0" fill="rgba(255,255,255,.15)">
  <animate attributeName="opacity" values="0;1;0;0" keyTimes="0;.154;.41;1" calcMode="linear" begin="0s" dur="2.04s" rotate="auto" repeatCount="indefinite" fill="freeze"></animate>
  <animateTransform attributeName="transform" attributeType="XML" type="scale" values="0.5;1;0" keyTimes="0;.41;1" begin="0s" dur="2.04s" repeatCount="indefinite"></animateTransform>
</ellipse>
```
### I do now
`ellipse(26, 16).cx(80).cy(20).stroke({ width: 0 }).opacity(0).scale(0.5).fill('rgba(255, 255, 255, .15)').animate(2040).ease('-').transform({ scale: 1 }).opacity(1).loop()`

**Comment by Fuzzyma** [comment]
What is wrong with your solution?

**Comment by skyunBoss** [comment]
### I want to execute in the time period of 2.04s

`.opacity('0;1;0;0').keyTimes('0;.154;.41;1')`

### Is it supported？

**Comment by Fuzzyma** [comment]
I dont know what that means. You can stack multiple animate calls behind each other.

`el.animate().opacity(0).animate(100).opacity(0.3).animate(400).opacity(1)`

Maybe that helps

**Comment by skyunBoss** [comment]
### That's what I wrote, but the animation is only executed once.

![image](https://github.com/user-attachments/assets/6d9553d8-4126-4dbc-b4a4-0016d3035587)

**Comment by Fuzzyma** [comment]
you have to loop the whole timeline. You only loop the last animationstep. Try:

```js
shape.animate()........animate().opacity(0).timeline().loop()
```

**Comment by aoun-mustafa** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
