### ISSUE TITLE
supported browsers

### ISSUE THREAD

**Issue by sender1977** [svgdotjs/svg.js#133]
The list of supported browsers have IE9 +, but the call SVG.supported in IE9 (IE11) returns false. IE9 + is supported or not?

**Comment by grayter1** [comment]
"IE9 is fully supported" - it concerns version 3.0 also? Foreign objects (which are included in 3.0) are not suported in ie11 and previous according to svg documentation. I tried to create simple project which should display div with colorized background but in ie11 nothing is displayed. Is there some polyfill for foreignobject tag?

**Comment by Fuzzyma** [comment]
Please dont revive old issues which are clearly out of context for your question. Also: It is enough to post at one place. That actually would keep my work load down a bit and I might focus on your specific bug sooner. However, IE11 is definitely not a browser we care a lot about. It just simply doesnt support svg well enough. So only a subset of svg.js might work
