### ISSUE TITLE
Search in docs does not work

### ISSUE THREAD

**Issue by SebastianStehle** [svgdotjs/svg.js#1330]
Hi,

for me the search does not work anymore and the Github icon is also broken.

Just another question: Is there an easy solution to implement a hit test on rotated bounding boxes?

**Comment by Fuzzyma** [comment]
Thanks for letting me know.

You can use rbox() to get the client react around an object. But that's still a box. So if you rotate a react, the rectangle around taht rotated rectangle.
That doesn't work well with hit tests.
You probably need to do the math yourself.

What works best is to transform the hit test point into the coordinate system of the object and do the hit test in the objects coordinate system

**Comment by Fuzzyma** [comment]
fixed the search and ribbon. thanks again!
