### ISSUE TITLE
How to add an <a> tag

### ISSUE THREAD

**Issue by fibo** [svgdotjs/svg.js#135]
Is there some SVG util to create an `<a>` tag containing shapes ?

Something like

``` html
<a xlink:href="http://svgjs.com">
    <rect x="10" y="10" width="60" height="30" rx="10" ry="10" style="fill:lightgrey"/>
    <text x="30" y="30" font-size="12">svg.js</text>
   </a>
```

**Comment by k-j-kleist** [comment]
Note that the documentation for v3.0 (https://svgjs.com/docs/3.0/parents/#svg-a) specifies the method name as link(), but the new method name seems to be linkTo() (see https://github.com/svgdotjs/svg.js/blob/master/src/elements/A.js).
