### ISSUE TITLE
How to add element manually

### ISSUE THREAD

**Issue by MightyPork** [svgdotjs/svg.js#147]
This may not be an issue, but I haven't figured out how to ask a question here.

I want to add a `<title>` element into a rect. It seems the library has no support for titles, so how should I do this?

Thanks.

**Comment by int-ua** [comment]
+1 for adding it to the library or at least posting it on http://svgjs.com/plugins/

**Comment by int-ua** [comment]
Can it somehow be used with `SVG.get()` result to add titles to elements created with `.svg(text);`?
