### ISSUE TITLE
Use SVG.js plugins with RequireJS

### ISSUE THREAD

**Issue by malinin01** [svgdotjs/svg.js#204]
I'd like to include svg.textwap.js plugin into my requirejs application. I can use SVG.js inside module, but inside plugin SVG is undefined. Is it possible to include plugins in AMD way?

**Comment by nolazybits** [comment]
Could we please reopen this issue?
I used to use the 1.1.0 and it worked. Updating to 2.x it now fails.
Trying to use SVG in my code will give me an exception SVG is not defined.

Tthx

**Comment by Fuzzyma** [comment]
You wanna use a plugin or svg itself?

**Comment by nolazybits** [comment]
Well both :)
I ended up doing something like
```
    require(['svg'], function (svg) {
        window.SVG = svg;
        require(['svg.draggable'], function () {
            //  plugins loaded
        });
    });
```

**Comment by Fuzzyma** [comment]
I am not familiar with require.js. Any Idea on how to solve this better in general?

**Comment by nolazybits** [comment]
Honestly I dunno how to make it both non requirejs and requirejs/commonjs compatible, but I googled a bit and found some links...
http://spadgos.github.io/blog/2013/10/19/using-requirejs-and-make-for-standalone-libraries/

**Comment by Fuzzyma** [comment]
Its more about on how adapt the plugins so they can use require.js and so on because svg.js itself has an UMD-Wrapper to support all of these loaders anyway
