### ISSUE TITLE
Firefox 18 throws exception on getBBox

### ISSUE THREAD

**Issue by robwalch** [svgdotjs/svg.js#21]
Firefox has something against 'getBBox()'

NS_ERROR_FAILURE: Component returned failure code: 0x80004005 

(NS_ERROR_FAILURE) [nsIDOMSVGLocatable.getBBox] @ svg.js:374

I'm looking into a workaround as I'm pretty invested in this at the moment. Any advice is more than welcome. I'm thinking the first thing to do is check that the node.method is present, and if not come up with a fallback - possibly something borrowing from jQuery's left/top/width/height methods, unless there are other svg node methods that will get the job done.

Also this might only apply to certain node types. Looking into it...

**Comment by eldamir** [comment]
Had similar problems just recently. Even though I felt certain that the element was added to the DOM, `getBBox` still resulted in `NS_ERROR_FAILURE` with no helpful stacktrace in Firefox 58. Solved it with try/catch around it and manual fallback in the catch block. Thanks for the hints in this thread

**Comment by Fuzzyma** [comment]
if you use svg.js a simpe `el.bbox()` will give you the bbox even if the element is not in the dom.
