### ISSUE TITLE
Move an element to front/back

### ISSUE THREAD

**Issue by chinhodado** [svgdotjs/svg.js#224]
Is there a method to move an element to the front/back (i.e. changing its z-index)?

**Comment by lalitbansal457** [comment]
Hey @wout 

http://documentup.com/wout/svg.js#arranging-elements
This URL is not working

**Comment by HimbeersaftLP** [comment]
@lalitbansal457 The documentation moved, that part can now be found here: https://svgjs.com/docs/2.7/manipulating/#arranging

**Comment by SilverGaucho** [comment]
Maybe someone can help me here.
I want to load svg.js element from file and restore their drawing order.
I can save the order on file and load it and store in a variable but then it reach maximu call stack when I use the following function:

```
//Order loaded element
    function ordering(el,order){
        console.log('ordering '+ el.position(), order)
        if(el.position() > order){
            el.backward();
            ordering(el,order);
        } else if(el.position() < order){
            el.forward();
            ordering(el,order);
        } else {
            return;
        }

    }
```


any suggestion? THX by the way
