### ISSUE TITLE
SVG Scaling not working in Chrome 36.0.1985.125

### ISSUE THREAD

**Issue by memloom-development** [svgdotjs/svg.js#230]
I've not yet figured out if this is an issue with my code, the svg.js library or with Chrome 36.0.1985.125.

However, as of the latest release none of my SVG is scaling i.e. transform='scale(0.5)' doesn't result in a 50% reduction in size - it shows at 1:1 regardless.

I have a production app (in beta) that is fubar because of this.  I know that's no one's problem but my own - but if you know of anything related to this issue any hints would be MUCH appreciated.  Thanks.

**Comment by aydos** [comment]
Here is my situation:
(1) Works on Firefox, Does not on Chrome:
```javascript
var sym = draw.symbol()
sym.path("...")
var s = sym.clone().scale(0.5,0,0)
draw.use(s)
```
(2) Works on Firefox and Chrome
```javascript
var sym = draw.symbol().path("...")
var s = sym.clone().scale(0.5,0,0)
draw.use(s)
```
There are some other combinations work on both browsers. But I need the first one, since I like to add multiple paths to symbol. ```scale()``` after ```use()``` is also working but this time ```dmove()``` is in ```symbol``` metrics, not in ```draw``` metrics.
Is there a solution?

**Comment by Fuzzyma** [comment]
You do have a thinking mistake there.

```
var sym = draw.symbol() // returns a symbol
var sym = draw.symbol().path("...") // returns a path not a symbol
```

So you just clone a path in the second example and use the path not the symbol - big difference.
Scaling the path works but scaling the symbol does not. Iam not even sure if transformations on symbols are allowed from the specs. If its not working in chrome the chances are good its not allowed. However - i have to check.
Meanwhile you can take a look into the viewbox feature of symbol. You could just add a viewbox to the symbol and scale it that way

**Comment by aydos** [comment]
Thanks for quick answer.
I tried viewbox(es) and totally lost metrics, and both browsers show unrelated sizes.
My final solution is:
```javascript
var R=0.3125
var T=1/R
var sym = draw.symbol()
sym.path("...")
sym.path("...")
var s = sym.clone()
draw.use(s).scale(R,0,0).dmove(10*T,10*T)
```
Scale with a ratio, dmove with inverse of the ratio.
