### ISSUE TITLE
Resizing

### ISSUE THREAD

**Issue by bevacqua** [svgdotjs/svg.js#239]
Hey @wout,

I was wondering if there's a native resize UI implementation like you did with draggable, or is it something that I'd have to implement myself from scratch?

Great library!

Thanks,
Nico

**Comment by pjfsilva** [comment]
@bevacqua any news of your work on a resize plugin? I'm very interested in helping on a plugin like that.

**Comment by Fuzzyma** [comment]
http://github.com/fuzzyma/svg.resize.js
