### ISSUE TITLE
Specifying an id for an element

### ISSUE THREAD

**Issue by wattsbn** [svgdotjs/svg.js#246]
I noticed that whenever you create a new svg element/shape, it is automatically given an id.
For example, the following will log something similar to `SvgjsRect1006` to the console.

``` javascript
var draw = SVG('drawing').size(300, 300);
var rect = draw.rect(100, 100);
console.log(rect.node.id);
// logs: SvgjsRect1006 
```

I can obviously change this element's id myself. However, since it was already set when its created, I am wondering if you are using that id somewhere. Is it safe to change it? Is there a way to set the id at creation time?

**Comment by MCDELTAT** [comment]
Just a quick related question: I'm creating many elements in a loop using the use() function. What's the best way to give each a unique id? Create a new object each iteration and set the id by counter? Apologizes, just coming over to JS.

**Comment by Fuzzyma** [comment]
Use the id given from svg.js. They are already unique. There is no need to create our own.
As you can see above you can retrieve your id with: `rect.node.id()`

**Comment by dryqiao** [comment]
@Fuzzyma Hi,I use `rect.node.id()`,got an error `typeError: rect.node.id is not a function`

**Comment by Fuzzyma** [comment]
Use rect.id()
Am 28.09.2018 07:34 schrieb "QIAO" <notifications@github.com>:
