### ISSUE TITLE
SVG.js on server side

### ISSUE THREAD

**Issue by jonywtf** [svgdotjs/svg.js#279]
How can i use svg.js with node.js on server side?
I want to render svg to string and save to file.

Can i get **var draw = SVG('drawing')** with no  'drawing'?
And save to string svg data. For example:
var svg_string = draw.render_to_string();

**Comment by Fuzzyma** [comment]
@jonywtf I dont know if its still relevant but we just released the new project [svgdom](https://github.com/svgdotjs/svgdom) which enables svg.js to run on node. Its nothing big but give it a try and report back :)

**Comment by fibo** [comment]
check out also [svgx](https://www.npmjs.com/package/svgx) which is renders SVG server side
