### ISSUE TITLE
Methods mimicking non-native attributes only work when all values involved are unitless

### ISSUE THREAD

**Issue by snowyplover** [svgdotjs/svg.js#400]
[Edit: This issue was originally titled "Center-based positioning methods do not work when attributes have units #400"]

Thanks for all the great work you've done on this library. I've been enjoying using it.

The problem I've been having stems from the `cx` and `cy` methods, which treat the values of `width` and `height` as purely numerical. If those attributes have values such as `'100%'`, the methods end up returning `NaN` (on get), or setting `x` and `y` to `0` (on set).

[This jsFiddle](http://jsfiddle.net/bbv4kv4q/5/) demonstrates the problem in the type of context I found it (in case I've somehow missed something).

**Comment by Fuzzyma** [comment]
This is more or less a feature and not a bug.
When you use center it itself calls `width()/2`. Imagine when every call to with would call `bbox()` to determine the width rather than just pulling it from the dom. It would be a huge performance issue.
Thats why it simply doenst work.

Just calculate the center on your own using bbox maybe like this: http://jsfiddle.net/bbv4kv4q/6/

**Comment by snowyplover** [comment]
I see your point regarding performance. I also certainly wasn't suggesting the problem lay in the behavior of `width()` -- I imagine it would be rather confusing if ordinary calls to `width` returned anything other than the value that was set.

However, it would be good to prevent the need for anyone else to spend time stepping through code to figure out why `center()` is misbehaving. Stated that way, the easiest fix is probably to change the documentation to say that `cx`, `cy`, and `center` only work on elements sized in user coordinates. The issue with that fix (and with the current setup in general) could be that elements such as `circle` for which `cx` and `cy` are standard svg attributes might not work as expected.

The fix I originally imagined would look something like:
```javascript
cx: function(x) {
  var w = this.width();
  try {
    w = +w;
  } catch (e) {
    // convert value
  }
  return x == null ? this.x() + w / 2 : this.x(x - w / 2);
}
```
A more general version of this solution might be a 'force user coordinates' flag for `width()` and `height()`, e.g.
```javascript
width: function(arg) {
  var width;

  if (typeof arg != 'boolean' )
    // treat arg as (possible) value of width attribute
    return this.attr('width', arg);

  // else treat arg as a force user coordinates flag
  width = this.attr('width')
  if (arg) {
    try {
      width = +width;
    } catch (e) {
      // convert value
    }
  return width;
}
```
`cx` could then call make a call to `width(true)` in the appropriate place.

The workaround I'm currently using is a method that explicitly converts coordinates from percentages to user space. So the `rect` in my jsFiddle example becomes
```javascript
tile.rect('100%', '100%')._percentToUserSpace().center(0,0);
```
Of course, this only works because I'm using % units for convenience and clarity in the code, and I don't care if the program stores the attributes that way. This fix does also avoid the overhead of the previous ones, but leaves the unexpected behavior of `cx`, `cy`, and `center` in place. My implementation is a hack, but perhaps the general idea is ok.

Anyway, I am intending to suggest a few a changes to the documentation, and I can include the one noted above. Other than that I'm just throwing ideas at the wall to see if anything sticks.

**Comment by Fuzzyma** [comment]
I am afraid I dont know how to handle this issue. I see myself open it again and again without writing anything.
I dont like the fact that it needs so much code.
However a unit conversion is a thing which is not reliable anyway. See the case where a parent is sized in percent, too. You would have to recursively calcuate the new sizes.
I dont think that such magic should be done in a rather simple function.
I think if someone would do something like that he should set the values in percentage, get the bbox and get the center of the box.
Of course that is something the user need to know but its not impossible to figure out

**Comment by snowyplover** [comment]
As became clear while working on the documentation, the issue I initially raised does not capture the scope of the problem well:
* My notion that, when `cx` and `cy` are applied, elements (such as `circle`) which natively use center based positioning might show similar behavior to a `rect` was inaccurate. The library ensures that calculations on native attributes will be done by browser code which is already set up to deal with unit issues.
* On the other hand, the issue is not restricted to center-based positioning, but shows up any time the library provides methods that mimic attributes not usually attached to a given element type (`cx` on `rect`, `x` on `circle`, etc).

Now that the documentation notes the circumstances under which using units fails to produce desired behavior, the issue should appear to users as a limitation of the library, rather than a bug. The source of the problem should be discoverable without stepping through code or combing through source files.

So the issue currently appears to be: is this an ok limitation for the library to have?

From a theoretical point of view, I would say that it's not ok. The intent of the library is to provide a convenient and consistent syntax for manipulating svg elements, a syntax that is, hopefully, more intuitive and less fussy than that provided by the svg standard. As I see it, a user should not need to know which attributes are native to which elements in order to use the library.

Anyway, it's a nice theory :)

So, is getting rid of this limitation worth whatever effort and/or performance hit it would take to fix it?

I don't really know. I'm still quite inexperienced with javascript and svg. I have a few ideas, but I can't necessarily tell if they'll work.

I did notice there's code for recursively calculating sizes in the `SVG.ViewBox` constructor that might possibly be refactored. `SVG.Number` also seems to have something to do with calculating from units.

I've been wondering if it might be possible to always store the size in user coordinates on the svg.js element objects so that it's available for calculations. Or perhaps some kind of lazy evaluator: the number would only be calculated once, and then only if needed. However, it seems unlikely this idea will work well with the animation code (which I haven't looked at yet).

It looks like the positioning methods were written over a year and half ago. If I'm the first person to complain, it seems likely that any non-trivial fix isn't worth it. For now maybe we just leave the issue open and see if anyone thinks of something? (And perhaps I should edit the issue title?)

**Comment by Fuzzyma** [comment]
You covered the whole issue quite well.
It is indeed a limitation of the library. If it would be possible you would be able to do something like this:

```javascript
var rect = draw.rect(100,100).cx('50%')
```

However even when you calculate the correct position of this element you still have to make sure, that the position adapts whenever the size of the parent element is changed.
That leads to a huge recalculation of many objects whenever one parent changes its size.
I would implement that using events. Whenever a percentage value is set, i would bind to the `resized` event or something similar which is fired, when an elemend changes its size. So I could adapt to the change.
But what would happen if someone calls `cx('50%').dx(20)`? Can we assume, that the user doenst want relative behavior at this point anymore? Or do we have to think about a way to always set the element at 50% + 20px?

The idea to always hold an absolute value of everything seems ok as long as the parent element doesnt change (you would have to calculate all absolute valus at once again). You then could determine a relative size or position faster.
Well - its much code...

The Code in SVG.Number doesnt help here because the unit conversion is only done to make sure that the number is morphable (and animatable). It actually has nothing to do with calculating some absolute value based on the relative.

However its an interesting issue and I will let this open. If you like to rename it feel free to do so :)

**Comment by snowyplover** [comment]
I think your examples get at the problem here well.

```javascript
var rect = draw.rect(100,100).cx('50%')

rect.cx('50%').dx(20)
```

The fact that methods are named after attributes suggests that they operate on a quantity that acts like an XML attribute in the sense of being a persistent quantity that appears in a well-specified (if possibly virtual) document. In other words, a method that sets an attribute doesn't say to an object "do this" (e.g. move yourself *there*), it says "be this" (e.g. part of your definition as an object is that your position is derived from *this* quantity).

A "do this" method implies (at least the way I'm thinking of it here) that the user doesn't care *how* it gets done: it tells the object, "I don't care how you think about your coordinates as long as you end up where I want". A "be this" method carries the expectation that the designated characteristic is recoverable in the same format it was given: intuitively, `rect.cx('50%').cx()` ought to return `'50%'`.

However, as it stands, when you set a position with `rect.cx()`, you *are* actually saying "do this", as there is no `cx` attribute to set. And that, I think, is what is bothering me here. Not only are the positioning methods both getters and setters (which is fine), they are two conceptually different kinds of setters, depending on the object that calls them. In my previous comment, I think the instinct I was following is that these methods should all be acting like "be this" methods, whether or not the underlying attribute exists. (The same notion also appears to be reflected in the examples I quoted.)

Another solution, though, would be to make sure "do this" behavior and "be this" behavior are not overloaded onto the same methods. In other words, methods named after svg attributes could only be available on the elements that possess those attributes, but there could be a separately defined set of generalized methods that could be used by all elements. Currently, `dx()`, `dy()`, and `dmove()` are this type of method.

Since the generalized methods would not be trying to mimic attributes, their functionality can be defined along lines that match the library implementation, e.g. such methods might only accept numerical arguments.

This route solves the difficulties in the quoted examples as `rect.cx('50%')` would no longer a valid statement. However, it does not solve my original problem. Suppose there is a new method called `centerX`. Then `draw.rect('100%', '100%').centerX(0)` still seems like a reasonable sequence.

Approaching things this way also simplifies user expectation questions. Mechanisms about which the user has distinct prior expectations -- anything directly modeled on XML structures or the SVG standard -- are separate from library-specific extensions, which can be defined more freely.

Anyway, that's how I ended up thinking this through. Whether it is worth implementing seems to be more dependent on the overall vision for what the library should be rather than fixing a particular problem. However, it does at least appear to be more manageable than fully persistent non-native attributes.

**Comment by patapron** [comment]
Hello everyone,

I have used all this method to set position to an element in my app, using realative value (%)
but it doesn't seem to work.


First, I load an external svg, I get the svg file "g" and insert this into a "draw.svg" serializing it.
( If anyone knows a better way to to this, please, tell me.


```

//declaration
  fetch("sensor.svg")
  .then(resp => resp.text())
  .then(svgtxt => {
      let t1 = parser.parseFromString(svgtxt, "image/svg+xml").getElementsByTagName("svg")[0].childNodes[0];
      t1.setAttribute("id", "idSensor1");
      draw.svg(new XMLSerializer().serializeToString(t1));


//from here

      draw.findOne("g#idSensor1").transform({
        relative: {x: '50%', y: '50%'}
      }) 
//or
      draw.findOne("g#idSensor1").transform({
        translate: {x: '50%', y: '50%'}
      })
/or ...
      draw.findOne("g#idSensor1").transform({
        translateX: '50%',
        translateY: '50%'
      })

      draw.findOne("g#idSensor1").center('50%','50%');
      draw.findOne("g#idSensor1").cx('50%').cy('50%');
      draw.findOne("g#idSensor1").x('50%').y('50%');
      draw.findOne("g#idSensor1").move('50%','50%');
      draw.findOne("g#idSensor1").dmove('50%','50%');
      draw.findOne("g#idSensor1").attr({ x: '50%', y: '50%' });
      draw.findOne("g#idSensor1").attr({ cx: '50%', cy: '50%' });
```

I need user percentage values, but I can't position it
