### ISSUE TITLE
Deprecation Warnings in Chrome offsetWidth and offsetHeight

### ISSUE THREAD

**Issue by bbergmann** [svgdotjs/svg.js#467]
Chrome Deprecation Warning:
'SVGElement.offsetWidth' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.
tests.js:181 
'SVGElement.offsetHeight' is deprecated and will be removed in M50, around April 2016. See https://www.chromestatus.com/features/5724912467574784 for more details.

I have not been able to sort out where if anywhere in my own code I might be causing these warnings.
In searching the source for svg.js, I am finding offsetWidth and offsetHeight being called only with the ViewBox object. lines 949 and 954 in svg.js version 2.5.5. 
In researching this I found mention that calling jquery .position() and offset() on an .svg element can also cause this warning, but I am not making those calls.

Is this a problem? I don't know svg.js and svg well enough to propose a workaround or solution.

**Comment by wout** [comment]
Thanks for reporting this.
It seems that `getBoundingClientRect()` can be used as a replacement for `offsetWidth` and `offsetHeight`.

**Comment by Fuzzyma** [comment]
>These attributes should only be supported on HTMLElement, but have been supported on all Elements in WebKit and Blink. getBoundingClientRect() can typically be used as a replacement.

As far as I know we are only using it on Html elements and not on svg elements (I think I found an error in the code regarding this but this is another thing) 
I will post code references when I have the time to do so

**Comment by ghost23** [comment]
Hi,

in fact, all offset* Parameters are now gone with latest Chrome. offsetParent, offsetTop, offsetLeft, offsetWidth, offsetHeight.

There is no direct replacement for offsetParent.

SVG.js uses offsetParent and offsetLeft/Top in its RBox Element, for example.

**Comment by wout** [comment]
What's the status on this issue?

**Comment by Fuzzyma** [comment]
The viewbox zoom feature will be removed in 3.0 so this is solved in the [3.0 branch](https://github.com/svgdotjs/svg.js/tree/3.0.0)
