### ISSUE TITLE
Animating gradient colors

### ISSUE THREAD

**Issue by RoBorg** [svgdotjs/svg.js#51]
Not sure is this is a bug, feature request or documentation thing, but animating gradient colors could definitely be easier.

1) It seems you have to take a reference to each stop when you add it to the gradient, like this:

``` javascript
var s1, s2, s3

draw.gradient('radial', function(stop) {
  s1 = stop.at({ offset: 0, color: '#000', opacity: 1 })
  s2 = stop.at({ offset: 50, color: '#f03', opacity: 1 })
  s3 = stop.at({ offset: 100, color: '#066', opacity: 1 })
})

s1.update({ offset: 10, color: '#0f0', opacity: 1 })
```

To me, it would be a lot cleaner if there was a getStops() or getStop(index) method on the Gradient.

2) The update() method is not animatable - i.e. you can't do this:

``` javascript
s1.animate().update({color: '#0f0'}); // Doesn't work
```

This would be really nice to have.

3) Animating the stop-color attribute doesn't work (at least in Chrome) because when the stop is created it adds style="stop-color: ...", which overrides the stop-color attribute.

``` javascript
s1.animate().attr({'stop-color': '#0f0'}); // Doesn't work
```
## Workaround

If you don't supply a color when you create the stop, then you can animate with the stop-color attribute

``` javascript
var s1, s2, s3

draw.gradient('radial', function(stop) {
  s1 = stop.at({ offset: 0, opacity: 1 }) // No color!
  s2 = stop.at({ offset: 50, color: '#f03', opacity: 1 })
  s3 = stop.at({ offset: 100, color: '#066', opacity: 1 })
})

s1.attr({'stop-color': '#000'});
s1.animate({'stop-color': '#0f0'}); // This now works
```

**Comment by heaversm** [comment]
I still don't understand the proper implementation. Could you possibly give an example of animating a gradient?

**Comment by Fuzzyma** [comment]
This is a question for stackoverflow. You can tag it with svg.js and we will come back to you. We also habe great docs at svgjs.com. I am pretty sure you can fing what you are looking for there :).

**Comment by heaversm** [comment]
I was still a little bit shaky on how ot implement this. I feel like this might help others for clarity. The animated syntax would be:

```
s1.animate()
    .attr({
        'stop-color': '#0f0',
    });
```

**Comment by Fuzzyma** [comment]
The correct way of doing it is the `update` method.

```js
s1n.animate().update('color', '#0f0')

// or 
...update({color: '#0f0'})
```

**Comment by nikitakotenko88** [comment]
What about existed gradients in def? How to animate them?

**Comment by nikitakotenko88** [comment]
What about existing gradient? How to animate them?

**Comment by nikitakotenko88** [comment]
by SVGjs author:

> Yes, another change here. Basically the constructor for the stop-element was renamed to `stop` for consistency:
```
var linear = draw.gradient('linear', function(add) {
  add.stop(0, '#f06', 1);
  add.stop(1, '#0f9', 1);
});
```

**Comment by Fuzzyma** [comment]
@nikitakotenko88 please dont revive old issues. Gradients can be animated as seen above. If you need to get the correct `stop` element you can simply get them with `SVG('#gradient_id:nth-child(2)')` or similar (v3.x)
