### ISSUE TITLE
back(), backward() not properly working for Foreign Objects

### ISSUE THREAD

**Issue by Santhoshsvg** [svgdotjs/svg.js#520]
Hi,

I am trying to arrange the elements in my application which is similar to an editor where the user can paste multiple svg elements and the display order can be changed for the elements with the four given options front(), forward(), back() and  backward().

All the above functions work properly for all the objects except For.Object. When executed back() on a foreign object, the foreign object is getting moved to the first position on the child list of the svg canvas, but the display of the child element of the foreign object in the html is not getting changed.

Any workaround for this?

**Comment by Fuzzyma** [comment]
Please give us some code to work with. As I understand your problem, your object gets correctly moved to the first position. So I dont know what your poblem is, because we dont care about child elements when calling `back()`

**Comment by Fuzzyma** [comment]
@Santhoshsvg I would like to know if this is still an issue. A feedback from you would be helpfull.
Otherwise I will close this in a few days...

**Comment by Santhoshsvg** [comment]
Sorry, didnt turn up here.
and currently not using this functionality.

so will close this issue.

Sorry for the inconvenience created.
