### ISSUE TITLE
Could you please provide me the typescript library which can be used in angular 2

### ISSUE THREAD

**Issue by yashwanthkata** [svgdotjs/svg.js#522]
Could you please provide me the typescript library which can be used in angular 2?

**Comment by Fuzzyma** [comment]
How is the typescripf file in the repo differnt from the the one you need in angular?

**Comment by yashwanthkata** [comment]
Getting lot of errors using the typings provided 
?

**Comment by Fuzzyma** [comment]
@rdfriedl isnt the typescript definition up to date?

**Comment by yashwanthkata** [comment]
this.svg.polyLine is not a function

**Comment by rdfriedl** [comment]
i cant say whether it is up to date or not, also there are a few odd bugs in it.
i built it over the course of a few days so i was not able to test everything.

if you could provide some code that is throwing the error that would help, though i cant say if i have time to fix it 😕

**Comment by aasukisuki** [comment]
For those wanting to use svg.js with Angular2 (or just wanting to use modules) here's how you can do it.  Define your import statement like this:

`import * as SVG from 'svg.js';`

You should then be able to use svg.js as the documentation states.  For typing your objects, all the definitions will also be on the SVG object (SVG.Element, SVG.Path, etc).

Hope this helps.

**Comment by Fuzzyma** [comment]
@yashwanthkata is this still an issue? If so, please give us a feedback. Otherwise I will close this in a few days...
