### ISSUE TITLE
jsfiddle broken - needs updating

### ISSUE THREAD

**Issue by dkebler** [svgdotjs/svg.js#523]
Can you update the jsfiddle svg.js playground?? (all your svg.js fiddles seems to have same issue)
https://jsfiddle.net/Vac2Q/6564/

Seems all old, by default it runs 0.x and that doesn't render anything, when I changed it to 2.1.1 (only other choice) the rectangle renders but the events don't fire.   Maybe better to load svg.js in html instead of via jsfiddle so latest releases can be used?

**Comment by Fuzzyma** [comment]
New page is at svgdotjs.github.com

**Comment by wout** [comment]
@dkebler 
A new playground is planned:
https://github.com/svgdotjs/svg.js/projects/2#card-1789609

For the time being, you'll need to grab the [latest SVG.js](https://cdnjs.com/libraries/svg.js) from CDNjs and add it as an external resource. Or you can use rawgit to grab the latest from source:

https://cdn.rawgit.com/svgdotjs/svg.js/master/dist/svg.min.js
