### ISSUE TITLE
dx() and dy() don't work with a percent value.

### ISSUE THREAD

**Issue by yiida-tempus** [svgdotjs/svg.js#524]
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>x</title>
  <script type="text/javascript" src="js/svg.js"></script>
</head>
<body>
  <div id="drawing"></div>
  <script>
  var draw = SVG('drawing').size(300, 300);
  var rect = draw.rect(100, 100).attr({ fill: '#f06' }).x("0%").y("0%");
  rect.dx("33.3%").dy("33.3%");
  </script>
</body>
</html>
```

Show the above code on Chrome, and get errors like `Error: <rect> attribute x: Expected length, "0%33.3%".`
svg.js version is 2.3.4.

**Comment by SegersIan** [comment]
Same here, I tried to use `SVG.Numer()` but that throws the exception `svg.min.js:1 Error: <rect> attribute x: Expected length, "0%undefined".`

**Comment by Fuzzyma** [comment]
see #400 as reference

**Comment by Fuzzyma** [comment]
@yiida-tempus @SegersIan Please confirm that its fixed for you with the current master

**Comment by yiida-tempus** [comment]
@Fuzzyma I confirmed the following case:
```
var draw = SVG('drawing').size(300, 300);
var rect = draw.rect(100, 100).attr({ fill: '#f06' }).x("0%").y("0%");
rect.dx("33.3%").dy("33.3%");
```
There are no errors, it works fine for calculating percent values.
(But I'm not sure the result of calculations with other SVGLength such as 'px' + '%' or '%' + 'em'.)

Thank you for the release and reply.

<br>
Should I close this issue?

**Comment by SegersIan** [comment]
@Fuzzyma : Work fine now ! Thanks

**Comment by Fuzzyma** [comment]
Thx for the confirmation. I am aware of the use case of px + %. In this case it wins the unit which was used in dx. That's kinda nonsense and we have to clarify this in the docs.
