### ISSUE TITLE
Separate out DOM-dependent code from svg.js

### ISSUE THREAD

**Issue by vivid-inc** [svgdotjs/svg.js#528]
We are using your wonderful svg.js library to produce SVG-based visualizations. Thanks for all the work that you have done on it.

The visualizations we do often end up being large/complex, which demands a lot of processing power – and users feel this as their browsers become momentarily unresponsive while the visualization is computed and the subsequent SVG document building takes place. So, we are looking into moving that code, along with the svg.js library, into a Web Worker. It seems that svg.js itself is dependent on the DOM in several places, whereas the DOM is unavailable in Web Workers. It seems as though the DOM could still be created and rendered to a string then communicated from the Web Worker back to the main thread through a message for direct insertion into the DOM.

**Comment by Fuzzyma** [comment]
I read from the subject, that you want us, to sort out dom depentent code fom svg.js.
Unfortunetaly svg.js wont work anymore when you do that. The creation of every object is bound to the dom. Dom objects are generated immediately when you create an svg.js object.
You could try to use a dom simulation like jsdom but svg is not implemented in their dom api until now.
See https://github.com/tmpvar/jsdom/pull/1445 as reference

**Comment by vivid-inc** [comment]
Thanks for replying. At the least I am/was hoping to stimulate discussion, possibly leading to me gaining enough information in order to enable to me do the work myself and then submit a PR.

To me, conceptually it's possible to create an SVG without a DOM, but there are limitations i.e. DOM listeners cannot be meaningfully attached to nodes when there is no DOM. Even from a cursory reading of the svg.js source code, I see much usage of DOM methods, primarily methods on node and some on document, so the surgery involved might not be trivial or even desirable to you. Your PR for jsdom above seems to be a more reasonable path? If there is something I might be able to do to help move that PR forward...

**Comment by Fuzzyma** [comment]
Yes ofc you can build an svg document out of strings and let the browser parse this string. But thats not what svg.js is doing. It builds the svg document out of dom nodes. Therefore it needs a dom.
One yould try overwritin the SVG.create methods to do what you want but thats smells like much work.
However: Implementing svg into jsdom is not less work.
When I tried doing it I was overwhelmed from the big framework jsdom is using to simulate dom properties. Actually I just need someone to explain me how things are working in jsdom so I can start implementing svg...

**Comment by Fuzzyma** [comment]
@vivid-inc we just released the new project [svgdom](https://github.com/svgdotjs/svgdom) which enables svg.js to run on node. Its nothing big but give it a try and report back :)
