### ISSUE TITLE
Move svg.js from wout to an organization

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#533]
Since we want contributors to have access to e.g. travis-ci settings, which requires administration privileges to the github account, we want to move svg.js to an organization.

Steps before we fully moved to [svgdotjs](https://github.com/svgdotjs)

Here is a list of links that will need to change, when we change github account for svg.js:
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 1        [travis-ci](https://travis-ci.org/wout/svg.js)
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 2015  [svg.easing.js](https://github.com/wout/svg.easing.js) plugin.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3438  [svg.pathmorphing.js](https://github.com/wout/svg.pathmorphing.js) extension.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3881 [svg.pathmorphing.js](https://github.com/wout/svg.pathmorphing.js) to make path animatable
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3884 [svg.textmorph.js](https://github.com/wout/svg.textmorph.js) to make text animatable
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3887 [svg.absorb.js](https://github.com/wout/svg.absorb.js) absorb raw SVG data into an SVG.js instance.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3890 [svg.draggable.js](https://github.com/wout/svg.draggable.js) to make elements draggable.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3898 [svg.easing.js](https://github.com/wout/svg.easing.js) for more easing methods on animations.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3901 [svg.export.js](https://github.com/wout/svg.export.js) export raw SVG.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3904 [svg.filter.js](https://github.com/wout/svg.filter.js) adding svg filters to elements.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3910 [svg.import.js](https://github.com/wout/svg.import.js) import raw SVG data.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3925 [svg.shapes.js](https://github.com/wout/svg.shapes.js) for more polygon based shapes.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3928 [svg.topath.js](https://github.com/wout/svg.topath.js) to convert any other shape to a path.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3931 [svg.topoly.js](https://github.com/wout/svg.topoly.js) to convert a path to polygon or polyline.
- [x] [README.md](https://github.com/wout/svg.js/blob/master/README.md) line 3934 [svg.wiml.js](https://github.com/wout/svg.wiml.js) a templating language for svg output.

**Comment by Fuzzyma** [comment]
From the [docs](https://help.github.com/articles/about-repository-transfers/):
>All links to the previous repository location are automatically redirected to the new location. When you use git clone, git fetch, or git push on a transferred repository, these commands will redirect to the new repository location or URL. However, to avoid confusion, we strongly recommend updating any existing local clones to point to the new repository URL

**Comment by dotnetCarpenter** [comment]
@wout Are we moving all of svg.js plugins to the new organization, or only some or nothing?

**Comment by wout** [comment]
We'll be moving everything to the organisation. There's no use in keeping anything on my account. I suggest all SVG.js plugins owned by the three of us to be moved to the organisation. Unless you guys object :)

**Comment by wout** [comment]
@dotnetCarpenter Are there still things left to do before moving alle plugins to the organisation?

**Comment by dotnetCarpenter** [comment]
@wout not as far as I know. I think we can just move the repositories, update the `package.json`, e.g.
```json
"repository": {
    "type": "git",
    "url": "https://github.com/wout/svg.js.git"
  },
  "github": "https://github.com/wout/svg.js",
```
and then we're done. Well, we should still update the README, and if issues are not automatically moved then we could use something like https://github-issue-mover.appspot.com/.

I cannot think of anythings else we need to do. Is the website hosted on github pages? If yes, then we'll need to enable that in the repo. Again only, if this doesn't happen automatically.

**Comment by dotnetCarpenter** [comment]
I'll deprecate the `svgjs` package (#541) with a message with a link to our new home, once we have moved.

**Comment by wout** [comment]
SVG.js lives in the organisation now. Moving on to the plugins now.

**Comment by wout** [comment]
That's all done now. Next up is the new website.

**Comment by dotnetCarpenter** [comment]
ok, writing deprecating with our new url.
Nice logo btw ;)

**Comment by dotnetCarpenter** [comment]
@wout did you require two-factor authentication for the svgdotjs org? My phone is not working in Greenland, so I'm locked out of svgdotjs.

**Comment by dotnetCarpenter** [comment]
Travis moved to https://travis-ci.org/svgdotjs/svg.js

**Comment by dotnetCarpenter** [comment]
@wout [svg.pathmorphing.js](https://github.com/wout/svg.pathmorphing.js) and [svg.textmorph.js](https://github.com/wout/svg.textmorph.js) is still not moved. But everything else mentioned in the README is moved to the new org

**Comment by dotnetCarpenter** [comment]
@wout about documentup - it doesn't seem like I can do anything to update here. I have updated the README, pushed it to master and ran `gulp docs` but nothing seems to have changed. http://documentup.com/wout/SVG.js

Wait I was wrong - http://documentup.com/svgdotjs/SVG.js is the new place. Don't know how to remove the old one though

**Comment by dotnetCarpenter** [comment]
I think we should do a 3.6.7 release to update the readme on npm. Do you @wout and @Fuzzyma have something that should go into the next patch release?

**Comment by wout** [comment]
@dotnetCarpenter 
svg.pathmorphing.js and svg.textmorph.js are not managed by me .

@Fuzzyma 
Can you move them to svgdotjs?

**Comment by wout** [comment]
@dotnetCarpenter 
Documentup will be replaced by our own docs, so don't worry about that.

But please enlighten me about the 3.6.7 release...

**Comment by dotnetCarpenter** [comment]
sorry **2.3.7** - it was just to update the readme shown o npm. But we might not need to make a release to do that. Perhaps we can just republish with the corrected README.

**Comment by wout** [comment]
Yeah, I’ll disable it right away.

**Comment by Fuzzyma** [comment]
Looks like everything happens, when I am not there for a short moment :D.
Yes I can move my plugins, too. But will need some time, though.
Imo there is no release required for just updating the readme. No code changed. And teh current readme is always shown anyway so no need to pulish or even tag that.
I like to think about it as a user. I wouldnt like to update my library every day and when I do I want new stuff in it :D

**Comment by dotnetCarpenter** [comment]
@Fuzzyma You right about the user perspective. But alas the documentation on npm doesn't show the current README, only the `npm publish`ed one. It is not possible to update npm without doing a new release. But since most of our links are to github and that github redirect old URL's to the new svgdotjs. I think you're right that we shouldn't do a release unless we have something substantial to release.
https://www.npmjs.com/package/svg.js

**Comment by Fuzzyma** [comment]
We forgot to change all the plugins on npm and their package.json. Also whats about bower? I did not get any answer to my question: https://github.com/bower/registry/issues/226

**Comment by wout** [comment]
I'm not familiar with bower at all. If the plugins were bowered, it was done by someone else. So I'm not really familiar with the issue.

**Comment by dotnetCarpenter** [comment]
I just updated one of my projects which depends on svg.draggable.js, svg.topath.js and svg.js and it seems to not be an issue. They resolve to the old `github.com/wout/` address and then redirects to `github.com/svgdotjs/` address. I'm not aware of what will happen when wout reclaim one of the old github repository names... But currently its not an issue.
Unfortunately it's not possible to re-register a bower component on another address. If we run into trouble, then we can try to unregister a package and then register it again with the new URL. Hmm how is it? Don't fix what ain't broken?

**Comment by dotnetCarpenter** [comment]
Anyhow, we should either update or remove the URL in `bower.json` in each repo as part of our maintenance. I suspect that many plugins don't work with the current version of svg.js, so we need go through them anyway.

**Comment by wout** [comment]
> I'm not aware of what will happen when wout reclaim one of the old github repository names... 

Won't happen :)

> Don't fix what ain't broken?

Agreed. As long as it redirects, everything is fine.

> I suspect that many plugins don't work with the current version of svg.js, so we need go through them anyway.

True. Many plugins are even obsolete because their functionality is baked into SVG.js (e.g. import, export, absorb, ...).

**Comment by dotnetCarpenter** [comment]
@Fuzzyma is there any reason why you haven't moved https://github.com/Fuzzyma/svg.pathmorphing.js and https://github.com/Fuzzyma/svg.textmorph.js? Should I close this issue?

I just installed **svg.easing.js** via npm without issues. I agree that we should update their respective `package.json` but can we agree to do that when we go through each package?

**Comment by Fuzzyma** [comment]
No there is no reason. I just didn't have come to that yet. Maybe at Monday
I will find some time...

Am 04.11.2016 18:38 schrieb "Jon Ege Ronnenberg" <notifications@github.com>:

**Comment by dotnetCarpenter** [comment]
@wout What happen to [svg.textmorph.js](https://github.com/wout/svg.textmorph.js)?

@Fuzzyma Do you still want to move [svg.pathmorphing.js](https://github.com/Fuzzyma/svg.pathmorphing.js) to [svgdotjs](/svgdotjs)?

These two plugins are the only outstanding issues here. Then we can close this.

**Comment by Fuzzyma** [comment]
oh yes ofc. Already forgot this again

**Comment by Fuzzyma** [comment]
Done - I wanst aware that I have so much of them. My repository page is now locking so empty :/
Btw: The textmorph plugin was mine. With the new fx module I need to rewrite it a bit to make it better :)

**Comment by dotnetCarpenter** [comment]
@Fuzzyma try this first: https://github.com/svgdotjs/svg.js/issues/586#issuecomment-279088004

If that doesn't work then you have to create an issue at https://github.com/bower/registry/issues and perhaps even write them an email team@bower.io, as @wout did.

:dancing_men: nice that you moved all. I'm excited about trying them all out!
