### ISSUE TITLE
viewbox().zoom returns 0 in 2.3.5 and calculates the zoom in 2.2.5 (for svg elements with dynamic width/height)

### ISSUE THREAD

**Issue by ohjames** [svgdotjs/svg.js#542]
I have this code:

``` javascript
const bbox = svgJsObject.bbox()
svgJsObject.viewbox(bbox)        
const vbox = svgJsObject.viewbox()
// in 2.2.5 vbox.zoom is correct, in 2.3.5 it is 0.
```

This should calculate the zoom according to how the bounding box fits in the svg element. In `2.2.5` this worked great, in `2.3.5` I always get an invalid zoom value of `0`.

**Comment by Fuzzyma** [comment]
Does it correctly set the viewbox on the element?

**Comment by ohjames** [comment]
@Fuzzyma yes, in both versions. The only issue I'm seeing is the faulty zoom calculation. This makes it impossible for me to convert between svg units and pixels.

**Comment by ohjames** [comment]
Although I assume the zoom can be calculated from `Math.min(vbox.x / bbox.x, vbox.y / bbox.y)`

**Comment by ohjames** [comment]
Hm there seems to be more issues with the bbox()/vbox() calls...

```javascript
const bbox = svgJsObj.bbox()
svgJsBbox.viewbox(bbox)
const vbox = svgJsBbox.viewbox()
const newBbox = svgJsBbox.bbox()
```

After this call newBbox and bbox are different! `newBbox` ends up with a much taller `height`. But setting the vbox shouldn't cause the bbox to change? In both cases the bbox fits inside of the vbox.

**Comment by Fuzzyma** [comment]
could you pls provide a jsfiddle which shows your issue?

**Comment by ohjames** [comment]
Unfortunately I'm super low on time and given I've found a work around with:

```
vbox.zoom = Math.min(this.container.width() / vbox.width, this.container.height() / vbox.height)
```

I'm having to move on from this.

This bug is so trivial to reproduce that I'm sure someone else will report it soon though, or that you'd be able to check it out with just a few seconds.

**Comment by ohjames** [comment]
I debugged svg.js a bit and I see on line 3135:

```javascript
        this.zoom = ((this.width / this.height) > (width / height)) ?
          this.height / height :
          this.width  / width
```

Here `this.width` and `this.height` are both, incorrectly, 0 (despite the vbox having a correct width and height).

**Comment by ohjames** [comment]
Ah, `this.width` and `this.height` come from `attr('width')` and yet my SVG has no width set... it is sized dynamically. So I think there it should use the calculated width rather than the width set via attributes.

**Comment by Fuzzyma** [comment]
Well I am a bit curious why this worked in 2.2.5 then. I am pretty sure we didnt call bbox to get the svgs width and height there. Could be wrong though...

**Comment by ohjames** [comment]
We held off upgrading to 2.3.x for a while due to this issue but eventually it became necessary when the performance improvement was released.

**Comment by Fuzzyma** [comment]
Are you sure, that no width and heiht is set on your svg? Because of so, both codes produce the same result.
Please check if there is not a `width=100% height=100%` in your svg. That would explain a lot

**Comment by Fuzzyma** [comment]
@ohjames please come back to my last question which is really important to find a fix for this problem

**Comment by Fuzzyma** [comment]
Closed due to no feedback
