### ISSUE TITLE
What's the best way to inject an existing SVG string to an SVG document?

### ISSUE THREAD

**Issue by peterschmidler** [svgdotjs/svg.js#544]
I am currently using ...

```js
svg = "<svg> ... </svg>"
group = draw.group()
svgjs = group.nested().svg(svg)
```

but i have the impression that there might be a cleaner way without the group element...

**Comment by Fuzzyma** [comment]
As far as I know imported svgs are always wrapped into SVG tags from
SVG.js. So you might also well just do draw.svg(svg)

Am 02.11.2016 14:17 schrieb "Peter Schmidler" <notifications@github.com>:

**Comment by Fuzzyma** [comment]
Can this be closed?

**Comment by peterschmidler** [comment]
Yes, thanks!
