### ISSUE TITLE
Sort out leftovers from the old fx module

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#547]
When I rewrote the fx module, chaining of animations was introduced. As a consequence (and because of other issues), the startpoint of the animated properties isnt evaluated when the call to the function e.g. `dx` or `x` happens but when the animation starts. That makes relative movements possible. And ensures the right startpoint when the next animation starts.

This is done in the `initAnimation` method of the fx module. The code in there is rather ugly because it has to handle the old concept of morphable objects which have a start and a destination value.  
Since the startvalue is overwritten in the `initAnimation` method, we basically dont need to set it anymore.
That leads to code like this:

```js
  x: function(x, relative) {
    // make sure that groups are correctly handled
    if(this.target() instanceof SVG.G){
      this.transform({x:x}, relative)
      return this
    }
    
    // create an EMPTY Number and morph it to destination
    var num = new SVG.Number().morph(x)
    // also make sure that the relative flag is set
    num.relative = relative
    return this.add('x', num)
  }
```

I see no point in creating an empty object which is _really_ filled at another place. So I would like to search for another solution here.
Obtaining the start value from the element is somtimes difficult. For you a bid of madness from the `initAnimation` method:

```js
          // sometimes we get back an object and not the real value, fix this
          if(s.animations[i].value.value){
            s.animations[i].value = s.animations[i].value.value // woooot
          }
```

@wout @dotnetCarpenter @RmiTtro any ideas on how to circumvent this issues are welcome.

**Some more information for the fx module**
Animations are grouped into several groups:

- animations: Everything you can call with a function from svg.js like `move`, `size`...
- attrs: Bare attributes which are animated. This is mostly for attributes which are not covered by any methods from svg.js but can be used for any attribute
- styles: Holds all styles beeing animated
- transforms: Holds all transformations in the right order which are first morphed and then merged into a single matrix. This prevents that e.g. a rotation becomes a flip and so on

When initAnimation is called, all arrays are gone through and the start values are set to the state of the element. For the `animations` array this is a bit tricky because the svg.js method is used to obtain the value. That ofc has many advantages (size, plot, all custom methods) but can also lead to cases where an object is returned instead of a value (e.g. you get back an SVG.Number instead of just a plain Numer). Thats why this is corrected immediatley (see the madness code above).
Maybe we should return always an object. That would makes things less complicated.

Sorry for the long and maybe a bit confusing post. However this issue gnaws at my brain for some time now and I thought its time now :)

**Comment by RmiTtro** [comment]
Well, for the first problem, I suppose a simple solution would be to just store the number directly in the array and you create the SVG.Number in `initAnimation` where you have access to the start value. Turning `x` into something like this:
```javascript
x: function(x, relative) {
    // make sure that groups are correctly handled
    if(this.target() instanceof SVG.G){
      this.transform({x:x}, relative)
      return this
    }
    
    // Do note that it is still necessary to create an SVG.Number here since it is impossible
    // to add a relative flag to a primitive Number (I tried and it didn't work XD)
    var num = new SVG.Number(x)
    // also make sure that the relative flag is set
    num.relative = relative
    return this.add('x', num)
  }
```

As for the second problem where an SVG.Number is returned instead of a primitive one, could you provide some cases where this is happening? My only problem with always returning an object is from a user point of view. If a user of this library thinks that that the methods return a plain Number while they are returning an SVG.Number this could be the source of some issues. For example, a test like this would always be false: `svgnumber === 3`. Before making any decision, it would be good to know which methods return an Object and which return a Number so we can have the bigger picture.

**Comment by RmiTtro** [comment]
I just realised that the `animations` group can also contain array which mean that my previous solution is not complete, I will need to think more about this...

**Comment by RmiTtro** [comment]
I think I have found another simple solution, we could just reverse the way the method `morph` is used. Instead of passing it the destination, we would be passing it the start value. As an example, the `x` method would look like this:
```javascript
x: function(x, relative) {
    // make sure that groups are correctly handled
    if(this.target() instanceof SVG.G){
      this.transform({x:x}, relative)
      return this
    }

    var num = new SVG.Number(x)
    // also make sure that the relative flag is set
    num.relative = relative
    return this.add('x', num)
  }
```

And, in `initAnimation`, there would be something like this:
```
s.animations[i].morph(startvalue)
```

This should also handle the second problem since the method `morph` convert its parameter using the constructor: SVG.Number, SVG.Array, etc.

**Comment by Fuzzyma** [comment]
I thought about that, too. But its not that simple. All these objects of svg.js are not only there for morphing.
E.g. take the `PathArray` which can be morphed, but is used in many different cases like parsing a path string, converting the array back to a string, calculating the BBox of a string and so on.
The morphing functionality comes after all these other features.
Switching out constructur value and morph value does only make sense regarding to animations but in no other case.

**Comment by RmiTtro** [comment]
I'm not sure I'm getting your point, reversing the way the method `morph` is used should only require to modify the methods `morph` and `at` of all the objects of svg.js. Since these methods are only used in the animation module, it shouldn't have an impact on the others functionalities provided by these objects.

**Comment by RmiTtro** [comment]
As an example, here is a new implementation of the methods `at` and `morph` for the SVG.Number class:
```javascript
  // Make number morphable
  , morph: function(number) {
      this.origin = new SVG.Number(number)

      return this
    }
    // Get morphed number at given position
  , at: function(pos) {
      // Make sure a origin is defined
      if (!this.origin) return this

      // Generate new morphed number
      return new SVG.Number(this)
          .minus(this.origin)
          .times(pos)
          .plus(this.origin)
    }
```

**Comment by Fuzzyma** [comment]
Ah I think I get your point. Sorry my objections are trash.
Yes this solution sounds reasonable. Still there is the problem in the `initAnimation` method I described above. I need to find the methods which return a morphable object instead of a plain value (or the other way round) and review them...

**Comment by RmiTtro** [comment]
This problem is actually also solved since the method `morph` perform a conversion on its parameter. So, if its parameter is a plain value, it gets converted in a morphable object and if it is a morphable object, it just get copied. Here is what this part of initAnimation could look like with the change:
```javascript
for(i in s.animations){

  if(i == 'viewbox'){
    s.animations[i].morph(this.target().viewbox())
  }else{

  // TODO: this is not a clean clone of the array. We may have some unchecked references
  s.animations[i].morph(i == 'plot' ? this.target().array() : this.target()[i]())

  if(s.animations[i].relative)
    s.animations[i].value = s.animations[i].value + s.animations[i].origin.value
  }
}
```

**Comment by Fuzzyma** [comment]
mh, mh and mh :). Yes that would simplify this a lot. We wouldnt need the extra `if` for `viewbox`, too. I also would think about a change of the plot-function which could work as getter and setter. So that confusion could be sorted out, too. Also the relative value could be calculated at morphing time.

Actually that seems to be a very comfortable solution. The whole block would condense to this:

```js
s.animations[i].morph(this.target()[i]())
```

Any pitfalls I do not see here?

**Comment by RmiTtro** [comment]
Look good to me! ;)

**Comment by RmiTtro** [comment]
I rethought about this and I think that I have a better solution. Basically, it would be to do the same thing that is done for [viewbox()](https://github.com/svgdotjs/svg.js/blob/516f575cf4ea4921fab4d66fbce3b8dad25e7e66/src/fx.js#L225). I had proposed this solution a few comments back but then I discarded it for some reason (I was a bit dumb back then it would seem). But now, I think can make it work. The advantage over my previous solution is that almost all the change will be made in `fx.js` so it should be much easier to implement than my previous solution. I will test it out and if it work you will see a pull request pop out :wink: !

**Comment by Fuzzyma** [comment]
All changes implemented in #589

**Comment by wout** [comment]
I'm documenting the relative value for `SVG.Number` and now I'm wondering, shouldn't there be a method for making a number relative? Something like:

```js
number.relative(false) // default
number.relative(true) // -> now it's relative
```

Or do we just flag the property from the outside? Although, that makes method chaining a bit more difficult. Also, if we don't provide a method, isn't this more of an internal feature?

**Comment by wout** [comment]
Please ignore the above. @Fuzzyma already mentioned this here #595:

> The relative values for svg number is an fx internal. There is no need to mention that in the docs except if you want to make relative numbers a feature (I do not suggest that ^^)
