### ISSUE TITLE
Make events cancelable

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#550]
On default the events created by `fire` are not cancelable. That means a call to `preventDefault()` on them will not have any effect. I just tried to add an option for this to the `fire` method but stumbled over another problem.
To check if an event was `defaultPrevented` you look into said argument. When its true, someone called `preventDefault()` on it. However: To check this, you need the event object which is capsulated from the user with the fire method. We also cant change the return value from `fire` without breaking the api.

Ofc you can create your event outside of `fire` and pass it to the method but thats replicated code all day long. So I thought about a helper function like this:

```js
SVG.getEvent = function(name, data, cancelable){
    return new CustomEvent(name, {details: data, cancelable: cancelable})
}
```

But that doesnt really save much charakters...
Would be cool after all to have the `fire` return the event so you could just do:

```js
if(el.fire(name, data, true).defaultPrevented)
    return
```

However: Any thoughts?

**Comment by Fuzzyma** [comment]
@wout @dotnetCarpenter @RmiTtro I would like to hear your ideas on this.
I really would like to have that into 2.5 but I am not sure how to implement it

**Comment by Fuzzyma** [comment]
Ok so I have 5 different proposals sorted from (imo) bad to better. 

1. **The ugly hack**
```js
  // Fire given event
, fire: function(event, data) {

    // Dispatch event
    if(event instanceof Event){
        this.node.dispatchEvent(event)
    }else{
        this.node.dispatchEvent(event = new CustomEvent(event, {detail:data}))
    }
    
    this.event = function() {
      delete this.event
      return event
    }.bind(this)

    return this
  }
```

Whever an event is fired, a function gets added to this, which returns the event. The function is deleted after being used (uaah - never wrote such a big hack).

2. **The C way**
```js
, fire: function(event, data, returnObj) {

    // Dispatch event
    if(event instanceof Event){
        this.node.dispatchEvent(event)
    }else{
        this.node.dispatchEvent(event = new CustomEvent(event, {detail:data}))
    }
    
    if(returnObj) returnObj.event = event

    return this
  }
```

Pass an object to the function. Add the event to that object.


3. **The confusing return**
```js
, fire: function(event, data, returnEvent) {

    // Dispatch event
    if(event instanceof Event){
        this.node.dispatchEvent(event)
    }else{
        this.node.dispatchEvent(event = new CustomEvent(event, {detail:data}))
    }
    
    if(returnEvent) return event

    return this
  }
```

Its getting better but the return value depends on a parameter.

4. **The straightforward solution**
```js
, fire: function(event, data) {

    // Dispatch event
    if(event instanceof Event){
        this.node.dispatchEvent(event)
    }else{
        this.node.dispatchEvent(event = new CustomEvent(event, {detail:data}))
    }
    
    return event
  }
```

Always return the event. Simple and clean. However - it does not conform to our chainable api. It does not return `this`.

5. **Basically the first but without hack**
```js
, fire: function(event, data) {

    // Dispatch event
    if(event instanceof Event){
        this.node.dispatchEvent(event)
    }else{
        this.node.dispatchEvent(event = new CustomEvent(event, {detail:data}))
    }
    
    this._event = event
    return this
  }
, event: function() {
    return this._event
  }
```

It does not break anything and therefore might be the best solution. However it reminds of the good old IE way to get events (`window.event`).

---

I see **4.** and **5.** as equally good and bad. However **4.** has an api break and cant be used in 2.5 while **5.** could.

**Comment by RmiTtro** [comment]
My favorite is **4** but I suppose that for 2.5 we should go with **5** and consider **4** for version 3.

**Comment by Fuzzyma** [comment]
So this issue is open for 3.0 again. I would like to go for version 4. of my proposals for 3.0. @saivan @wout what do you think? Or we take proposal number 6 which would be:

*2 Methods for fireing elements*

- `fire`, triggers event, returns `this`
- `dispatch/trigger` which returns the event

sooo - which one? :D

**Comment by wout** [comment]
I'd go for **6**. It's not the first time we add a method variant for a different return value (`put()` / `add()`). Option **4** would be my second choice but brings two downsides:
- breaks the method chain
- changes the API
