### ISSUE TITLE
Gradient Animation Question

### ISSUE THREAD

**Issue by skrichten** [svgdotjs/svg.js#551]
How can I do the following with this library...

`<linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="0">
    <stop offset="0%" style="stop-color:#33235b;">
    <animate attributeName="stop-color" values="#33235b; #E97639; #33235b;" dur="7s" fill="freeze" repeatCount="indefinite" />
  </stop>
  <stop offset="50%" style="stop-color:#E97639;">
    <animate attributeName="stop-color" values="#E97639; #33235b; #E97639;" dur="7s" fill="freeze" repeatCount="indefinite" />
  </stop>
  <stop offset="100%" style="stop-color:#33235b;">
    <animate attributeName="stop-color" values="#33235b; #E97639; #33235b;" dur="7s" fill="freeze" repeatCount="indefinite" />
  </stop>
</linearGradient>`

**Comment by skrichten** [comment]
OK, I just found the reverse flag on the loop function, but the doc does not explain how to get an infinite loop and use reverse... do I set the loop count to 0, or null maybe?

**Comment by Fuzzyma** [comment]
To get an infinite loop you just call loop without any parameters.

**Comment by skrichten** [comment]
I know that... I asked how to get infinite AND reverse at the same time.  But I figured that out on my own.  It works if I pass null for the loop count and then I can pass true for the reverse (second param)

**Comment by Fuzzyma** [comment]
null might work as first parameter because it's the default value. However the correct way of calling a reversing loop would be `loop(true, true)`

**Comment by skrichten** [comment]
Gotcha, Thanks!
