### ISSUE TITLE
Animation with negative percent position values

### ISSUE THREAD

**Issue by skrichten** [svgdotjs/svg.js#552]
When directly using SMIL, I can use negative percent values for x,y.  This can be very handy to do things like this...

https://codepen.io/bradleyboy/pen/lIqag/

When I tried such a value with this library the animation did not play at all.  Any workarounds or other suggestions for achieving this affect would be appreciated.

**Comment by Fuzzyma** [comment]
Please include the relevant code from your example in your question. Also add the code you tried to achieve the effect with this library

**Comment by skrichten** [comment]
Code from the example...

`
<pattern id="pattern" x="0" y="0" width="300%" height="100%" patternUnits="userSpaceOnUse">
      <rect x="0" y="0" width="150%" height="100%" fill="url(#gradient)">
        <animate attributeType="XML"
                 attributeName="x"
                 from="0" to="150%"
                 dur="7s"
                 repeatCount="indefinite"/>
      </rect>
      <rect x="-150%" y="0" width="150%" height="100%" fill="url(#gradient)">
        <animate attributeType="XML"
                 attributeName="x"
                 from="-150%" to="0"
                 dur="7s"
                 repeatCount="indefinite"/>
      </rect>
    </pattern>
`

Code I tried...

`var draw = SVG('drawing'); 

    var gradient = draw.gradient('linear', function(stop) {
        s1 = stop.at(0, '#33235b');
        s2 = stop.at(0.5, '#E97639');
        s3 = stop.at(1, '#33235b');
    });

    var r1, r2;
    var fill = draw.pattern('300%', '100%', function(add) {
      r1 = add.rect('150%', '100%').fill(gradient);
      r2 = add.rect('150%', '100%').fill(gradient);
    });
    fill.attr({patternUnits: 'userSpaceOnUse'});

    r1.attr('x', 0).animate('7s').attr('x', '150%').loop();
    r2.attr('x', '-150%').animate('7s').attr('x', 0).loop();

var text = draw.text('Manifesto').move('50%', '50%').fill(fill);
    text.font({
      size: 70
      , anchor: 'middle'
      , leading: 1
    });`

Sorry about the formatting, I don't know why it is getting messed up.

Anyway, the r1 rectangle animates as expected, but r2 does not.

**Comment by skrichten** [comment]
A related issue... trying to use percentage values in general often doesn't work.  For example...

`var fill = draw.gradient('radial', function(stop) {
        s1 = stop.at(0, '#ffe39b')
        s2 = stop.at(0.5, '#635238')
    });
    fill.attr({gradientUnits: 'userSpaceOnUse', fx: '10%', fy: '50%'});

    fill.attr('fx', '10%').animate('5s').attr('fx', '90%').loop(true, true);`

When I inspect this, I can see that the fx value is changing over time, but the values are very small.

**Comment by dotnetCarpenter** [comment]
@skrichten The format is enclosing your code in 3 back-ticks and optional an abbreviation of the language (ei. js, svg etc):

**format:** \`\`\`js

**Comment by Fuzzyma** [comment]
Ok I spotted the bug. I think the problem will be resolved with #547.
The broken line is [here](https://github.com/svgdotjs/svg.js/blob/998265133f95edcf5b863686e87a9821bdc62a2e/src/fx.js#L250)

It reads the value directly from the node and passing it to value which should be an integer and is then a string. Instead the node value has to be prepared with `SVG.Number` or `SVG.MorphObj`.

Another thing to mention: Your code reads the following:

```js
r2.attr('x', '-150%').animate('7s').attr('x', 0).loop();
                ^-string                      ^-int
```

svg.js converts values directly between percentage and int. So you basically see the int-value animating (from 0 to 1.5) instead from 0% to 150%.

However this does not explain your second post where you passed 2 times percentage values. But again I guess that this will be resolved with #547.

**Comment by skrichten** [comment]
Thanks for the update.  Yeah, the only reason I mixed int and string like that was because using both strings wasn't working.

**Comment by Fuzzyma** [comment]
@RmiTtro this issue is not resolved with your changes to the code. The SVG.Number module still converts the -150% to -1.5 in this example. Any idea how to fix that?
We could setup the guideline that one has to write "0%" but 0 is 0 no matter which unit you have so I would like to avoid that

**Comment by Fuzzyma** [comment]
@skrichten your examples now work when working the trick with the '0%' instead of the integer `0`

**Comment by RmiTtro** [comment]
What if in `SVG.Number` we replaced all the operation methods that are like this one:
```javascript
plus: function(number) {
      return new SVG.Number(this + new SVG.Number(number), this.unit)
    }
```

By something like this:
```javascript
plus: function(number) {
      return new SVG.Number(this + new SVG.Number(number), this.unit || number.unit)
    }
```

I think that could allow 0 to be used in place of '0%'.

**Comment by Fuzzyma** [comment]
Yes that would work I think

**Comment by RmiTtro** [comment]
In that case I will make a small commit to apply this fix. This will allow me to test my new power ;).

**Comment by RmiTtro** [comment]
Finished fixing by commit 669c10a76ebd164c147d7f896fa162784c0b49df.

**Comment by RmiTtro** [comment]
@skrichten your examples now work without requiring any modifications! Thanks again for reporting this issue.
