### ISSUE TITLE
TSpan.text(text) is vulnerable to stored xss attack 

### ISSUE THREAD

**Issue by Saddham** [svgdotjs/svg.js#556]
Hi,
tspan element does not have any means to set innerhtml.
Setting text is creating stored xss vulnerability.
Example text:  `>'>"><img src=x onerror=alert(74)>`

Note: Tried escaping before setting text but then original text will not be displayed (escaped text will be displayed).

Need help to overcome this issue!

**Comment by Fuzzyma** [comment]
Please post your full code and explain your usecase. In which case will a call to `text()` create xss vulnerability?
Cosider adding a [jsfiddle](https://jsfiddle.net/), too

**Comment by Fuzzyma** [comment]
Looks like help is no longer needed. 

Closing because of no reaction!
