### ISSUE TITLE
Working with SVG elements created without svg.js

### ISSUE THREAD

**Issue by ibarral** [svgdotjs/svg.js#557]
Hello,

Is there any way to work with existing SVG code and the svg.js library?

For example, I have the following SVG code:

```
<svg id="mySvg" width="500" height="500">
  <g id="myGroup"></g>
</svg>
```

And the following Javascript code:

```
var mySvg = SVG('mySvg');
var myGroup = mySvg.select('#myGroup');
var rect = myGroup.rect(100, 200);
```

But that trows an error:

`Uncaught TypeError: myGroup.rect is not a function`

I want to work with an existing `G` element, as it was created using `var group = mySvg.group();`.

Is that possible?

Thanks!

**Comment by jcorentin** [comment]
Hello !

Yes, that's possible :+1: 
http://documentup.com/wout/svg.js#svg

For your example :

JS :
```
var mySvg = SVG('mySvg').size(500, 500);
mySvg.svg('<g id="myGroup"></g>');
var myGroup = SVG.get('myGroup');
var rect = myGroup.rect(100, 200);
```

HTML :
```
<div id="mySvg'></div>
```

**Comment by ibarral** [comment]
Thanks! but I think that's to replicate my original SVG using svg.js, right? (creating all the elements from the start).

I need to use my existing SVG code, and extend it with svg.js to create new elements.

**Comment by jcorentin** [comment]
Not only.
It's indeed used as export function if you don't specify arguments, but as import if you pass a string argument containing your svg xml code. 

To use your full existing svg code, store it in a variable and pass it to svg().

I don't know what's the best way to get your svg code, either store it directly in a variable in your js file or get your .svg file with an ajax request and store its content in a variable.

I'm personaly using this function. I use inkscape to draw, then copy the generated code (excluding svg tags) in a js variable. Finally i use svg() function from svg.js to include it in the DOM. Exactly as i did it for your example.

**Comment by Fuzzyma** [comment]
Your mistake lays in the use of `select()`. This method does not return a single svg element but a `set` of elements. To get the first element in the set you either use `first()` or `get(0)`.

**Comment by ibarral** [comment]
@Fuzzyma thanks! now it work's as expected :)

**Comment by Vktun** [comment]
hello , I havs same problem with v3.0.12 or v.2.7.1   
v3.0.12  code 
html
`<embed src="../aircondition.svg" class="svgDom" id="eleSvg" width="100%" height="100%"  type="image/svg+xml" pluginspage="http://www.adobe.com/svg/viewer/install/">
`
SVG File
`<svg xmlns="http://www.w3.org/2000/svg" id="svg-aircondition" ><rect x="0" y="148.65" width="10.723" height="41.9054" class="st89"/><rect x="0" y="48.65" width="10.723" height="41.9054" class="st89"/></svg>`
JS
`var d = SVG("#eleSvg")`
      `  console.log(d) //Dom events: {…}, node: embed#eleSvg.svgDom, type: "EMBED"`
       ` console.log(d.find(".st89")) //[]   svg file has many elements use class='st89'`
     `   var s = SVG("#svg-aircondition") //null`

I cant get any elements in svgs  .  I dont know how to use this .

**Comment by Fuzzyma** [comment]
You cannot change files you loaded via embed, object or any other kind. You can only change svg which is in the dom. So, copy paste the contents of the file into your html page or load the file via ajax and inject its contents into the dom. Thats the only way to make the file accessible to svg.js

**Comment by metaphore** [comment]
> You cannot change files you loaded
@Fuzzyma I wish I read this somewhere in the documentation two days ago... Why is such important information is not mentioned anywhere? It seems that a lot of people are confused about it.

**Comment by Fuzzyma** [comment]
Well mostly I think it's because of 2 reasons:

- svg.js manipulates the Dom. Everyone should know that because it's a Dom library. You cannot manipulate what's not in the Dom
- you cannot manipulate shadow downs. At least not the one generated by loading an svg file via image or object tag

But yes - maybe you are right and there should be something about that in the documentation. But where would you put this?
