### ISSUE TITLE
parents() method on SVG.Element returns array instead of SVG.Set

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#562]
https://github.com/svgdotjs/svg.js/blob/master/src/element.js#L195

Shouldn't this return an `SVG.Set` instead?

**Comment by Fuzzyma** [comment]
Indeed - my mistake :)

**Comment by wout** [comment]
I was already in doubt here :)
Because `children()` also returns an array...

**Comment by Fuzzyma** [comment]
Well - that on the other hand wasn't me :D

**Comment by wout** [comment]
No, not blaming anyone. That's a blunder on my account ;)

It involves a breaking change so let's keep it for the next minor or even major release.

**Comment by dotnetCarpenter** [comment]
It might be a good idea to collect changes like these in the [CHANGELOG.md](../blob/master/CHANGELOG.md)

**Comment by wout** [comment]
Done. I added point 3-7 in [CHANGELOG.md#Changed](https://github.com/svgdotjs/svg.js/blob/master/CHANGELOG.md#changed).

**Comment by Fuzzyma** [comment]
In 60236e07f161e23772922eed2e5c489b6964a712 in the [3.0 branch](https://github.com/svgdotjs/svg.js/tree/3.0.0) `SVG.Set` was removed in favour for array. So I will close this.
