### ISSUE TITLE
masker reference not a method

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#563]
This will need to be reworked as well:

https://github.com/svgdotjs/svg.js/blob/master/src/mask.js#L44

This method should be dynamic in order to work with adopted svg's.

**Comment by wout** [comment]
Same is true for clipPath's:

https://github.com/svgdotjs/svg.js/blob/master/src/clip.js#L44

**Comment by Fuzzyma** [comment]
Solved in the [3.0 branch](https://github.com/svgdotjs/svg.js/tree/3.0.0)
