### ISSUE TITLE
How do I select an svg in html that is not created by svg.js

### ISSUE THREAD

**Issue by amjith** [svgdotjs/svg.js#567]
I've been scouring the docs trying to find a way to do this. I'm including an svg in my html file that is not created by svg.js but it is from Inkscape. 

I would like to select a specific id inside that svg file and animate it. But I can't find any concrete examples in the docs or in codepen that shows me how to do this. 

Is this possible? 

eg: 

index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Truck Race</title>
</head>
<body>
  <object id="truck" data="truck-6.svg" type="image/svg+xml" />
  <script src="https://rawgit.com/wout/svg.js/master/dist/svg.js"></script>
  <script src='index.js'></script>
</body>
</html>
```

index.js: 
```
function ready(fn) {
  if (document.readyState != 'loading'){
    fn();
  } else {
    document.addEventListener('DOMContentLoaded', fn);
  }
}

ready(function() {
  var elem = SVG.get('truck')
  var back = elem.select('moveable-part-1')
  back.animate().rotate(45)
})
```

I'm a complete novice when it comes to svg manipulation, so feel free to send me to external references if you think that'll help me grasp the basics.

Thanks!

**Comment by Fuzzyma** [comment]
This was also asked in #557. When you use `select()` you get back a set of elements. To get the first one just call `first()` or `get(0)`

**Comment by snagareddy** [comment]
Hi ,
I was not able to get the Svg.js working for the same scenario mentioned. Can you show or give a working example of selecting/getting svg from the html <object> tag as mentioned above "amjith "

Thanks in advance.

**Comment by Fuzzyma** [comment]
Show me your code
