### ISSUE TITLE
Unable to use a clip multiple times

### ISSUE THREAD

**Issue by siegenthalerroger** [svgdotjs/svg.js#570]
I have a code piece where I create a clip assigned to a variable, followed by creating and moving text elements to their correct positions within a for loop. The last procedure in the for loop is text.clipWith(variableOfClipElement). 

However I cannot use the clip element on more than the first text element for some reason, when manually changing the clipURL in the DOM there's no problem with this. I have resorted to creating a new clip for every text element within the for loop.

Is there a reason for this behaviour or is it a bug? If you need more details/a code example/demo do tell me.

**Comment by Fuzzyma** [comment]
Please show us a fiddle with the issue and also post the relevant code here.
Furthermore: Look into the generated code. Is there ANY clipurl shown? Which one?

**Comment by Fuzzyma** [comment]
@siegenthalerroger is this still an issue? Without feedback I will close this in a few days...

**Comment by siegenthalerroger** [comment]
I will check up on this and get back to you. On my todo list now :)

**Comment by siegenthalerroger** [comment]
Yeah this still happens, on v2.4.0 and the latest git commit. 

My code is the following:
```
        var labelClip = draw.rect(graphToLeftMargin - paddingLeft, height - paddingBottom - paddingTop)
            .move(paddingLeft, paddingTop, graphToLeftMargin, height - paddingBottom);
        for (i = 0; i < pb.BuildingElements.length; i++) {
            var label = draw.text(pb.BuildingElements[i].ElementDescription);
            label.move(paddingLeft + (label.native().getComputedTextLength() / 2),
                       height - paddingBottom - elementHeight - elementPadding - (i * elementTotalHeight) );
            label.clipWith(labelClip);
        }
```

And this produces the following (irrelevant parts omitted):
```
<svg xmlns="http://www.w3.org/2000/svg" id="graphicalDisplaySVG" width="1570" height="100%" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs">
    <defs id="SvgjsDefs1007">
        <clipPath id="SvgjsClipPath1056" />
        <clipPath id="SvgjsClipPath1059" />
        <clipPath id="SvgjsClipPath1062" />
        <clipPath id="SvgjsClipPath1065" />
        <clipPath id="SvgjsClipPath1068" />
        <clipPath id="SvgjsClipPath1071">
            <rect id="SvgjsRect1053" x="10" y="40" width="200" height="240" />
        </clipPath>
    </defs>

    // more elements 

    <text id="SvgjsText1054" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1056&quot;)" x="78.91" y="242.1">
        <tspan id="SvgjsTspan1055" x="78.91" dy="20.8">Kanalisation Gebäude</tspan>
    </text>
    <text id="SvgjsText1057" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1059&quot;)" x="87.845" y="202.1">
        <tspan id="SvgjsTspan1058" x="87.845" dy="20.8">Aussenwandkonstruktion</tspan>
    </text>
    <text id="SvgjsText1060" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1062&quot;)" x="82.015" y="162.1">
        <tspan id="SvgjsTspan1061" x="82.015" dy="20.8">Innenwandkonstruktion</tspan>
    </text>
    <text id="SvgjsText1063" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1065&quot;)" x="52.035" y="122.1">
        <tspan id="SvgjsTspan1064" x="52.035" dy="20.8">Aussenstütze</tspan>
    </text>
    <text id="SvgjsText1066" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1068&quot;)" x="46.205" y="82.1">
        <tspan id="SvgjsTspan1067" x="46.205" dy="20.8">Innenstütze</tspan>
    </text>
    <text id="SvgjsText1069" font-family="Helvetica,Arial,sans-serif" clip-path="url(&quot;#SvgjsClipPath1071&quot;)" x="67.615" y="42.1">
        <tspan id="SvgjsTspan1070" x="67.615" dy="20.8">Deckenbekleidung</tspan>
    </text>

    // more elements 

</svg>
```

As you can see, all the clippaths are made and are correctly referenced, yet only one of them has a defined clip rectangle. If I manually change the svg to have all the text fields referencing the same clippath that works no problem.

**Comment by Fuzzyma** [comment]
You have a thinking mistake there. If you call `clipWith` on an element, a clipPath is created and added to the defs. When you do that again, a new clipPath is created and the element you passed is now added to _this_ clipPath. So you end up with multiple clipPaths and the last one holds the element.

What you want is not passing an element to `clipWoth` but passing a clipPath instead.
You can do this in two ways:
- you use the instance from when you first called `clipPWidth`
```js
rect.clipWith(other_rect)
rect.clipper // clipPath instance

circle.clipWith(rect.clipper) // use the same clipPath
```

- you create an instance of clipPath first and pass this `clipWidth`
```js
var clipPathInstance = new SVG.ClipPath().add(other_rect) // clipPathInstance 
rect.clipWith(clipPathInstance )
circle.clipWith(clipPathInstance ) // use the same clipPath
```

I would prefer the second one

**Comment by siegenthalerroger** [comment]
Thanks a lot, that fixed it all.
