### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by angusforbes** [svgdotjs/svg.js#572]
Did the documentation change recently? It's very difficult to find relevant information now, since you can't search the entire docs with out pressing on the the plusses by the side. And you can only have one portion of the docs open at once. This is all I can find now: https://svgdotjs.github.io/. I swear there was a much better version of this online just a few weeks ago where ctrl-F works on *all* of the docs. Is there at least a link to the old docs???

**Comment by Fuzzyma** [comment]
Here you go: https://github.com/svgdotjs/svg.js/blob/8b24eb02ded49b77f04cb7b5214c224569fc841b/README.md

This version is from the 4th of November but should be quite actual.

For the new version: Thanks for your criticism. We are working on a search function to make things easier.

**Comment by wout** [comment]
Thank you for your input. We are working on an instant search function. I hope we can implement it this week.

**Comment by angusforbes** [comment]
Awesome! Thanks for the pointer to the Nov 4 docs - look forward to the instant search on the new docs.

**Comment by wout** [comment]
They are now live!
