### ISSUE TITLE
Docs: describe what the letters T/R/B in `{T|R|B}Box` mean

### ISSUE THREAD

**Issue by Zearin** [svgdotjs/svg.js#574]
I’m trying to keep straight in my head which class does what, but it’s hard when the only thing I have to go on is the letter prefixing each class.  

I can only guess that `BBox` stands for “Bounding Box”, but without the docs explicitly saying so, I get cognitive dissonance as my brain argues with itself as to whether I am “filling in” the meaning of the letter “B” accurately.

Can you add a quick sentence to all their descriptions to clarify this?  Something like:

> BBox (short for “Bounding Box”) does «description»…

**Comment by dotnetCarpenter** [comment]
We are currently updating our documentation at https://github.com/svgdotjs/svgdotjs.github.io.

It's a lengthy process so PR's are more than welcome.

**Comment by dotnetCarpenter** [comment]
Moved to https://github.com/svgdotjs/svgdotjs.github.io/issues/2
