### ISSUE TITLE
Support for rotation in markers (Orient attribute)

### ISSUE THREAD

**Issue by askari12** [svgdotjs/svg.js#576]
It would be very useful for a support for the orient method to move the arrow head directions. This could be done by adding an orient method for markers and hence changing the orient attribute of the marker.

**Comment by dotnetCarpenter** [comment]
#577

**Comment by Fuzzyma** [comment]
This is `.orient(...)` vs `attr('orient', ...)`.
Is it worth adding?

**Comment by dotnetCarpenter** [comment]
@Fuzzyma no, not really. In my opinion, we can close this.

@askari12 Feel free to re-open, if you can provide argumentation, for having a specialized method for setting an attribute.

**Comment by xpe** [comment]
> This is `.orient(...)` vs `attr('orient', ...)`.
> Is it worth adding?

This library tends to provide both, right? For one, I would appreciate the consistency.

**Comment by xpe** [comment]
> @askari12 Feel free to re-open, if you can provide argumentation, for having a specialized method for setting an attribute.

Isn't exactly this done quite frequently across the library?
