### ISSUE TITLE
Transform origin when animating

### ISSUE THREAD

**Issue by mixn** [svgdotjs/svg.js#58]
Thanks for the great work you put into svg.js — it’s quiet handy. I was just wondering if it is possible to set a transform-origin when animating, or scaling, that is. I want it to scale/blow up a hexagon, but using the center as the origin, not the upper left corner? Here’s a hacked up, quick pen to elaborate a bit: [codepen.io/mixn/pen/qbDJp](codepen.io/mixn/pen/qbDJp)

**Comment by selfyguy** [comment]
Just wondering if the "origin" feature ever made it? I couldnt find any in the documentation.
