### ISSUE TITLE
New documentation not easily searchable

### ISSUE THREAD

**Issue by marekjedrzejewski** [svgdotjs/svg.js#580]
When documentation was on single page it was really fast to find something, just /pattern or ctrl+f away, now that every entry is on separate page it is imposible. Maybe there's option to display it as one page, but I just didn't find it. 

If there is not, I think it would be a good to add separate single-page version.

**Comment by Fuzzyma** [comment]
Please use the search function before opening new issues: #572

**Comment by marekjedrzejewski** [comment]
Oh, sorry, I searched in open issues only.

**Comment by wout** [comment]
We just released a new version with a search function. You might want to clear your browser cache.
