### ISSUE TITLE
animate().during() not called

### ISSUE THREAD

**Issue by edemaine** [svgdotjs/svg.js#583]
The following code doesn't animate:

```javascript
var s = svg.polygon(square);
s.animate(5000, '<').loop(true, true).during(function (x, y, t) {
  s.untransform()
  .rotate(-90*(1-Math.asin(1-t)/(Math.PI/2)), -0.5, 0.5)
});
```

If I add a no-op transform like `.fill('red')` before the `.during` call, then it animates.  Presumably there is a check for whether to animate the object, which currently isn't triggered by `.during`, but I think it should be.

**Comment by Fuzzyma** [comment]
That module was rewritten shortly. In the old one a timeout made sure that the animation is started in every case. I don't know exactly if this is still the case. However you can start the animation manually using `start()`.

**Comment by edemaine** [comment]
Confirmed: calling `.start()` fixes the issue, so it's a good workaround.

**Comment by RmiTtro** [comment]
The animations are started only when there is something to be animated (ex: `.x(14)`). When you specify something to animate, the method `add` is the method that end up being called by the methods `x`, `move`, `attr`, etc. This method in turn call `start` if the animation is not already started. Maybe we should call the method `start` when the method `animate` is called instead? 

It shouldn't make a difference in call like this one `rect.animate().move(10,20)` and would make the code snippet of @edemaine work.

Although, I could see problems in a call like this one:
```javascript
var anim = rect.animate(5000)

// Then, after some time, you do this:
anim.move(10,20)
```

I can't decide if it would better or not, what do you all think?

**Comment by Fuzzyma** [comment]
I think before the rework it always started the animation even if nothing was added to it.
However: I like it as it is. The case that one want to animate nothing is rare enough that we can handle this as special case. We should add that to the docs, though...

**Comment by RmiTtro** [comment]
Then it shall remain has it is, I didn't really want to change it either :wink:.

**Comment by edemaine** [comment]
I'm fine with the animation not starting unless there's something to animate, but shouldn't `.during` count as "something to animate"?

**Comment by wout** [comment]
@edemaine Absolutely. I used the `during()` method many times to control other elements.

**Comment by edemaine** [comment]
@wout I mean that, shouldn't `.during` count as something to animate, so `.start` should automatically be called, just like if a property was specified to be animated?

**Comment by wout** [comment]
@edemaine Just to be clear, I totally agree with you. The `during()` method is just as valid as any other method for starting animations. I'm not sure why this behaviour has been changed because it used to be that way in early 2.x versions. So we'll have to sort that out.

**Comment by Fuzzyma** [comment]
During is more or less an event and the during function binds a handler to this event. For me this is not the same as adding an attribute to animation. 
Also o didn't think about that. 
After, once, during all bind events and so they may start the animation loop. But in my opinion just adding an event handled to an element should not start an animation...

**Comment by wout** [comment]
@Fuzzyma I used to be able to do this for example:

```js
draw.animate('3s', '<>').during( function(pos, morph) {
  rect.x( morph(0, 100) )
  circle.y( morph(30, 100) )
})
```

Now `start()` needs to be added, which is a pity:

```js
draw.animate('3s', '<>').start().during( function(pos, morph) {
  rect.x( morph(0, 100) )
  circle.y( morph(30, 100) )
})
```

https://jsfiddle.net/wout/Lwt4mazL/

**Comment by Fuzzyma** [comment]
Thats because `during` is only the lazy way to do `on('during', function(){})` and that should imo not start an animation. Ofc we can discuss about that. In the old code EVERY animation was started (even when you only did `aimate()` and nothing more. I did not find this very intuitive.
On the other hand it produces an api break which I didnt intend. I did not think about the possibility to only use `during` and nothing else

**Comment by edemaine** [comment]
FWIW, this change broke a bunch of my code.

**Comment by Fuzzyma** [comment]
To stay consistent we would need the additional start in `after()`, `afterAll()` and `duringAll()`, too.
If you @RmiTtro @wout agree with that I will add that.

**Comment by RmiTtro** [comment]
I can't make my mind on this so I guess I will go with whatever you decide XD

**Comment by Fuzzyma** [comment]
@edemaine just fixed that in the last commit. Can you confirm?

**Comment by edemaine** [comment]
Tested with `.during` in my original code.  Works!  Thanks!
