### ISSUE TITLE
svg.js homepage: broken link

### ISSUE THREAD

**Issue by boly38** [svgdotjs/svg.js#585]
Hi,
Sorry to use this way to communicate about http://svgjs.com/ but your home page documentation links are broken..
point to http://documentup.com/wout/svg.js
instead of https://svgdotjs.github.io/

out of error from me
regards

**Comment by wout** [comment]
Thanks for letting us know. We don't have access to svgjs.com anymore. I'll try to update the documentup page.

**Comment by wout** [comment]
Et voila. It's fixed.
