### ISSUE TITLE
Bower registry update.

### ISSUE THREAD

**Issue by chrisskilton** [svgdotjs/svg.js#586]
Hi, I think the info for this repo needs updating in bower:

```
bower info svg.js
bower not-cached    https://github.com/wout/svg.js.git#*
bower resolve       https://github.com/wout/svg.js.git#*
bower checkout      svg.js#master
bower resolved      https://github.com/wout/svg.js.git#4515635c8d

{
  name: 'svg.js',
  homepage: 'https://github.com/wout/svg.js'
}

No versions available.
```

Cached installs work but fresh ones don't.

```
bower install svg.js#2.4.0
bower not-cached    https://github.com/wout/svg.js.git#2.4.0
bower resolve       https://github.com/wout/svg.js.git#2.4.0
bower cached        git@github.com:svgdotjs/svg.js.git#2.4.0
bower validate      2.4.0 against git@github.com:svgdotjs/svg.js.git#^2.3.0
bower ENORESTARGET  No tag found that was able to satisfy 2.4.0

Additional error details:
No versions found in https://github.com/wout/svg.js.git
```

**Comment by wout** [comment]
Today I created a new repo at /wout/svg.js to solve issue #585. So I guess the redirect got lost. Anyway, it's about time we update all references to the old repo location.

Personally, I don't use bower, so I have no idea where to start, nor do I have the time to sort it out.

@Fuzzyma?
@dotnetCarpenter?

**Comment by dotnetCarpenter** [comment]
I'm working on this but is BLOCKED by https://github.com/bower/registry/issues/157

**Comment by dotnetCarpenter** [comment]
- To check current bower endpoint: `curl http://bower.herokuapp.com/packages/svg.js`
- To login (use github username/password): `bower login`
- To unregister: `unregister svg.js`
- To register our new endpoint: `bower register svg.js git@github.com:svgdotjs/svg.js.git`

You need to be logged in to unregister and register a package.

**Comment by dadifairman** [comment]
Hello,
Do you have any idea about the time we will have to expect for having a solution?
I need a fix in order to push in production a client project with many proxys and specifics infra rules which are blocking us and I'm not allowed to add the lib in my project without bower.

THX

**Comment by chrisskilton** [comment]
@dadifairman I just changed it to use the lib as a regular github dependency for now from the right repo:

```
"svg.js": "git@github.com:svgdotjs/svg.js#^2.3.0"
```

**Comment by dotnetCarpenter** [comment]
@dadifairman sorry, we're still waiting on the bower registry team to make the change. See [#248](/bower/registry/issues/248)

**Comment by nopantsmonkey** [comment]
until unresolved please restore the svg.js repo

**Comment by wout** [comment]
@nopantsmonkey That's impossible unless we make a copy of the whole repo. I suggest you make your voice heard at [bower/registry](https://github.com/bower/registry) or join in on [bower/registry#248](https://github.com/bower/registry/issues/248).

**Comment by dotnetCarpenter** [comment]
@chrisskilton, @dadifairman and @nopantsmonkey, the bower registry is updated.

>Please notice bower cache clean might be needed on clients for bower to recognize new repository.
https://github.com/bower/registry/issues/248#issuecomment-279961173

**Comment by dadifairman** [comment]
THX it works locally! I hope it will be the same with the continuous integration server!

**Comment by dotnetCarpenter** [comment]
@dadifairman That depends on you CI provider. If you use travis-ci, it should work since the bower cache is empty on each build. But if not, then you'll have to add `bower cache clean` to your `.yaml` file or what-ever means you have to control your build.

**Comment by Fuzzyma** [comment]
@dadifairman @dotnetCarpenter @nopantsmonkey @chrisskilton @wout 
just followed the instructions and it worked for me:

```
$ bower unregister svg.js
? You are about to remove component "svg.js" from the bower registry (https://bower.herokuapp.com). It is generally considered bad behavior to remove versions of a library that others are depending on. Are you really sure? Yes
bower unregister    svg.js
bower Package unregistered      svg.js

$ bower register svg.js git@github.com:svgdotjs/svg.js.git
bower svg.js#*                 resolve git@github.com:svgdotjs/svg.js.git#*
bower svg.js#*                checkout 2.4.0
bower svg.js#*                resolved git@github.com:svgdotjs/svg.js.git#2.4.0
? Registering a package will make it installable via the registry (https://bower.herokuapp.com), continue? Yes
bower svg.js                  register git@github.com:svgdotjs/svg.js.git

Package svg.js registered successfully!
All valid semver tags on git@github.com:svgdotjs/svg.js.git will be available as versions.
To publish a new version, just release a valid semver tag.

Run bower info svg.js to list the available versions.
```
