### ISSUE TITLE
Animating other elements with during() method does not take easing into account

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#587]
In this animation, easing is not taken into account:

```js
draw.animate('3s', '<>').during( function(pos, morph) {
  rect.x( morph(0, 100) )
  circle.y( morph(30, 100) )
})
```

https://jsfiddle.net/wout/Lwt4mazL/

**Comment by Fuzzyma** [comment]
Guess you found out about the other parameters? :D

**Comment by wout** [comment]
My bad, didn't realise the api has been changed there. :)
Not really intuitive though.

**Comment by wout** [comment]
Might be something for v3.0 but I think the `morph()` closure should take easing into account. The `during()` method was created to animate elements alongside the animation so making it linear by default is unexpected. Same goes for `pos` I think. A better construct would be:

```js
element.animate('1s').during(function(pos, morph, linear, situation) {
  // ...magic...
})
```

So `pos` and `morph` are following the animation and `linear` is the percentile location of the animation.

**Comment by Fuzzyma** [comment]
The api is intuitive because I only added things and tried not to change old. I guess I mixed up both positions in case the old code passed the eased position.

**Comment by wout** [comment]
Yeah, we'll have to change them around I think. Or do you disagree? :)

For version 3 I would like to reevaluate every part of the library to see if things kan be done better or made easier. I think the CHANGELOG is not the right place to do it, neither is Slack. Where shall we gather all those suggestions and proposals?

**Comment by Fuzzyma** [comment]
Yeah I guess we can do that. For gathering all that we could use issues here on github because thats what they are for. We can tag them with proposal or 3.0.0 to seperate them from the other issues
