### ISSUE TITLE
Rename old v tags.

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#592]
Rename all tags with a `v` prefix from the olden days. (`v0.1` - `v1.0.0-rc.4.1`).

**Comment by Fuzzyma** [comment]
I renamed all tags except 2 which leads to no more commits. I would just delete those 2 `[v1.0.0-rc.4.1, 2.3.5-0]`.

Please run `git pull --prune --tags` to delete the tags on your local machine so you dont push them again by accident. You can also specify `--dry-run` to see what would get deleted.

**Comment by dotnetCarpenter** [comment]
>I renamed all tags except 2 which leads to no more commits.
You mean that they contain the same commits as another tag?

I would just leave them. Some project might depend on them and they do no harm.
I think this issue can be closed?

**Comment by Fuzzyma** [comment]
I am not sure atm and have to double check. I think there wasn't really a sense for those two. And since we want to clean up I would remove them. They are not even real release tags...

**Comment by dotnetCarpenter** [comment]
Well, I don't feel very strongly about keeping them. If you want to delete
them, then just do it :+1: :)
