### ISSUE TITLE
Add unit test for the fx.js module

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#593]
#589 expanded vastly expanded our unit tests of `fx.js` but 3 important lines were left uncovered.

- [x] [If in a infinite loop, we end the current iteration](https://coveralls.io/builds/10236307/source?filename=dist%2Fsvg.js#L1600)
-  [x] [the user may call stop or finish in the during callback](https://coveralls.io/builds/10236307//source?filename=dist%2Fsvg.js#L1830)
- [x] [you can pass an object as the first argument to `animate()`](https://coveralls.io/builds/10236307/source?filename=dist%2Fsvg.js#L1380) `rect.animate({ ease: '<', delay: '1.5s' }).attr({ fill: '#f03' })`

**Comment by RmiTtro** [comment]
I'm on it!

**Comment by RmiTtro** [comment]
It is done! :raised_hands:
