### ISSUE TITLE
Fix TBox

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#594]
The [TBox](http://svgjs.com/geometry/#tbox) example, [`x` and `y` doesn't follow scale](http://jsfiddle.net/qa8y7qp2/2/), even though the docs suggest that they should.

The TBox can be fixed easily:
- get the bbox and apply the scale transformation, resulting in a correctly sized tbox
- get the rbox and use it's cx and cy values to position the tbox at its center

**Comment by dotnetCarpenter** [comment]
@woutf I have a conceptual question about [`TBox`](http://svgjs.com/geometry/?q=TBox#tbox).

Should `.tbox()` return the actual `x`, `y`, `width` etc values and a [matrix](http://svgjs.com/classes/matrix/?q=matrix) object with the transformed values, thus mimicking the actual rendered SVG element or the transformed  `x`, `y`, `width` etc values?

The former requires you to do:
```js
// draw transformed rect
var rect = draw
	.rect(175,175)
	.move(75,75)
	.rotate(20)
	.scale(1, 0.5)
        .transform({
		skewX: 2
	})

// draw tbox
var t = rect.tbox()
draw
	.rect(t.width, t.height)
	.transform(t.matrix)
	.addClass('box')
	.move(t.x, t.y)
```

While the latter requires you to do:
```js
// draw transformed rect
var rect = draw
	.rect(175,175)
	.move(75,75)
	.rotate(20)
	.scale(1, 0.5)
	.transform({
		skewX: 2
	})

// draw tbox
var t = rect.tbox()
draw
	.rect(t.width, t.height)
	.transform({
		rotation: t.rotation
	      , skewX: t.skewX
              // etc. for all other transforms
	})
	.addClass('box')
	.move(t.x, t.y) // not sure how to get the correct x,y values with the transformations
```

The issue with the latter is that, I'm not sure how to get the correct x,y values and that you can not apply the matrix from `.ctm().extract()` without retaining the original x,y values.

The former will return an object with:
![svgjs_tbox1 1](https://cloud.githubusercontent.com/assets/43763/23232426/7eef40ec-f94b-11e6-8299-7f18bfcd0506.png)

As we [discussed previously, it's doubtful that anyone is actually using `tbox()` in its current state](https://github.com/svgdotjs/svgdotjs.github.io/issues/2#issuecomment-279946995), so I'm not too afraid about breaking stuff if we decide to change the return object.

**Comment by dotnetCarpenter** [comment]
Our tests reflects the fact that `x` and `y` is translated to new `x` and `y` with transformations. But this  has not worked, for at least a while.

I haven't found any good documentation on how the matrix values is suppose to be calculated to give the skewed, scaled, rotated, translated `x` and `y`. The `fullBox` helper is useless in this regard. `transformedX/Y` also perplex me.

[SVG Coordinate Transformations](https://msdn.microsoft.com/en-us/library/hh535760(v=vs.85).aspx)

[W3 coordinate systems](https://www.w3.org/TR/SVG/coords.html#EstablishingANewUserSpace):

Mathematically, all transformations can be represented as 3x3 transformation matrices of the following form:
![3-by-3 transformation matrix](https://www.w3.org/TR/SVG/images/coords/Matrix.png)
  

Since only six values are used in the above 3x3 matrix, a transformation matrix is also expressed as a vector: [a b c d e f].

Transformations map coordinates and lengths from a new coordinate system into a previous coordinate system:
      ![3-by-3 transformation matrix](https://www.w3.org/TR/SVG/images/coords/MatrixMultiply.png)

**Comment by dotnetCarpenter** [comment]
If we opt for the latter solution, which is how `.tbox()` was initial thought, that is transforming `x`'s and `y`'s, then the only way, that make sense, is to draw it as a polygon.

```js
// draw tbox
var t = rect.tbox()
draw
	.polygon(`${t.xA},${t.yA} ${t.xB},${t.yB} ${t.xC},${t.yC} ${t.xD},${t.yD}`)
	.addClass('box')
```

But then it doesn't make any sense if we wanted to expand this to a circle. However, the name *box* implies that you can not use it with circles.

**Comment by Fuzzyma** [comment]
>I haven't found any good documentation on how the matrix values is suppose to be calculated to give the skewed, scaled, rotated, translated x and y

There are formulars for that and `extract` does exactly that. However: You cant just extract the plain values from a matrix and then chain them together and have the matrix you started with. That just doenst work. When you extract all plain values, you can use _only_ rotation, _only_ translation, _only_ scale or _only_ skew. 
As soon as you alter the matrix in any way mostly all your extracted values are not correct anymore.

Rotation not around the center also translates the object, skewing by a value can end up as rotation and scale and so on.
You have to be very careful when using these plain values and thats also the reason I would never use plain values to calculate a bounding box. 
The only way I see is, to take any point of the shape, transform it to the screen with `screenCTM` and calculate the bounding box of all those points or create a polygon/path out of them and let the browser calculate the bounding box.

>transformedX/Y also perplex me
this is an attribute I added for the SVG.Transformations class. It is needed there and when you look into it you will see why.

**Comment by dotnetCarpenter** [comment]
@Fuzzyma thanks for the explanation. I'm in favor of #601 since it's much simpler to use and implement. But maybe I got the use case wrong? What do you think?

**Comment by dotnetCarpenter** [comment]
The latter can be implement via `.createSVGPoint()` and its `matrixTransform` transform method. But the output is only useful if you want to draw a polygon, as far as I can tell.

**Comment by wout** [comment]
Maybe this will help to make some choices.

I created SVG.js to develop a web-to-print editor. The `rbox()` and `tbox()` were added to visualise a tracker box around one or multiple transformed elements on the canvas because `bbox()` lacked in that area.

**rbox()**
Was created to visualise the tracker box around a selection of multiple elements. Thus not taking rotation into account. And it works fine.

**tbox()**
Was initially created to visualise the tracker box around a single element, including its rotation scale and translation. So if one element was selected, the tracker box would match the visual representation, including rotation. Ultimately, we decided not to go this way. That's why the `tbox()` was never completed.


Now we could wonder if the `tbox()` isn't just too confusing. So I was thinking about the following.

If we skip the `tbox()` method, we can add the following methods to `SVG.BBox`:
- `translated()` (adds any translations to the bbox)
- `rotated()` (adds any translations to the bbox)
- `scaled()` (adds any translations to the bbox)
- `skewed()` (adds any translations to the bbox)

That way, users can choose which transformations to apply to the resulting bbox object. It adds more flexibility and an easier api.

**Comment by dotnetCarpenter** [comment]
@wout I agree with the latter but I would add matrix as well, as in http://svgjs.com/classes/matrix/ to get the matrix methods. The implementation is just:
```js
var ctm = element.ctm().extract()
this.matrix = new SVG.Matrix(ctm.matrix)
```

**Comment by wout** [comment]
Yes, of course. That's what `transformed()` does. It just adds the full matrix. We can all it `matrix()` too.

**Comment by Fuzzyma** [comment]
I dont find this overly useful. The whole purpose can be achieved with using bbox and transform of the element.
If you do 
```js
// draw transformed rect
var rect = draw
	.rect(175,175)
	.move(75,75)
	.rotate(20)
	.scale(1, 0.5)
	.transform({
		skewX: 2
	})

// draw tbox
var t = rect.tbox()
draw
	.rect(t.width, t.height)
	.transform(t.matrix)
	.addClass('box')
	.move(t.x, t.y)
```

or 

```
var rect = draw
    .rect(175,175)
    .move(75,75)
    .rotate(20)
    .scale(1, 0.5)
    .transform({
        skewX: 2
     })

var bbox = rect.bbox()
var rect2 = draw.rect(bbox.height, bbox.height)
    .move(bbox.x, bbox.y)
    .transform(rect.transform())
```
makes no difference and I would always prefer the last one

**Comment by dotnetCarpenter** [comment]
@Fuzzyma We're proposing to remove `.tbox()` and augment `.bbox()`.

**Comment by Fuzzyma** [comment]
Guess I didnt read the full post of wout^^
I agree with wouts proposal. That would also make SVG.GBox unneccesarry

**Comment by wout** [comment]
Agreed. `SVG.RBox` takes a completely different approach, while `SVG.TBox` is just a modified `SVG.BBox`.

**Comment by dotnetCarpenter** [comment]
@wout I don't see `transformed()`. Where is it?

**Comment by wout** [comment]
I'm not sure that you mean?

**Comment by dotnetCarpenter** [comment]
>Yes, of course. That's what **`transformed()`** does. It just adds the full matrix. We can call it matrix() too.

In your [previous comment](https://github.com/svgdotjs/svg.js/issues/594#issuecomment-281954741).

**Comment by Fuzzyma** [comment]
- `translated()` (adds any translations to the bbox)
- `rotated()` (adds any translations to the bbox)
- `scaled()` (adds any translations to the bbox)
- `skewed()` (adds any translations to the bbox)
- `transformed()` (adds the full matrix to the bbox)

**Comment by wout** [comment]
Yes, I proposed it as a modifier method on the `SVG.BBox`, it doesn't exist yet.

**Comment by dotnetCarpenter** [comment]
OK, let us agree on an API.

What about:
`bbox()` returns:

```js
{
	x: 75,
	y: 75,
	width: 175,
	height: 175,
	w: 175,
	h: 175,
	x2: 250,
	y2: 250,
	cx: 162.5,
	cy: 162.5,
	matrix: {
		f: 51.82339859008789,
		e: -10.827729225158691,
		d: 0.5300810933113098,
		c: 0.18190118670463562,
		b: 0.15100568532943726,
		a: 0.8847309947013855
		extract: SVG.Matrix < .extend.extract(),
		clone: SVG.Matrix < .extend.clone(),
		morph: SVG.Matrix < .extend.morph(),
		at: SVG.Matrix < .extend.at(),
		multiply: SVG.Matrix < .extend.multiply(),
		inverse: SVG.Matrix < .extend.inverse(),
		translate: SVG.Matrix < .extend.translate(),
		scale: SVG.Matrix < .extend.scale(),
		rotate: SVG.Matrix < .extend.rotate(),
		flip: SVG.Matrix < .extend.flip(),
		7 more…
	}
}
```

**Comment by dotnetCarpenter** [comment]
The implementation is 1 line added to `SVG.BBox`:

```js
this.matrix = new SVG.Matrix(element.ctm())
```

**Comment by dotnetCarpenter** [comment]
oops, forgot the transformation properties

**Comment by dotnetCarpenter** [comment]
Or do you guys prefer:

```js
{
	x: 75,
	y: 75,
	width: 175,
	height: 175,
	w: 175,
	h: 175,
	x2: 250,
	y2: 250,
	cx: 162.5,
	cy: 162.5,
	transformed: return new SVG.Matrix() + augmented with `element.ctm().extract()`
}
```

**Comment by wout** [comment]
I prefer the latter. Makes for a cleaner API.

**Comment by dotnetCarpenter** [comment]
@wout, when you say:

>skewed() (adds any skew to the bbox)

How do you imagine adding skew to the bbox? As in changing the bbox values, `x`, `cx`, `y2` etc values or returning a matrix object or just the `skewX`,`skewY` vector?

**Comment by wout** [comment]
I've been thinking about that too. Skew is difficult because it's a combination of two transformations: scale and rotation. I'll have to play with it to get a clear vision.

**Comment by wout** [comment]
What do you think is the best approach? Or maybe adding skew is a bridge too far?

**Comment by dotnetCarpenter** [comment]
I feel that if we don't have all of the transformations, then there is little point in having the addition.

The big question is how an end-user would use this. An easy implementation that would pick up changes from `SVG.Matrix` will just be a shortcut to the `SVG.Matrix.ctm()` methods and properties from `SVG.Matrix.ctm().extract()`. This would have to be used in confuction with `.transform()`.

As @Fuzzyma, rightfully says - it's just an alternative for doing `rect2.transform(rect1.transform())` but with added properties.

Transforming only `x`,`y` and `x2`,`y2` doesn't make sense since you need all vectors to get the right coordinates. In a rectangle 4, in a polygon or polyline you need an arbitrary number of vectors.

**Comment by wout** [comment]
It's not completely correct saying `rect2.transform(rect1.transform())` is the same. Transforming the `bbox()` is transforming a calculated geometry while `rect2.transform(rect1.transform())` is actually transforming an existing rect.

**Comment by wout** [comment]
BTW, this can be postponed if there is too much doubt. As you said, `SVG.TBox` isn't any useful in its current state so it can be removed anyway without the need for a replacement.

**Comment by Fuzzyma** [comment]
Agree on removing Tbox.
For bbox I dont see the difficulties.
When the bbox is created we just add the matrix as @dotnetCarpenter suggested.
Also we extend the BBox class with the properties from the list (translated, scaled...).
One of these would somehow look like this:

```js
translated:
    thix.x += this.matrix.e
    this.y += this.matrix.f
    return this
```

Thats ofc the most easy method. For all others we really would need to transform the points of the bbox.

**Comment by dotnetCarpenter** [comment]
You're right.

I believe you can get the calculated geometry without adding to `.bbox()`:

```js
var tbox = Object
  .assign(
    {},
    rect.ctm().extract(),
    new SVG.Matrix(rect.ctm().extract().matrix
  )
```

**Comment by wout** [comment]
Now the only question is, will anyone actually need it?

**Comment by Fuzzyma** [comment]
I believe that having a closest rectangle around a transformed object is very useful. But I guess thats what RBox does. However I like the idea of combining it into the bbox.
Guess I need to think about that. For now I am fine when we remove that from the milestone

**Comment by Fuzzyma** [comment]
@dotnetCarpenter I dont get your code. Why you take the matrix property of the exract method when you just can go with the original matrix? When you want the matrix of an element just use `el.transform()` or when you want the ctm only use `el.ctm()`. No need to extract anything

**Comment by dotnetCarpenter** [comment]
@Fuzzyma [The extract code was there already](https://github.com/svgdotjs/svg.js/blob/master/src/boxes.js#L62) and I didn't realized that I could get it with `element.transform()`.

I noticed that el.ctm() gives me what I need to create a new SVG.Matrix with the transformed values and noted it [here](https://github.com/svgdotjs/svg.js/issues/594#issuecomment-281954137) but not in my PR, which I ditched since we are removing `TBox`.

What is the most efficient way to get the SVG.Matrix with the transformed values for an element?

**Comment by Fuzzyma** [comment]
When you mean the extracted values, go for `element.transform()` because thats the purpose of the method.
If you only want the matrix you might use `element.matrixify()` or `new SVG.Matrix(element)`

**Comment by dotnetCarpenter** [comment]
>When you mean the extracted values, go for element.transform() because thats the purpose of the method.
>If you only want the matrix you might use element.matrixify() or new SVG.Matrix(element)
>
>Please note that ctm works as specified in the specs. element.ctm() and element.matrixify() might return different vaules because ctm gives you the matrix up to the nearest viewport. So if you nest your transformations it will differ

This is great for the docs. ping @wout

**Comment by Fuzzyma** [comment]
@oscarcalvo explain your bug in a seperate issue with code examples and a jsfiddle.
Just writing two lines wont help us to help you

**Comment by dotnetCarpenter** [comment]
@oscarcalvo `TBox` is going away in 2.5.0. Some of `TBox` functionality is covered by `RBox` and you should use `RBox` instead. We have chosen to map `TBox` to `RBox` in 2.5.0, since `TBox` has been broken for a long time and because you easily can use other methods in SVG.js to accomplish what our use-case for `TBox` was.

As @Fuzzyma says, we need more info in order to understand what you are trying to accomplish and before we are able to suggest a workaround or incorporate a solution in SVG.js.

**Comment by oscarcalvo** [comment]
Thanks guys, fixed. I was using 2.3.7.

**Comment by mooreaa** [comment]
Hi guys, I just updated an old project and ran into this issue. Seems rbox by itself doesn't return the center of my transformed object like tbox did. 
I have a "port" object which includes a circle and so the circle inherits a transform from the port. I had to call rbox(object.doc()) to get the center coordinate the same as tbox. 

return {x:this.circle.rbox(this.circle.doc()).cx, y:this.circle.rbox(this.circle.doc()).cy};

**Comment by Fuzzyma** [comment]
Thats a known issue related to the rbox rework. In short: rbox was buggy (and tbox not usefull at all). So we fixed rbox (which includes the new parameter) and **removed** tbox. 
Yes its kinda an api break - but rbox was not usefull the way it was.
