### ISSUE TITLE
SVG.Tspan missing font() method

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#599]
Just discovered this while creating graphics for the docs.

**Comment by dotnetCarpenter** [comment]
Should this go into the 2.5.0 release?

**Comment by wout** [comment]
No, let's leave it for a later release. I just noticed it while building these graphs:
http://jsfiddle.net/wout/xutwzmg5/
http://jsfiddle.net/wout/kdy3ssqx/21/

**Comment by dotnetCarpenter** [comment]
Nice graphs. :heart: 
Good starting point for a graph article.

**Comment by wout** [comment]
Good idea indeed!

**Comment by Fuzzyma** [comment]
@wout adding this is just adding 11 (`, SVG.Tspan`) charackters so it would be quite forward. Do you expect any issues when adding this?

**Comment by wout** [comment]
No, this seems like a logical addition.

**Comment by Fuzzyma** [comment]
Then I will go ahead and add it
