### ISSUE TITLE
Only a few properties are documented for [TextPath](http://svgjs.com/elements/textpath/).

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#600]
Missing: dom, node, x, y, cx, cy, text, size, leading, lines, rebuild, build, setData, plain, **tspan**, clear and length.

Better doc for: font

**Comment by wout** [comment]
@dotnetCarpenter 
Since `SVG.TextPath` is inheriting from `SVG.Text`, those methods are implied. I added a small note about it in the new version, which I will push later today.

What do you suggest for the `font()` method?

**Comment by RmiTtro** [comment]
Maybe we could say that it provide an easy way to set the font properties and then link to [this page](https://www.w3.org/TR/SVG/text.html#FontPropertiesUsedBySVG) in the svg spec.

**Comment by dotnetCarpenter** [comment]
When I browse the docs, I expect to see which methods and properties a
class has. I think that making people click around multiple pages to get
the information is bad UX.

For the font, it is only mention in the example. I think it should have a
prominent place like the rest of the methods.

**Comment by RmiTtro** [comment]
Well the reason I thought it was good to reference the svg spec here is because the `font` method exist just to make it easier to set SVG attributes relating to fonts. Basically `text.font({family:   'Helvetica'})` is the same thing as doing this: `text.attr({font-family:   'Helvetica'})`. 

To rephrase, the `font` method is a part of SVG.js while the attributes it allow to set are a part of the SVG spec.

Anyway, that is what I think but I might be biased since I like to keep things simple :laughing: .

**Comment by dotnetCarpenter** [comment]
@RmiTtro Sorry, it was not a remark to have a link to specs. I think that is a good idea. Without knowing SVG, SVG.js is hard to use.

My remark was to the documentation in general. The more information we can show about a class, without requiring the user to read other pages, the better. I usually have 3 taps open when I browse the docs, which probably mean, that we should consider whether or not our information level on each page is high enough.

In an ideal world, I would get all the information about `TextPath`'s methods and properties from the [TextPath](http://svgjs.com/elements/textpath/) page. Currently, I tend to use the devtool debugger to get that information.

**Comment by wout** [comment]
I've been thinking about further flattening the structure of the docs. For example, have all element pages merged into one large page with anchor links in the menu, just like it's done with the [referencing page](http://svgjs.com/referencing) for example.

**Comment by wout** [comment]
Font method has been described in more detail:
http://svgjs.com/elements/text/#font

TextPath moved to the Text page, so all the methods are available on the same page for both elements. It does, however, retain a link in the menu:
http://svgjs.com/elements/text/#textpath

**Comment by dotnetCarpenter** [comment]
Haha enter the *dragon* :)

Look very good to me.

I think we should take the overall documentation (single page) discussion on slack.

**Comment by dotnetCarpenter** [comment]
Oops, `setData` doesn't seem to be documented but appears in devtools for a `Textpath`.

**Comment by Fuzzyma** [comment]
setData is a thing of SVG.Element and is again an internal method which is not public api

**Comment by RmiTtro** [comment]
Really nice what you did with the docs!!

**Comment by dotnetCarpenter** [comment]
@Fuzzyma We should mark internal methods with a prefix e.i. `_setData()` or people will start to use them.

**Comment by Fuzzyma** [comment]
@dotnetCarpenter imo people should only use documented methods ;). But I guess you are right

**Comment by wout** [comment]
I agree on the prefix.
