### ISSUE TITLE
Array.settle() does not work for PointArray

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#603]
...and also not for a PathArray but I agree that it makes no sense there.
However in case of the PointArray there could be usecases.
We should rework the settle() method so it works with multidimensional arrays.

**Comment by Fuzzyma** [comment]
Array settle also does not return an SVG.Array but a normal array which looks wrong to me

**Comment by wout** [comment]
That's a more general issue. We should return SVG.js objects where possible. Just as I mentioned in the [3.0.0 project](/svgdotjs/svg.js/projects/1)

**Comment by Fuzzyma** [comment]
We also should think if we should always return new objects instead of altering the old ones. That would be then "pure functions". So we can go with the spirit of functional programming and reduce side effects.

**Comment by Fuzzyma** [comment]
settle was remove in 3.0. Just put the array into a set if you need unique values. Closing...
