### ISSUE TITLE
Array constructor calls array.valueOf() which denies optimisation when parsing

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#608]
When you do this:

```js
var a = new PathArray('....')

// and later for some reason this:
var b = new PathArray(a)
```

the whole array is flattened and parsed again because the Array constructor does `array.valueOf()` and therefore the check `if(array instanceof SVG.PathArray)` has no effect anymore because array is a plain array.

Thats not very optimal.

// EDIT: I dont know what user expect when doing `new PathArray(new PathArray))`. Do they want a clone?

**Comment by wout** [comment]
Not very optimal indeed, which might be the cause of the slowness when dealing with paths. The paths benchmark is pretty slow compared to the one with rects:

https://github.com/svgdotjs/svg.js/blob/master/bench/tests/10000-paths.js

As for cloning, I think yes. If you create a new instance, you don't want a relation to the old one.

**Comment by Fuzzyma** [comment]
This optimization is not often used. Only in case of the discussed `new PathArray(new PathArray)`. The slowness comes from the parse function itself. Albeit its faster than the old one, it still could need some love.
However I couldnt come with a better solution at this time and still cant think of an easier one

**Comment by wout** [comment]
Ok, we'll take a look at that later then. Wondering about speeding up path creation, is it absolutely necessary to parse the path string on `plot()`?

https://github.com/svgdotjs/svg.js/blob/master/src/path.js#L17-L21

If we can just `delete this._array` on plot as a setter, then the array cache is removed and regenerated only when required (e.g. on `move()`, `size()`, ...) using the `array()` method.

**Comment by Fuzzyma** [comment]
We need to parse the array at this place in order to draw the path.
When you plot the path you can pass different values (string, array, patharray) and all that needs to be normalized before we even can think about setting the `d` attribute. 
I admit that I dont know which way you wanna take there.

**Comment by wout** [comment]
Something along the lines of:

```js
// Plot new path string
plot: function(d) {
  if (d == null) return this.array()

   if (typeof d !== 'string')
     d = this._array = new SVG.PathArray(d)

   return this.attr('d', d)
}
```

Goes from this:
```
Generate 10000 paths

using SVG.js v2.4.0 completed in 352ms
using vanilla js completed in 46ms
using Snap.svg v0.5.1 completed in 342ms
```

To this:
```
Generate 10000 paths

using SVG.js v2.4.0 completed in 78ms
using vanilla js completed in 44ms
using Snap.svg v0.5.1 completed in 336ms
```

**Comment by Fuzzyma** [comment]
Mh I feel like this is dirty. When we parse the path array we convert all commands to absolute ones. User may start wondering why this isnt done, when a string is passed to plot.
Furthermore I am pretty sure one could speed up the parse process a lot when being smart. I went the most straightforward way because I needed it fast (chrome was removing the feature which we used before)

**Comment by wout** [comment]
Yes, it's dirty indeed. Theoretically speaking, absolute or relative command should not make a difference. when initially rendering.

But if we can fix it by being smart, better :)

**Comment by wout** [comment]
I've been thinking about it, and for me, the extra overhead is the issue. It's not necessary to parse the given string when initially drawing the path. If the user decides to use `translate()` instead of `move()` or `scale()` instead of `size()` for performance reasons, they do still get the punishment for parsing the string while they don't need it. And it's also a heavy task where we can gain maybe 50% of speed, but never the 100% like when skipping it. So I'd rather have a smitch of ugly code than a massive performance hit. And I'm sure we can me it less ugly.
