### ISSUE TITLE
When I type `rotate` in the search, I don't get any docs about `.rotate()`.

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#609]
Better configuration of fuse.js.

**Comment by wout** [comment]
@dotnetCarpenter typing `rotate()` will now get you straight to the right point.

**Comment by wout** [comment]
Ok, exit fuse.js, enter Agolia search.

<img width="814" alt="agolia" src="https://cloud.githubusercontent.com/assets/107324/23339091/0cc92276-fc1b-11e6-906d-fc7d3e4f6204.png">

Thanks @Fuzzyma for reminding me.

**Comment by Fuzzyma** [comment]
That looks great!
