### ISSUE TITLE
rbox() throws in IE/Edge

### ISSUE THREAD

**Issue by showdep** [svgdotjs/svg.js#612]
# Problem

rbox() works under assumption that element.doc() has a parent. This is not true for self-contained SVG files.

# Repro

Create the following SVG file using text editor:

```
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="drawing">

<script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.4.0/svg.min.js"></script>

<script type="text/ecmascript">
window.onload = function(e){ 
  var draw = SVG('drawing').size(300, 300);
  var rect = draw.rect(100, 100).attr({ x:50,y:50, fill: '#f06' });
  // This rbox throws
  console.log(JSON.stringify(rect.rbox()));
  rect.rotate(15,50,50);
  // This rbox throws too
  console.log(JSON.stringify(rect.rbox()));
}
</script>
</svg>
```

Open it in the browser and check the console.

# Fix

In rbox() implementation, enclose the usage of "e" with "if":

```
if(!!e){
  // subtract parent offset
  this.x -= e.offsetLeft
  this.y -= e.offsetTop
  while (e = e.offsetParent) {
    this.x -= e.offsetLeft
    this.y -= e.offsetTop
  }
}
```

**Comment by Fuzzyma** [comment]
Our test cases does not cover that because we always test in html environment... 
@dotnetCarpenter can we build an svg only test environment?

**Comment by showdep** [comment]
There is a similar issue with bbox():
for top-level SVGs, IE does not support document.documentElement.contains, so bbox() should perform element presence in DOM in some other way:

```
      // yes this is ugly, but Firefox can be a bitch when it comes to elements that are not yet rendered
      try {
        if (!document.documentElement.contains){
          // This is IE - it does not support contains() for top-level SVGs
          var topParent = element.node;
          while (!!topParent.parentNode){
            topParent = topParent.parentNode;
          }
          if (topParent != document) throw new Exception('Element not in the IE dom')
        }
        else{
          // the element is NOT in the dom, throw error
          if(!document.documentElement.contains(element.node)) throw new Exception('Element not in the dom')
        }

        // find native bbox
        box = element.node.getBBox()
      } catch(e) {
```

**Comment by Fuzzyma** [comment]
When I tried to find a solution which works in every browser I used contains because it is listed to work everywhere (https://developer.mozilla.org/en-US/docs/Web/API/Node/contains). It surprises me that it isn't working in ie...

**Comment by showdep** [comment]
Yep, I looked at your change history, and I was surprised it didn't work for top-level SVGs as well. Apparently, top-level SVGs make IE/Edge even more special.

On a more general note:
I do understand that self-contained SVGs are not mainstream yet, but if the fix is easy and maintaning top SVG test cases is cheap - why not having it. I am half-way through our experiment with migrating from snap to svg.js, and these two issues (rbox and bbox) are the only big problems I have found so far (inaccurate svg.js typescript definitions are a separate story, but they are much lower priority).

**Comment by Fuzzyma** [comment]
I wrote a [jsperf](https://jsperf.com/element-contains-vs-manual-implementation/1) in order to see if the manual implementation could be maybe faster.
Disappointing result though...

I think we can include your fix albeit I dont know how to write a testcase for that because our test environment runs firefox :/

**Comment by dotnetCarpenter** [comment]
@Fuzzyma It should be pretty straight forward. But how much work it will take before all of our unit tests will pass in a SVG environment, I don't know.

I'll see if I can easily setup the SVG environment.

**Comment by dotnetCarpenter** [comment]
Hmm.. since all of our tests are based on creating an SVG element in a HTML element, I doubt we can get it to work easily. I will ask the Karma people, but don't have high hopes.

BTW, just noticed that [Karma is advertising us as one of their users](https://karma-runner.github.io/1.0/index.html) (in the bottom of the page). I told them a while ago but didn't see the logo until just now.

**Comment by Fuzzyma** [comment]
We could run all the tests for different documents. Only the very first setup code would be different for svg (the first four lines in helper.js).

For now I dont think a seperate environment is needed. Op updated its post and he uses an html document, too. So we can test the most relevant cases in our normal spec.

However to make sure that everything really works, it might be useful to have this svg environment.

Cool thing about the logo on the karma website. They should change the title to svg.js though... :)

**Comment by Fuzzyma** [comment]
@showdep for your usecase you could also go `SVG.get('drawing')` which will just adopt the svg in your document. Everything should work as normal after that.

**Comment by dotnetCarpenter** [comment]
@showdep I just pasted your code into a blank `.htm` document and I see no problem. In what browser are you experiencing this?

**Comment by Fuzzyma** [comment]
>Yep, I looked at your change history, and I was surprised it didn't work for top-level SVGs as well. Apparently, top-level SVGs make IE/Edge even more special.

;)

**Comment by dotnetCarpenter** [comment]
So IE. Yes, we can use the same setup to run the test in IE on appveyor.com

**Comment by showdep** [comment]
> @showdep for your usecase you could also go draw = SVG.get('drawing') which will just adopt the svg in your document. Everything should work as normal after that.
> 
> @showdep I just pasted your code into a blank .htm document and I see no problem. In what browser are you experiencing this?

Just to make it 100% clear: there is no HTML in my scenario. Neither html markup, nor html files. All content and all scripts are hosted by svg file.

**Comment by Fuzzyma** [comment]
@showdep please try #626 for your rbox issue and report back

**Comment by showdep** [comment]
@Fuzzyma , rbox issue not reproducible in #626, I tried Chrome and IE11. Thanks!

**Comment by Fuzzyma** [comment]
OK great! For the bbox issue I will wait until the other one is merged so we don't get merge conflicts. I will take your solution in this case.

**Comment by Fuzzyma** [comment]
@showdep I pushed your fix to master. However, could you please provide us the file / a similar file in which this bug occured? I would like to have it for testing purposes.

**Comment by Fuzzyma** [comment]
@showdep I also would suggest you to file a bug to the Edge team so that this becomes fixed soon.
Reference: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

**Comment by showdep** [comment]
Thank you @Fuzzyma for taking care of the bbox() issue. Looks good when I run it with the current master.

IE 11 bug filed (it seems to work ok in Edge):
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11212388/

I wouldn't hold my breath though, they say "_we do not plan further feature updates. All new feature work is focused on Microsoft Edge at this time. For this reason, only high-impact security bugs will be considered for Internet Explorer servicing_"

As for the test file for you, here it is:

```
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="drawing">
<script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.4.0/svg.min.js"></script>
<script type="text/ecmascript">
window.onload = function(e){ 
  var draw = SVG('drawing').size(300, 300);
  var rect = draw.rect(100, 100).attr({ x:50,y:50, fill: '#f06' });
  // This bbox works in FF and Chrome and Microsoft Edge 38.14393.0.0
  // Gives SCRIPT28: Out of stack space in IE 11.0.9600.18537 for Windows 7
  console.log(JSON.stringify(rect.bbox()));
}
</script>
</svg>
```

**Comment by Fuzzyma** [comment]
Cool, thank you very much. Yes I hadn't much hope for ie 11 anyway but asking doesn't hurt :).
