### ISSUE TITLE
Wrong documentation on SVG.Gradient and SVG.Pattern

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#615]
http://svgjs.com/elements/pattern/#fill-as-setter
http://svgjs.com/elements/gradient/#fill-as-setter

Those setters are not related to those classes.

**Comment by Fuzzyma** [comment]
But its a useful addition when you search for patterns. Because you want to know how to use them :)

**Comment by wout** [comment]
Yes, of course, I agree. But I would like to show that in a usage example. Now it's defined as a setter on `SVG.Pattern`, but `fill()` only acts a getter there. I'm thinking about reformatting the element pages into the following format:
- introduction + usage example(s)
- class-specific methods, each with a description
- listing of inherited methods with a link to the super class for more info

I think that will make things very much more clear and easier to read.

**Comment by Fuzzyma** [comment]
I am a bit confused how the getter has a valid relation to the gradient class and the setter has not. Is there even a fill method on SVG.Gradient? I will check myself when I am at home :)

**Comment by wout** [comment]
Maybe that's a bit confusing indeed. :)  The `fill()` method on a gradient returns a value for the fill attribute on fillable elements. Something like: `url(#SvgjsGradient1234)`.

**Comment by Fuzzyma** [comment]
Ah I now see it. OK that's really confusing indeed. For 3.0 I would rename that method. Method overloading is only nice if it does what the user expects :D

**Comment by wout** [comment]
Yeah, same with `show()` on `SVG.A`. Not good :!

**Comment by Fuzzyma** [comment]
In that case it's even worse because the normal how function gets overwritten. That problem is already added to the 3.0 project

**Comment by wout** [comment]
Added the `fill()` method too: https://github.com/svgdotjs/svg.js/projects/1#card-1874822
