### ISSUE TITLE
Bug in text.x() which will not move lines()

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#616]
Just found this line in text.js:
```js
      if (!this.textPath)
        this.lines().each(function() { if (this.dom.newLined) this.x(x) })
```

I feel like `this.textPath` is always defined because its a function. Shouldnt it be `this.textPath()` instead?
Coverage report also says that this condition is never true and the line below never executed

**Comment by wout** [comment]
I think we might have had an internal reference there before it became a method. Or it used the be from the time that svg.js included a builder to compile your own custom version, but that seems less likely given the code.

**Comment by Fuzzyma** [comment]
Yes I think so, too. When I got through the history of the file you see that all these occurrences where replaced. But it looks like this was missing. The odd thing is, that no tests are failing and I wonder why. I even added a test to exactly test that and it passes anyway

**Comment by Fuzzyma** [comment]
@wout so I found the bug or better the thing which make it work anyway:

When you call `x()`, it calls the `attr()` method which has a notable line at the end:

```js
      if (this.rebuild && (a == 'font-size' || a == 'x'))
        this.rebuild(a, v)
```

this condition is true and a rebuild is triggered. The rebuild will then adjust the x attr of the children properly.

The question is now: Do we still need to adjust the children in the x-method?
Imo whenever the build-mode is on, the x should be adjusted automatically. And thats how it is atm. So we could remove the 2 lines from the first post.
