### ISSUE TITLE
flip element on both axis when calling flip without a parameter

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#619]
`flip('x')` flips on x axis, `flip('y')` on y axis. Why does `flip()` not flip it on both?
Even worse: It flips on y - thats totally unexpected

**Comment by wout** [comment]
Bad behaviour indeed:

```js
a == 'x' ? this.scale(-1, 1, o, 0) : this.scale(1, -1, 0, o)
```

Auch.

Love your suggestion. Although flipping `x` and `y` would be the same as rotating` 180º`.

**Comment by Fuzzyma** [comment]
I think that would be no problem. Users know what they get when they flip on both axes so it should be fine...

**Comment by Fuzzyma** [comment]
@wout what do you think of this:

```js
      o = typeof a == 'number' ? o : a
      return a == 'x' ?
          this.scale(-1, 1, o, 0) :
        a == 'y'
          this.scale(1, -1, 0, o) :
          this.scale(-1, -1, o, o)
```

It should work for any usecase

**Comment by wout** [comment]
Looks good to me at first sight! Great additional feature.

**Comment by wout** [comment]
As for documentation, maybe we should open a documentation 2.5.0 issue instead of separate issues. Otherwise, the issue stream gets too polluted. Next week I'll have the time I'll do everything in one go, including flattening.

**Comment by Fuzzyma** [comment]
I already thought that, too. I will create a documentation issue and add everything else on the list.
Btw: It would be great if we could have tags for teh documentation, too. That way we could have one revision for the documentation for every tag. So that people which are not using the master still have a valid documentation.
If you look here: https://laravel.com/docs/5.4/installation
They have a select field where you can select your version to see the corresponding docs

**Comment by Fuzzyma** [comment]
added with 41b55427a71f85e444a8729a552b4db5aa9ac772

**Comment by wout** [comment]
Exactly what I was thinking too! So we'll have:

- http://svgjs.com/
- http://svgjs.com/2.5/
- http://svgjs.com/2.4/

That's going to be necessary.
