### ISSUE TITLE
Run unit test in IE/edge

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#622]
We got [1 bug report about `RBox` not working in IE](https://github.com/svgdotjs/svg.js/issues/612#issuecomment-282541470).

To catch these bugs, we can run our unit tests in IE and Edge on [appveyor.com](https://ci.appveyor.com/projects).

It needs a little setup, mainly on the appveyor project page but also has a different Karma launcher dependency (IE launcher). In `karma.conf.js` we probably only want to change `browsers: ['Firefox']` to `browsers: ['IE', 'edge']`

**Comment by dotnetCarpenter** [comment]
We will only be able to run our test in IE11 on appveyor, because [they use Windows Server 2016 Datacenter which does not come with MS Edge](https://appveyor.tenderapp.com/discussions/questions/3424-confusion-about-how-to-change-to-os#comment_42139304).

@Fuzzyma Do we want to run our unit tests in IE11? A lot of [the failing tests](https://ci.appveyor.com/project/dotnetCarpenter/svg-js/build/1.0.35) are rounding differences from Firefox.

**Comment by Fuzzyma** [comment]
I fixed a lot of this rounding errors. However - still many tests fail. I had no more time to look into this.
Before we can automate this I need to check the tests again.

**Comment by dotnetCarpenter** [comment]
@Fuzzyma I should also clean up the test code a bit. Since MS Edge will never work on appveyor.

We could also migrate all our tests to [saucelabs.com](https://saucelabs.com/open-source) and run our tests on 800 browsers. But I imagine the rounding differences will grow enormously.

**Comment by Fuzzyma** [comment]
Wow thats cool! Again free for open source - I like this new way of thinking. What is needed to migrate our tests there? Can we just use our jasmine tests?

**Comment by dotnetCarpenter** [comment]
Yes, we can run out Jasmine test suite on sourcelabs. I hope we just need to use this module: https://github.com/karma-runner/karma-sauce-launcher and create an account with sourcelabs,

**Comment by Fuzzyma** [comment]
@dotnetCarpenter was this issue resolved?

**Comment by dotnetCarpenter** [comment]
Not as far as I know. Saucelabs was working for a fix for Safari on macOS, which is part of the test suite but...
 I honestly haven't checked in months but last I heard was that there was almost a PR. But AFAIK we haven't received a PR. I'm pretty busy the next month with a vue.js project, my spare time will be spend in that area.

**Comment by Fuzzyma** [comment]
No problem - was just asking in case this can be closed :)

**Comment by saivan** [comment]
Can this be closed now?

**Comment by Fuzzyma** [comment]
Yes. There is a try catch for rbox in the code now
