### ISSUE TITLE
In the FX module, stop is calling start

### ISSUE THREAD

**Issue by RmiTtro** [svgdotjs/svg.js#623]
The method [stop()](https://github.com/svgdotjs/svg.js/blob/f6d15b07cff5be7cefea62ea874f2e7361108253/src/fx.js#L260) of the FX module is calling `start()` when the animation is not active like so:

```javascript
if(!this.active) this.start()
```

I don't think this is good, it should probably be something more like this:

```javascript
if(!this.active) return this
```

**Comment by Fuzzyma** [comment]
I think there was a good reason why I did that. Maybe this reason went away when you reworked the module.

I guess one reason was because: `stop()` calls `this.clearCurrent()` which should be performed even if the animation is not active. At least that were my thoughts. Maybe its not what the user expects...

**Comment by RmiTtro** [comment]
Your right, I was wrongly assuming that when the animation is not active
there are no situations which is not necessary true.

Still, I think we should make it so that if 'stop' is called when there are
no situation it doesn't fail.

Le 3 mars 2017 11:46 AM, "Ulrich-Matthias Schäfer" <notifications@github.com>
a écrit :

I think there was a good reason why I did that. Maybe this reason went away
when you reworked the module.

I guess one reason was because: stop() calls this.clearCurrent() which
should be performed even if the animation is not active. At least that were
my thoughts. Maybe its not what the user expects...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/svgdotjs/svg.js/issues/623#issuecomment-284005838>, or mute
the thread

**Comment by RmiTtro** [comment]
Forget about this issue, nothing is wrong with stop. The problems I spotted were caused by something else. I guess I was just taken aback by the call of `start()` in `stop()` XD.

**Comment by Fuzzyma** [comment]
ok, if you say so.... :D
