### ISSUE TITLE
Animating a flip transform does not work 

### ISSUE THREAD

**Issue by RmiTtro** [svgdotjs/svg.js#624]
This bug was found by @Fuzzyma, I'm just reporting it here. The problem lies with [this line](https://github.com/svgdotjs/svg.js/blob/f6d15b07cff5be7cefea62ea874f2e7361108253/src/transform.js#L153-L156):

```javascript
 matrix = new SVG.Matrix().morph(new SVG.Matrix().flip(
        o.flip
      , o.offset == null ? target.bbox()['c' + o.flip] : o.offset
      ))
```

Replacing it by this seem to fix the problem:

```javascript
 matrix = new SVG.Matrix().flip(
        o.flip
      , o.offset == null ? target.bbox()['c' + o.flip] : o.offset
      )
```

**Comment by Fuzzyma** [comment]
The thing with is is, that I added tests for that and it does something.
My test shows that

```js
fx.transform({flip: 'x', offset: 100}) == new SVG.Matrix().flip('x', 100))
```

And now I dont know if this is only just wrong or kinda working anyway.

**Comment by RmiTtro** [comment]
I found your tests for `flip` and they actually show that there is a problem. If you compare a test for `rotate` with a test for `flip` the problem become apparent.

```javascript
// The test for rotate
it('adds an entry to transforms when rotation given', function() {
      fx.transform({rotation: 30, cx:0, cy:0})
      expect(fx.situation.transforms[0]).toEqual(jasmine.objectContaining(new SVG.Rotate(30, 0, 0)))
})

// The test for flip
it('adds an entry to transforms when flip x given', function() {
      fx.transform({flip: 'x'})
      expect(fx.situation.transforms[0].destination).toEqual(jasmine.objectContaining((new SVG.Matrix()).flip('x', 150)))
})
```

You see that the `flip` test need to be performed on the `.destination` attribute why this is not the case for the `rotate` test. There lies the problem! You shouldn't need to make the test on the `.destination` attribute.

**Comment by Fuzzyma** [comment]
Yes you are right :D. I guess I intuitively did that to make the test pass. Well then the case is clear. Do you mind fixing it? I am on the `rbox()` fix at the moment

**Comment by RmiTtro** [comment]
I'm on it! :wink:

**Comment by RmiTtro** [comment]
Done and done!!
