### ISSUE TITLE
animate().size() is not flexible enough, animate().scale() is (mysteriously) working

### ISSUE THREAD

**Issue by showdep** [svgdotjs/svg.js#630]
I have 100x100 rect and I want to animate it so it becomes bigger, and I want this transform to have the center at the center of the rect, not at the top left corner. snapsvg.js allows the following solution (just create an SVG file and open it in the browser):

```
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="drawing">
<script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.4.0/svg.min.js"></script>
<script type="text/ecmascript">
window.onload = function(e){ 
  var draw = SVG('drawing').size(300, 300);
  var rect = draw.rect(100, 100).attr({ x:50,y:50, fill: '#f06' });
  // Makes rect 2 times bigger, transform center is 50,50 (rect's left top corner)
  rect.animate(1000,'>').size(200,200);
}
</script>
</svg>
```

which is I am not happy with, because the rectangle grows relative to it's top left corner. I tried the following code:

```
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="drawing">
<script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.4.0/svg.min.js"></script>
<script type="text/ecmascript">
window.onload = function(e){ 
  var draw = SVG('drawing').size(300, 300);
  var rect = draw.rect(100, 100).attr({ x:50,y:50, fill: '#f06' });
  // Makes rect 2 times bigger, transform center is 100,100 (center of the rect)
  rect.animate(1000,'>').scale(2,2,100,100);
}
</script>
</svg>
```

and, surprisingly, it works as I would like it to, although animation object (SVG.FX I guess) does not have a "scale" method.

What am I missing here? Is scale() a kind of undocumented functionality? Is there any chance we can make this animate().scale() legal since animate().size() is not flexible enough (no way to specify transform centerpoint)? Thanks!

**Comment by RmiTtro** [comment]
`scale` is totally legit and is also documented: http://svgjs.com/manipulating/transforms/
 When you see `animate yes` in the docs it mean you can use it in animation too.
Also, SVG.FX as a `scale` method, but it is not defined in `fx.js`. It is defined in `sugar.js` if I'm not mistaking.

**Comment by showdep** [comment]
My impression was that "scale" can be applied to an element (not an animation), and the documentation at http://svgjs.com/animating/ says that "animate() method will not return the targeted element but an instance of SVG.FX". Hence the confusion. I think I just missed the "animate yes" part, thank you for the explanation.

I am totally happy with scale() working against the animation returned by animate(), just wanted to be sure this is not a kind of undocumented feature that will silently disappear at some point. Also, size() method of SVG.FX looks redundant then: scale() can do what size() does and much more.

Anyways, if scale() called against animation is to stay as it is forever please feel free to close this issue as "by design". Thanks!

**Comment by Fuzzyma** [comment]
Size and scale do completely different things. While scale just adds a transformation to the element, size alters the height and width if the element. There are multiple use cases where you don't want the scale. You can even create a scale around the center with size if you animate the x and y attribute to move the shape while resizing it. It looks the same ;)
