### ISSUE TITLE
rbox() returns empty (0,0,0,0) box for top-level SVG (2.5.0 master, change 8a0a4d7, Chrome/Windows)

### ISSUE THREAD

**Issue by showdep** [svgdotjs/svg.js#632]
Create an HTML file and copy the following content in it:

```
<html>
<body>
<svg width="800" height="600" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="drawing">
<script type="text/javascript" xlink:href="svg-2.5.0.js"></script>
<script type="text/ecmascript">
window.onload = function(e){ 
  var draw = SVG('drawing').size(300, 300);
  var g = draw.group();
  g.rect(1000, 1000).attr({ fill: '#f06' });
  g.scale(0.015,0.015,0,0);
  // For SVG within HTML, this rbox() returns proper result.
  // For standalone SVG, this rbox() returns (0,0,0,0) box.
  console.log("svg.js rbox():", JSON.stringify(g.rbox()));
  console.log("plain javascript:", g.node.getBoundingClientRect());
}
</script>
</svg>
</body>
</html>
```

Open this HTML file in Chrome and see the console - it reports proper box size and position:

```
svg.js rbox(): {"w":15,"h":15,"x2":23,"y2":23,"cx":15.5,"cy":15.5,"x":8,"y":8,"width":15,"height":15}
plain javascript: ClientRect {top: 8, right: 23, bottom: 23, left: 8, width: 15…}
```
 
Now take the
```
<svg>...</svg>
```
part from the content above and save it to a standalone svg file and open it in Chrome. In the console, you will see:

```
svg.js rbox(): {"w":0,"h":0,"x2":0,"y2":0,"cx":0,"cy":0,"x":0,"y":0,"width":0,"height":0}
plain javascript: ClientRect {top: 0, right: 15.000000953674316, bottom: 15.000000953674316, left: 0, width: 15.000000953674316…}
```

So, plain JS reports proper rect, while svg.js falls back to (0,0,0,0). I was under impression that new rbox() implementation in 2.5.0 simply calls getBoundingClientRect(). Apparently, this is not all it does.

**Comment by Fuzzyma** [comment]
It does exactly that. The only thing it does is adding the scroll offset to the top and left. I need to debug this. Don't want this bug shipped with 2.5

**Comment by Fuzzyma** [comment]
Thats what I get: 

```
svg.js rbox(): {"w":15,"h":15,"x2":15,"y2":15,"cx":7.5,"cy":7.5,"x":0,"y":0,"width":15,"height":15}
"plain javascript:" DOMRect { x: 0, y: 0, width: 15, height: 15, top: 0, right: 15, bottom: 15, left: 0 }
```

Looks good to me

**Comment by showdep** [comment]
You are using FF. It's Chrome :)

**Comment by Fuzzyma** [comment]
```
svg.js rbox(): {"w":15.000000953674316,"h":15.000000953674316,"x2":15.000000953674316,"y2":15.000000953674316,"cx":7.500000476837158,"cy":7.500000476837158,"x":0,"y":0,"width":15.000000953674316,"height":15.000000953674316}
plain javascript: ClientRect {top: 0, right: 15.000000953674316, bottom: 15.000000953674316, left: 0, width: 15.000000953674316…}
```

Looks better now :)

**Comment by showdep** [comment]
|| is a known producer. And when null/undefined comes into play... I miss C++ days sometimes. Let me check the fix.

**Comment by Fuzzyma** [comment]
This only happend here because of many aspects I'd the box initializer + the differences between browsers. Chrome returns only left and top as position in the client rect while FF also returns x and y. Since our boxes are normalized to x and y I have to correct chromes appearance. 
In this case left was zero so x was taken instead which was undefined. The initializer was then reused with 4 parameters (x, y, width, height) with x wet to undefined which let to a wrong check ^^
