### ISSUE TITLE
Update doc to say we can pass a parent param to SVG.select()

### ISSUE THREAD

**Issue by cherihung** [svgdotjs/svg.js#633]
tiny suggestion. May be good to include an example in the documentation's Referencing section to show we can pass a dom object as a parent element to do the query.

After looking at the code, I figured I can do this -
```javascript
var wrapper = $('#parentId').get(0);
var element = SVG.select('.someElement', wrapper);
```
I know I can pass in the css selectors within SVG.select(). But this made the code more cleaner with the angular app I'm working on. I can just pass in the scoped element with a much shorter string of selectors.

i'm referring to this piece of functionality. neat feature.
```javascript
SVG.select = function(query, parent) {
  return new SVG.Set(
    SVG.utils.map((parent || document).querySelectorAll(query), function(node) {
      return SVG.adopt(node)
    })
  )
}
```

**Comment by Fuzzyma** [comment]
Why you dont just go `wrapper.select('.someElement')`?

I will add it to the list in #629 so we include it into the docs. Thanks!

**Comment by cherihung** [comment]
My wrapper isn't created or initialized by SVG. When I tried to do that, it gave me a .select() is not a method for wrapper error. so i was happy to find this functionality. thanks!
