### ISSUE TITLE
Animation for group transformation using transform and matrix

### ISSUE THREAD

**Issue by abnemo** [svgdotjs/svg.js#636]
I decided to update svg.js from 2.2.3 to the latest version in my old project. After update everthing works fine except the animation while transforming the group using matrix:
```javascript
var matrix = new svgjs.Matrix(a, b, c, d, e, f);
group.animate(500, '<>').attr({
    'transform': matrix.toString()
});
```
As i understand, this does not work with the current svg.js version. Reading the documentation i found the morph() method, that let me pass a destination matrix.

What i cant figure out is, how to use the morph() method in order to animate group transformation. Is it the right way, to solve this problem?

I would appreciate if someone could help me here.

Thanks

**Comment by Fuzzyma** [comment]
You could animate everything in svg. Not only the attr method. So you can go `element.animate().transforn(yourMatrix)`. That should work.

**Comment by abnemo** [comment]
@Fuzzyma thank you for your advice. it works. :)

**Comment by Fuzzyma** [comment]
`yourMatrix` in my example is an `SVG.Matrix`. So you would use `transform(new SVG.Matrix(1, 0, 0, 1, cx, cy))` but you rather want `transform({x: cx, y: cy})`

**Comment by heaversm** [comment]
Thanks, worked great!
