### ISSUE TITLE
Rename DOM query selector methods

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#637]
### Precis
- there is confusion around methods to get elements by tag/id/class
- more comprehensible methods should be provided to replace the old ones

### Problem
1. `SVG.get()` _(getElementById)_ and `SVG.select` _(querySelectorAll)_ are rather confusing
2. `SVG.get()` is too referencial to the `get()` method on `SVG.Parent`
3. `SVG.get()` only allows to get elements by id, not class or tag names
4. `SVG.select()` clashes with the `SVG.select` plugin
5. `SVG.select()` returns an instance of `SVG.Set`, which will be removed in 3.0

### Proposal
- [ ] `SVG.get()` becomes `SVG.find()`, which basically wraps the native `querySelector` and returns an instance of `SVG.Element` or one of its subclasses
- [ ] `SVG.select()` becomes `SVG.all()`, which basically wraps the native querySelectorAll and returns an array of `SVG.Element` instances (or the corresponding subclasses)

**Comment by Fuzzyma** [comment]
I like that very much. The only concern left is, that you cant conclude from one method to the other. However, that really is a minor problem. So +1 from me!

**Comment by wout** [comment]
I'm not really sure what you mean by:
> conclude from one method to the other

**Comment by Fuzzyma** [comment]
When you know one method you dont know automatically the other one. But as I said - it doesnt matter that much :)

**Comment by wout** [comment]
Ok, you got a point. But indeed, it doesn't really matter. :)

**Comment by RmiTtro** [comment]
I agree with the changes but I'm a bit surprised that we are removing `SVG.Set` from 3.0. I think that being able to group similar elements together in order to execute the same method on all of them is useful. That being said, I certainly agree that the implementation of `SVG.Set` need some reworking to make it more efficient. Unless, we are replacing it by something that perform a similar task that I am not aware of?

**Comment by Fuzzyma** [comment]
The code overhead of `set.fill()` vs `arr.forEach(function(el){ el.fill() })` is not that big. the implementation of `SVG.Set` only includes the base methods (e.g. `text()` doesnt work). If we would have proxies already (so we can catch calls on methods which does not exist) we could easily call all methods. That would also remove the need for the rather confusing code of `Set.inherit`.
Furthermore the access to elements is not possible via indexing.

That all together leads to that decision. Instead we have plain arrays everyone knows. No magic involved.

**Comment by wout** [comment]
For me, it is a difficult decision to remove `SVG.Set`. I love the ease of use. But to be honest, `SVG.Set` never really worked as it should, at least not in its current state. The `inherit()` approach was a flawed concept from the beginning. All elements have their dedicated class, and therby also methods, but sets can't. How can we apply all methods from all `SVG.Element` subclasses? It's prone to get messy and unreliable.

A possible solution I have been thinking about is to remove the `inherit()` method  and extend the use of the `each()` method instead. For example:

```js
set.each('fill', '#f06')
```

That's a lot nicer than the following, which I still think is rather hard to swallow:

```js
arr.forEach(function(el){ el.fill('#f06') })
```

This could also work with key/value pairs:

```js
set.each('attr', 'fill', '#f06')
```

And this functionality could be mirrored to the `each()` method on `SVG.Parent` as well:

```js
group.each('fill', '#f06')
```

**Comment by Fuzzyma** [comment]
Well if we really do this, I would like to have the same approach as jauery. They somehow used an array as prototype and thats what I would like to have, too. So you can access elements using indices.

**Comment by wout** [comment]
That would be useful indeed, also for `SVG.Array` by the way. Unfortunately, subclassing the native `Array` does not bring along this functionality, I've looked into that.

Briefly looking at the jQuery code, I noticed the initialize with `this.length = x`. So I suspect they store the members in indices locally. Something like:

```js
for (var i = 0; i < members.length; i++)
  this[i] = members[i]

this.length = members.length
```

Not very pretty but that would make it work.

**Comment by wout** [comment]
Coming back to the original proposal, shall I implement this as suggested?

**Comment by Fuzzyma** [comment]
Yes from me

**Comment by Fuzzyma** [comment]
We just had an elightment. The `SVG()` method already has a querySelector build in. So you can go `SVG('#comeElement')` and will get back one Element. So we can use `find()` for multiple elements - and thats great!

**Comment by saivan** [comment]
This is now working on the 3.0.0 branch.
