### ISSUE TITLE
Referencing newly-created/imported svg

### ISSUE THREAD

**Issue by brandondurham** [svgdotjs/svg.js#638]
I’m importing raw SVG data and then adding it to my svg.js-managed SVG like this:

```javascript
theGallerySVG.svg(response);
```

In this instance `response` is just the SVG as a string, and it’s working wonderfully. How do I then easily reference this new child SVG, though? I tried adding it to a variable (`const theChild = theGallerySVG.svg(response);`) but it only returns the parent container, or `theGallerySVG`.

**Comment by Fuzzyma** [comment]
Yes that is indeed correct behavior because you could also import multiple child `<rect ...><circle ...>`. Thats why only the container is returned.
However you can access this elements in multiple ways:

```js
// by index
parent.get(0) // gets the first element
// by selector
parent.select(css-selector).get(0) // select returns a set from which you get the first matche element
```

Hope I could help :)

**Comment by brandondurham** [comment]
Thanks so much. Fortunately in my case I’m cycling though several SVGs and adding them, so I can add quick local references for them to an object.
