### ISSUE TITLE
Is SVG.adopt part of the public API?

### ISSUE THREAD

**Issue by nickbreaton** [svgdotjs/svg.js#639]
I was working with an existing `g` element already queried with JavaScript. I needed to use svg.js to transform that element.

In the documentation, http://svgjs.com/referencing/, there was no way of referencing an existing element. I checked out the source for the selecting, and found the function [`SVG.adopt(node)`](https://github.com/svgdotjs/svg.js/blob/master/src/selector.js#L11).

I then used that in my code and everything worked perfectly. 👍 

Upon further inspection, I see this is documented in the [Typescript typings](https://github.com/svgdotjs/svg.js/blob/master/svg.js.d.ts#L23). 

Would it be appropriate to add a section on `SVG.adopt` to the documentation [here](http://svgjs.com/referencing/)? If so I would be more than happy to submit a PR.

Thanks for all the hard work!

**Comment by Fuzzyma** [comment]
Yes! Feel free to submit a PR to the [source branch](https://github.com/svgdotjs/svgdotjs.github.io/tree/source). We will review it and include it in the next revision.
