### ISSUE TITLE
Can't rotate inline SVG

### ISSUE THREAD

**Issue by justintanner** [svgdotjs/svg.js#642]
Given the following inline SVG:

```
<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px" id="rekt">
  <rect width="100" height="100"></rect>
</svg>
```

And the following JS:

```
var rekt = SVG('rekt');
rekt.rotate(25);
```

The rectangle does not rotate.

Is this a bug? or am I using SVG.js incorrectly?

Please advise.

**Comment by showdep** [comment]
In your code, you are trying to rotate the whole SVG object, not the rectangle. If you want to rotate the rectangle within your SVG content, you have to reference it properly, for example (just paste this code into an SVG file and open it in your browser):

```
<svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px" id="rekt" xmlns:xlink="http://www.w3.org/1999/xlink">
<script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.5.0/svg.min.js"></script>
<script type="text/ecmascript">
<![CDATA[
window.onload = function(e){ 
var rekt = SVG('rekt');
var actual_rekt = SVG.get("actual_rekt");
actual_rekt.rotate(25);
}
]]>
</script>
  <rect id="actual_rekt" width="100" height="100"></rect>
</svg>
```

If this is not your intent, please clarify it.

**Comment by dotnetCarpenter** [comment]
@showdep While I applause your SVG only approach. I think it's easier for @justintanner to understand an HTML example with in-lined SVG.

Say you have this page:

```html
<!DOCTYPE html>
<html>
<body>
  <svg xmlns="http://www.w3.org/2000/svg" width="100px" height="100px" id="rekt">
    <rect width="100" height="100"></rect>
  </svg>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.5.0/svg.min.js"></script>
  <script>
    var rects = SVG.select("rect") // use CSS selector - returns a SVG.Set
    rects.rotate(25)
  </script>
</body>
</html>
```

+ http://svgjs.com/referencing/#svg-select
+ http://svgjs.com/classes/#svg-set
+ http://svgjs.com/manipulating/#rotate

As you can see, we have rotate a 100\*100 square inside a 100\*100 canvas (`id="rekt"`). `<svg>` is your canvas which you can draw 2D scalable graphics and `<html>` is your page. If you want to manipulate or create figures inside your `<svg>` element, you should use SVG.js. But if you want to manipulate an element in your `<html>` page, then use CSS.

```css
svg { transform: rotate(25); }
```

You where trying to manipulate an HTML element in your page with SVG.js. That does **not** work.
