### ISSUE TITLE
Firefox: bbox() causes "too much recursion"

### ISSUE THREAD

**Issue by showdep** [svgdotjs/svg.js#643]
# Symptoms
Simple code:
```
var g = drawing.group();
var t = drawing.plain("ABCD").attr({...});
var bBox = new SVG.BBox(t); // This is the problematic call
```
causes "too much recursion" error in FF 52.0.1 32 bit Windows, svgjs 2.5.0

# Problem
Consider this svg.js 2.5.0 bbox code:
```
SVG.BBox = SVG.invent({
  // Initialize
  create: function(element) {
        ...
       // In FF, this throws error 2147500037, name: "NS_ERROR_FAILURE"
       box = element.node.getBBox()
    } catch(e) {
      if(element instanceof SVG.Shape){
        var clone = element.clone(SVG.parser.draw).show()
        // This calls BBox create again causing recursion
        box = clone.bbox()
```
The problem is: the exception is handled, but only under assumption that it was originated from the 
```
if(!document.documentElement.contains(element.node)) throw new Exception('Element not in the dom')
```
piece right above the element.node.getBBox() call. The scenario with throwing element.node.getBBox() is not covered, causing endless recursion.

# Workaround
I call t.node.getBBox() directly to avoid svg.js code, and wrap it with try/catch. For unknown reason, native getBBox() never throws.

# Repro
Unfortunately, no good repro - it is happening only when called by my framework (it's not a standalone SVG this time - SVG is running within HTML). As this is a pretty obscure issue, feel free to close as no-repro, but I would like to:
- leave some trace just in case;
- draw attention to the getBBox/clone.bbox() recursion possibility which potentially can backfire in other scenarios.

Thanks!

**Comment by Fuzzyma** [comment]
Please retry with the current master. I am pretty sure I fixed that issue
yesterday evening :)

Am 22.03.2017 08:38 schrieb "showdep" <notifications@github.com>:

**Comment by showdep** [comment]
That was quick!
I see:
box = clone.bbox()
became
box = clone.node.getBBox()
I agree - there is no more recursion. But clone.node.getBBox() may throw too... Let me try master when I have time.
Thanks!

**Comment by Fuzzyma** [comment]
Yes you are right it may throw. We could wrap it in another try catch. This is done properly in 3.0. I might fix it today...

**Comment by showdep** [comment]
> We could wrap it in another try catch

I wouldn't do that - it will just mask the real issue in the caller code, like calling bbox against an item that is not in a good state for bbox. This kind of issues must be handled by the caller code, not svg.js. Eliminating the endless recursion is the best thing you can do here, and you have done it. Thanks!

**Comment by Fuzzyma** [comment]
3.0 is outputting a warning and gives back a nulled box. I think that is even better. But for 2.5 this might be enough here...
