### ISSUE TITLE
Change `SVG()` to use querySelector instead of getElementById.

### ISSUE THREAD

**Issue by wout** [svgdotjs/svg.js#646]
### Precis
The `SVG()` initializer only accepts an id or an existing html element to serve as a container.

### Problem
1. This approach is far too limited in current day situations.
2. Adopting existing or raw SVG elements is not obvious; like in the jQuery API for example.

### Proposal
- [x] Switch to `querySelector ` for initialization; e.g. `SVG('body')`, `SVG('#drawing')` or `SVG('.canvas')`
- [x] Create new SVG elements; e.g. `SVG('<rect>').addTo(group)` or `SVG('<rect>').putIn(group)`
- [x] Adopt existing SVG elements created using vanilla JS
- [x] Make `addTo()` and `putIn()` accept selectors using `querySelector `; e.g. `SVG('<svg><rect></svg>').putIn('body')`

**Comment by Fuzzyma** [comment]
we broke so much stuff in 3.0 that people have to review their code anyway. So I find `#drawing` ok - especially when we want to support `<svg>...</svg>`, too.

**Comment by wout** [comment]
@Fuzzyma while creating an issue from the project I wasn't ready with the content ;)

I too agree we should use selectors and no longer the `id` value alone.

**Comment by Fuzzyma** [comment]
This is in the 3.0 branch now. Thats what is possible now:

```js
var draw = SVG().addTo('body').size('100%', '100%')
draw.add('<rect width="150" height="150"></rect>')
draw.add(document.createElementNS(ns, 'rect'))
SVG(node).addTo(draw)
SVG('<circle></circle>').addTo(draw)
```
