### ISSUE TITLE
No animation when calling path.animate().plot()

### ISSUE THREAD

**Issue by SimoneMSR** [svgdotjs/svg.js#647]
I would like to animate a path moving his nodes, like this

var path = SVG.get("#use3850");
		var a = path.array();
		a.value[0][1]=5;
		path.animate(3000, '>', 1000).plot(a.toString());

the plotting works, but no animation happens.

Is it possible to do something like this? Where am I wrong?

**Comment by wxs77577** [comment]
@SimoneMSR Same problem, how did you resolve?

**Comment by Fuzzyma** [comment]
Array values are passes by reference. So by changing the array values directly you change the shape and there is nothing to animate animore. Create a clone of the array and use it instead

**Comment by wxs77577** [comment]
@Fuzzyma  Thanks a lot, Your code It's not work for me but what you said gives me inspiration. I use `let points = shape.array().value.slice(0)` instead and it works fine.
