### ISSUE TITLE
Remove component.json

### ISSUE THREAD

**Issue by dotnetCarpenter** [svgdotjs/svg.js#652]
I find updating [`component.json`](https://github.com/svgdotjs/svg.js/blob/master/component.json) a little annoying in each release (usually I remember to do it some time in a commit after the release) and just read that it's not maintained anymore and SVG.js is not in the public component registry.

https://github.com/componentjs/component/issues/639
http://component.github.io/

**Can we remove it?**

Duo is mention in the component.js readme, but as far as I can tell, Duo does not rely on having `component.json` file.

https://github.com/duojs/duo

webpack uses `package.json`.
https://webpack.js.org/guides/get-started/

**Comment by wout** [comment]
Less bureaucracy is better :)
So if we don't need it, we should remove it.
