### ISSUE TITLE
A due date for ver. 3.0.0 ?

### ISSUE THREAD

**Issue by ctzurcanu** [svgdotjs/svg.js#657]
At least some tentative.
We would love to re-program the [Oroboro Editor](https://github.com/oro8oro/oroboro) based on ver. 3 (now is using ver. 1)
And we would love to know how we will manage our time for the next months (it depends on ver.3).
:)

**Comment by Fuzzyma** [comment]
Thats really hard to say. We are all working on svg.js v3 whenever we find some time and we would like to deliver a good product which finally has no odd discrepancies. So its one step after another and its done when its done. I would say we are ready in 3 months but that is estimated on the time I have atm (and this will change soon). Furthermore we would like to update the website with visal examples and that takes time, too (you are all welcome to add fancy stuff when you have something).
For a super big timeframe we set end of the year as very last date.

**Comment by wout** [comment]
I second that. It also depends on all the features we decide to implement for 3.0. Nothing is set in stone yet. But in the upcoming weeks, I would like to create more clarity and define a list of must-haves. The breaking changes will get priority, additional features can be 3.1, 3.2, ...

**Comment by simonwidjaja** [comment]
Any news on this one? We are in a similar situation as @ctzurcanu.
BTW: Keep up the amazing work!

**Comment by dotnetCarpenter** [comment]
I would base it off 2.x and then upgrade. So far the breaking changes are in `SVG(id)`, being `SVG(css-selector)`, SVG not being global when `require()` via commonjs and `TBox` being removed. The internals are being heavily reworked but the surface should see minor, but breaking changes. Going from 2.x to 3.x should be little work.

@fuzzyma and @wout, am I missing more things? Perhaps we should create a public list, aside from our changelog, where we list the things that are going to break.

**Comment by Fuzzyma** [comment]
Transformations are relative by default, good chances that positioning functions for groups are removed (they cause confusion and wrong assumptions about groups). 
Text positioning will hopefully be reworked. 
SVG.Set gets a huge rework or it is removed (more likely a rework). 
Polyfills are removed. 

I am pretty sure I missed stuff

**Comment by dotnetCarpenter** [comment]
our github repo issues provides a pretty good list: https://github.com/svgdotjs/svg.js/milestone/2

**Comment by saivan** [comment]
We are making a fair bit of progress with 3.0.0. You can check our milestones and pr's as @dotnetCarpenter pointed out. But if you'd like to pick up any of the issues to speed up the process, we are welcoming prs :)

**Comment by saivan** [comment]
Just let us know before you get started so we don't end up writing the same code twice :P

**Comment by jfhenon** [comment]
Hello, thank you for this package and the time you spend on improving it. Do you have in mind a potential date for the 3.0.0 release

**Comment by Fuzzyma** [comment]
Not a date yet but as you can see in the commit history we are really working on it :).
So somewhere in the next months is realistic.

In the meantime you have something to play with :D
https://jsfiddle.net/Fuzzy/ucb1w8rz/2/

**Comment by saivan** [comment]
yep, we are working on it pretty much every day

**Comment by jfhenon** [comment]
Thank you for your quick responses. I had indeed a look at the activity and I will patiently be waiting playing with you jsfiddle :-)

**Comment by dotnetCarpenter** [comment]
Nice! Here is a version that also work with touch:
https://jsfiddle.net/ucb1w8rz/4/

**Comment by saivan** [comment]
Its out 😄 Try it on the master branch!
