### ISSUE TITLE
Calling .move() on text with empty string doesn't set y properly

### ISSUE THREAD

**Issue by deborahhh** [svgdotjs/svg.js#658]
It seems that when the text is empty, when I call move(a,b) it will set the x attribute to a, but it will add b to the y attribute, instead of setting the y attribute to b. If the text is not empty, it works properly (sets x=a, y=b). 

Eg. if I do
```
var text = draw.text('');
text.move(100,100);
text.move(100,100);
```

Then the text will be at x=100, y=200.

Is there some reason for this to be the intended behavior, or is this a bug?

**Comment by Fuzzyma** [comment]
When you draw text without text, the browser renders nothing. We use `bbox()` to get the dimensions of the text to position it correctly. When no text is rendered the `bbox()` is `0` and therefore the position does not work correctly. So: First add text, then position it. That might change in 3.0

**Comment by deborahhh** [comment]
Got it, thanks!
