### ISSUE TITLE
SVG not found after updating to 2.5.3 (using node)

### ISSUE THREAD

**Issue by deborahhh** [svgdotjs/svg.js#659]
I'm using node, with browserify. I had
```
require('svg.js');
var draw = SVG('canvas');
...
```
 before and it was working with 2.5.0. I just updated to 2.5.3 and it breaks, saying SVG not defined. Any hints why?

Thanks!

**Comment by RmiTtro** [comment]
That is weird, I'm using Webpack which basically do the same thing as browserify and I don't have any problems. @dotnetCarpenter, do you think it could be related to the changes you made to support strict mode? From the quick look I gave through the commits between 2.5.0 and 2.5.3, this seem to me that those are the changes that are most likely to have caused this issue.

**Comment by RmiTtro** [comment]
Wait, I think I got it! @deborahhh, if you do the following, I think it should work:

```javascript
var SVG = require('svg.js');
var draw = SVG('canvas');
```

**Comment by deborahhh** [comment]
That worked, thank you!
