### ISSUE TITLE
move() breaks path

### ISSUE THREAD

**Issue by mbalk** [svgdotjs/svg.js#665]
As learned in https://github.com/svgdotjs/svg.js/issues/654 I think we are using a compound path. :-) move() does destroy the path. We did not test any other transformations.

Problem did not exist in 2.5.0.

Example (TypeScript):
```typescript
let svgDoc = SVG();
let path = svgDoc.path(
    'm 0,0 0,3189 2209,0 0,-3189 -2209,0 z m 154,154 1901,0 0,2881 -1901,0 0,-2881 z');
path.move(0, 0);
// results in following path: "M0 0L0 3189L2209 3189L2209 0L0 0Z "
```

**Comment by Fuzzyma** [comment]
Which version are you using? I could think about a bug in 2.5.1 which was fixed in 2.5.2.

**Comment by Fuzzyma** [comment]
checkout https://github.com/svgdotjs/svg.js/releases/tag/2.6.1 which will fix your problem

**Comment by mbalk** [comment]
2.6.1 works, thank you!
