### ISSUE TITLE
Moving paths causes complex paths to break

### ISSUE THREAD

**Issue by villanus** [svgdotjs/svg.js#667]
I have a path which only displays correctly when using the fill-rule of evenodd

When i move the path around using the dmove or any other option then the fill rule no longer applies.   When opening the path in illustrator, the inner circles are filled.  `

https://jsfiddle.net/

**Comment by Fuzzyma** [comment]
Update to 2.6.1 and see if the error remains. Report back please.

**Comment by villanus** [comment]
Solved with 2.6.1   I was on 2.5.x

**Comment by villanus** [comment]
Quick side question.  I know this has been discussed but is there a way to limit the decimal places?
I have been trying to use WOUT's old code for doing this and cant seem to make it work.  

`SVG.extend(SVG.Path, {
  // Round path directives to a given amount of decimals
  compress: function(decimals) {
    decimals = eval('1e' + decimals)
 
    for (var n, i = this.array.value.length - 1; i >= 0; i--) 
      for (n = this.array.value[i].length - 1; n >= 1; n--) 
        this.array.value[i][n] = ~~(this.array.value[i][n] * decimals) / decimals
      
    return this
  }
})`

**Comment by Fuzzyma** [comment]
Loop through the path array, multiply by your accuracy, round, divide by your accuracy, plot the path array as path - done

```js
coordinate = Math.round(coordinate * 1000)/1000
```

**Comment by villanus** [comment]
Sorry to be stupid. 
I dont know if I am going about this correctly.   I am having a hard time even assigning the path array to a variable. 

All i have working is:
       myPath = SVG.get('mypath')
       myPath.dmove(200,200)

How do I get the PathArray from here so that I can follow your psuedo code?
Is there a reason that Wout's old code doesnt work anymore?

**Comment by Fuzzyma** [comment]
Every path has a patharray which is the representation of the path commands in array form.
You can create a patharray without creating a path with `new SVG.PathArray(pathdata)`. You then can loop through said array and correct the values in it.
Then you can plot it like a normal path with `rootSVG.path(pathArray)`.

In your case it seems you already have a path in your html so you would do it this way:

```js
var myPath = SVG.get('mypath')

// get array of path
var pathArray = myPath.array()

// to get the underlying data of the PathArray (which is only an object) you call `valueOf()`
var data = pathArray.valueOf()

// pathArrays are multidimensional arrays of the form [['M', 0, 0], ['L', 10, 10]]
// this loops trough the whole data array from length-1 to zero
for(var i = data.length; i--;) {
  // this loops through all coordinates but will skip index 0 because its the command (note the --i instead of i--)
  for(var j = data[i].length; --i;) {
    data[i][j] = Math.round(data[i][j]*1000)/1000
  }
}

// plot thew new data
myPath.plot(data)

// tadaaa
```

Code not tested

**Comment by villanus** [comment]
THANKS!!!
