### ISSUE TITLE
Is rbox() off by 20 pixels on the y axis or am I doing something wrong?

### ISSUE THREAD

**Issue by AlessandroDM** [svgdotjs/svg.js#668]
Good Day,
Can you please check the below?

https://jsfiddle.net/xv3yumuL/2/

For some reasons the rectangle around the group (that follows coordinates calculated using rbox) seems off by a little on the y axis.

What am I doing wrong?

Thank you.

**Comment by Fuzzyma** [comment]
Without even looking into the code I knew what your mistake was. I really sorry that this feature is not documented in the docs. We have to do that asap. 

rbox was buggy in many cases so we fixed it. However the new implementation always gives you the box in screen coordinates (normal css px) and not in the coordinate space of your root svg.
Therefore we added an optional argument you can pass to rbox. rbox then calculates the box and transformes the box into the space of given element e.g. `el.rbox(rootSVG)`.

I fixed your fiddle: https://jsfiddle.net/xv3yumuL/3/

**Comment by AlessandroDM** [comment]
Fantastic :-)

Thank you so much.
