### ISSUE TITLE
Import method svg() should adopt elements

### ISSUE THREAD

**Issue by wiiiteek** [svgdotjs/svg.js#669]
Hello,

I think that `draw.svg('...');` should automatically adopt imported elements.

Motivation: I am using in my project global event listener, something like this:

```typescript
this.renderer.innerDIV.addEventListener("click", (e) => {
    let s = (e.target as any).instance as svgjs.Element;
    if (!s || s.type == "svg" || s.hasClass("no-edit")) {
        return this.editor.closeEditor(); 
    }

    this.editor.openEditor(s);
}) 
```

In this case imported elements does not have `.instance` object and I can't use any library methods on it.

For now on I am using this workaround

```typescript
let a = '<g transform="rotate(45)"><rect width="100" height="50" x="20" fill="#f06"></rect><g transform="rotate(45) translate(50,50)"><rect width="30" height="30" x="0" fill="#50F"></rect></g></g>'
draw.svg(a);
draw.each(() => {}, true); // <-- this will adopt all earlier elements
```

**Comment by Fuzzyma** [comment]
Do not rely on instance. If you need an instance you are better off using `SVG.adopt()` on the node which gives you back the instance if there is one and otherwise creates one for you.
So your code would look like this:

```js
this.renderer.innerDIV.addEventListener("click", (e) => {
    let s = SVG.adopt(e.target as any) as svgjs.Element;
    if (!s || s.type == "svg" || s.hasClass("no-edit")) {
        return this.editor.closeEditor(); 
    }

    this.editor.openEditor(s);
})
```

**Comment by wiiiteek** [comment]
Hello,
Yes maybe you're right and in this given example I should not assume that given element always has svg instance. Now I see why this was made this way. Import method does not need to adopt elements because elements will be adopted automatically during any selector operation.
ok, I think issue can be closed than.
