### ISSUE TITLE
Morph between paths when dragging

### ISSUE THREAD

**Issue by giovannibedetti** [svgdotjs/svg.js#670]
I am using svg.draggable.js and trying to morph from one path to another (commands are in the same order) when dragging. Is this possible? Does the "plot" function supports a percent value as parameter?

**Comment by Fuzzyma** [comment]
sorry i am not sure what you are trying to achieve. `plot` takes a string or array and draws a path from that. This has nothin to do with morph. And dragging a path is not related to morphinga path either.
If you want to morph a path you need to `path.array().morph(otherPath.array())` the path. Then you can call `at(pos)` and you get back a `pathArray` which is mrophed to position `pos`. You can plot this new path with `rootSVG.path(pathArray)`

**Comment by giovannibedetti** [comment]
thanks for the answer, it is what I needed. 
But how can I store a path in a var without drawing it?

**Comment by Fuzzyma** [comment]
You can do it like this: `new SVG.Path().plot('path commands')`. But when you plan to morph it you can as well directly create a `SVG.PathArray`:

```js
var pathArray1 = new SVG.PahthArray('pathcommands')
var pathArray2 = new SVG.PahthArray('pathcommands')

path1.morph(path2) // you can also pass the path data here directly if you dont need pathArray2 at another place

// get path in between both paths
var pathArrayInBetween = path1.at(0.5)

// draw the path
rootSVG.path(pathArrayInBetween)
```

**Comment by giovannibedetti** [comment]
That's perfect, thank you!
