### ISSUE TITLE
Construct error when using with svg.path.js

### ISSUE THREAD

**Issue by julienmusat** [svgdotjs/svg.js#674]
I'm getting a "TypeError: this.clear(...).attr is not a function" (svg.js:4377:30)).

When debugging I can see that the clear() method of SVG.Path from svg.path.js in used instead of the one implemented in svg.js.

**Comment by Fuzzyma** [comment]
Please report this issue to the corresponding repository at https://github.com/otm/svg.path.js.
Also make sure to use the latest version of svg.js.
