### ISSUE TITLE
Forced to use setTimeout to recursively animate a chain using afterAll

### ISSUE THREAD

**Issue by SimoneMSR** [svgdotjs/svg.js#677]
I would like the rect to become a triangle, then a circle, then a rect and so on to infinite WITHOUT using setTimeout. Is it possible?
Herese the jsfiddle

https://jsfiddle.net/simone_msr/vceakozz/10/

**Comment by Fuzzyma** [comment]
Try the `afterAll()` method which lets you execute a function when all animations are finished. Just pass your function there to start the animation again

**Comment by SimoneMSR** [comment]
As you can see from the jsfiddle, my problem origins just using the afterAll function: the thing is that I am forced su re-animate the svg within a setTimeout call

**Comment by SimoneMSR** [comment]
Sorry, I linked an old version of the jsfiddle. Here what I did (with afterAll AND setTimeout)

https://jsfiddle.net/simone_msr/vceakozz/16/

**Comment by RmiTtro** [comment]
It wasn't possible before but now it is! Thank you for reporting this issue.

Also, I have have added some tips to your fiddle that show how to accomplish the same thing with less line: https://jsfiddle.net/tb0mm5w7/1/

**Comment by Fuzzyma** [comment]
@RmiTtro there was a little typo in the example. I fixed it: https://jsfiddle.net/tb0mm5w7/2/

**Comment by RmiTtro** [comment]
Thanks @Fuzzyma!
