### ISSUE TITLE
Use units other than pixels?

### ISSUE THREAD

**Issue by Yuleblinker** [svgdotjs/svg.js#678]
Is it possible to use units other than pixels in svg.js? I am considering options for an svg library to use with this project: https://github.com/Wintergatan/Midi-to-laser-cutter/tree/master and we will have a requirement to be able to output svg documents that use millimeters or inches as the units. I have had a quick look at svg.js and do not see a way to specifiy units - i'm assuming it uses pixels by default.

**Comment by Fuzzyma** [comment]
What's better than just testing? :) 
Try `el.move("20mm", "10mm")` or any other unit specified in the svg specs

**Comment by Yuleblinker** [comment]
It might be useful for others if this is mentioned somewhere in the documentation. Thanks for a great library.

**Comment by Fuzzyma** [comment]
If not specified otherwise everything works as defined in the specs so I dont see a need to note that in the documentation. There are even examples which use percent
