### ISSUE TITLE
Timing function library

### ISSUE THREAD

**Issue by SimoneMSR** [svgdotjs/svg.js#679]
I was wondering whether within the pluging (or event the svg.js library) is there a collection of standard animation timing function. I have in mind the ones from snap.svg:
- backIn/backOut
- elastic
- bounce

**Comment by Fuzzyma** [comment]
Linear sinIn, sinOut and sinInOut is in the core. For other easing functions see the svg.easing.js extension

**Comment by SimoneMSR** [comment]
Wow! I will see each of them, looking for the one I want. Would you think about making a demo of that library?

**Comment by Fuzzyma** [comment]
Not planned. PRs are welcome :)

**Comment by Fuzzyma** [comment]
Here you can find examples of most plugins: http://svgdiscovery.com/SVG.js/07-svg.js-plugins.htm
