### ISSUE TITLE
Export with animation

### ISSUE THREAD

**Issue by SimoneMSR** [svgdotjs/svg.js#683]
Is it possible to export a SVG element (created with svg.js) with its animations?

**Comment by SimoneMSR** [comment]
in alternative, is it possible to embed svg.js code within a svg file?

**Comment by Fuzzyma** [comment]
Again: please use stackoverflow or gitter for questions! 

Animations are not exported. However you can just take the Javascript which created the svg and include it on every page. 

As stated in the docs svg.js also works in svg documents

**Comment by SimoneMSR** [comment]
I am sorry for this. I have just forgot. I will use stackoverflow in the future.
By the way, thanks for your reply, it is useful.
