### ISSUE TITLE
Namespaced attribute fails on Firefox

### ISSUE THREAD

**Issue by DoKraus** [svgdotjs/svg.js#687]
Yo!

If I load an image with `image.load(imageSrc);` the href-attribute has lost his namespace on firefox (v45.9.0)

The "problem" is the line `return this.attr('href', (img.src = this.src = url), SVG.xlink)` in src/image.js.

If I replace this line with following, it seems to work:
```
var href = this.node.getAttributeNodeNS(SVG.xlink, 'href');
href.value = (img.src = this.src = url);
this.node.setAttributeNodeNS(href);
return this.node;
```

Both of them are setting the namespace.
For the sake of completeness:
```
return this.node.setAttributeNS('href', SVG.xlink, (img.src = this.src = url))
```
won't work either.

I don't understand why and so I won't create a pull request yet.
Can anyone explain why this changes work and the previous code will not?
And maybe change the code, so that it will work on firefox?
Thanks in advance!

**Comment by Fuzzyma** [comment]
There are ongoing attempts to align svg with html. xlink will be removed in the next svg version and browser sees to adapt to this already. 
This is Ofc only guessing. The important question is: is the code still working?

**Comment by DoKraus** [comment]
The image is displayed, only if the namespace is set.
If the namespace isn't set, the image is not displayed.

I used in my fork following code snippe and this do the thing...
```
try {
  var href = this.node.getAttributeNodeNS(SVG.xlink, "href");
  href.value = (img.src = this.src = url);
  this.node.setAttributeNodeNS(href);
  return this.node;
}
catch (e) {
  return this.attr('href', (img.src = this.src = url), SVG.xlink);
}
```
MY tests does not reveal any problem. Maybe some of you guys see a critical problem?

**Comment by Fuzzyma** [comment]
I see one :). You return `this.node` but it should be `this` to allow chainability.
However - this is a pity. Do you have time to file a bug to mozilla?
Can you try `src` instead of ``href`? When both is not working its most likey a regression bug and needs to be reported

**Comment by DoKraus** [comment]
Hu. I've found the problem for my specific case.
I had used a custom xml serializer, which did magic things. And this magic is not compatible with the further procedure.
So this issue can be closed.

Thanks for help!
