### ISSUE TITLE
Image via file input

### ISSUE THREAD

**Issue by aydos** [svgdotjs/svg.js#688]
How can I create an Image via file input?

**Comment by Fuzzyma** [comment]
Can you please elabroate further? Add an example so we know what your actual question is

**Comment by aydos** [comment]
Thanks for quick response...
I want user load image file via file input on web page, so can see his/her local image file.
It seems that
https://stackoverflow.com/a/4459419
is working.

**Comment by Fuzzyma** [comment]
and how is this topic related to svg.js?

**Comment by aydos** [comment]
I want show the image on svg with svg.js :)
