### ISSUE TITLE
Why does rbox not show actual visible bounds of text

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#690]
In the case of using text the rbox shows what I believe is the bounding box of all possible glyphs (including the highest and lowest glyphs) instead of the actual visible text which is what I need. 
http://jsfiddle.net/cyberwombat/Lmu56awz/323/

Can you confirm that this is correct? It's **not** actually measuring the visible text? Do you have an easy workaround? I am currently using Raphael/Opentype and have to convert to path to get an actual measurement but unfortunately that is messy and CPU intensive.

**Comment by Fuzzyma** [comment]
Yes that's exactly what is the case. It's not the highest letter but the letter + accent + line gap and whatsoever. Unfortunately there is no easy workaround for this. We already came across this problem and opentype as well as fontkit (used in svgdom) are the only solutions (dunno what you need Raphael for, though).

**Comment by cyberwombat** [comment]
Shoot. Yes I use OpenType behind the scenes to calculate the real bounding box (doesn't always come out right though depending on font family) and then use that to modify my raphael text. But the conversion to and fro OpenType and Raphael boxes is semi nightmarish (they don't use the same origins for one)  so transforms are painful. Was hoping for a cleaner solutions.Thanks.
