### ISSUE TITLE
How is position of text determined

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#691]
If I place a text element it seems to be placed down quite a bit and I cannot figure out a) why it does so and b) how to get the measurement I need to move it to the very top.

See this fiddle - http://jsfiddle.net/cyberwombat/Lmu56awz/339/ - why is the text ~40px down?

````
var draw = SVG('drawing').size(700, 700)
var text = draw.text('Hello world')

text.font({
    family: 'Helvetica',
    size: 104
  })
// draw bbox
var b = text.rbox(draw)
draw.rect(b.width, b.height).move(b.x, b.y).fill('none').stroke({
  width: 1
})
````

![screen shot 2017-06-12 at 11 08 52 am](https://user-images.githubusercontent.com/777498/27048220-d4492606-4f5f-11e7-82be-4db747ec8a1f.png)

Thanks

**Comment by Fuzzyma** [comment]
Because you changed the fontsize without changing the position.
Text in svg kinda sucks because it is placed by its baseline. svg.js _tries_ to position it by its upper left edge (like any other shape). We use bbox() to calculate the actual position and move the text so that it will be at the right place. However, when you change fontsize, it does not fit anymore. So to recalculate the position a simple `move(0,0)` after font would be sufficient

**Comment by cyberwombat** [comment]
Diving into it I see now that browsers position text quite differently. Safari correctly (or within <1px) positions text on the Y axis but Chrome ads about 7-10% of the font size which results in dramatic shifts in larger fonts.

Attached are two images - the right text is CSS places font and the left is SVG.js using `text().move(0,0)`  

![screen shot 2017-07-11 at 2 17 18 pm](https://user-images.githubusercontent.com/777498/28091348-48a723cc-6644-11e7-8c66-d5e19a7cee0c.png)
![screen shot 2017-07-11 at 2 17 37 pm](https://user-images.githubusercontent.com/777498/28091346-478fe474-6644-11e7-9b59-dc0cd4f59e24.png)

You can see that the SVG y attribute for the text element is different. 

Do you know why this is? I understand that browsers are iffy but is there a fix I can use?

**Comment by Fuzzyma** [comment]
When left is svg.js I don't see a problem. Both browsers render the text at the same position

**Comment by Fuzzyma** [comment]
Check the bbox() method in both browsers. If they return different results for text height there is nothing we can do about it.

**Comment by cyberwombat** [comment]
Not too different for the initial text (before it is sized. (blue one is safari)
![screen shot 2017-07-12 at 7 57 08 am](https://user-images.githubusercontent.com/777498/28124251-fd14e568-66d7-11e7-81ec-42d245e63422.png)
![screen shot 2017-07-12 at 7 56 58 am](https://user-images.githubusercontent.com/777498/28124252-fd19071a-66d7-11e7-95be-5eb7c6a92587.png)

**Comment by cyberwombat** [comment]
What I am seeing when I compare the svg text and the regular html/css text in chrome is that the bboxes are the same (besides the x shift). So the svg bbox after transform is correct but the rendered svg is not taking that into account correctly it seems else I assume I would get the same positioning as the css text?

**Comment by Fuzzyma** [comment]
Yes bbox is used to position the text at its upper left edge. And when browser vendors cannot decide which implementation they wanna take I cant do anything about it

**Comment by cyberwombat** [comment]
I understand. So what I am doing now is this. I have a premade SVG using the same font and size. I use plain JS to get the bbox which tells me how offset Y is and I then adjust my svg object accordingly. Its awkward for sure but does imply that the data is there. Not sure what the better approach is yet but sharing that in case it tickles your brain :)

**Comment by Fuzzyma** [comment]
The formulat for positioning is like this: 

```
newY + oldY - bbox().y
```

This way it moves the text to a position where bbox().y is 0 (which should be then the upper edge of the text)

**Comment by Fuzzyma** [comment]
This can be tamed in 3.0 where text can be moved by baseline, too

**Comment by Adam-Langley** [comment]
@Fuzzyma - you mention positioning by baseline in v3.0 - can you provide a reference to how to utilise this?
Thanks

**Comment by Fuzzyma** [comment]
Just yet y directly with attr:

```js
text.attr('y', 50)
```
