### ISSUE TITLE
import a whole SVG in node with svgdom

### ISSUE THREAD

**Issue by schmi85** [svgdotjs/svg.js#692]
Right now, I have followed the given documentation to use svg.js with node and right now my code looks like:
```
const window   = require('svgdom'),
      SVG      = require('svg.js')(window),
      document = window.document,
      draw     = SVG(document.documentElement);

const data = <content of an svg file>

draw.svg(data);

console.log(draw.svg());

--- result (code shortened for sake of simplicity) ---

<svg xmlns:svgjs="http://svgjs.com/svgjs">
    <defs id="SvgjsDefs1001"></defs>
    <svg id="SvgjsSvg1002" width="2" height="0" style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0">
        <polyline id="SvgjsPolyline1003" points="0,0"></polyline>
        <path id="SvgjsPath1004" d="M0 0 "></path>
    </svg>
    <svg id="imported" viewBox="0 0 210 297">
        <defs id="defs2"></defs>
        <g id="layer1">
            <!-- much more content here -->
        </g>
    </svg>
</svg>

```

So the code above creates three svg elements, whereby one of them (`#imported`) is the one I am actually importing. Basically that is not invalid, but I would really prefer a way in which only the imported svg exists.

Is that possible? Thanks in advance!

**Comment by Fuzzyma** [comment]
Hey @schmi85. No that is not possible at the moment but its a feature we want to include (include in svg.js and not in svgdom because tahts an svg.js thing). However, even if this is done you wont get away under 2 svgs because one of them is actually a parser object which is used by svg.js internally to calculate things like path bboxes.

**Comment by schmi85** [comment]
Hey @Fuzzyma, thanks for the quick answer! But could I »exchange« the document element of the svgdom with the svg I would like to import?

**Comment by Fuzzyma** [comment]
Well there is nothing like readonly in svgdom so you can change everything. Please take a look into the dom.js file where the relation between the root node and the document is set. Make sure that a valid relation still exist and it should work. 
However - as I said above svg.js needs the parser to work well. Make also sure to include it in your svg
