### ISSUE TITLE
can't get the width and height of svg.nested

### ISSUE THREAD

**Issue by kadaliao** [svgdotjs/svg.js#693]
Hi,

nested.width() and nested.height() are not working correctly. No matter what content you put in a nested container, it will always return 0, 0 for it's width and height. And I think maybe because of it, nested.center() dose not work too.

```
var draw = SVG('canvas');
draw.size(400, 400);

var nested = draw.nested()
nested.rect(100, 100, 100, 100).fill('red')
nested.text('simple text here').move(100, 50)

console.log('x, y = ' + nested.x() + ', ' + nested.y())
console.log('width, height = ' + nested.width() + ', ' + nested.height())

nested.center(200, 200)

```

The output is:
"x, y = 0, 0"
"width, height = 0, 0"

Which is not expected.

my code pen URL: https://codepen.io/kadaliao/pen/YQNGxo?editors=1011

**Comment by Fuzzyma** [comment]
You never set a size to the nested element. Ofc it has no width or height. This is totally expected.
If you want computed height/width use `bbox()` instead

**Comment by kadaliao** [comment]
I put them in nested so I can easily move them in the center of the canvas.

I thought it will automatically return the calculated width and height.

@Fuzzyma Thanks.

**Comment by Fuzzyma** [comment]
We dont want to do this sort of magic. Nested elements can have dimensions and so we use them.
I think only in case of groups is magic involved - and that confuses a lot of people
