### ISSUE TITLE
Problem with Bounding Box (bbox)

### ISSUE THREAD

**Issue by simonwidjaja** [svgdotjs/svg.js#694]
Hi, my team is working on an authoring tool and we are considering using svg.js over SnapSVG. First prototype was promising. But now we ran into a problem with bounding boxes.

Are there any known issues? 
There seems to be an unwanted offset in the bbox.

Even on the official website (http://svgjs.com/geometry/#svg-box) you can see the problem (see screenshot)

<img width="932" alt="screen shot 2017-06-21 at 10 41 22" src="https://user-images.githubusercontent.com/1757398/27375217-c43ebd5a-566e-11e7-9496-3b05c07f9d02.png">

Any feedback appreciated

**Comment by Fuzzyma** [comment]
Please add the code to the issue

**Comment by wiiiteek** [comment]
@simonwidjaja please remember that bounding box is not affected by transform. Bbox represents box before any transforms. Try using `rbox()` instead.

**Comment by simonwidjaja** [comment]
Same with RBox

I guess it's your own code ;) (tested on Chrome (newest), Safari and Firebox on Mac)

http://jsfiddle.net/wout/2ryg8v28/?utm_source=website&utm_medium=embed&utm_campaign=2ryg8v28

<img width="887" alt="screen shot 2017-06-21 at 10 57 57" src="https://user-images.githubusercontent.com/1757398/27375890-c8d915c0-5670-11e7-9f1c-dbada8f45c52.png">

**Comment by Fuzzyma** [comment]
I still dont see any code!
Its not our code. The bbox implementation is working correct as well as the rbox implementation.
Its just the docs which are not always up to date. 

Thats why I want to see your code!

**Comment by wiiiteek** [comment]
This offset is because jsfiddle adds 5px margin to the html body. Add `body { margin: 0px; }` to CSS in fiddle and everything looks ok

**Comment by Fuzzyma** [comment]
As I alreary said: The doc is not always up to date.
In case of rbox that means:

`rbox()` has an additional parameter which is the reference frame it is calculating the box to.
It defaults to absolute screen coordinates (so when you create a div and move it to that position with `position:absolute` it will fit). 
In svgs you often want your document to be the reference.
So you do: 

```
var rect = draw.rect(100,100).move(100,100).rotate(10)
var rbox = rect.rbox(draw) // or rect.rbox(rect.doc())

// draw the box
draw.rect(rbox.width, rbox.height).move(rbox.x, rbox.y).fill('none').stroke('black')
```

**Comment by simonwidjaja** [comment]
Thanks @Fuzzyma that argument solved it.
I guess it would be helpful to update the JSFiddle used on the official website accordingly (remove margin on body or add argument to rbox() call). 

Thanks for your instant feedback!
