### ISSUE TITLE
Top-Page Index for Methods and Properties

### ISSUE THREAD

**Issue by xenoken** [svgdotjs/svg.js#695]
Wouldn't it be nice to have a top-page index of the method specified in the current page of the documentation? I know there is an index for the documentation pages, but I'd like to have an index for the methods\properties in each page.
For example:
In the "Elements" page in the documentation, I'd like to have a handy index ( with links referring to anchors in the page possibly ) at the top of the page. This way, I'll be able to skim quickly through the methods\properties and then click on a method\property link to go to the method\property details.

**Comment by Fuzzyma** [comment]
We dont have the ressources to do such a change to the documentation at the moment. However, feel free to open a PR at [svgdotjs/svgdotjs.github.io](https://github.com/svgdotjs/svgdotjs.github.io)

**Comment by xenoken** [comment]
I'll work on it right away. 
Thanks for your reply :+1:

**Comment by Fuzzyma** [comment]
If you can make it so that it wont fill up to much room that would be awesome :)
