### ISSUE TITLE
Transparent background rect instead of default black

### ISSUE THREAD

**Issue by chitgoks** [svgdotjs/svg.js#696]
drawing a stroked rectangle like this

draw.rect(100, 100).attr({ stroke: '#f06' });

results in red line on the rectangle sides but the background is black. how to set background to transparent? because i plan to add text within the rectangle area.

**Comment by Fuzzyma** [comment]
`fill('none')` will make the rectangle transparent

**Comment by chitgoks** [comment]
thank you
