### ISSUE TITLE
Can't use remove() during animation

### ISSUE THREAD

**Issue by locdirect** [svgdotjs/svg.js#699]
Removing a non-animating object is fine:
   var rect = draw.rect(100, 100).attr({ fill: '#f06' })
   rect.remove()

However: 
   var rect = draw.rect(100, 100).attr({ fill: '#f06' }).animate().move(100,100)
   rect.remove()

Gives: Uncaught TypeError: rect.remove is not a function

It would be great to be able to remove animating objects without having to wait for the animation to finish

**Comment by Fuzzyma** [comment]
Animate does **not** return the element itself. It returns an instance of fx. Albeit these two are similar, they don't share all methods. To remove the object simply save a reference before animation and use that or call `rect.animate(...).target().remove()`
