### ISSUE TITLE
Problem with moving imported text

### ISSUE THREAD

**Issue by wiiiteek** [svgdotjs/svg.js#702]
Hi,

I found something, maybe it's a bug.
When you try to move imported text then only root `text` tag is affected and `tspan` tags inside stays at previous position. To move whole text block I need to iterate through children and move them too.

My description is little mess, so better check this fiddle: 
https://jsfiddle.net/wiiiteek/3tdcdLwt/2/

**Comment by Fuzzyma** [comment]
When you import text which was not exported with svg.js, svg.js is missing the information that it should move the tspan as well. To make this work again, you need to call `newLine()` on the tspans (or you dont use `x` in the first place)

**Comment by wiiiteek** [comment]
OK, I see. But is there any way to recognize (using js methods) which text is imported and which is native svg.js ?

**Comment by Fuzzyma** [comment]
Sure, you can check if the `svgjs:data` attribute is present on the node. This attribute holds the information about newlines and leading and is exported/imported when using `svg()`.
You can also check for the `dom` property on the element which will hold the information of the above attribute already parsed for you. However - these are internal properties. Its unlikely that they change but its no public api

**Comment by wiiiteek** [comment]
Thanks for info :)
