### ISSUE TITLE
RBox show a wrong result with an imported svg

### ISSUE THREAD

**Issue by bbqaaq** [svgdotjs/svg.js#703]
Hi!

My target is to find out the bounding box for a imported SVG. However, I got a quite weird result when I get it by rbox().

Here are the simplified example for what I get.

https://jsfiddle.net/bbqaaq/e59wdwvL/

And a successful example without using any import. The result is good to go.

https://jsfiddle.net/bbqaaq/az30hsv6/

Is it a issue or just using the function wrongly?
Thanks so much!

**Comment by Fuzzyma** [comment]
The results are completely correct.
You measure the rbox once time from a group and one time from a nested svg element.
A group has no dimension on its own so the rbox is the one which holds all element. However, an svg element has a dimension. And it is shown as the big red box

**Comment by bbqaaq** [comment]
But im questioned, if i change the "var b = icon.rbox(draw);" to "var b = icon.bbox(draw);" in the fail case, the result will be showing what i need.

Why will it be different in this case?

**Comment by Fuzzyma** [comment]
I guess you have to ask the browservendors here. It could be, that nested svgs are seen as transformation somehow and so the rbox is different. Iam not really sure here. All I can say is, that the behavior seems to be consistent between all major browsers and we only wrap that functionality. Use the one which fits best for you
