### ISSUE TITLE
Setting stroke width on imported elements sets the color to black

### ISSUE THREAD

**Issue by jlherren** [svgdotjs/svg.js#704]
When I import an existing SVG and then modify the stroke width of an existing line, then its color turns black. This doesn't happen on newly created elements, or on elements that had their color set previously. It's as if it doesn't properly import the existing color property. See this self-contained example:

```
<?xml version="1.0" encoding="utf-8" ?>
<svg id="drawing" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
    <line x1="10" y1="10" x2="90" y2="90" stroke="#ff8000" stroke-width="5"></line>
    <script type="text/javascript" xlink:href="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.2/svg.min.js"></script>
    <script type="text/javascript"><![CDATA[
        var draw = SVG('drawing');
        draw.children()[0].stroke({width: 20});
        // ^ this line turns black
        draw.line(90, 10, 10, 90).stroke({color:'#ff8000'}).stroke({width: 20});
        // ^ this line stays orange
    ]]></script>
</svg>
```

It happens in all 3 major browsers.

**Comment by Fuzzyma** [comment]
I think this issue is related to a browser hack we did. And this hack only works when svgjs created the element. Please try the 3.0 branch and report back. It should not happen there.

Here is a link for that version: https://rawgit.com/svgdotjs/svg.js/3.0.0/dist/svg.js

**Comment by jlherren** [comment]
Indeed, using version 3.0.0 fixes the issue. I understand that version 3 isn't stable and released yet, right?

**Comment by Fuzzyma** [comment]
Yes that's true. It was just to verify that my guess is right. You can workaround your issue by first reading the value and setting it after that. This should work without any problems

**Comment by jlherren** [comment]
Okay thanks. If anyone else encounters this issue, this worked fine (do it once for each shape after importing):

`line.attr('stroke', line.attr('stroke'));`

Would still be nice to have it fixed some time :)

**Comment by Fuzzyma** [comment]
Most likely not in version 2 - it's a kinda breaking change

**Comment by jlherren** [comment]
I don't think people rely on this broken behavior. Unless you mean that a fix is too invasive to implement, then maybe fixing it is not worth it.

**Comment by Fuzzyma** [comment]
The hack was because some browsers rendered a stroke when color was set but stroke was set to zero. I am pretty sure, that all modern browsers dont do this anymore. However - it might break some websites. The workaround for this issue is manageable and so I think that 3.0 is ok
