### ISSUE TITLE
Safari and other browsers require xlink namespace for href for <use>

### ISSUE THREAD

**Issue by mattkelly** [svgdotjs/svg.js#711]
I was having an issue where SVGs generated using `use()` were not displaying on Safari 10.0.3 and mobile browsers (they worked on Chrome for OS X). Also, libraries like [domenic/svg2png](https://github.com/domenic/svg2png) would not work.

I fixed the issue by adding the `xlink:` namespace to `href` but I'm not sure that it's the correct way to do it: https://github.com/mattkelly/svg.js/commit/fc053a62c283ce6a2bd9143f8b365914155ba928. This makes the generated SVGs display in all browsers I've tested and work with utils like svg2png.

Note that `xlink:href` is [deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href) in SVG 2, so maybe I was just doing something else wrong - happy to investigate. Example code is here: [mattkelly/cats-as-a-service](https://github.com/mattkelly/cats-as-a-service) (excuse my terrible js).

**Comment by Fuzzyma** [comment]
mh thats odd. When you look into the source you can see this: 

```js
return this.attr('href', (file || '') + '#' + element, SVG.xlink)
```

So we add the `href` with the xlink namespace. So the question is: Why is the namespace not added?

**Comment by mattkelly** [comment]
That's one of the reasons I figured it's not the correct way to fix it :). FWIW I'm running this in node v8.1.2.

**Comment by Fuzzyma** [comment]
Ah, so you are using svgdom?

**Comment by mattkelly** [comment]
Yes, I'm using svgdom. You can see how I'm initializing everything [here](https://github.com/mattkelly/cats-as-a-service/blob/master/server.js).

**Comment by Fuzzyma** [comment]
So your problem is, that svgdom does not add the xlink correctly. The browser does not do anything. Ok - good to know. I will take a look

**Comment by mattkelly** [comment]
@Fuzzyma were you ever able to take a look at this?

**Comment by Fuzzyma** [comment]
Sorry I am really short on time. I dont know when I can continue working on this. However I will review PRs everytime!

**Comment by Fuzzyma** [comment]
Opened an issue for this on svgdom so i will close this one
