### ISSUE TITLE
how to fill a rect with a pattern from new SVG or new path?

### ISSUE THREAD

**Issue by mspanish** [svgdotjs/svg.js#715]
If I have a path string, or an external SVG with a compound path - and I want to use this as a pattern inside of a rect or circle - do you know how would I do this in 3.0?

I see the example of how to draw a new pattern - but how about using a path or SVG as the pattern?

**Comment by Fuzzyma** [comment]
To use something as pattern you have to wrap it in a `<pattern>` element. Mostly this element stays in the defs because its just there for reference. To use a path as a pattern you might want to add it to a pattern element. Same goes for a whole svg (which you need to import or load at the dom somewhere).

In the docs is stated how you can create a pattern and add your own stuff to it:

```
var pattern = draw.pattern(20, 20, function(add) {
  add.path(yourPath)
  add.svg(import)
  // ...
})
```

Hope it helps!

**Comment by mspanish** [comment]
Thanks very much @Fuzzyma  - I did see the docs but was not doing something quite right - I will try again!

**Comment by mspanish** [comment]
That was perfect - thanks again. Now I have another problem I am trying to wrap my brain around! I have over 33,000 SVG images in my system, and they are not all the same size. So I use viewbox to make it look like they are the same size even when they aren't! For applying bg patterns to them, this is now a bit of a problem - I am thinking of various ways I can try to load them into the "sets designer" so I can apply background patterns uniformly. Do you by chance see an easy way I am missing?

Here is a screenshot of the BG pattern applied to the different sized images.

![bgs](https://user-images.githubusercontent.com/206150/28182474-c37cb3e4-67b8-11e7-89fb-b032123c5cc8.png)

**Comment by mspanish** [comment]
making sure the thumbs all have a uniform size has been a problem in general - as you can see the in the screenshot as some of the things are too big. I got icons and artwork from many sources and some are not coded very well.

**Comment by Fuzzyma** [comment]
What about using percentage values on the pattern size? Could this work?

**Comment by mspanish** [comment]
maybe - I got a little closer to what I need by adding this:

`var id = $(this).attr('id')
var targetElement = SVG.get(id)
var w = targetElement.bbox().w;
var h = targetElement.bbox().h;
var rect = targetElement.rect(w,h)

var svg = SVG('s');

var pW = w/10;
var pH = h/10;

if (pW>pH) {
  pH = pW
}
if (pH>pW) {
  pW = pH
}

var pattern = svg.pattern(pW,pH, function(add) {
  add.rect(pW,pH).fill('#f06')
  add.rect(pW/2,pH/2)
  add.rect(pW/2,pH/2).move(pW/2,pH/2)
})`

![bgs2](https://user-images.githubusercontent.com/206150/28184451-ef903382-67bf-11e7-8405-dbd312bf62bd.png)

**Comment by mspanish** [comment]
actually switching to match the smaller size produces a slightly more uniform result

    if (pW<pH) {
          pH = pW
        }
      if (pH<pW) {
          pW = pH
      }

**Comment by mspanish** [comment]
maybe what I really need is to get better control over the sizing of these thumbs :)

**Comment by mspanish** [comment]
Using viewbox seems to work better than bbox - I also need to adjust the x, y of the rect to the viewbox x,y

     var targetElement = SVG.get(id)
      var vb = targetElement.viewbox();
      console.log('vb '+vb)
      vb = vb.toString().split(' ')
      var x = vb[0]
      var y = vb[1]
      var w = vb[2]// targetElement.bbox().w;
      var h = vb[3]//targetElement.bbox().h;
      var rect = targetElement.rect(w,h)
   // rect.dx(-70).dy(-10)

        var svg = SVG('s');

        var pW = w/10;
        var pH = h/10;
        if (pW<pH) {
          pH = pW
        }
        if (pH<pW) {
          pW = pH
        }
        
      var pattern = svg.pattern(pW,pH, function(add) {
        //add.path(path1).opacity(.3).fill('#999999')  
          add.rect(pW,pH).fill('#f06')
          add.rect(pW/2,pH/2)
          add.rect(pW/2,pH/2).move(pW/2,pH/2)
        })

    rect.back();
    rect.x(x);
    rect.y(y)
    rect.fill(pattern)

![bgs4](https://user-images.githubusercontent.com/206150/28186374-672cc642-67c7-11e7-83d3-52f42b0d5255.png)

**Comment by mspanish** [comment]
So it seems like to get these looking uniform maybe I'd have to create a parent container SVG for each one, that is the same for each one, and has the rect w/ the background - then maybe use a group with a viewbox on it to attach the interior elements?  I think I can't have any nested SVGs or it gives me a lot of trouble exporting to PNG.

I tried adding a viewbox to a group today and had no luck - is that still available in 3.0?

**Comment by Fuzzyma** [comment]
Viewbox is only available on svgs. Groups don't have that. However you coud use a transformation instead which should be the same. But I am not sure if this is what you want

**Comment by mspanish** [comment]
oh i thought groups had all methods of SVG.

Transformation might be ok - let me try that a bit, thank you for the suggestion.

**Comment by Fuzzyma** [comment]
Groups are just - well - groups. Like you would group multiple shapes in Photoshop. The only thing groups can do is transformation

**Comment by mspanish** [comment]
any idea how I can mimic a viewbox with transforrmation? 

I drew all the BGs to their own SVGs, now I thought I'd re-add the other SVGs as groups inside the BG, but the sizing will be all over the map w/out the ability to use something like viewbox.

**Comment by Fuzzyma** [comment]
Viewbox is just scale and translation. You can do the same with a transformation

**Comment by mspanish** [comment]
ok Fuzzy, that's what I thought! Will rework now.

**Comment by mspanish** [comment]
what about width and height - not sure how to convert the width/height in viewbox to a transformation

**Comment by Fuzzyma** [comment]
Width and height of the viewbox is the scale. Svgwith/viewboxwith = scale

Am 14.07.2017 22:54 schrieb "Stacey Reiman" <notifications@github.com>:

**Comment by mspanish** [comment]
thanks a lot, sorry to keep pestering you!

**Comment by mspanish** [comment]
@Fuzzyma you've been so helpful, I wanted to let you know I'm nearly there! Still some padding to add inside each thumb so they look better - but it looks like making the rect for the pattern size of 100% 100%, then just cloning and moving the entire SVG as a nested SVG inside the BG - works perfectly. The output in Illustrator is exactly what I'd want too, it looks just like what the user has created on screen.

Thanks for the help on this - helped drive me to a better solution :)

![bgs6](https://user-images.githubusercontent.com/206150/28233164-5d907af4-68a1-11e7-9684-0ab146f636ef.PNG)

![illstrator](https://user-images.githubusercontent.com/206150/28233170-6be2733c-68a1-11e7-9985-90f8f4bb2f54.png)

**Comment by Fuzzyma** [comment]
No problem. Good to knot hat people use the full power of svg.js ^^

**Comment by mspanish** [comment]
Yes svg.js is pure awesomeness 👍  I'll give you all a shout when I'm finally live! Working on a cool pattern maker now..

**Comment by mspanish** [comment]
Thought you might like to see the result of integrating the SVG BG generator w/ the SVG.js thumbs I was working with before - it's really quite awesome! I finally got the viewbox scaling working too - although I'll say that getting the x,y values for new scaling or adding some padding did take some work!  Thanks again for your help.
![bgs7](https://user-images.githubusercontent.com/206150/28345173-f015cd4e-6bd4-11e7-876b-6114332c2c27.png)

**Comment by Fuzzyma** [comment]
At the end the result is all what counts, right? :) 
Looks Really good what you did there!

**Comment by mspanish** [comment]
yeah thanks! Wait till you see the actual app  - working hard, wanted it live already but my new deadline is Aug 1, agghh. Thanks for your friendly advice - I also rigged up a precision hack - had trouble applying rounding in SVG.Numbers, but i loop through the seg array before pushing it - and that was a good place to check for numbers and round using 
` val = parseFloat(val.toFixed(2))`

Feels like a hack but it's better than hacking it front end.
