### ISSUE TITLE
do we need the parser?

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#716]
I think there is nothing which confused the users of the libraray more than the parser we create for parsing paths and polygons. It also produces a few edge cases which were imo fixed quite a bit the hacky way.

I searched through the code and found, that the parser is only used for 5 lines from which 2 of them dont require the parser to be in the dom.

- calculate bbox of pointarrays
- calculate bbox of patharrays
- bbox of elements which are not in the dom or hidden
- create SVGPoint
- create SVGMatrix

The first two need/create something in the dom. So the question is: Can we solve this in another way?
Calculating the bounding box on our own is a quite heavy task for paths (while for polygon its trivial and could be used).

The clone could be also appended to the normal svg and deleted after.

So the problem to solve are paths bboxes. It has to be noted that the bbox of patharray is only used in move and size commands. Can we try to create a path on the fly to get the bbox which we delete after? Are this extra dom operations to slow?

Getting rid of the parser would solve quite a few problems. So it would be kinda worth.
I will now go and make some tests.

All your opinions are appreciated!

@dotnetCarpenter @RmiTtro

**Comment by Fuzzyma** [comment]
Oh well generating elements on the fly is no option:

```
Generate 1000 pathArrays bbox
using SVG.js v3.0.0 completed in 17ms
using SVG.js v3.0.0 more data completed in 19ms
using SVG.js v3.0.0 complicated data completed in 4ms
using SVG.js v3.0.0 without parser completed in 222ms
using SVG.js v3.0.0 more data without parser completed in 358ms
using SVG.js v3.0.0 complicated data without parser completed in 338ms
```

**Comment by Fuzzyma** [comment]
On the other hand: Calculating bbox of a point array is even faster when done by hand:

```
Generate 10000 pathArrays bbox
using SVG.js v3.0.0 completed in 13ms
using SVG.js v3.0.0 without parser completed in 6ms
```

**Comment by dotnetCarpenter** [comment]
I'm in favor of ditching the parser if possible. But it all depends on performance and complexity.

Maybe we can use [Melkman's Algorithm](https://maxgoldste.in/melkman/) to calculate the bbox of a path to speed things up? Wait, are you calculating a pointarray or a patharray in your example?

>Generate 10000 pathArrays bbox
using SVG.js v3.0.0 completed in 13ms
using SVG.js v3.0.0 without parser completed in 6ms

**Comment by Fuzzyma** [comment]
Sorry the description is wrong. It's a point array. Calculating the bbox if a path is way more complex

**Comment by dotnetCarpenter** [comment]
Here is an interesting discussion and solution to finding the bounding box or convex hull: https://stackoverflow.com/questions/44642712/minimum-bounding-box-or-convex-hull-for-any-shape-quadrilateral

As inspiration together with the previous link to Melkman's algorithm, to implement an efficient algorithm. We could even speed things up more by using web workers which can not use the parser anyway since there is no DOM access.

**Comment by Fuzzyma** [comment]
Melkmans seems to be a nice algorythm! However - thats only for polygons (and my implementation for polygons is already quite easy and fast). 
I dont think we should implement something the browser can already do faster (which is pretty surely the case for paths bboxesd). We only need to discuss how we handle the path in the dom which we need to calculate the bbox. Chrome allows to get bbox of elements in the defs (which woud be a nice solution) but this doesnt work in FF

**Comment by Fuzzyma** [comment]
I tried and failed. SVG.PathArray is never bound to any instance. It can be used completely decoupled from an instance and therefore it cant just create a path in an SVG.Doc. It needs the static reference to the parser.
Therefore the parser has to stay!

What we can do is: use a libraray to calculate the bbox of a path. But thats a bunch of code only for this calculation so we might add it as additionally. I will close this for now.
