### ISSUE TITLE
radial gradients in 3.0

### ISSUE THREAD

**Issue by mspanish** [svgdotjs/svg.js#717]
Hello guys have there been any changes to the way you make a radial gradient in 3.0? I saw there were some changes, but don't know if it affected the syntax to create one.  I'm just trying to apply a radial gradient to a rect - do I need to add more than just this?

```
  var gradient = element.gradient('radial', function(stop) {
    stop.at(0, color1)
    stop.at(1, color2)
  })
```

**Comment by mspanish** [comment]
sorry I had the wrong number the other ones were just an experiment!

**Comment by Fuzzyma** [comment]
The at-method is called stop now. That's the only change until now
