### ISSUE TITLE
I can save works but I can't load saved works.

### ISSUE THREAD

**Issue by Zapwasd** [svgdotjs/svg.js#719]
With the method draw.svg() I can save works.
var mySavedWork = draw.svg();
The saved work contains the whole svg including <svg></svg> tags.
Which method should i use to load a saved work?
The method draw.svg(mySavedWork) duplicates <svg><defs></defs></svg> tags.
Is there an easy way to load a saved work?

Thanks in advance.

**Comment by Fuzzyma** [comment]
What do you mean with "duplicates tags"? The method you are using is indeed the one to import am svg. Alternatively you can include the svg in your document and adopt it with svg.js

**Comment by Zapwasd** [comment]
This is what I do.

1) Create a new instance of SVG:
	draw = draw.svg("canvas");	// create a new instance

2) Save the instance of SVG:
	mySvgWork = draw.svg();		// save the instance

	Result:
	<svg xmlns="http://www.w3.org/2000/svg" id="SvgjsSvg1006" viewBox="0 0 2048 1024" width="2048" height="1024" xmlns="http://www.w3.org/2000/svg" version="1.1"><defs id="SvgjsDefs1007" /></svg>

	It works fine.

3) Load the saved instance of SVG:
	if(draw) draw.remove(); 	// remove the old instance
	draw = draw.svg("canvas");	// create a new instance

	draw.svg(mySvgWork);		// load the previous saved instance

	Result:
	It works fine.

4) Save again the instance of SVG:
	mySvgWork = draw.svg();		// save again the instance

	Result:
	<svg xmlns="http://www.w3.org/2000/svg" id="SvgjsSvg1006" viewBox="0 0 2048 1024" width="2048" height="1024" xmlns="http://www.w3.org/2000/svg" version="1.1"><defs id="SvgjsDefs1007" /><svg id="SvgjsSvg1006" viewBox="0 0 2048 1024" width="2048" height="1024" xmlns="http://www.w3.org/2000/svg" version="1.1"><defs id="SvgjsDefs1007" /></svg></svg>

	WRONG!

	As you can see, now there are two <svg></svg> tags.
	If I create also a rectangle in the step 1), in the step 4) I obtain also a duplication for <defs></defs> tags.
	This happens again every time I save the instance.

Am I doing someting wrong?

When you say
"Alternatively you can include the svg in your document and adopt it with svg.js"
How can I do it?

Thank you so much for your patience and for SVG.js

**Comment by Fuzzyma** [comment]
This is expected behavior. When creating a new instance you create an empty svg document (`<svg></svg>). When you import something into that document it shows up in the document tree. You exported `<svg>...</svg>` and then you import that into that empty document. So you end up with 2 svgs.

You can insert the svg string you eported into the dom using `innerHTML` or something and pick this instance with `SVG.get(id)` after. That why you stay with one `<svg>`.

Btw this behavior will most likely changed in 3.0 so it fits more your usecase

**Comment by Zapwasd** [comment]
Thank you Fuzzyma.
I'll try this way.
I'm happy to know there will be a 3.0 version.
