### ISSUE TITLE
Get the ID of a shape dinamically created.

### ISSUE THREAD

**Issue by Zapwasd** [svgdotjs/svg.js#721]
I'd like to get the id of a shape with mouse click. I don't want to attach the event listener direcltly on the shape. I've added an event listner to the svg instance:

```js
draw.on('click', function (e) {
    var targ;
    if (!e) var e = window.event;
    if (e.target) targ = e.target;
    else if (e.srcElement) targ = e.srcElement;
    if (targ.nodeType == 3) // defeat Safari bug
        targ = targ.parentNode;
});
```

If I click on the shape or if I click outside the shape I always obtain the ID of the svg tag and never the ID of the shape.

How can I get the ID of the clicked shape?

Thanks in advance.

**Comment by Fuzzyma** [comment]
I cant see where you finally access the id of the target. However your solution should work well when you add `console.log(targ.id)`

**Comment by Zapwasd** [comment]
I access the ID with targ.id and it alway return the ID of the svg tag and never the ID of the shape where I clicked on. Very strange behavior.

**Comment by Fuzzyma** [comment]
In that case your target is always the svg element. Dont know whats wrong there. But this is issue is not related to svg.js. Try to ask stackoverflow

**Comment by Zapwasd** [comment]
Yes, the target is always the svg element also if I click on a shape.
Thank you any way Fuzzyma. I'll try on stackoverflow.
