### ISSUE TITLE
rotate an already rotated element

### ISSUE THREAD

**Issue by kievking** [svgdotjs/svg.js#722]
Hi
How can I correctly rotate an already rotated element around center which is outside of the object? Thanks

**Comment by Fuzzyma** [comment]
This is an issue forum. Questions are best asked on stackoverflow or in our gitter chat!

```js
el.transform({rotation:12, cx: 50, cy: 90}, true) // true is relative flag
```

**Comment by kievking** [comment]
el.transform({rotation:12, cx: 50, cy: 90}, true) // true is relative flag 
doesn't work lol, I guess it is considered an issue now

**Comment by kievking** [comment]
but does it have anything to do with rotating an already rotated coordinate?

**Comment by Fuzzyma** [comment]
please consider reading tutorials about how transformation works. Its a rather complicated thing and wrapping your head around it needs some time.

> doesn't work lol

is not that great of an error description. Set up a fiddle on http://jsfiddle.net and show whats not working
