### ISSUE TITLE
How to import and use svg file in svg.js?

### ISSUE THREAD

**Issue by ridwan85** [svgdotjs/svg.js#724]
How to import and manipulate and svg file ? So far i am only able to create and svg from svg.js. What if i want to import svg file and use it? And be able to get the path etc... kinda like in raphael.js
[http://readysetraphael.com/](http://readysetraphael.com/)

**Comment by Fuzzyma** [comment]
Svg.js has no build in way to load files. You can do so with Ajax or any Ajax library out there (jquery is able to do that, too). When you have the content of the file you can adopt any node you want and insert it into your svg document. 

You can also import the whole svg with `svg()` or insert the whole svg into the Dom and use it there

**Comment by rolmkolm** [comment]
I've struggled like hell to achieve this. And I finally was able to fix the issue using XMLHttpRequest:
1) First you have to retrieve your SVG file.

2) Then you have to make sure your file is accessible if it's stored on another domain (CORS policy).
If it's not, you can use a Proxy CORS. The one that worked for me is https://cors-anywhere.herokuapp.com/ (apparently http://crossorigin.me/ doesn't work anymore).

3) Use svg() to load the content of your file INSIDE of your XMLHttp Request Listener (if not inside, it won't work).
Make sure to add your SVG file content as a parameter in svg(): svg( mySVGcontent ).

4) Add it to a node.

I wrote a Codepen for that: https://codepen.io/rolm-kolm/pen/zYwqaJN

Note: on Codepen, also make sure to load SVG.JS library (https://cdn.jsdelivr.net/npm/@svgdotjs/svg.js@3.0/dist/svg.min.js) through Settings > JS.
