### ISSUE TITLE
Animating from zero-width is not working

### ISSUE THREAD

**Issue by m-hagberg** [svgdotjs/svg.js#725]
**Setting width (or height) to 0 - does not work**
```javascript
const originalWidth = element.width();

console.log(originalWidth);   // 128

element
    .width(0)
    .animate(400)
    .width(originalWidth);

console.log(element.width()); // 0
console.log(originalWidth);   // 128
```

**Setting width (or height) to 1 - works as expected**
```javascript
const originalWidth = element.width();

console.log(originalWidth);   // 128

element
    .width(1)
    .animate(400)
    .width(originalWidth);

console.log(element.width()); // 128
console.log(originalWidth);   // 128
```

**Comment by ar7casper** [comment]
I'm having similar issues with width & height. 
`const rect = draw.rect(200,200).fill('red').animate().width(100)`

Results in "rect.animate(...).width is not a function.

**Comment by ar7casper** [comment]
@m-hagberg I found a solution - 

Just use `.attr({width: }) instead`, like so -

`const rect = draw.rect(200,200).fill('red').animate().attr({width:400});`

Works as expected

**Comment by m-hagberg** [comment]
@ar7casper Thanks! In your case, I think you could solve it by doing

```javascript
const rect = draw.rect(200,200).fill('red');

rect.animate().width(100);
```

**Comment by ar7casper** [comment]
Thanks, but I'm already way past this issue :)

**Comment by saivan** [comment]
We updated the fx module in 3.0.0, according to #776, so this isn't relevant anymore
