### ISSUE TITLE
Question about .point() and origin

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#730]
I use `point()` to get the untransformed coordinates of something in order to create drag bounds after rotation for example. However it doesn't take the actual  svg container position into consideration and use the top left of my screen. So as I scroll or somehow change the position of the svg main container I have to adjust this. I can fetch these x/y offsets using the DOM but am wondering if:

1.  is that intentional since I would assume `point()` to deal with transforms and I wasn't considering the position in my browser where the entire svg takes place to be a transform (is it?)

2. is there a build in method to get the coordinates of the main `SVG` element?

Thanks

**Comment by cyberwombat** [comment]
I changed the `getCTM` to `ctm` and it seems to work. What are the drawbacks of this approach?

**Comment by Fuzzyma** [comment]
The point function is designed to work with mouse coordinates (`screenX, screenY`). So you can just plug in a mouse coordinate and get the right coordinates in the elements space you called `point` on.
Thats why screenCTM is used. You can easily take the screenCTM of your root svg and use that matrix to transform it wheer you want.
`ctm()` should also work. It returns the matrix relative to the next viewport element.
This is mostly what you want

**Comment by cyberwombat** [comment]
Ok. I ended up using `ctm`. Thank you.
