### ISSUE TITLE
Cx and cy for radial gradients

### ISSUE THREAD

**Issue by ViggoV** [svgdotjs/svg.js#733]
Hi there, thanks for an awesome library.

I am currently playing around with radial gradients but I can't figure out how to change the cx and cy values of the gradient, which makes it mostly unusable. Am I missing something or is it currently not possible?

Thanks and sorry for the fuzzy question :)

**Comment by Fuzzyma** [comment]
Its just an attribute - go ahead and use `attr('cx', val)` for it

**Comment by ViggoV** [comment]
Oh, great! Thanks :)
