### ISSUE TITLE
Feature request - svg onload event

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#734]
It takes a bit of time for the svg element to appear on screen. I have tried adding an `attr` of onload as SVG supports this but that does not fire. It would be nice to know when it's loaded and ready (my use case is that I need to determine the bounding box of a fluid svg element from outside code for page formatting reasons so right now I insert an invisible image and use that loaded event.

**Comment by Fuzzyma** [comment]
When you can trust microsoft the onload event...
>Occurs when the browser has fully parsed the element and all of its descendants.

So it does not fire after everything is displayed but when everything is parsed - which is earlier. A bbox might not be available at that time.

You can try this:

```js
draw = SVG('drawing')

// code to draw the svg...


draw.fire('svgloaded')
```

In your outer code you can do `draw.on('svgloaded', function() { ... })`

**Comment by cyberwombat** [comment]
Nah - doesn't fire. I ended up using the image loader with a base64 1x1.

````

this.loader = this.svg.image('data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=').loaded(loader => {
  this.onReady()
})

onReady () {
  this.loader.remove()
  if (this.hooks.ready && typeof this.hooks.ready === 'function') this.hooks.ready()
 }
```
That's in my SVG class. In my calling code I register the `ready` hook.

**Comment by cyberwombat** [comment]
One note about the onload is that it never fires. I can see it in the source code and if I copy the svg from source and paste it like a regular svg then it fires so it's something about how it's all assembled.

**Comment by Fuzzyma** [comment]
The real reason why it does not fire might be that it already fired when you bind to it.
With svg.js you build your svg with code. But as soon as you create one svg-element (without any content) it fires immediatley the onload event. Everything you add to the svg document after that wont change that

**Comment by cyberwombat** [comment]
Hmm. I tried adding adding an `onload='alert(..)'` right after instantiating the svg element which is as early as I can put it. So you're saying that this is too late and the SVG element is already in the DOM which makes sense. Which brings me back to the feature request :)

**Comment by Fuzzyma** [comment]
Well svg.js just does not know when something is loaded. I think the onload event is only useful when you have a whole svg loaded at once. For svgs which are build up it doesnt make real sense

**Comment by cyberwombat** [comment]
Ok. Thanks. I will continue to use the image loaded event.
