### ISSUE TITLE
bounding boxes off by 8 px

### ISSUE THREAD

**Issue by mtnrbq** [svgdotjs/svg.js#735]
Documentation at [http://svgjs.com/geometry/#svg-rbox](url) shows the bounding box (rbox) **not** bounding the rotated block.
Running the jsfiddle referenced [http://jsfiddle.net/wout/2ryg8v28/?utm_source=website&utm_medium=embed&utm_campaign=2ryg8v28](url) shows the same issue.
I can also reproduce this outside of jsfiddle with local css, html and v2.6.3 of svg.js. using FireFox, Chrome and Edge

replacing (from the sample code)
`draw.rect(b.width, b.height).addClass('box').move(b.x, b.y)`
with
`draw.rect(b.width, b.height).addClass('box').move(b.x-8, b.y-8)`
displays the correct bounding box, but it is unclear if the offsets are constant.

**Comment by Fuzzyma** [comment]
#668 #694

Unfortunately the docs are not completely up to date here

**Comment by mtnrbq** [comment]
I took a look at the docs repo, but [https://github.com/svgdotjs/svgdotjs.github.io](url) , but it did not appear straightforward to just update. If anyone can give me a little guidance I'm more than happy to update and stop more people tripping over this

**Comment by Fuzzyma** [comment]
I think this is what you are looking for: https://github.com/svgdotjs/svgdotjs.github.io/blob/agolia/content/8-geometry/default.txt but iam not sure.
You can also take a look at http://svgjs.com/contributing/documentation/

**Comment by bumprat** [comment]
[SVG.BBox](http://svgjs.com/geometry/#svg-bbox) is a wrapper for [SVGGraphicsElement.getBBox()](https://developer.mozilla.org/en-US/docs/Web/API/SVGGraphicsElement), which calculates against the coordinate system of the **svg doc container**.
[SVG.RBox](http://svgjs.com/geometry/#svg-rbox) is a wrapper for [Element.getBoundingClientRect()](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), which calculates against the coordinate system of **html page viewport**, whose origin is the left-top point of the page's current visible area in your browser.
The 8px offset therefore can be explained considering the fact that in most browsers document body has [**a default 8px margin**](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjIx5yVsJvYAhUKwrwKHYyZBqAQFggnMAA&url=https%3a%2f%2fstackoverflow%2ecom%2fquestions%2f13127887%2fhtml-default-body-margin&usg=AOvVaw2Wmn5qZTXlM9t6iO_wpURV). 
You can resolve this by simply set the css style `body{ margin: 0 }`, if you are sure that the svg dom element will always be rendered at the origin of viewport. 
In most cases, extending the SVG.Element Class is recommended to do those extra calculation.

**Comment by Fuzzyma** [comment]
This is not entirely true. As I stated above rbox has a parameter which you can pass which resolves thus issue completely. I won't repeat me here but pls read again before you make wrong statements!

**Comment by mtnrbq** [comment]
@Fuzzyma - I did the PR for the change on the docs site and it's been merged, but it doesn't look like the new version has been published.
The JSFiddle for RBox is at http://jsfiddle.net/mtnrbq/bhunb7xp/4/   and one for BBox is at http://jsfiddle.net/mtnrbq/dneqfs9d/3/

**Comment by Fuzzyma** [comment]
@mtnrbq seems like i got no mail . Will look into it!
