### ISSUE TITLE
SVG.js powered editor and variations editor, finally live - free for SVG.js users

### ISSUE THREAD

**Issue by mspanish** [svgdotjs/svg.js#737]
Hello guys! The editor I've been working on is finally ready enough to put online at [https://kwippe.com](https://kwippe.com) -while certainly far from done :) - I made a coupon so anybody from SVG.js can upgrade to the pro user level for free - will be good for at least a few months from the day you activate it, possibly more.

The coupon code is

**prouser**

Enter it at [https://www.kwippe.com/app.html#upgrade_beta](https://www.kwippe.com/app.html#upgrade_beta)

Feedback from anybody would be awesome, remember I'm a lone dev though so don't expect an app done by the Adobe/MSFT engineering team or anything!

![kwippe](https://user-images.githubusercontent.com/206150/30462350-79ff7bda-9971-11e7-9cb6-c6de46eda4d2.PNG)

**Comment by saivan** [comment]
I'm just seeing this, and it looks impressive. The login isn't working for me though :) How is this coming along?

**Comment by mspanish** [comment]
hello thanks for taking a look. which login are you trying? Are you using the button on the main menu, or the login that is on the onboarding/welcome modal window?

**Comment by dotnetCarpenter** [comment]
@mspanish you have 2 identical login buttons. The first I tried is in the middle of the page and leads to https://www.kwippe.com/login_upgrade.html, which is an almost black page as @saivan is describing. The second is in the upper right of the page and leads to https://www.kwippe.com/login.html. the latter has a range of oAuth buttons and let me login with GitHub. That seems to work.

**Comment by dotnetCarpenter** [comment]
When I visit https://www.kwippe.com/app.html#upgrade_beta after I'm logged in, I see the blue upgrade button.

**Comment by dotnetCarpenter** [comment]
@mspanish I'm trying out on a tablet and it pretty much works. Already had fun coloring things. Going forward I don't think it's worth supporting touch editing of paths, my thumbs are too big, but it looks to me that you have focused on the coloring part.

The undo/redo functionality works really good.
The color wheel was not doing anything but I assume it doesn't support touch.

Keep up the good work and congrats!

**Comment by saivan** [comment]
Awesome, I like the premise. Looks really easy to use! Just to clarify though, is there a way to add new shapes to an existing design/ modify the current design?

I really like the glowing stroke too, gives you a nice effect. I think you'd probably be pretty interested in having other colour spaces available, especially for your application. You might be able to generate some cool pallets programmatically. But it looks really promising.

**Comment by mspanish** [comment]
hello and thanks to both of you for trying out my app! @dotnetCarpenter touch should be supported by the color wheel - what OS are you using? I can definitely switch it out - honestly every color thing I tried had some problems, so I settled on this one - but I'd be happy to find something better. I'm glad undo redo worked for you, because it definitely still has issues. The app grew - and each time I added something new, I had to recode stuff, and frankly I should have thought a few things out better beforehand - but that can be really hard some times. Adding new shapes to an existing design @saivan is a great idea - thanks for that idea - would you like to see a basic geometric type of panel where you pull stuff in there, or something more complicated?  The editor is something I've taken just baby steps with as there is a lot going on there, and it's easy to overreach and end up with all kinds of glitches.

I've been away from the app for a while, but hoping to dive back in soon. All feedback helps!

**Comment by saivan** [comment]
Awesome, a basic geometry panel seems like a good idea. Maybe you could even put the geometry into a colour layer - so each layer shares the same colour :P Just an idea!

**Comment by mspanish** [comment]
thanks! I'm thinking of redoing the app in React - it would open up a lot of possibilities and help me manage the app better - still going through docs and tutorials to see if it makes sense. I'll let you know when the app is updated!

**Comment by wout** [comment]
Looks great :)

**Comment by saivan** [comment]
You might want to check 3.0, might be some useful stuff for you there :)

**Comment by David263** [comment]
I confirm the impossibility of logging in.

Here is the login screen:

<img width="387" alt="kwippe edit login" src="https://user-images.githubusercontent.com/3837238/52150133-03324f00-263d-11e9-99ef-cad151dbe496.png">

**Comment by mspanish** [comment]
Ah sorry I haven't checked things in a while, I meant to pull all payment to make all features free until I get more features added - the login is Firebase and I've moved on from that as well, but maybe I can throw up a workaround for now.

Yeah adding the drawing stuff was not the initial focus -  the point isn't to be a full fledged SVG editor, but rather a variations editor and tweaker.  The idea is to help people generate things very quickly, and let them export the SVGs and PNGS so they can further manipulate them. But it'd be pretty easy to add basic drawing stuff - and will certainly be planned for 3.0.

**Comment by Fuzzyma** [comment]
@mspanish
