### ISSUE TITLE
Animating rotation not working

### ISSUE THREAD

**Issue by JugglerRick** [svgdotjs/svg.js#739]
I have found 2 issues when trying to animate a rotation:
1. Using animate.rotate; if an angle over 90 is used the positive angle value is flipped to a negative and the object spins an extra 360 degrees.
2. As a solution to this issue I used a matrix set to the desired angle and  use animate.transform. This works, except the object scale shrinks and grows during the animation.

I have created a this CodePen  https://codepen.io/JugglerRick/pen/bodZgg to demonstrate the issue

**Comment by Fuzzyma** [comment]
You are setting absolute transformations. This never works out quite well.
What you want is a relative transformation. Every time for 45 defgree.
You do that by calling transform directly and passing the relative flag:

```js
el.animate().transform({rotation:45}, true)
```

No need to track the angle yourself.
When you use `rotate()` directly, it tries to undo all other rotation and apply the new. This is a mathematical problem which is not always solvable and you see the result in your sample.
So just go with relative transformations

**Comment by JugglerRick** [comment]
But absolute transformations are what I want, the CodePen is just hacked up to demonstrate the issue. Which leaves the second issue; Why does the image scale down and back out while rotating?

**Comment by Fuzzyma** [comment]
Well then you should just REMOVE all transformation from the element and set it again. But what YOU want is realtive. You want to rotate the shape BY 45 degrees. These absolute transformations will be most likely removed in 3.0 since they only lead to confusion and bad code because people dont understand transformations correctly.

I dont know why your matric code scales. The codepen no longer works:

```js
      let angleMatrix = new SVG.Matrix().rotate(angle); // angleMatrix is never used
      this.torso.animate(time_, "-",0).transform(angle, true) // passing a number to transform is not allowed
```



If you want absolute transformation you just call `untransform`

**Comment by JugglerRick** [comment]
I have created a new CodePen  https://codepen.io/JugglerRick/pen/XemMrG that demonstrates the scaling issues and exactly what it is happening. The why it is happening is because the animation of matrix is applied linearly to the values of the matrix, which both a scale and rotation operation to the transform. 
After a fairly dead review of the code round this (and my linear algebra) the issue SVG.Matrix is implemented to attempt to extract transformation information given only the matrix, which is not possible unless you know what transformations where applied to create the matrix. You do not need to remove all matrix transformations, but they should not be animatable.
I am not sure if there is a non-breaking way to make this work correctly, but I will take a look at it.

**Comment by Fuzzyma** [comment]
I think this issue will be fixed when changing to the new transformation system. So I will close this for now!
