### ISSUE TITLE
Would there be any possible way to export an SVG?

### ISSUE THREAD

**Issue by shahzeb1** [svgdotjs/svg.js#741]
Earlier today I spent a good amount of time creating something I really liked using SVG.js, but I now realize that SVG.js will not be compatible with React. Is there any possible way to extract the useful SVG content which SVG.js is generating? This would be so incredibly helpful.

Thank you.

**Comment by Fuzzyma** [comment]
I guess Google would have helped you there. Exporting an svg as a string is done with the svg() method which you just call on the element you want to export
