### ISSUE TITLE
How to reset SVG js?

### ISSUE THREAD

**Issue by smanaqvi83** [svgdotjs/svg.js#742]
Hi, 
I am using SVGjs in Angular Service. Now the issue is that a service is a singleton object. And it is keeping SVG.get('side') data. I have tried using the clear and other ways but of no use. 
How can I reset all the data? How can SVG js be reset, so it can be cleared.

**Comment by Fuzzyma** [comment]
`draw.clear()`?

**Comment by smanaqvi83** [comment]
It's not working.
Perhaps any way of resetting the SVG object. So that every time I get the
new object.

**Comment by Fuzzyma** [comment]
Can you please elaborate your use case further? I am not aware about what do you mean with reset

**Comment by smanaqvi83** [comment]
I have written a service in Angular JS. What it do is it reads the SVG from
DOM and show that SVG in that same web page. But when I drag and drop the
SVG object it shows the previous instance in the SVG as well.

I have attached the video along with it.
It should have the same behaviour as it is shown on the T-Shirt, that when
I drag the object it should be dragged, not a copy of that object should be
created.
So if there is any way of resetting the SVG Object this will solve my
problem.

P.S: Please ignore the back sound.

**Comment by smanaqvi83** [comment]
@Fuzzyma  Found the issue and fixed it, SVG was being added right after the clear method. It's working like a charm now.
