### ISSUE TITLE
children does not exist on IE 10-11

### ISSUE THREAD

**Issue by cyberwombat** [svgdotjs/svg.js#743]
I am working off the 3.0 branch and it doesn't work in IE10 - digging into it it seems that `children` is not part of the SVGElement spec. 

See this SO post https://stackoverflow.com/questions/22498045/svgsvgelement-children-not-working-in-ie11

For example, in `parent.js` this code will never populate `chlldren`. 
```
, add: function(element, i) {
      element = createElement(element)

      if (i == null)
        this.node.appendChild(element.node)
      else if (element.node != this.node.children[i])
        this.node.insertBefore(element.node, this.node.children[i])

      return this
    }
```

I see you had some other issue about switching from `childNodes` to `children`. is there a reason to not use `childNodes`?

**Comment by Fuzzyma** [comment]
Child nodes forces us to filter the elements from the text nodes every time someone access an element. That dramatically reduces the performance.
Beside that the 3.0 branch does not care about not supported features which can be polyfilled easily.
So just load a children polyfill im ie and it should be fine

**Comment by cyberwombat** [comment]
Ah thanks. Took a while to find the polyfill - posting here.

      (function (constructor) {
        if (constructor &&
            constructor.prototype &&
            constructor.prototype.children == null) {
            Object.defineProperty(constructor.prototype, 'children', {
                get: function () {
                    var i = 0, node, nodes = this.childNodes, children = [];
                    //iterate all childNodes
                    while (node = nodes[i++]) {
                        //remenber those, that are Node.ELEMENT_NODE (1)
                        if (node.nodeType === 1) { children.push(node); }
                    }
                    return children;
                }
            });
        }
      //apply the fix to all HTMLElements (window.Element) and to SVG/XML (window.Node)
    })(window.Node || window.Element);
