### ISSUE TITLE
Manipulate svg without render

### ISSUE THREAD

**Issue by Lewik** [svgdotjs/svg.js#745]
How to manipulate svg without render? I have some svg template and want to modify it without render and pass to another lib for render.

**Comment by Fuzzyma** [comment]
These issues pops out every then and now. As you can read in other issues its not possible.
svg.js uses the dom to render its content. All actions are directly executed on the dom. There is no dom abstraction whatsoever. If you want to use it serverside you can try svgdom which gives you the dom abstraction svg.js needs.

**Comment by Lewik** [comment]
jQuery helps me )

**Comment by Fuzzyma** [comment]
just as a side note: jquery also uses dom functions and operates on the dom. So you will run into the same issues
