### ISSUE TITLE
DOMException when initializing.

### ISSUE THREAD

**Issue by facelesspanda** [svgdotjs/svg.js#750]
(maybe) relevant context:
running in Electron(Chrome).

I'm getting started with SVG.js and I'm meeting this exception:
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('http://www.w3.org/2000/svg') is not a valid name.
    at Function.g.create (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js:1:2541)
    at create (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js:2:17298)
    at Function.g.prepare (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js:1:3580)
    at HTMLDocument.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.min.js:1:3929)
```
I would like to emphasize on the absence of my codebase from the stack-trace.
The only svg.js related code in my files is the script tag linking for the cdn.

What's happening here? does my environment not support SVG? Or do I need to do something else to initialize SVG correctly?

**Comment by Fuzzyma** [comment]
Seems like electron does not support the svg namespace. Actually we test for svg support on svg.js but this test tries to create an svg element minimum. This seems to work because the later code is executed.
Not using the minified version here would help to get useful line numbers

**Comment by facelesspanda** [comment]
After fiddling in my JS console, in Electron `document.createElement('svg')` works out of the box, so I don't really know how to go from there.

The exception with actual line numbers:
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('http://www.w3.org/2000/svg') is not a valid name.
    at Function.SVG.create (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.js:62:26)
    at create (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.js:3972:41)
    at Function.SVG.prepare (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.js:156:22)
    at HTMLDocument.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.3/svg.js:174:9)
SVG.create @ svg.js:62
create @ svg.js:3972
SVG.prepare @ svg.js:156
(anonymous) @ svg.js:174
```

here's what I can do in Electron:
![Imgur](https://i.imgur.com/vkrks48.png)

**Comment by facelesspanda** [comment]
Okay this might be actually be an issue with Riot, since as you said `SVG.supported` returns true.
I'm closing this and will check up on their end.

**Comment by facelesspanda** [comment]
Fixed my issue. It was indeed a riot issue, but not a bug.
People are going to have to know this when mixing riot and svg.js:
if you `require('riot')`, then `document.createElementNS()` is messed up.
Changing that to a static `<script src="path/to/riot.min.js"/>` fixed it.
Just putting this out there.

**Comment by Fuzzyma** [comment]
Why does riot changes createElementNS? I thought people finally learned that you shouldnt alter native APIs

**Comment by facelesspanda** [comment]
Apparently it was to fix an issue with server-side rendering in node.js, so maybe they thought it was not critical since the server doesn't have a document to interact with to begin with.
But that's not the case when you can `require()` in Electron `¯\_(ツ)_/¯`
