### ISSUE TITLE
Is there any way to init by dom string?

### ISSUE THREAD

**Issue by apple1324hk** [svgdotjs/svg.js#751]
Is there any way to init by dom string? not document.Element??
Only a javascript string data

because i want to use at javascript framework like vue, angular
want to update the string data with svg.js

Thanks

**Comment by Fuzzyma** [comment]
Take a look into the 3.0 branch. Its support multiple initialisations:

```js
SVG('<rect width="" height=""></rect>') // returns SVG.Rect element
SVG('<svg ...></svg>')
SVG('#id')
SVG('.class')
// ...
```

Give it a try and report back. 3.0 is still under development but the most stuff should work
