### ISSUE TITLE
Typescript type declaration issues

### ISSUE THREAD

**Issue by somethingkindawierd** [svgdotjs/svg.js#752]
I have the following Typescript code which compiles runs just fine.

```typescript
"use strict";

import * as window from "svgdom"
import * as SVGJS from "svg.js"

export const SVG = SVGJS(window)
export const document = window.document

SVG.extend(SVG.Element, {
  ...
})
```

But the typescript compiler reports some issues. Specifically it thinks:

- `SVG.extend` does not exist.
- `SVG.Element` does not exist.

Here are the exact errors.

```
file: 'file:///...svg.ts'
severity: 'Error'
message: 'Property 'extend' does not exist on type 'Doc'.'
at: '9,5'
```

and

```
file: 'file:///Users/beebe/Source/svg-processor/src/svg.ts'
severity: 'Error'
message: 'Property 'Element' does not exist on type 'Doc'. Did you mean 'element'?'
at: '9,16'
```

**Comment by somethingkindawierd** [comment]
I have no idea how much of this makes sense. This is my first time digging in to a Typescript declaration. I cloned the `svgjs` repo and linked it to see if I could fix anything. Here is what I have found.

Within the UMD definition we have:

```
(function(root, factory) {
  ...
  } else if (typeof exports === 'object') {
    module.exports = root.document ? factory(root, root.document) : function(w){ return factory(w, w.document) }
  }
  ...
```

Specifically, in the node + svgdom environment I think that `module.exports` becomes `function(w){ return factory(w, w.document)`.

But in the Typescript declarations file it is declared to be the _result_ of that function, not the function itself:

```
declare var svgjs: svgjs.Library;
```

So back in node when we say:

```
import * as SVGFactory from "svg.js"
```

Typescript _thinks_ `SVGFactory` is an _instance_ of `svgjs.Library` and invoking it returns the type `Doc`.

But `SVGFactory` _is actually_ a wrapper function with the signature `(domElement: HTMLElement) => svgjs.Library`.

Hence the type mismatches when actually using it in Typescript.

----

All the above to say, if we change line 4 of `svg.js.d.ts`:

```diff
- declare var svgjs: svgjs.Library;
+ declare var svgjs: (domElement: HTMLElement) => svgjs.Library;
```

Then the following shows no warnings.

```
import * as window from "svgdom"
import * as SVGFactory from "svg.js"

export const SVG = SVGFactory(window)

SVG.extend(SVG.Element, { ... })
```

But it still does not solve the type issues, so saying something like:

```
import * as window from "svgdom"
import * as SVGFactory from "svg.js"

export const SVG = SVGFactory(window)

const k: SVG.Element = undefined; // <-- type warning
```

will still report:

```
file: 'file:...svg.ts'
severity: 'Error'
message: 'Cannot find namespace 'SVG'.'
at: '9,10'
```

**Comment by Dmitrij-Polyanin** [comment]
I have the same issue, cannot use SVG object in TypeScript.
Is there any plans to fix it?

**Comment by Fuzzyma** [comment]
Try `import window from 'svgdom'  and then import svg.js without passing the window. The first declaration will define a global var window. Svg.js will return the svg object directly when it finds a global window and thus not returning a wrapper function.

I did not Try it but it could work. I am not working with typescript

**Comment by Dmitrij-Polyanin** [comment]
Can you post this code. I did not understand.

**Comment by Fuzzyma** [comment]
```typescript
"use strict";

import window from "svgdom"
import SVG from "svg.js"


SVG.extend(SVG.Element, {
  ...
})
```

I am on smartphone right know. Above us what I mean. The goal is to make `window` a global variable instead if a local one

**Comment by Dmitrij-Polyanin** [comment]
I tried this code:

```
import window from "svgdom";
import SVG from "svg.js";


var draw = SVG('drawing');

draw.rect(100, 100).move(100, 50).fill('#f06');
```

The same error: 

> Uncaught TypeError: Cannot set property 'SVG' of undefined.

**Comment by Fuzzyma** [comment]
Try assigning window to global.window

**Comment by Dmitrij-Polyanin** [comment]
It works, thanks!

Msbe it will be usefull for anyone, posting my `rollup.config` file

```
import typescript from 'rollup-plugin-typescript';
import globals from 'rollup-plugin-node-globals';
import builtins from 'rollup-plugin-node-builtins';
import commonjs from 'rollup-plugin-commonjs';
import resolve from 'rollup-plugin-node-resolve';

export default {
    entry: './src/index.ts',
    dest: './dist/index.js',
    format: 'iife',

    plugins: [
        typescript(),
        resolve(),
        commonjs({
            include: 'node_modules/**' 
        }),
        globals(),
        builtins()
    ],
    globals: ["svgdom:window"],
    external: ["svg.js"]
};
```
