### ISSUE TITLE
Edit/change the existing svg using javascript

### ISSUE THREAD

**Issue by davchang** [svgdotjs/svg.js#753]
Can we change the existing svg using javascript?  I use the following code and it is not working.

<body>
  <div id="drawing">
      <svg xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="300" height="300">
       <rect id="myRect" width="100" height="100" fill="#f06"></rect>
     </svg>
  </div>
</body>

<script>
     SVG.select('rect#myRect').fill('green');
</script>

**Comment by Fuzzyma** [comment]
Select returns a set. If you want to get elements from this set you need to use one of the functions designed for that purpose - first(), last(), get(index). And then you can call your fill() on it
