### ISSUE TITLE
Is there a better way to use animation.at()?

### ISSUE THREAD

**Issue by Foxhunt** [svgdotjs/svg.js#757]
Hi,

#554 is an old issue but relevant to my usecase.
I want to "search" through a set of animations with a slider element.
The slider has a min of 0 and a max of 1000
```javascript
function animate(at) {
  lineAnims.forEach(a => a.at(at))
  circleAnims.forEach(a => a.at(at))
  rotations.forEach(a => a.at(at))
}

document.getElementById('slider').oninput = (event) => {
  let val = event.target.value / 1001
  console.log(val)
  animate(val)
}
```
When i divide by 1000 i can't go back in time as soon as i hit the end of the slider.
I understand that this is working as intended because animations are cleaned up after finishing.
I worked around that by never getting to 1 in my val calculation and using 1000s instead of 100s to have it still look like its at 1.

Is there another way to do it?

full code [here](https://github.com/Foxhunt/svg-animation-test)

**Comment by Fuzzyma** [comment]
No need to open up a new issue. I already saw that you posted. You can try to `loop()` the animation. That way it will never leave the queue und you can use `at(1)`. Definitely something you can try.

**Comment by Foxhunt** [comment]
Thanks for the heads up. Will try that out.

**Comment by Foxhunt** [comment]
Hi again,

if i enable loop the animation will never leave the queue that is nice. 
But at(0) and at(1) both are at the same point in time of the animation.
So if i scroll to the end of the animation it will show the first frame again,
witch is not how i imagine a scroll bar to behave. I think i will stick to never hit 1.

It does not hurt to use both loop() and never hit 1. But adds some unnecessary code in my case.

**Comment by Fuzzyma** [comment]
I think its the closest we can get atm. Sorry
