### ISSUE TITLE
parent() fails on detached Documents

### ISSUE THREAD

**Issue by david-uebler** [svgdotjs/svg.js#759]
Hi,

when calling parent() on a SVG.Element inside a SVG.Document that is not attached to the DOM, 
the call fails with the following error message:

> TypeError: parent.node.parentNode is null

minimal example:

```
const doc = SVG(document.body);
const img = doc.image();

doc.remove();
img.parent(SVG.Pattern);
```

possible cause in SVG.Element.parent():
```
while(parent && parent.node instanceof window.SVGElement){
  ...
  if(parent.node.parentNode.nodeName == '#document') return null // #720
  ...
}
```

The loop condition above checks whether parent has a node, but not if parent.node has  a parentNode.
However, the parentNode may be null when it is accessed to read its nodeName.

Working on detached documents may seem like a silly thing to do, but it may happen in event handlers.
I stumbled upon this by removing a document from the DOM that contains images that did not yet finish loading. When they do, the load event handler calls the parent() method.

**Comment by Fuzzyma** [comment]
fixed in current master now
