### ISSUE TITLE
Add style from external scss file to SVG.js element.

### ISSUE THREAD

**Issue by fthsvk** [svgdotjs/svg.js#760]
I create a svg and add a path to it as follow.

`this.roomPlan = SVG('roomPlan').attr('id','roomPlanSvg').size(1024, 768);`

`this.roomPlan.path(room.area.d);`

I have a external scss file and I have some style as follow;

```
.room-bg {
    fill: nb-theme(card-bg);
    stroke: transparent;
    cursor: pointer;
    stroke-width: 4px;
  }
```
I want to add .room-bg selector to my path element as class like other html.
for example ;
`<path class="room-bg" />`

Note:I'm developing Angular2-Typescript app and I add SVG.js to project as npm package.

Thanks for helps.

**Comment by Fuzzyma** [comment]
use `addClass()`: http://svgjs.com/manipulating/#addclass

**Comment by fthsvk** [comment]
I used addClass but it didn't work.

**Comment by Fuzzyma** [comment]
code, errors?

**Comment by fthsvk** [comment]
I used addClass but it didn't work.I checked the page from the source code, added class, but the style is not applied to the path.

**Comment by Fuzzyma** [comment]
In this case it is not an issue of svg.js. You should use stackoverflow to get an answer to your question.

Just to make sure: The Browser gets a css file right? Because browser dont understand scss

**Comment by fthsvk** [comment]
Thanks for helps. 
Css loading correctly.

**Comment by fthsvk** [comment]
I using .css file and add class via addClass() method style is working.But I try to add scss class , style not working.Can you help me for this problem?

**Comment by Fuzzyma** [comment]
> Because browser dont understand scss

Please read up about scss. You cant use it in the browser. You need to compile it into css before using. Pease head to stackoverflow!
