### ISSUE TITLE
Chaining skew transformations

### ISSUE THREAD

**Issue by ykessler** [svgdotjs/svg.js#763]
There is no difference between the result of any of these lines:
```
draw.rect(100, 100).fill('blue').skew(25,0);
draw.rect(100, 100).fill('purple').skew(0,25).skew(25,0);
draw.rect(100, 100).fill('orange').skew(45,0).skew(0,45).skew(25,0);
```
In other words, any `skew` transformations after the first (going right-to-left) are being ignored.

Fiddle: http://jsfiddle.net/Lmu56awz/978/

**Comment by jiajianbo** [comment]
I dont think so ,you can try it  with two steps
aa=draw.rect(100, 100).fill('purple').skew(0,25);
aa.skew(25,0);
it tell us that aa have been skewed twice,although it like skew(25,0) only.

**Comment by Fuzzyma** [comment]
Please use relative transformation when you want relative transformation. At the moment you are just overwriting the transformation every time
