### ISSUE TITLE
Switch "bitch" to "pain" in comments

### ISSUE THREAD

**Issue by mark-sivill-splunk** [svgdotjs/svg.js#764]
Could you switch the word "bitch" to "pain" in comments for both src/boxes.js and dist/svg.js?

I've embedded this library (via npm) into some work I've have done and it is being picked up by one of our internal profanity checks (before being released) so having some challenges getting code out.

**Comment by Fuzzyma** [comment]
Sure just change it and create a pr. I will merge it immediately

**Comment by mark-sivill-splunk** [comment]
Just created my first ever PR so be gentle :o)

**Comment by Fuzzyma** [comment]
Congratulation! Thats always a big milestone in the life of every developer.
Keep doing it and you will make the open source community happier PR by PR :)

Btw: In your production code you should use svg.min.js which has zero comments. So beside it wont trigger your "bad words filter" it also has less size than the normal version ;)
