### ISSUE TITLE
how to fill object with it's real coorditions/position?

### ISSUE THREAD

**Issue by jiajianbo** [svgdotjs/svg.js#766]
I am new of svg.js, when I do a test .I found a problem, I hope anyone can help me. I  use svg.js draw a polygon,I want it fill some pattern, acturely it does, but the num of pattern always same,I want when I zoomout ,it can fill more pattern ,zoomin fill less. Could anyone give me some suggest? 3Q very much

**Comment by Fuzzyma** [comment]
How do you zoom? Viewbox? Browser zoom?

**Comment by jiajianbo** [comment]
I don't understand the difference about 'Viewbox' and 'Browser zoom',I import svg.panzoom.js and use draw.panZoom() to zoom it.

**Comment by Fuzzyma** [comment]
When you zoom, everything zooms - including every pattern you might have. Please read about the viewbox attribute to understand what it does.
I found that this was a quite good article: https://www.justinmccandless.com/post/making-sense-of-svg-viewboxs

As a solution you can try the following (albeit I am not sure that I works. Never did that) :
Use a nested svg which holds your element. Call panzoom on the nested svg.
This way the pattern is created in the root svg which is not bound to the viewbox if the nested svg.
Maybe this way the pattern stays and does not zoom together with the element

**Comment by jiajianbo** [comment]
Thanks for your Recommendations，but I tryed this solution,it can't work and I got some errors.this  is my code:`/* create an svg drawing */

    var draw = SVG('drawing').size('100%', '100%');
    var pattern = draw.pattern(20, 20, function(add) {
        add.rect(20,20).fill('#f06');
        add.rect(10,10).fill('#0f9');
        add.rect(10,10).move(10,10).fill('#fff')
    });
    var nested =draw.nested();
   // nested.viewbox(0,0,600,600);
    nested.panZoom();
    var box1 = nested.rect(600,300).move(100,100).stroke({width:1,color:'red'}).fill(pattern);`

  svg.js:2719 Error: <svg> attribute viewBox: Expected number, "NaN NaN NaN NaN".

**Comment by jiajianbo** [comment]
when I set nested viewbox I also got this errors

**Comment by jiajianbo** [comment]
this is  my code and errors,what can i do now . I have no idear 



bayuechuixue@163.com
 
From: Ulrich-Matthias Schäfer
Date: 2017-12-24 18:15
To: svgdotjs/svg.js
CC: jiajianbo; Author
Subject: Re: [svgdotjs/svg.js] how to fill object with it's real coorditions/position? (#766)
When you zoom, everything zooms - including every pattern you might have. Please read about the viewbox attribute to understand what it does.
I found that this was a quite good article: https://www.justinmccandless.com/post/making-sense-of-svg-viewboxs
As a solution you can try the following (albeit I am not sure that I works. Never did that) :
Use a nested svg which holds your element. Call panzoom on the nested svg.
This way the pattern is created in the root svg which is not bound to the viewbox if the nested svg.
Maybe this way the pattern stays and does not zoom together with the element

**Comment by jiajianbo** [comment]
now I found the main reason, the"nested.zoom()"is NaN,the test code are 
`var nested =draw.nested();
    nested.panZoom({
        zoomFactor:0.1,
        zoomMin:0.01,
        zoomMax:20
    });
    nested.on('wheel',function(){
        console.log("ss",this.zoom());
    });`
this is a bug or what I write is wrony ?

**Comment by Fuzzyma** [comment]
Try to set width() height() attributes to the nested svg

**Comment by jiajianbo** [comment]
I have tryed it ,when I debug I found this can't get the width and height:
my code:
 var nested =draw.nested().attr({

    height:900,
    width:1600
});debug:



bayuechuixue@163.com
 
From: Ulrich-Matthias Schäfer
Date: 2017-12-25 19:06
To: svgdotjs/svg.js
CC: jiajianbo; Author
Subject: Re: [svgdotjs/svg.js] how to fill object with it's real coorditions/position? (#766)
Try to set width() height() attributes to the nested svg

**Comment by jiajianbo** [comment]
bayuechuixue@163.com
 
From: Ulrich-Matthias Schäfer
Date: 2017-12-25 19:06
To: svgdotjs/svg.js
CC: jiajianbo; Author
Subject: Re: [svgdotjs/svg.js] how to fill object with it's real coorditions/position? (#766)
Try to set width() height() attributes to the nested svg

**Comment by Fuzzyma** [comment]
@jiajianbo sorry what you wrote makes no sense. Looks like some part of your mail does not came through. Please reread your posts on github directly and answer it there, too. Would like to fix this problem

**Comment by saivan** [comment]
Should we close this?

**Comment by Fuzzyma** [comment]
Jeah. Until an answer comes through we can close this
