### ISSUE TITLE
use this context in source of svg.js Incorrectly

### ISSUE THREAD

**Issue by bung87** [svgdotjs/svg.js#767]
https://github.com/svgdotjs/svg.js/blob/f16e4708b6cf0bf9ed939f3fd169776f67f8e0b1/src/umd.js#L12

https://github.com/svgdotjs/svg.js/blob/f16e4708b6cf0bf9ed939f3fd169776f67f8e0b1/src/svg.js#L2

since the umd wrap function use "window" as first parameter,the wraped function should use "window" as this context.

**Comment by Fuzzyma** [comment]
This is done for the reason that the plugins require a global SVG.
In case of running svg.js in the browser without any module system or bundler this is no problem.
But when you use e.g. require() SVG has to be a global variable. Therefore that's how it is atm.
We hope to remove that "hack" in later versions

**Comment by bung87** [comment]
If dont use `src/svg.js` directly,I did't see there is problem with change it be `var SVG = window.SVG = function(element) { `,since it use umd wrap function and **this** context has been resolved.but when it comes to webpack ,**this** context inside factory is unresolved obviously.

**Comment by Fuzzyma** [comment]
`this` is always defined. When you dont pass a context, this refers to the global context. And thats what we want

**Comment by perry-mitchell** [comment]
`this` is not defined in webpack:

![image](https://user-images.githubusercontent.com/3869469/35380057-d35f78a8-01c0-11e8-83b0-6a5e0d39a358.png)

![image](https://user-images.githubusercontent.com/3869469/35380120-045cb77c-01c1-11e8-8926-228ab673b568.png)

I think it'd be better to fallback to window in the case that `this` is not available. Even this would be better:

```javascript
var SVG = (this || window).SVG = function (element) {
```

**Comment by perry-mitchell** [comment]
I managed to get it working in webpack 3.10 by using `imports-loader` and `define=>false`:

```javascript
module.exports = {
  module: {
    rules: [
      {
        test: require.resolve("svg.js"),
        use: "imports-loader?define=>false"
      }
    ]
  }
};
```

**Comment by Fuzzyma** [comment]
@perry-mitchell sorry to loose you as a user. You are the first one who encountered this issue. Unfortunately we need the `this` at this point to not break our plugins.
Did you try differenz syntax on require/imports? The transcription to es5 is quite random sometimes

**Comment by ValLisetsky** [comment]
I have exactly the same issue but with rollup. 
`this` not exists for `var SVG = this.SVG = function(element) {` line.
please fix as its clearly broken if svgjs used in bundlers

**Comment by Fuzzyma** [comment]
The problem is that we break working behavior when we just remove it. As I said plugins rely on this syntax (on nodejs) when SVG is not explicitely defined on the global space. 
I am afraid you have to wait for 3.0

**Comment by perry-mitchell** [comment]
@Fuzzyma I hear you on the point of not breaking existing implementations.. but is it so risky to _check_ `this` before using it? Something like the following could be done to ensure that this error doesn't crop up in bundlers:

```javascript
var globalRef = (typeof this !== "undefined") ? this : window;

var SVG = globalRef.SVG = function (element) {
  // etc
```

You can still prioritise `this`, like I did above - All existing implementations which use `this` will continue to use it. In the case that it is `undefined`, like for us, it would simply fall back to `window` gracefully instead of failing. All it'd be changing is the random error of `this` being undefined. I would think that this could be classified as a non-breaking change suitable for a minor revision...

**Comment by junedchhipa** [comment]
I ran into the same issue while using svgjs with a bundler, and I think @perry-mitchell's suggestion might work out well in `this` case. 
@Fuzzyma  Would love to hear your thoughts.

**Comment by Fuzzyma** [comment]
I like that solution. Can you wrap it up into a PR?

**Comment by perry-mitchell** [comment]
@Fuzzyma I made a PR - #883

**Comment by dotnetCarpenter** [comment]
Refs:
+ https://github.com/svgdotjs/svg.js/issues/659
+ https://github.com/svgdotjs/svg.js/issues/660
