### ISSUE TITLE
Question about Transformations

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#768]
Upon reading the code and implementing a sample 

https://codepen.io/saivan/pen/zporxv

I got a fair idea of the way transforms are morphed in svg.js.
Of specific interest is the `morph` defined in `matrix.js`.

When I tried reimplementing it directly:

https://codepen.io/saivan/pen/vpyNrg

It didn't quite work out the way I had hoped as you can tell.
Also, as far as I am aware, morphing in this way shouldn't work, as is explained [here](https://www.quora.com/Can-I-interpolate-between-two-3-by-3-matrices-representing-affine-transformations-of-a-2D-shape), so how exactly is this morph being achieved in this code and is the `matrix` morph redundant?

**Comment by saivan** [comment]
Upon updating this, I noticed that the implementations are the same, I forgot to remove some css (doh!). Is there a reason this morphing method is preferable to the one provided in the link?

**Comment by Fuzzyma** [comment]
As you can write in the article you linked, you can morph a matrix by using the time parameter together with the components of the matrix. And that's exactly what we are doing.

I am not sure what the question is...

**Comment by saivan** [comment]
Yes thats right. But in terms of decomposing the matrix into a translate, scale and skew matrix to preserve lengths. 

For example, If I replace my triangle for a picture like a smiley face, the smiley face will squash and distort to reach the new location. It would be cool to implement an affine transform so that lengths are preserved as much as possible, I have a pen here:

https://codepen.io/saivan/pen/jYVqmV

thoughts?

**Comment by Fuzzyma** [comment]
There is no way you can find a unique affin transform which leads to a matrix. There are infinite solutions. What you are asking for is impossible to achieve.

However if you know which affin transforms you want, it's easy to do.
Just use `el.animate().rotate(45).scale(2).translate(200,300) `

But in case you want to Morph a matrix and only morph a matrix, you just morph their values.

**Comment by saivan** [comment]
Yes there are an infinite number of solutions if you have allow the operations to occur in any order. I suppose this probably isn't so valuable anyway because a user could just override the morph provided by SVG.js so I guess there isn't much value here.
