### ISSUE TITLE
Can't change text of text element

### ISSUE THREAD

**Issue by Jordan4jc** [svgdotjs/svg.js#770]
I'm using svgdom on a node server

```
const window = require('svgdom');
const SVG = require('svg.js')(window);
const document = window.document;
const draw = SVG(document.documentElement);
const fs = require('fs');
const tag = fs.readFileSync(`images/name-tag-1-with-name.svg`,'utf8');
const svg = draw.svg(tag);
const svg2png = require("svg2png");
```

Later on I'm attempting to set the text on text elements like so

```
svg.select('text.first-name').plain(firstName)
svg.select('text.last-name').plain(lastName)
```

The error I'm getting is

    svg.select(...).plain is not a function

I'm I misunderstanding how this select is supposed to be used?

**Comment by Fuzzyma** [comment]
Please ask questions in stackoverflow. This forum is for issues.

The documentation for svg.js is quite good.

select() returns a set. You can access an element with get(index), first() or last()
