### ISSUE TITLE
Rotation animation does not continue

### ISSUE THREAD

**Issue by HannesVo** [svgdotjs/svg.js#772]
Hello, 
i am trying continue an animation rotation of a pointer on a circle line, which seams not to continue but makes an 360 rotation when the angel of start is higher then 120 degrees. What do i make wrong or is this a bug or by design.

https://jsfiddle.net/qz19e1zb/

Thanks in advance
Regards
Hannes

**Comment by Fuzzyma** [comment]
Interesting case... No that is not intended.
When you plan to dig deeper post your findings.
Unfortunately I am short on time atm so I won't look into it soon.

**Comment by HannesVo** [comment]
my finding: 
the skewX calculation in svg.js in 2405 uses an atan2 function. 
        , skewX = 180 / Math.PI * Math.atan2(px.y, px.x) - 90
As i understand, this is an reversconversation to degrees which is also used as initial "rotation" angle (line:2420) for the animation. atan2(y,x) changes it's quadrant at 90 degrees.

maybe some mathpeople can help to solve that??

PS:
1)SkewY calculation (line: 2415) may also be affected
2)i added some excel calcs show the calculation.
[Book1.xlsx](https://github.com/svgdotjs/svg.js/files/1596302/Book1.xlsx)

**Comment by Fuzzyma** [comment]
I am not sure how skew could interfere with your usecase here. You only use rotation. You never touch the atan2 function

**Comment by saivan** [comment]
I think the new transforms should fix this problem.

**Comment by Fuzzyma** [comment]
To follow up with this:
Your best chance to have it right is using relative transformations here.
I changed your fiddle to a relative version. Relative always works as expected.
https://jsfiddle.net/Fuzzy/qz19e1zb/8/

These kinds of bugs will not happen in 3.0 anymore. But unfortunately for now you have to go with this solution.
