### ISSUE TITLE
why get repeate images  when fill an image to rect，i simple move a image?

### ISSUE THREAD

**Issue by hanhui** [svgdotjs/svg.js#773]
svg code :
img1 = draw.image("/zts/jz_close.png", 45, 55);
var pattern = draw.pattern(45, 55, function (add) {
            add.rect(45, 55).fill(img1)
        })
var rectImg1 = draw.rect(45, 55).move(153,58).fill(pattern);
 
 the source image `jz_close.png`:
![image](https://user-images.githubusercontent.com/1829623/34465954-16f605b6-eeff-11e7-8e6a-42d0425e6767.png)

after fill and move to a new possition ,the image show bellow:
![image](https://user-images.githubusercontent.com/1829623/34465997-7c6f23f4-ef00-11e7-94e6-a024ff05f92a.png)

**Comment by Fuzzyma** [comment]
The question you are asking is not svg.js related. There are many tutorials out there which teach why the pattern behaves as it dies (tl;dr pattern is fixed, when you move rect, you see another portion of the pattern). Stackoverflow will also help you.
