### ISSUE TITLE
There should be bottomY() and rightX() functions

### ISSUE THREAD

**Issue by x13machine** [svgdotjs/svg.js#777]
I needed this feature because I was trying to align text. 
bottomY() would basically do this:
```
elm.y(height - elm.bbox().height);
```

**Comment by Fuzzyma** [comment]
svg.js is easily extensible. Just add the functions you need...

```js
SVG.extend(SVG.Text, {
  bottomY: function() {
    // your code
  }
})
```

**Comment by x13machine** [comment]
ok, but it should still have that feature

**Comment by Fuzzyma** [comment]
No - not really
