### ISSUE TITLE
[Question] iterate over geometries only

### ISSUE THREAD

**Issue by ValYouW** [svgdotjs/svg.js#779]
Hi,

I am looking for a nice way to iterate over geometries only, something equivalent to:
```js
var elems = svg.node.querySelectorAll('*');
elems.forEach(e => {
    if (e instanceof SVGGeometryElement) {
        // Do something...
    }
});
```

Is there any syntactic sugar for that in svg.js?
Thx!

**Comment by Fuzzyma** [comment]
`parent.children().filter((el) => el instanceof SVG.Shape).forEach(yourstuff)`

Or directly `parents.each(yourstuff)` - without the filter

**Comment by ValYouW** [comment]
Yeah, that's more or less what I'm currently doing.
What do you think about a "geometries" method (like "each") that will filter for geometries? If you are for it I can make a PR...

**Comment by Fuzzyma** [comment]
I don't think it is needed. Adding it yourself is a breeze. It would only bloat the core even more.
Thank you anyway!

**Comment by ValYouW** [comment]
Sure!
