### ISSUE TITLE
Bug with clear() while using Webpack

### ISSUE THREAD

**Issue by chadsaun** [svgdotjs/svg.js#781]
I believe there is a bug when trying to use the clear() method while using SVG.js in Webpack. When trying to use clear() I get the error `TypeError: Cannot read property 'parentNode' of undefined at create.clear`. See my example below.

[![Edit webpack and svg.filter.js example](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/1op0xy1ymj)

**Comment by Fuzzyma** [comment]
Dont use SVG.Doc directly if you dont know what you are doing:

https://codesandbox.io/s/9ymx30pjxp

Also `100vw` does not seem to be supported by the browser (take a look into the console)

**Comment by chadsaun** [comment]
I'm glad to see that it works! I remember reading somewhere that if you wanted to use SVG.js as an import to use SVG.Doc().  I guess that's not the case.

**Comment by Fuzzyma** [comment]
It depends on what the transpilation process produces. The svg.js plugins need a global balance variable SVG. So as along as this is created its all fine
