### ISSUE TITLE
Is there any possibility to manupulate SVG objects in memory first?

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [svgdotjs/svg.js#783]
I have lots of javascript calculations and logic, and i want to make all graphics in memory, not rendering immediatly. After I prepair all elements I want to draw all on svg tag.

Is there any possibility to manupulate SVG objects in memory first?

For start i need to make in memory Polyline and then to render.

Trying this code.
```
var draw = SVG('drawing');
draw.polyline("0,0 100,50 50,100");
```

but it renders imediatly.

I need something like

```
var l = new Polyline("0,0 100,50 50,100");
draw.Draw(l);
```

**Comment by Fuzzyma** [comment]
You almost got it. try to use

```js
var l = new Polyline().plot("0,0 100,50 50,100");
draw.Draw(l);
```

However - using it this way has edgecases you need to be aware of.
First of all: elements which are not in the dom do not have a `bbox()`. svg.js fixes this by inserting the element to the dom, getting the bbox and removing it after.
So whenevery you call bbox or use a function which needs bbox (e.g. `size()`) it will append the element to the dom anyway. So please be careful with your approach.

Other cases I can think of are:
- cloning the element
- rbox, screenCTM, ctm
- everything which needs browser calculation and/or a visible element

**Comment by Dmitrij-Polyanin** [comment]
This is working, cool!

Trying to make it work with syntax highlighting.

I tried this code, it works, but WebStorm did not see SVG.Polyline

![2018-01-18_15-06-57](https://user-images.githubusercontent.com/10674646/35097500-79b7b8ce-fc61-11e7-94b9-e7c962b32ed1.png)

Trying this code, with L big in PolyLine, it highlight this, showes correctly, but not working...

![2018-01-18_15-09-16](https://user-images.githubusercontent.com/10674646/35097527-974e4916-fc61-11e7-96ad-e050d5ac9118.png)

> Uncaught TypeError: SVG.PolyLine is not a constructor

**Comment by Fuzzyma** [comment]
I have no idea how your syntax highlighting works. That's nothing I can fix for you.
However you can look into the wonderful docs at svgjs.com or peek into the source code which is quite nice to read.

**Comment by Dmitrij-Polyanin** [comment]
Thanks for your help!
