### ISSUE TITLE
Rethink absolute transformations / relative transformations

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#786]
Absolute transformations as is are broken. The new api will look like this:

- absolute:

```js
transform({
  origin: [20, 30], // ox, oy
  skew: 20,
  scale: 1 // sx, sy
  rotate:
  position: // px, py - use center if not provided
  translate: // tx, ty
  
  basisX: // that might go away.
  basisY: // its not that important
})

matrix()
```

- relative:

```js
- scale()
- translate
- skewX...
- rotate
- applyMatrix() - sugar
```

**Comment by saivan** [comment]
We should also allow for 

```
transform ({
    origin: "bottom left",
})
```

**Comment by Fuzzyma** [comment]
What's your plan to figure out what 'bottom right' is? Just bbox? Or anything else?

Btw we might want to go for more standardized syntax like in css borderradius:

top-left
top-right
bottom-left
bottom-right

But that's just a quick thought

**Comment by saivan** [comment]
Yes, bottom right should just use the bottom right of the bbox (because thats what we will be transforming anyway). Whilst we should encourage the use of a standardised syntax, the code block I showed you should be able to handle `    TOP LEFT `, `tOp      LeFt`, `top_left` and the sensible `top left` :p Since its cheap and short, it should work fine I think.

**Comment by Fuzzyma** [comment]
Yes I think that's OK. A simple `str.toLowerCase().includes('top')` check would satisfy every format. We just have to make sure that we add the includes function to the Polyfills list because it might not be supported in older browsers

**Comment by saivan** [comment]
Even though I'd get really mad reading code that included it :P

**Comment by Fuzzyma** [comment]
Both methods you mentioned need Polyfills. It's in the same spec as includes().
But all modern browsers support it.
Hopefully people who need the Polyfills will do a browser check before loading them ^^

**Comment by saivan** [comment]
Well, polyfill it is then! :P

**Comment by saivan** [comment]
I think `matrix(MAT, relative)` is probably the better approach instead of applyMatrix.

**Comment by Fuzzyma** [comment]
I agree

**Comment by saivan** [comment]
This is now completed in #829
