### ISSUE TITLE
Add support for new colour spaces

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#790]
http://stackoverflow.com/questions/2353211/hsl-to-rgb-color-conversion#9493060

Also add LAB and LCH spaces
as shown: https://en.wikipedia.org/wiki/HCL_color_space

**Comment by matuss1899** [comment]
I'll try this

**Comment by Fuzzyma** [comment]
Feel free to contact us on [gitter](https://gitter.im/svgdotjs/svg.js) if you need any help. Also make sure to work on the 3.0 branch. Good luck! :)

**Comment by matuss1899** [comment]
Hi, I created code to support required functionality outside of project, but I'm not really sure where to put them. I was thinking that maybe color.js or svg.js may be appropriate, but I'm not sure. Can you give me any directions regarding this?

**Comment by Fuzzyma** [comment]
Yes, it has to go into color.js. Please ignore all these comments sticking around there. They are basically for us, how we intend later api to work.

**Comment by saivan** [comment]
Okay, this is done now too, #939
