### ISSUE TITLE
.animate('=') not working

### ISSUE THREAD

**Issue by timothyachumba** [svgdotjs/svg.js#793]
I can't seem to bind the animation to an event. Is this still working?

**Comment by Fuzzyma** [comment]
The docs wrongly state, that `=` is an easing parameter. Actually it was designed to be passed as duration together with a function which performs an animation.
However that was just forgotten to implement after refactoring the fx module.

For now this parameter just does not work. However we plan on having it back in 3.0.

I will allow the following:

```js
// this will not animate anything
Var fx = el.animate('=').move(100,100)

// instead you can control the animation
document.mousemove = function(e) {
  // you can pass 0 to 1 to at() to move the animation 
  fx.at(someCalculatedStuff)
}
```

**Comment by timothyachumba** [comment]
Ahh I see, out of interest, do you have a timeline for 3.0?

**Comment by Fuzzyma** [comment]
It was planned to be released of the end of 2017 but as you can see we missed this target.
However the svg.js gathered a bit momentum im the last week so it might get more progress in the next weeks. However I cant give you a time line or date. Not yet.
But that shouldn't stop you from testing the new features in the 3.0 branch.
Unfortunately the docs are for v2 but the changelog will give you a good grasp on what was changed and how it can be used now (most importantly: `SVG('#id')`)

**Comment by saivan** [comment]
This is no longer relevant for 3.0, so I'll close this for now. We will be documenting the way animations work in 3.0 soon :)
