### ISSUE TITLE
Angular 2+: Not possible to access svg root from element.

### ISSUE THREAD

**Issue by ivandroid** [svgdotjs/svg.js#794]
Cannot call this method http://svgjs.com/referencing/#doc. The Element interface doesn't provide it at all.

**Comment by Fuzzyma** [comment]
Well - this methods exists. You can be sure about that. If this isn't the case for you, provide code and more information so we can help you

**Comment by ivandroid** [comment]
Search for` doc(`) method in `svg.js.d.ts`. I cannot find it at all.

**Comment by Fuzzyma** [comment]
We are not actively maintaining the ts file since nobody of our team uses typescript. If you find bugs please open a PR to fix those. We are not able to do that

**Comment by ivandroid** [comment]
Is svg.js developed for your team or for it's users? :) Okay, I will open a PR.

**Comment by Fuzzyma** [comment]
Sorry - what? Seriously we simply don't have the KNOWLEDGE to maintain the ts file. It's not about us or the user!

**Comment by ivandroid** [comment]
Anyways, you've provided a **ts file**. But it seems to be incomplete.

**Comment by Fuzzyma** [comment]
It's completely maintained from users. If people need a fix they just open a pr for it

**Comment by ivandroid** [comment]
Okay, understood.

**Comment by MarkLodato** [comment]
Looks like this has been fixed in 2.6.5 (c1ce0c9d63e87423f3a6d7eca381546ec8a89104) so I think this issue can be closed.
