### ISSUE TITLE
anchor:middle for text on a path does not appear to work

### ISSUE THREAD

**Issue by russellbits** [svgdotjs/svg.js#795]
I created a JSFiddle http://jsfiddle.net/ruzel/k239y2u5/4 demonstrating that the text on the arc is anchoring itself to the start of the arc with the text being cut off. I believe that anchor:middle should position the whole line of text in the middle of the line (that's what raw SVG in the browser does anyway).

**Comment by Fuzzyma** [comment]
I don't geht what you want. You programmatically set the text to anchor middle and then complains that it is centered. A text path ALWAYS starts at the start of the path and goes ftom there on. Or better said: the anchor point is always at the start of the path. So when you use anchor middle, it will center the path at the anchor of. What you want to use is an offset which moves the text along the path.
You can calculate the path length and take the half if it to move the text anchor to the center of the path and the use anchor middle. That should center the text OK the path
