### ISSUE TITLE
In SVG.FX the size function maps to width and height.

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#798]
When we use it directly instead we could save a bunch of code

**Comment by Fuzzyma** [comment]
We have to be careful about that. For this to work `size()` needs to return an array of `[with, height]`. Same is true for `move()`

**Comment by Fuzzyma** [comment]
With the new animations in 3.0 what i said before isnt necessary.
However it might be useful to let move and size return useful values anyways

**Comment by Fuzzyma** [comment]
Size is differenty implemented for different shapes (e.g. circle and rect). Therefore we should rely on width and height to do the correct job here. Closing!
