### ISSUE TITLE
Remove SVG.Text.size in favour of fontSize() to avoid name clash

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#799]

**Comment by wout** [comment]
Not a fan. I'd prefer to remove the `size()` method on `SVG.Text` and endorse the use of `font({ size: 12px })`

**Comment by Fuzzyma** [comment]
Yes that looks good, too. Maybe deletion is better

**Comment by saivan** [comment]
Yep, agreed!

**Comment by Fuzzyma** [comment]
fixed with 31e94c28d85f676a0f4ec073a06435bc86b1dc73
