### ISSUE TITLE
Plugin idea: multiple select of elements

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.js#804]
First, apologies because this is a feature request/question but I don't think there is a mailing list or forum to discuss these issues :\

I'm trying to build a custom diagram editor where I want to draw a few things, move them around, resize, etc. 

Like #650 I'm using a combination of plugins to achieve this, namely: svg.select.js + svg.resize.js + svg.draggable plugins + svg.draw.js

What I think is lacking is another plugin that allows the user to do a multiple select of elements. Use case is to quickly select many elements and move them around. I made a video sample of another software showing this interaction: https://cl.ly/pHuV

Anyone already has something like this done that can be transformed into a plugin? or maybe I missed some plugin that already achieve this?

I'll probably start working on this, reading the source code on some of the other SVG.js plugins but just wondering if anyone already solved this need because it seems a quite common one.

**Comment by Fuzzyma** [comment]
Hey - no problem! Feature requests are something which belongs here. Your idea already came up here. However the way things are selected, resized and dragged are not really compatible to do what you want.

I think an example will make it a lot easier.
Imagine you have a Photoshop document.
When you select a shape and drag it around, you basically translate it to another point. When you resize it you scale it which it a transformation, too - as well  as when you rotate or skew it.
You can do the same thing when selecting multiple elements.
The reason why I say that is: the plugins you use are based entirely on coordinates and not transformations. When you drag a shape you change the coordinates. When you resize it you change the width and height.
So the way these things are achieved are different from those used in photoshop.

In general, when you select multiple elements you need to put them into a group and resize/scale/rotate the whole group. That would be the behavior which you know from Photoshop and similar tools.
It is all based on transformations while our plugins use coordinates directly.

Both has its pros and cons. E. G. The coordinate approach produces nicer code (no transformations all around). Furthermore you don't run into issues with the stroke of elements (when you scale up an element, the stroke gets bigger and bigger. Scale independent stroke comes in svg2 which is far away). However, transformations allow for easy grouping of elements and transform them together which is a huge plus

When you really want photoshop behavior you should try to rewrite that plugins with transformations only. Then there is nothing in your way to include all that stuff Photoshop can do (including multiple selections and transformations)

Hope I could make things a bit more clear!
(and looking forward to your first plugin :D)

**Comment by pjfsilva** [comment]
Thanks, I understand your answer but maybe you were thinking a bit more broadly because of the plugins I mentioned. 

My use case is just selecting multiple and dragging them around. Resizing I think the best UI is still to do it 1 by 1. 

So my idea is just implementing something that allows me to select multiple and then drag them as a group (no pun intended with SVG grouping, just a plain english 'group' of things). The part of drawing a dashed rectangle on mousedown like on the video I already have some ideas. The drag multiple I have to check into the drag plugin and how to achieve this. (If I SVG-group them it's probably easy but that also causes other problems with grouping/ungrouping multiple times)

Now that I think more of it I'm not sure if this should actually be an extension of 'svg.select', of 'svg.draw' or just a plain new plugin.

If anyone has some kind of fiddle experiment or similar things to this, it would be appreciated.

**Comment by Fuzzyma** [comment]
When your use case is only based on dragging around a couple of elements at once then you can implement that with the plugins already.
Make sure to call selectize on all elements you want to drag (actually you don't have to do that but when you want the select-effect you need it). Then you catch all mouse events which affect your root svg and fire those events in every shape you want to move. Actually I am not sure if you can just re-fire events in other elements but it's worth a try.

**Comment by saivan** [comment]
You effectively just want to check for bounding box intersections as far as I can tell here. But as @Fuzzyma said, you'd have to take into account the fact that under transformations; you can rotate and skew the bounding boxes of the elements as you move them. It would need a kind of recursive descent approach here:

Assuming you have a `boxesIntersect` function that returns true if intersected, and false otherwise; then you also have a `fullyInside` function that returns true if the second box is fully inside the first; the pseudocode would be:

```
selectInside(yourBox, domNode)
     inside = []
     if fullyInside(yourBox, domNode)
          inside.push(domNode)

     else if boxesIntersect(yourBox, domNode)
         for childNode of domNodes
             selectInside(yourBox, domNode)
    
    return inside
```

Of course you can have different behaviours to this, but most of the difficulty is in the `fullyInside` and `boxesIntersect` methods. But I would imagine that probably already exists? @Fuzzyma

**Comment by Fuzzyma** [comment]
The selection rectangle you "draw" with your mouse around the elements is never transformed or anything. So you can just use rbox on the elements to get a box which is in the same space as the selection rectangle. Checking if one box is in another box should be trivial then. However selecting is the easy part. Moving them all around at once is way more complicated than when our) you don't don't group them before. You need to trigger the mouse events for dragging on all elements. I pointer out a possible way in my last post

**Comment by saivan** [comment]
Well thats not true is it? Because in the pseudocode I wrote; only the highest element in the tree that is fully enclosed by the box is selected. So applying a translation to that element alone should translate everything the right way automatically (because you don't reapply the translation to children).

**Comment by Fuzzyma** [comment]
Jeah but we are talking about dragging multiple elements at once without grouping them. So there is no parent node you could drag.

**Comment by pjfsilva** [comment]
@Fuzzyma can you provide details on where was this implemented?

**Comment by Fuzzyma** [comment]
I am in the process of cleaning up issues and try to only keep the relevant ones.
If you are still waiting for such a plugin, I am sorry, that there is one yet.
If you want, I can keep the issue open. Just trying to reduce noise
