### ISSUE TITLE
Image memory leaks (and possible solution)

### ISSUE THREAD

**Issue by kuzmanovicnenad** [svgdotjs/svg.js#805]
First, thanks for awesome lib!

Second, well, it looks like (creating and) removing image is making memory leaks and maybe I've manage to track down the problem...

If you execute next piece of code and keep track of heap memory and events in chrome developer tool (performance tab) you'll find out that for each created and removed image you got +2 events and +1 SVGImageElement detached from DOM.

```
    var draw = SVG('test', 200, 200);

    // Create 100 images
    for(var i = 0; i < 100; i++) {
        var image = draw
            .image('./Testing.jpg', 200, 200);
    }

    // Remove 100 images
    SVG.select('image').each(function () {
        this.off();
        this.remove();
    });

    draw.clear();
    draw.remove();
    draw = null;
```

Those +2 events are 'load' and 'error' events in Image class and (I think) the problem is that events are registered with img element and not this.node element:
```
img  = new window.Image()
SVG.on(img, 'load', function() {
```

Now, when those are to be disposed, SVG.off method is trying to find this.node in handlerMap but can't find it:
```
SVG.off = function(node, event, listener) {
  var index = SVG.handlerMap.indexOf(node) // 'node' is this.node and can't be find because it's registered with img element
   ...
  if(index == -1) return
```

So, after the image is removed the events are not disposed (+2 events) and reference to SVGImageElement still exists in SVG.handlerMap (and SVG.listeners?) (+1 detached DOM element).

What I did is next:
```
img  = new window.Image()
//SVG.on(img, 'load', function() {
SVG.on(this.node, 'load', function() {
```
...and that fixed the mem leaks but I'm not sure if this could cause some different problems...

This also works for me but it's a bit hacky solution:
```
   SVG.handlerMap = [];
   SVG.listeners = [];
```

**Comment by Fuzzyma** [comment]
Good find! Thanks for reporting. 

The reason we bind the load event to the img element instead of this.node is, that (as far as I remember) the load event on svg images is not working as good or does not provide the information needed (width, height...) to properly scale the image.
So you cannot just switch this.

The proper way to fix the memory leak would be to call `SVG.off(img)` in both, loaded handler and error handler. This way we make sure that no event on img remains.

**Comment by kuzmanovicnenad** [comment]
For some reason it's not working in handler but I managed to dispose it by saving this.img and extending remove() function (Image class):
```
...
, extend: {
    remove: function() {
        SVG.Element.prototype.remove.call(this);
        SVG.off(this.img);
        return this
    }
...
```

And this is working.

I've noticed one more thing - the way you remove elements from SVG.handlerMap and SVG.listeners:
```
delete SVG.listeners[index]
delete SVG.handlerMap[index]
```

If you remove array element this way, array is still the same length (but with undefined instead of deleted object). So basically array is always growing while events are added/removed.
Maybe this is problem if there are frequent iteration over those arrays.

I've change it to:
```
SVG.listeners.splice(index, 1)
SVG.handlerMap.splice(index, 1)
```

This will remove elements from arrays (but will work slower)
Also maybe there should be check after removing specific event or event.namespace and remove element from array if there are no more events. (isEmpty(object)). 

Thanks for help!

**Comment by Fuzzyma** [comment]
I looked around what delete does and if undefined takes any space in an array and according to this stackoverflow question, the array becomes sparse when you delete something (so it does NOT take space): https://stackoverflow.com/a/6499525/2129897

**Comment by kuzmanovicnenad** [comment]
My point was that you still have to iterate over all elements of the array (undefined of defined) in for example indexOf method. But there is like none performance improvement in this so I'll just revert it.

**Comment by Fuzzyma** [comment]
Mh I know that array functions like map or forEach skip empty indices. So I assumed that would be the case here to. But I am not entirely sure

**Comment by Fuzzyma** [comment]
So I tested this with a simple `SVG.off` like this:

```js
      SVG.on(img, 'load error', function() {
        // dont forget to unbind memory leaking events
        SVG.off(img)
      })
```

And that works

**Comment by kuzmanovicnenad** [comment]
OK, I'm working with your last release (2.6.3) and I've added that code to the exact same place. Still, I got mem leaks, even more now (+3 events per image). Here are dev tools screenshots after test code from above is executed and cache is cleared:

<img width="1183" alt="screen shot 2018-02-07 at 5 52 53 pm" src="https://user-images.githubusercontent.com/4664621/35930707-f44e0ad0-0c32-11e8-887c-2b656bdabada.png">

<img width="1182" alt="screen shot 2018-02-07 at 6 08 09 pm" src="https://user-images.githubusercontent.com/4664621/35930712-f9ab119e-0c32-11e8-827b-aa1b25ebf29c.png">

**Comment by Fuzzyma** [comment]
Please note that binding multiple events at once (as done in my last commit) is only possible in the 3.0 branch but not in 2.x. I tested my code by adding `SVG.off(img)` to the load and error handler and it is working as expected. The handlerMap gets cleared as well as the listeners

**Comment by kuzmanovicnenad** [comment]
Ah! It actually works.
...unless you put it at the end of handler which I obviously did last time... 
Anyway, it definitively work as a first command.

Thanks man!

**Comment by Fuzzyma** [comment]
Glad that it worked. Thanks for finding that leak :D
