### ISSUE TITLE
Remove SVG.parents()

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#813]
This is easily done with

```
// return array of all ancestors of given type up to the root svg
  , parents: function(type) {
      var parents = [], parent = this

      do{
        parent = parent.parent(type)
        if(!parent || !parent.node) break

        parents.push(parent)
```

But for es6, we might consider adding a generator to do this

**Comment by saivan** [comment]
If anybody has a good use case for parents that would make us keep it, please let us know :)

**Comment by Zythyr** [comment]
@saivan  Does this mean that v3.0.0 will no longer have the parents() method (http://svgjs.com/referencing/#parents)???

I am using the parents() method in my code.

**Comment by Fuzzyma** [comment]
What's your use case?

**Comment by Zythyr** [comment]
@Fuzzyma I am handling multiple SVG canvas, and for my application a node(s) may  need to be transferred from one canvas to another. nodes are being transferred from one canvas to another. 

The parents() function has been very helpful for me for proper identification of depth (parents()l.ength) as well the list of parents for proper insertion of a node into another canvas. 

Sorry for asking a silly question, I am still a noob programmer, but is there a reason why parents() function needs to be removed in v3.0.0? If you guys need to remove it, no worries, I can create my own parents() function using the same code that @saivan mentioned.

**Comment by saivan** [comment]
We are mainly thinking of removing it because it's just doing what you could achieve easily with a for loop. Eventually once we fully support es6, the syntax will be so clean that having a parents method wouldn't make too much sense :)

**Comment by Zythyr** [comment]
After further thought, I strongly recommend keeping the `parents()` method in v3.0.0. 

Please pardon my lack of understanding of  SVGjs library architecture. I am still a novice to JS. Based on what @saivan said that one can easily recreate the `parents()` method using a for loop; I still don't understand why remove this functionality from SVGjs? This puts the burden on the end user of SVGjs to understand the architecture os SVGjs library and having to create the `parents() `method independently. Its almost like removing other helper methods such as `doc()`, `parent()`, `last()`, `first()`, etc... 

I am heavily using SVGjs and the `parents()` method in my application. The `parents()` helper method has made some of the logic in my application very smooth to implement. Without having the `parents()` method in SVGjs, I would have to create a separate function to do the same and break the smooth flow SVGjs already provides.

**Comment by saivan** [comment]
Do you mind providing some examples of where you used it? I'd be interested in seeing some use cases.

**Comment by Fuzzyma** [comment]
with 334d9c73c2f74679a93b1d7b3e39b614f6444faa I reworked the parents method so that it is actually useful. It now returns all parents until it hits document or it hits the element passed as parameter.
The passed parameter can be a selector, a node or an element.

```js
rect.parents('body') // returns List of all elements up to but not including body
```

I feel comfortable with leaving this version in the library

**Comment by saivan** [comment]
Should the default behaviour be until it hits `rect.doc()` ?

**Comment by Fuzzyma** [comment]
Well for me this is a Dom method now. And the Dom doesn't care about Html or svg. In case the user wants it until doc he can simply call `this.parents(this.doc())` (which would not include the doc).
To be fair it also makes the function a lot easier that way. And when I don't have a strong opinion, simplicity wins. Beside that I really think it is the more useful behavior
