### ISSUE TITLE
Positioning of rotated element

### ISSUE THREAD

**Issue by palodelincak** [svgdotjs/svg.js#814]
When I try to change the position of element which was `rotated` (transform tag is applied) then it doesn't work as expected. 

Take a look at this example:
https://jsfiddle.net/skomyb2j/

The `rectBlack` is rotated by 45 degree and positioned far away from viewbox. Once this `rectBlack` is cloned to another SVG and positioned to `.x(0).y(0)` it doesn't show up properly.

The `rectRed` is setup the same way as `rectBlack` but it is not rotated - and as you can see it show up properly once cloned.

I'm not sure what is the cause, but seems that the `transform` tag is not updated after the position is changed.

**Comment by Fuzzyma** [comment]
I dont know what you expect. You set the svg size to 50px only and then you move your elements to 100,100. Ofc you cannot see them. Here is your fiddle so you can see whats going on:

https://jsfiddle.net/Fuzzy/skomyb2j/11/

**Comment by palodelincak** [comment]
Sorry, maybe my description was not good enough. The sizes doesn't matter...

Here is hopefully better explanation:
https://jsfiddle.net/pqdyuLhw/

Imagine having two SVGs - one bigger and one smaller. I positioned elements on the bigger SVG. After that I cloned these elements to the smaller SVG.

The cloned red element without transform is positioned as expected - respecting the .x(25).y(25). This part works.

But the cloned black element with transform (rotate) is not positioned as expected - it ignores the .x(25).y(25). Just take a look where this element is placed.

I expect the cloned elements on the right side to be placed in the same way as the elements on the left side.

**Comment by Fuzzyma** [comment]
It is working as expected. When cloning the element you clone everything including the transformation matrix. And this matrix says: Rotate my element by 45 degree around the point 125, 125. Why 125 you might ask? Because thats the center of the element (first black square).
And this matrix applied to new coordinates after the move just looks like that. There is everything correct there.

You might want to look into transformations to learn more about that

**Comment by palodelincak** [comment]
Oh, I'm sorry I thought this is a bug because it was really confusing.

What is the best way to position element once the transformation matrix is applied? Is there a way which can handle both elements (with/without transformation) the same way and position them to the same place?

**Comment by Fuzzyma** [comment]
You can translate the element back to where you want it. With `el.transform({x:x, y:y}, true)` you can translate the element back. It's a relative transformation so you have to know how much you have to move it back.

However it would be better to use translation from the very start. It's easier to go full transformation when you start with it.

**Comment by palodelincak** [comment]
Ok thanks, I will try that...
