### ISSUE TITLE
RBox including filters, it is possible?

### ISSUE THREAD

**Issue by UXDart** [svgdotjs/svg.js#815]
Hello! I'm using the filter plugin to add drop shadows, is there anyway to know the size (RBox) of a rect but including all filters? I tried different things, but also in the dev inspector I can see that all 'use' and 'rect' really have the size of the rect. so not sure which node should I calculate its box... tried rbox and bbox, on all nodes, is not possible?

the reason is that I need to move the node but without the shadow size/rect, so I need to know somehow the two rects to calculate the difference

TIA

**Comment by Fuzzyma** [comment]
Did you find a solution or workaround? If so I would be interested. Can you share it? :)

**Comment by UXDart** [comment]
yes, what I really needed was only the top left space between the "including filters" and "without filters", so what I did was to get the rbox() as soon as I added the svg to the DOM, so it was at (0, 0)... so the box.x and box.y are the filter differences. not sure how to get the width/height... HTH

**Comment by Fuzzyma** [comment]
Did you try using `rbox` with a parameter? Airbox gives you the box relative to the window by default. When you need it relative to your root svg (or any other parent) pass the parent to the rbox function: `el.rbox(el.dox())`

**Comment by UXDart** [comment]
yes, I tried... even more I'm using atm, but anyway with that I could get the rect x,y that is moved top,left because of the filter, but the width/height won't work with that

**Comment by Fuzzyma** [comment]
OK. Thx for sharing!
