### ISSUE TITLE
Matrix Equality

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#816]
Perhaps we should have a way to check if two matrices are equal. Eg:

```
matrix1.equals(matrix2, tolerance)
```

I know you can use tostring, but thats not so safe with floating point numbers. Thoughts?

**Comment by Fuzzyma** [comment]
Never needed it. Do you have a special usecase in mind?

However wouldn't be hard to add I guess

**Comment by saivan** [comment]
Well for caching it would be useful. If you apply:

```
matrix(1, 0, 0, 1, 0, 0)
```

Then change it to:

```
matrix(1.001, 0, 0, 1, 0, 0) 
```

It will force a browser repaint, but the visual difference may be too small for you too care in some cases. If you're animating lots of objects, this might get pretty important :P

**Comment by saivan** [comment]
Added as part of the new transforms.
