### ISSUE TITLE
Add a demos folder

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#818]
I'm not sure what the preferred format for this is, whether we should add the demos as codepens in the documentation. But I think there is also merit to having the demos in a self contained folder, so that they can serve as an alternative tl;dr; type of documentation.

Thoughts?

**Comment by Fuzzyma** [comment]
When we add such a folder then not in the repo. Imo this is for source code only. We could make a seperate repository or add a folder to the docs repo?!?

**Comment by saivan** [comment]
Yep, that is probably best, but then we would have to tie each demo to a particular version number and clearly state which version the demo is working on.

**Comment by saivan** [comment]
I like the idea of modifying the docs with demos; but it would be nice to make them fullscreen as well.
