### ISSUE TITLE
Import SVG issues with different SVG formats/coordinate systems? 

### ISSUE THREAD

**Issue by AlexMarshall12** [svgdotjs/svg.js#821]
I have this cod which works perfectly. 

```
<html>
        <header>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.4/svg.min.js"></script>
                <script   src="http://code.jquery.com/jquery-2.2.4.min.js"   integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="   crossorigin="anonymous"></script>
                <script>
$(document).ready(function() {
        jQuery.get('Arctic_big.svg', function(data) {
                var draw = SVG('svgimage').size(300,300);
                var svg = new XMLSerializer().serializeToString(data);
                var rect = draw.svg(svg);
        });
});
                </script>
        </header>
        <body>
                <div style="width:100%" id="svgimage"></div>
        </body>
</html>
```

Arctic_big.svg: https://commons.wikimedia.org/wiki/File:Arctic_big.svg#/media/File:Arctic_big.svg

It draws the svg file in the browser. However with another SVG file such as the one hosted here: https://pastebin.com/Cns1uJ6i it draws nothing. 

The html rendered shows no paths/objects

`<svg id="SvgjsSvg1001" width="2" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0;"><defs id="SvgjsDefs1002"></defs><polyline id="SvgjsPolyline1003" points="0,0"></polyline><path id="SvgjsPath1004" d="M0 0 "></path></svg>`

I conclude that there must be something about the format differences between the two svg files. For instance if you look at the paths of the non-working svg, the coordinate system is pretty large. Im not clear on what exactly would case this issue. Any advice?

**Comment by Fuzzyma** [comment]
Could be that the cordinates rae to big to handle for the browser: `viewBox="662.5 375 196812.5 55975`.
Also try to strip away the `<?xml version="1.0" encoding="UTF-8"?>`

**Comment by saivan** [comment]
It could also be that the svg just got rejected by your network. Check that you actually have the svg elements in your developer tools panel. Otherwise, post a minimal example (jsbin or codepen) and I'd be happy to look into it for you :)

**Comment by Fuzzyma** [comment]
I will close this for now. If you have any new information or want to discuss it further feel free to write.
