### ISSUE TITLE
looking for a solution about animation with both rotating and moving

### ISSUE THREAD

**Issue by coolhihi** [svgdotjs/svg.js#822]
I make an [demo](https://jsfiddle.net/k066t1uk/9/) to make a ball rotating in the pipe.
`ball.rotate` and `ball.center` work well.
but when I use them both. the ball's center seem chaotic...

**Comment by Fuzzyma** [comment]
You are dealing with groups. Understand that groups are no shapes. Just a grouping of elements. Similar to what you get when you select multiple things in photoshop. You can only transform it (move the whole selection, rotate it, and so in). So by calling `center` on a group, you translate it.
Next thing to know is, that svg.js tries to do absolute transformation - which almost always goes wrong.
When you need reliable results you need to stack the transformations on each other. So the translation you do with center has to be relative.

Here is your now working example: https://jsfiddle.net/Fuzzy/k066t1uk/16/

**Comment by Fuzzyma** [comment]
Are you mind when we use your pen in our demos?

**Comment by coolhihi** [comment]
@Fuzzyma Thank you! your explain help me much.

**Comment by coolhihi** [comment]
@Fuzzyma of couse not mind.

**Comment by Fuzzyma** [comment]
Thanks!

**Comment by coolhihi** [comment]
@Fuzzyma I'm sorry to bother you again. I have a question.
after `ball.untransform()`, the ball back to left top of container,
then why use `p.x` and `p.y` as the `cx` and `cy` to rotate?
why not `wHalf` and `hHalf`?
i try to use `.transform({rotation: eased * finalDeg, cx: wHalf, cy: hHalf})`, it works well if i comment the next `.transform`.
but it didn't work when I go on to use `.transform` to move it.
why the secord action make the first action failed?

**Comment by coolhihi** [comment]
here might be the simplest code
```
ball
  .untransform()
  .center(p.x, p.y)
  .transform({rotation: eased * finalDeg})
```

**Comment by Fuzzyma** [comment]
When you want to do it that way you have to switch both transformations as seen here: https://jsfiddle.net/Fuzzy/k066t1uk/20/

The reason is: When you do a rotation around a specifc spot what happens is basically that:
 - translate the object by the negative amount specified with cx and cy
 - rotate it around the origin (which is 0,0)
 - translate it back using cx and cy

So when you first rotate and then translate, you translate it by negative cx and cy, rotate it, translate it back, followed by your second tansformation.

When you do translation first, you can then drop the translated part in the rotation.

**Comment by Fuzzyma** [comment]
Make sure to pass the relative flag in the transformation. It might work here but you really want to be save with this. Plus: its faster doing it relative.

But yes - that code is basically the same. When you dont pass cx and cy it automatically takes the center.

Great - so as you can see - so many ways to do it :D. Always helps to get an insight into the library^^

**Comment by coolhihi** [comment]
@Fuzzyma I got it! Thanks again!

**Comment by echolove38** [comment]
> You are dealing with groups. Understand that groups are no shapes. Just a grouping of elements. Similar to what you get when you select multiple things in photoshop. You can only transform it (move the whole selection, rotate it, and so in). So by calling `center` on a group, you translate it. Next thing to know is, that svg.js tries to do absolute transformation - which almost always goes wrong. When you need reliable results you need to stack the transformations on each other. So the translation you do with center has to be relative.
> 
> Here is your now working example: https://jsfiddle.net/Fuzzy/k066t1uk/16/

hi, can u help me for my case, move and rotate together. 
demo url: https://codepen.io/echolove38/pen/jOxoQpK
