### ISSUE TITLE
Rotation not working

### ISSUE THREAD

**Issue by chadsaun** [svgdotjs/svg.js#825]
See [this jsFiddle](https://jsfiddle.net/chadsaun/4oaeL0dv/49/). Just click the button to place the image which is suppose to resize it down, and then rotate it.

The SVG that is inserted gets resized, but not rotated. Why not? I can see the transform attribute was applied.

```
$('#placeImg').on('click', () => {
    draw.svg(svg)
    let g = SVG.get('graphic')
    g.size(50)
    g.rotate(45)
})
```

**Comment by Fuzzyma** [comment]
It is not allowed to transform `<svg>`-elements in any way. When you need transformations (such as rotate), you need to put it into a group
