### ISSUE TITLE
Clarify the flatten/ungroup method

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#826]
At the moment, when you call flatten, all children and their children gets flattend so you end up with elements on one level.
However, flatten was named ungroup before and I feel like it should only break up ONE level. You ungroup elements you grouped before.

So when you start with this:

```html
<svg>
 <g>
  <rect></rect>
  <circle></circle>
  <g>
   <line></line>
   <circle></circle>
  </g>
 </g>
</svg>
```

I would (when calling `ungroup`) expect it to come out as:

```html
<svg>
 <rect></rect>
 <circle></circle>
 <g>
  <line></line>
  <circle></circle>
 </g>
</svg>
```

But when calling `flatten` I would expect this:

```html
<svg>
 <rect></rect>
 <circle></circle>
 <line></line>
 <circle></circle>
</svg>
```

Our implementation currently does the last. But I think we should mak it 2 seperate methods. Ungroup for REAL ungrouping and flatten for REAL flattening.

**Comment by wout** [comment]
Agree completely.
