### ISSUE TITLE
svg.js doesn't work with Server Side Rendering

### ISSUE THREAD

**Issue by mpro7** [svgdotjs/svg.js#832]
The project base on the Angular 4+ framework with SSR (Angular Universal).

While running ` npm run build:dynamic && npm run serve:dynamic` tasks I've got the error:

> TypeError: Cannot read property 'createElementsNS` of undefined

![screenshot_5](https://user-images.githubusercontent.com/29251288/37710889-56aec7f8-2d0f-11e8-8e82-2d08b6775262.jpg)

Here is the code where it stops:

```
// Svg support test
SVG.supported = (function() {
  return !! document.createElementNS &&
         !! document.createElementNS(SVG.ns,'svg').createSVGRect
})()

// Don't bother to continue if SVG is not supported
if (!SVG.supported) return false
```

Do you know any solution to make it work?

**Comment by Fuzzyma** [comment]
Obviously the library you use does not support SVG. Because that's exact the place where it checks for svg support. You can try to get svgdom up and running which gives you a Dom to work with on the server

**Comment by mpro7** [comment]
Do you mean [svgdom](https://github.com/svgdotjs/svgdom)? Thanks for the hint, I'll check this out.

**Comment by Fuzzyma** [comment]
Yes exactly

**Comment by dotnetCarpenter** [comment]
Solved by using [svgdom](https://github.com/svgdotjs/svgdom)...
