### ISSUE TITLE
Can't make it work with existing svg

### ISSUE THREAD

**Issue by Bobz-zg** [svgdotjs/svg.js#833]
Hi,

I cannot make this work properly, or this works but doesn't work like I expected:
https://codepen.io/bobz-zg/pen/LdyXBe

When I try to click on some area on the map, instead of change fill color I get nothing.
Actually svgjs triggers 'create' as you can see in console with inspector.

Not sure what am I doing wrong here?
I would expect that the area will change fill color?

Thanks in advanced

BR
V

**Comment by Fuzzyma** [comment]
You want to use `SVG.get(id)`  instead of `SVG(id)` when you want to use an existing SVG. Also: This kind of questions belong to stackoverflow. We have a dedicated tag there and we surely answer all questions there. It is even far more likely that you get a fast answer because other people will be helping, too

**Comment by Bobz-zg** [comment]
Right, I'm sorry thanks.
But even with get, I still can't make it work even with get. I've tried different ways but none of them turned out to be working.

**Comment by Fuzzyma** [comment]
I saw you got an answer on stackoverflow. Is it sufficient for you? If yes, please close the issue. Otherwise you can head to out gitter chat to get in contact with us

**Comment by Bobz-zg** [comment]
Right, sorry, busy days.
I think the real problem was that if svg elements have ‘fill: none;’ set in css they will not trigger events.

**Comment by Fuzzyma** [comment]
Oh - thats not entierly correct. Which events are fired depends on the pointer-events property.
You can set those pointer-events to none and the shape wont fire any events. But when you set it to e.g. `fill` it will fire when the mouse is in ´the fill area. Take a look here: https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events
