### ISSUE TITLE
Call to defs() results in TypeError in IE11/Edge

### ISSUE THREAD

**Issue by SteveGZr** [svgdotjs/svg.js#834]
When I try to call defs() I get a TypeError, but the problem only occurs in IE11 / MS Edge: 
`
Cannot read property 'getElementsByTagName' of undefined
`

Here's what I'm doing:

`  278     const doc = (new DOMParser()).parseFromString(someSvgString, 'image/svg+xml');`
`  279     const svg = SVG(doc.firstElementChild as HTMLElement);`
`  280                                                                      `
`  281     // Collect defs and add to own defs`
`  282     const targetSvg = this.element.doc();`
`  283     const targetDefs = targetSvg.defs();`
`  284                                                                      `
`  285     for (const def of svg.defs().children()) {`
`  286        def.addTo(targetDefs);`
` 287     }`

The problem is the call of `defs()` in line 285.
I looked into your code in src/doc.js and it seems that line 44 is the problem. But I don't understand why `this.node` is undefined when called in IE11 / MS Edge
`   38   , defs: function() {`
`   39       if (!this._defs) {`
`   40         var defs`
`   41`
`   42         // Find or create a defs element in this instance`
`   43         console.log(this.node);`
`   44         if (defs = this.node.getElementsByTagName('defs')[0])`
`   45           this._defs = SVG.adopt(defs)`
`   46         else...`

**Comment by Fuzzyma** [comment]
I am not sure how well the Domparser works with svg.js. You basically create a document fragment outside of the real Dom. Svg.js relies on the svg document being in the Dom at many points. Maybe that comes into your way here. However you reported that it works in all other browsers so this can't be really the case.

Best option would be to tap into trough it with the debugger I guess.
Do you kind creating a minimal example fiddle for this on jsfiddle?

**Comment by SteveGZr** [comment]
Here's a minimal example fiddle, which works fine in Firefox, Chrome and Vivaldi but throws the mentioned TypeError in IE11 / MS Edge:

https://jsfiddle.net/v2k47Ldh/32/
