### ISSUE TITLE
npm is listing 2.6.2 as most recent version not 2.6.4

### ISSUE THREAD

**Issue by mark-sivill-splunk** [svgdotjs/svg.js#835]
When trying to do
`npm install svgjs@2.6.4`
an error including
 `version not found: svgjs@2.6.4`
is returned.

`npm install svgjs@2.6.2`
works fine.

From looking at the github repository 2.6.4 appears to be the most recent version available.

**Comment by Fuzzyma** [comment]
The correct library name is svg.js not svgjs. It could happen that this second (unwanted) name is not always up to date.

**Comment by mark-sivill-splunk** [comment]
Thank you just tested with svg.js not svgjs and all work perfectly. Thanks for the quick response.
