### ISSUE TITLE
Documentation clarification: circle() diameter or radius

### ISSUE THREAD

**Issue by Zythyr** [svgdotjs/svg.js#836]
Documentation for circle() needs clarification: http://svgjs.com/elements/#svg-circle 

The document says 

> The only argument necessary for a circle is the diameter:
> var circle = draw.circle(100)

When creating the circle element, is the argument the diameter or the radius? I think the documentation accidentally mentioned diameter instead of radius. The standard way to define a circle in SVG is by the radius: https://developer.mozilla.org/en-US/docs/Web/SVG/Element/circle

**Comment by Fuzzyma** [comment]
The documentation is correct. You pass the diameter not the radius
