### ISSUE TITLE
Source code for documentation for offiline use?

### ISSUE THREAD

**Issue by Zythyr** [svgdotjs/svg.js#837]
Is there a way we can download the SVG.js documentation for offline use? Or is there a way to make the documentation contributeable to so we can also submit improvements to the documentation?

**Comment by Fuzzyma** [comment]
Not that i can think of. You can Ofc just grab all pages of svgjs.com. There are tools out there to do that.
Another option would be to check out an older version of svg.js where the docs were in the Readme and use the Readme as docs

**Comment by aristath** [comment]
All docs for svg.js are on https://github.com/svgdotjs/svgdotjs.github.io
You can just fork it and submit PRs there :)

**Comment by Fuzzyma** [comment]
Oh right - I feel like I should haven known that :D

**Comment by Zythyr** [comment]
Thanks! Issue resolved :)
