### ISSUE TITLE
Vertical alignment of text, produces different results in Firefox vs Chrome

### ISSUE THREAD

**Issue by behrangsa** [svgdotjs/svg.js#842]
I have two examples in [this link](https://jsbin.com/ciyileg/14/edit?html,js,output).

In the first example, I am vertically and horizontally aligning two rectangles and all is working as expected:

![screenshot from 2018-04-02 14-44-07](https://user-images.githubusercontent.com/18451/38183526-55244da8-3684-11e8-922a-b188e361c51c.png)

In the second example, I am trying to do the same, but instead of two rectangle, I am vertically aligning a text node inside a rectangle.

When `dominant-baseline` is not set, Firefox and Chrome produces the following different results respectively:

_Firefox_:

![Firefox](https://user-images.githubusercontent.com/18451/38183568-b19fbdba-3684-11e8-9994-08a79587e5b1.png)

_Chrome_:
![Chrome](https://user-images.githubusercontent.com/18451/38183573-bd675edc-3684-11e8-907f-a0ec50279787.png)

When I set the `dominant-baseline` to `text-after-edge`, Firefox properly aligns the text in the middle of the rectangle, but Chrome still fails to vertically align the text:

_Firefox_:

![Firefox - text-after-edge](https://user-images.githubusercontent.com/18451/38183608-1b459d48-3685-11e8-82cf-d905d6b7dc3a.png)

_Chrome_:

![Chrome - text-after-edge](https://user-images.githubusercontent.com/18451/38183613-1f97f1ac-3685-11e8-8f36-c1a092f3758f.png)

Is this a bug in SVG.js or am I missing something here?

**Comment by Fuzzyma** [comment]
Baseline support in browsers is terrible. Bbox calculation of text differs too among browsers. It's not that easy to handle text in svg

**Comment by behrangsa** [comment]
Just FYI, I could center the text in a cross-browser compatible way using the `center` method: https://jsfiddle.net/behrangsa/vzLmc0jo/

**Comment by Fuzzyma** [comment]
I thought this issue was about vertical center and not horizontal center?

**Comment by behrangsa** [comment]
After closer inspection I noticed the text is still not precisely aligned vertically, but the method using `center` leads to better results.
