### ISSUE TITLE
May I run more than one animates in the same time ？

### ISSUE THREAD

**Issue by binggege** [svgdotjs/svg.js#846]
My code
``` javascript
const animate_1 = react.animate(1000, '>', 0).transform({ rotation: 90 });
const animate_2 = react.animate(3000, '>', 0).transform({ scaleX: 0.8 });
```
Present performance：

animate_2 will run when animate_1 is finished 

but i'd like animate_1 & animate_2 run in the same time

I can't merge function，because i have different config in `animate`

**Comment by binggege** [comment]
@Fuzzyma  thanks for your answer

It's good if @saivan  can help me to give some better shots . 

```
Animating 2 different attributes at the same time is totally OK 
```
Are you sure?  I have a test ,It's not work,  but it's ok to different element .
I was trying to  add  some config to animate
``` javascript
now:
ele.animate(duration, ease, delay);
plan:
ele.animate(duration, ease, delay, startCurrently);
```
I can past my animate schema to you ：
``` json
{
  "id": "48",
  "name": "anim",
  "duration": 3000,
  "blocks": [
      {
          "id": "48289",
          "layerId": "46",
          "propertyName": "scaleX",
          "startTime": 0,
          "endTime": 3000,
          "interpolator": "LINEAR",
          "type": "number",
          "fromValue": 1,
          "toValue": 0.2
      },
      {
          "id": "48290",
          "layerId": "46",
          "propertyName": "scaleY",
          "startTime": 0,
          "endTime": 100,
          "interpolator": "LINEAR",
          "type": "number",
          "fromValue": 1,
          "toValue": 0.2
      },
      {
        "id": "28",
        "layerId": "47",
        "propertyName": "strokeColor",
        "startTime": 0,
        "endTime": 1000,
        "interpolator": "LINEAR",
        "type": "color",
        "fromValue": "#ff0000",
        "toValue": "#0000ff"
    },
    {
        "id": "29",
        "layerId": "47",
        "propertyName": "fillColor",
        "startTime": 0,
        "endTime": 400,
        "interpolator": "LINEAR",
        "type": "color",
        "fromValue": "#000",
        "toValue": "#ff0000"
    }
  ]
}
```

I was trying to create a platform to create icon animation, the user is web designer，so focus on my problem please.

**Comment by saivan** [comment]
For now, the easiest way you could get around this is to put the element into a group and then just rotate the group while you scale the element independently. This should work fine. Is that a possibility?

**Comment by binggege** [comment]
transform attributes is  ok,  but no work to path attributes ,like strokeColor 、fillColor ...

**Comment by Fuzzyma** [comment]
Not at PC and writing from phone so not sure if this works but try the following:

```js
var element = canvas.rect(100,100).move(100,100)

var fx1 = new SVG.FX(element).animate(1000).move(200,200)

var fx2 = new SVG.FX(element).animate(3000).size(500,500)
```

**Comment by saivan** [comment]
It's not too difficult at all. Just try to get your element into its own group first (the documentation can help you with that). After that, you can scale the group and rotate the element (or the other way around). Give it a go and send me a pen if you get stuck :) alternatively, @fuzzymas method above should work too for simple shapes as well.

**Comment by binggege** [comment]
ok，I will have a try. thank you @Fuzzyma  @saivan 

I hope to add this config in v 3.0

I'd like to be a tester for v 3.0

**Comment by Fuzzyma** [comment]
For transformations you go with multiple groups and for multiple attributes you go with the solution provided above. Should work.

Please report back. We will shortly rework the fx module and any input is highly appreciated!

**Comment by binggege** [comment]
@saivan  @Fuzzyma  , For transformations go with multiple groups will change the performance,
I have test, you can have a try, so this problem has not been solved.

**Comment by saivan** [comment]
Can you send me a code pen containing your code. Also. Which program are you using there?

**Comment by binggege** [comment]
[lively.zip](https://github.com/svgdotjs/svg.js/files/1892944/lively.zip)

```
npm i
npm start
```

then you can test app.jsx  

try to change the order of  animation.blocks 

![image](https://user-images.githubusercontent.com/5547743/38537793-2149432c-3cc3-11e8-8aa9-7d12187581c4.png)

it have different performance

I want to be the same

**Comment by saivan** [comment]
Sorry, can you try putting the code onto https://codepen.io/
This will avoid me having to install modules to my computer.

**Comment by binggege** [comment]
can you send your email to me , I email my code to you 
my email: 1204363612@qq.com

It's difficult to create my demo to you

**Comment by Fuzzyma** [comment]
If you want to report an issue or help, the first thing is to break down your problem to something which is easy to test and debug so we can review it fast. This is after all an open source project and we are doing this in our spare time.

So please go ahead and create a jsfiddle or codepen or whatever you like so we can help you properly

**Comment by Fuzzyma** [comment]
Creating the g elements is done once and then you can animate forever. It's a fixed cost you pay for doing what you want. It should not in any case harm the animation speed. If so, then only because the browsers slows it down

**Comment by binggege** [comment]
sorry, Speed is not a problem

![image](https://user-images.githubusercontent.com/5547743/38666293-1f287b44-3e71-11e8-968f-83e2265f6bdf.png)

I mean create g elements for every transform animation can't solve my problem. 
because the order of animation decide the order of g element, if you rotate parent g 180 deg, the x-axis of it's child will change ,Then the animation is not what I want.

**Comment by Fuzzyma** [comment]
I don't see any problem with this. You cannot "insert" a new transformation somewhere anyway. It will just jump around and look weird. Transformations are always stacked on top of each other.

**Comment by Fuzzyma** [comment]
Deleted my last comment. Was not useful. You say that your x-axis change when you rotate with a group. First if all: UT doesn't matter if you transform one element alone with all transformations or you take groups for that. The result is always the same.
The x axis  changes in any case. I mean, when you translate something Ofc it is somewhere else after that.
We need to know what you want to achieve. With that in mind we can help you. I think in the end it will be a matter of ordering the transformations correctly

**Comment by binggege** [comment]
download this file and unpack it
[vector (6).shapeshifter.zip](https://github.com/svgdotjs/svg.js/files/1902231/vector.6.shapeshifter.zip)

open https://shapeshifter.design/  and  open the unpack file， try to run this animation , you will find the differences

**Comment by saivan** [comment]
you asked in your original question whether you could run two transformations together and I have shown you how to do that. 

If you want to change the point it's rotating around, you can change the rotation origin easily by just adding the new origin as a parameter. For example, 'item.rotate(30, ox, oy)' where ox and oy are the x and y coordinates of your new rotation origin. 

If you have any other issue beyond that, I think you're going to need to give us a clear explanation of what you expect and also a (working) pen of what you are currently seeing. 

I can't actually view the files you sent me and neither will future people who read this issue if they run into the same problems you did.

**Comment by binggege** [comment]
Ok, thanks. I found a way to solve this problem

**Comment by saivan** [comment]
Awesome!
