### ISSUE TITLE
Not able to get attribute for element using SVG.select

### ISSUE THREAD

**Issue by WillisShek** [svgdotjs/svg.js#848]
I have created a text object in side a svg in html file and reference it using `.select()`. However, when I want to get its attribute such as y using either `.attr("y")` or `.y()`, it just returned `create {members: Array(1)}` in Chrome and Opera, and `Object { members: […] }` in Firefox but not value. Here is some simple code.

Html
```
<svg width="500" height="250" viewBox="0 0 500 250" preserveAspectRatio="xMidYMid meet" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<g stroke-width="2" fill="none" fill-rule="evenodd" font-weight="normal" letter-spacing="3" font-size="120">
		<text id="text_01" x="50%" y=70 text-anchor="middle" dominant-baseline="middle" stroke="#000000">Some Text</text>
	</g>
</svg>
```

Js
```
var text = SVG.select("svg #text_01");
console.log(text.attr('y'));
```

Or you can view it in jsfiddle
[https://jsfiddle.net/cmL2xs8c/1/](https://jsfiddle.net/cmL2xs8c/1/)

Thank you so much for your help.

**Comment by Fuzzyma** [comment]
`select()` does return an SVG.Set which is an object similar to a normal array. You have to get your element from this set first before you can call getter on it. Note, that you can call setter without doing that. The setter then is applied to all elements in the set.

```js
var text = SVG.select("svg #text_01").first();
console.log(text.attr('y'));
```

**Comment by WillisShek** [comment]
Thank you so much.
