### ISSUE TITLE
[element].animate().rotate(n) problem in 4th quote, direction of spin inverted

### ISSUE THREAD

**Issue by yOyOeK1** [svgdotjs/svg.js#853]
Hi !
Really nice lib !
I step on small issue. I'm animating elements by rotating them to specific angle, like needle dials, compass, ...
When I'm trying to rotate element in to 4th quote (more then 270deg) not more then 360deg. Elements are animating int to o posit direction then efficient. 
Example:
sending element to 275 deg. 
sending to 280 deg.  
and instead of doing 5 deg of move its doing :) 365 deg

I'm using @version 2.6.4 of svg.js

**Comment by saivan** [comment]
Do you mind posting a codepen with a minimal example to demonstrate this?
We are currently doing a pretty big rework for 3.0 so this should be fixed pretty soon I hope :)
But for now, just send me a pen and I'll help you fix the problem you're having

**Comment by saivan** [comment]
Sorry to be a pain, but do you mind uploading it to codepen and posting a link

**Comment by yOyOeK1** [comment]
ok I think it's it 
I was not able to make working src for svg.js file from internet.

https://codepen.io/anon/pen/RyxBdM

**Comment by yOyOeK1** [comment]
@Fuzzyma sorry for additional stuff on codepen but it was easy for me to delete all additional staff from my test project and past it there.
Buttons are there to help rotate element and sea the bug.
Entry box is to rotate to deg.

sorry I have suuuuper limited internet access and entering github by it self is a challenge.

**Comment by saivan** [comment]
I have to agree, I don't even get an element when I try to run this

**Comment by Fuzzyma** [comment]
I will close this for now. Feel free to reopen when you have new information available

**Comment by nemish** [comment]
Hey! I've prepared a sandbox with wierd behaviour related to this issue. Can you [take a look](https://codesandbox.io/s/644zv6rynk)?
Input field for rotating angle. Try to enter 170 and then 110. Pay attention to rotation direction. Thank you.

**Comment by Fuzzyma** [comment]
The old 2.x version has issues with transformations. In 3.x we reworked the whole transformation module and made it stable.

For help with 3.x look at the numorous other issues and visit us on gitter

**Comment by nemish** [comment]
Thanks! I see that latest published version on npm is 2.6.2 https://www.npmjs.com/package/svgjs
How can I install latest release from 3.x version?

**Comment by Fuzzyma** [comment]
No, 2.7.1 is the latest 2.x version. However the 3.x versions are released unter the `@svgdotjs` org:
https://www.npmjs.com/search?q=svg.js
