### ISSUE TITLE
Path.length() - Error : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Trnk** [svgdotjs/svg.js#858]
Hi there.

I just started from SVG.js on Node.js and I have an issue to get the length of path involving Arcs...

Working with the exemple path of the doc :

```
var draw = SVG(document.documentElement);
var p = draw.path('M0 0 H50 A20 20 0 1 0 100 50 v25 C50 125 0 85 0 85 z')
console.log("Length:"+p.length());
```
Return systematically:

> G:\Node.js\SVGCalc\node_modules\svgdom\class\Point.js:6
>   create: function(x,y) {
>                   ^
> 
> RangeError: Maximum call stack size exceeded
>     at new create (G:\Node.js\SVGCalc\node_modules\svgdom\class\Point.js:6:19)
>     at new Arc (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:177:15)
>     at create.clone (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:289:14)
>     at create.splitAt (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:274:23)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:261:22)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:269:21)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:269:21)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:269:21)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:269:39)
>     at create.length (G:\Node.js\SVGCalc\node_modules\svgdom\utils\pathUtils.js:269:21)

Do you have an idea of the reason of that ?

Best,
G

**Comment by Fuzzyma** [comment]
Most certainly its a bug in svgdom.
I looked into the code. It dies when it tries to recursively calculate the length of the arc segment.
For some reason this recursion never terminates.

Please look into the code yourself and change the threshold of the break condition:

```js
      if(len1 + len2 - length < 0.00001){ // <-- here
        return len1 + len2
      }
```

Does it work when you have a higher threshold?

**Comment by Trnk** [comment]
Thank for your reply.
I am trying to figure out this code but my Maths level is very bad...

Changing the threshold does not change anything (tried to put it from 0.1 to 0.0000001 by factor 10) and the program bug.

However, changing the "t" value of the "splitAt" by a value <0.5 seems to unlock the process but the returned value is wrong.

```
var ret = this.splitAt(0.5) //<-- at <=0.4 the calculation is able to end
      var len1 = ret[0].p2.sub(ret[0].p1).abs()
      var len2 = ret[1].p2.sub(ret[1].p1).abs()

      if(len1 + len2 - length < 0.00001){ // <-- nothing change
		
        return len1 + len2
      }
      return ret[0].length() + ret[1].length()
```

I ll continue to work on it but my skills are too weak I guess...

**Comment by Fuzzyma** [comment]
This is strange. I honestly would have made me wonder if changing the
threshold would have worked. However, it makes me wonder even more that
changing the split value does change something and it is even more strange
that the result is not correct in the end. I guess i have to look into that
more closely
Am 23.05.2018 19:08 schrieb "Trnk" <notifications@github.com>:

**Comment by Trnk** [comment]
About the result : I did a circle of 8mm to easly calculate the perimeter.

> m 4.1239602,296.88093 a 4.0000005,4.0000005 0 1 0 0,-7.99999 4.0000005,4.0000005 0 1 0 0,7.99999 z

Which should be around 25mm and the result at splitAt(0.4) is 14.86mm.

Thank you for the next. I will update the issue if by chance I can solve it.

**Comment by Trnk** [comment]
Ok. MeaCulpa.

With a threshold >=1 I have a value near the true (24.52/25.13).

So I guess I can continue with that :)
Thank Fuzzyma.

**Comment by Fuzzyma** [comment]
It's a bug anyway so no need to close it :)
Am 23.05.2018 19:32 schrieb "Trnk" <notifications@github.com>:

**Comment by Fuzzyma** [comment]
I found the error. It was a big in the splitAt function which just did crap. I will push a fix soon

**Comment by Fuzzyma** [comment]
fixed in https://github.com/svgdotjs/svgdom/commit/e0a21bc25844677ea190f98a686c3e77df9b69f1

do you need a release?

**Comment by Trnk** [comment]
No need rigth now. I manually edit my file since it is few lines.

Thanks

**Comment by Fuzzyma** [comment]
Cool. Thanks for reporting. Was a huge bug :)
