### ISSUE TITLE
How does it run at  Vue.js?

### ISSUE THREAD

**Issue by Aspire0423** [svgdotjs/svg.js#861]
So sorry to trouble you, my English is poor becouse I'm from China  ~  These months  I learned svg.js and  Vue.js ,  but  I can't run svg.js in vue.  
Here I show  the images  about  my  questions  ,please gave me some  device...

![1527343312 1](https://user-images.githubusercontent.com/37784957/40576958-ae4a8998-6130-11e8-87a7-d7d25f7e6ad4.jpg)

**Comment by Aspire0423** [comment]
`Uncaught TypeError: fs.readFileSync is not a function                                                       index.js?112f:10 
    at Object.eval (index.js?112f:10)
    at eval (index.js:144)
    at Object../node_modules/unicode-properties/index.js (app.js:2877)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)
    at Object.eval (index.js?4575:24)
    at eval (index.js:14921)
    at Object../node_modules/fontkit/index.js (app.js:1988)
    at __webpack_require__ (app.js:679)
    at fn (app.js:89)`

**Comment by Aspire0423** [comment]
`Uncaught TypeError: fs.readFileSync is not a function`   

![1527343493 1](https://user-images.githubusercontent.com/37784957/40577048-b3d728e8-6131-11e8-9c6b-2d465d9be160.jpg)

**Comment by Fuzzyma** [comment]
Why are you using svgdom when you use svg.js in the browser?

**Comment by Aspire0423** [comment]
Could you give me a  vue  project documents? I using svg.js  in vue  can't run in the browser...
Perhaps  I have same misstake?

**Comment by Fuzzyma** [comment]
I don't use vue neither do i a use webpack. So i don't have a document for you. 

But iam pretty sure that your project ends up in the browser so why do you use server side libraries? 

Maybe you want to ask your question on stackoverflow.com.

**Comment by saivan** [comment]
You can just import the SVG.js file directly as a dependency for your project. Just use one of the files in the dist folder here https://github.com/svgdotjs/svg.js/tree/master/dist

**Comment by uebusaito** [comment]
You can just add it as a VueJS plugin

`import svgJS from 'svg.js';

export default {
  install: Vue => {
    Vue.prototype.$svg = svgJS ;
  }
}`

then on your import it to your mainJS file,

then you can call the method anywhere on vue instance, for example `this.$svg.get('elementID')`

**Comment by Aspire0423** [comment]
@uebusaito    Thanks ~   I've tried your method  ,but it has also takeback misstakes  like the picture...
![1527520356 1](https://user-images.githubusercontent.com/37784957/40620781-aa51f536-62cc-11e8-91a6-4b3e2f308802.jpg)

**Comment by Aspire0423** [comment]
@Fuzzyma @saivan @uebusaito Thank you for your help! From three days research, I have successed runing the svg.js into vue.  And I'd like to learn svg from you  in the leater days~~Give you a  赞👍

**Comment by nameszian** [comment]
@Aspire0423 @saivan How does `svg.js` run with `vue.js`? 🙏

**Comment by cafe4it** [comment]
https://blog.carbonteq.com/creating-interactive-map-in-vue-js/

**Comment by YuHao-KitPies** [comment]
I meet the same question. Here is a demo. [https://github.com/YuHao-KitPies/SvgVueDemo](url)
