### ISSUE TITLE
Select group by class name and remove all them with this class.

### ISSUE THREAD

**Issue by ralfger** [svgdotjs/svg.js#865]
Currently to remove group with specific class name, i need to select group by class name and by iterating members, i'm removing each separately. Could we simplify it by select group and remove it?

Best regards Rafael 😄

**Comment by Fuzzyma** [comment]
Whats wrong with `canvas.select('.className').remove()`?

**Comment by ralfger** [comment]
It doesn't work. 

My example:
`  console.warn(this.svg.select('.layer'), 'before remove');
    this.svg.select('.layer').remove();
    console.warn(this.svg.select('.layer'), 'after remove');`
Screen with log:
http://prntscr.com/jrnk1i

**Comment by Fuzzyma** [comment]
Jeah right because SVG.Set has its own remove method.
Well in that case its `canvas.select('.className').each(function () { this.remove() })?` which is only slightly longer
