### ISSUE TITLE
Layout rounding and crisp edges

### ISSUE THREAD

**Issue by SebastianStehle** [svgdotjs/svg.js#868]
Hi, I am about to svg.js for my wireframing application.

I already have a working version in a branch, but I have to deal issues with crisp edges (https://mydraft.cc/). When you draw a rect at rounded values and an uneven stroke width you get blurry borders. Therefore you have to indent the rect by 0.5 pixels in all directions. It works but is a little bit annoying to remember in all places. For shapes I solve it with a custom renderer (https://github.com/athene-wireframes/athene-ui/blob/master/src/wireframes/shapes/utils/paper-renderer.ts#L325), but there are other places where I do rendering.

It would be nice to have a central place that can be overriden where this rounding can be done. It should also be applied to transformations and anything else that effects the position.

https://blogs.msdn.microsoft.com/text/2009/08/27/layout-rounding/

**Comment by saivan** [comment]
We were talking about including an export renderer, but to be honest; I'm finding it very hard to reproduce this problem. Could you perhaps include a screenshot or something?

**Comment by Fuzzyma** [comment]
I had a talk with @SebastianStehle about that and we agreed that such a plugin should not be in the library. Beside that it is really hard to implement and only useful in edge cases.

I think this issed can be closed

**Comment by SebastianStehle** [comment]
In case somebody is looking for a similar solution: This is my my renderer: https://github.com/athene-wireframes/athene-ui/blob/svg-test/src/wireframes/shapes/utils/svg-renderer.ts

**Comment by Fuzzyma** [comment]
wow nice work!
