### ISSUE TITLE
Animation of scale not happening as expected

### ISSUE THREAD

**Issue by heaversm** [svgdotjs/svg.js#871]
# Bug report

I have a group which I am scaling upon creation:

```
scaleGroup = draw.group()
  .scale(1.5)
  .addTo(welcomeSVG.orbitsGroup);
```

Nested in that, I have a group which I am transforming:

```
orbitGroup = draw.group()
    .transform({
        x: 190,
        y: 105,
    })
    .addTo(scaleGroup);
```

Then I am simultaneously animating both of these elements:

```
scaleGroup.animate()
  .scale(1);

orbitGroup.animate()
  .transform({
    x: 150,
    y: 175,
  })
```

The end transform matrix for the scale group (parent) I would expect to be `matrix(1,0,0,1,0,0)`
but instead it is `matrix(1,0,0,1,91,52.5)`

The child, `orbitGroup` has the expected transform: `matrix(1,0,0,1,150,175)`

Any idea why this is happening, and how I ensure the expected transform on the parent?

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

Modify [this fiddle](https://jsfiddle.net/Fuzzy/s06mfv5u/) to demonstrate the problem clearly, just fork it and paste the resulting fiddle in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behaviour you expect?
- What is happening instead?
- What error message are you getting?

**Comment by heaversm** [comment]
Fixed - thanks. I'm a bit confused though as I thought the default origin of all the graphics in the group was at the center of the parent group. Is it because a group has no dimension technically?

**Comment by Fuzzyma** [comment]
When you scale something, its scaled around an origin. svg.js by default scales around teh center of the object. That means:

1. translate the objects center to the origin (which is 0, 0)
2. scale it there
3. translate it back where it was

Because of that, you get a matrix which includes translation. Thats completely normal.
You only get a plain scale matrix (like 2, 0, 0, 2, 0, 0) when you scale around 0, 0.
