### ISSUE TITLE
Bounding box calculations on elements seem inconsistent

### ISSUE THREAD

**Issue by heaversm** [svgdotjs/svg.js#872]
# Bug report

I have a group containing a text with tspans, which I am trying to center within a parent group that contains a circle, but I can't seem to center it in any calculated / dynamic way.

I noticed that the bbox function is giving me a different value when the element is created versus when the animation is running, even though nothing about the size of the element, its children, or its parent is being scaled / sized.

On creation:

```
const text = draw.text((add)=>{
  ...
}).addTo(textPositionGroup)
const groupWidth = textPositionGroup.bbox().width; //returns 91
```

On animation:

```
textGroup.animate({
            delay: 3500
            ease: '>',
            duration: 1500,
        })
            .opacity(1);
console.log(textPositionGroup.bbox().width) //returns 121
```

> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js)**.

## Fiddle

<img width="152" alt="screen shot 2018-06-15 at 8 54 29 am" src="https://user-images.githubusercontent.com/520541/41477680-e0ee8de2-7079-11e8-8387-3da478904d1e.png">

<img width="524" alt="screen shot 2018-06-15 at 8 54 18 am" src="https://user-images.githubusercontent.com/520541/41477745-1c90b6e0-707a-11e8-8bff-c13432f1fa87.png">

Second screenshot shows the width reported from the code upon creation, and then the width by console logging during animation (that width does not change on repeated calls).

Modify [this fiddle](https://jsfiddle.net/Fuzzy/s06mfv5u/) to demonstrate the problem clearly, just fork it and paste the resulting fiddle in your issue. Please make sure this is a **minimal example**, containing only the minimum necessary code to help us troubleshoot your problem.

## Explanation

- What is the behaviour you expect?

Consistent width of bounding box at time of creation as well as during animation.

The text, when not transformed, seems to align its upper left corner to the center of the circle. My presumption is that, given the group's bounding box width, I can center the text by transforming it's X position by negative half its width (`transform({x: -(textGroup.bbox().width/2)});`), or by calculating the width of the circle, calculating the width of the text group, and transforming the group by half the width of the circle minus the text group's respective widths. Neither works.

- What is happening instead?

Differing widths and text that is slightly off center when transformed.

<img width="202" alt="screen shot 2018-06-15 at 9 00 16 am" src="https://user-images.githubusercontent.com/520541/41477932-b9e32f36-707a-11e8-9a3b-a15159bd5c08.png">

- What error message are you getting?

None

**Comment by heaversm** [comment]
Just an update - the only way I have been able to resolve this so far is to wait for the animations on the parents to finish, and then position the text using the same calculations listed above - but it means that I cannot perform any animations on the text until after parent animations are complete, which is not desired.

**Comment by Fuzzyma** [comment]
I honestly dont get the problem. Can you please provide a fiddle which shows that issue?

**Comment by Fuzzyma** [comment]
Closing due to no feedback
