### ISSUE TITLE
ES6 Compatability

### ISSUE THREAD

**Issue by saivan** [svgdotjs/svg.js#875]
Hopefully you can see, we've been quite hard at work on developing some awesome new features; that we think you're going to love, to svg.js.

As discussed with @Fuzzyma, this issue is supposed to open the gate for es6 compatibility (I'm publicly declaring that I'm going to get him for this one 😜). We were thinking about modifying the build system a little bit to bring this library up to date with what is going on throughout the javascript ecosystem.

This issue is meant to allow the rest of you to get involved as well, and chime in on where you think changes need to be made!

These are the changes we (loosely) plan to make:
- [x] Modularise the library to make it easy for you to tree shake out the parts that you don't need
- [ ] Make plugin integration painless (hopefully just an npm-install and import statement somewhere)
- [x] Using rollup to bundle the library up into parts such as 'svgjs-core', 'svgjs-element', etc...
- [x] Update some key parts of the code to es6
- [ ] Provide builds for web browsers that target 99% of the features supported by users using babel's env plugin.

If you have any suggestions or better ideas, please join in :)

**Comment by saivan** [comment]
Okay, we merged this into the 3.0.0 branch; so can we close it yet @Fuzzyma ?

**Comment by Fuzzyma** [comment]
Well - I couldnt check all the boxes yet :D. Thats why I let it open. Sure we are es6, but the plugins are not. And the builds arent working perfectly too. So - your call!

**Comment by saivan** [comment]
This is done with 3.0
