### ISSUE TITLE
animate -> at() not working as expected

### ISSUE THREAD

**Issue by qwertasyx** [svgdotjs/svg.js#876]
Hello,

did i misinterp the use of at()? 

When the animations is running the at() is working since the situation is not 'null', i feel like the '=' is not working like its supposed to.

minimal example:
https://jsfiddle.net/qwertasyx/nawpkyvx/

expectation:
Button Click should move the rect to somewhere between  50,50 -> 200,200

error:
 Cannot read property 'duration' of null

docs:
http://svgjs.com/animating/#at

**Comment by Fuzzyma** [comment]
the `=` parameter is not impemented right now. It was dropped by accident in an earlier release but while in the process of implementing it back, we found, that it really overcomplicates things.

To have the behavior which you desire you can simply do: 

```js
var canvas = SVG('canvas')

// create your example here
var animation = canvas.rect(10, 10).move(50, 50).animate(1000).move(200, 200).pause()

document.getElementById("test").addEventListener("click", myFunction);
function myFunction() {  
  animation.at(0.5)
}
```

In this case the 1000 is just a number. It would work with every one.

**Comment by qwertasyx** [comment]
ok, good to know, this was also my workaround for now :).
