### ISSUE TITLE
Inconsistent .bbox() of hidden elements

### ISSUE THREAD

**Issue by 13djwright** [svgdotjs/svg.js#877]
# Bug report

## Fiddle
Open in both Firefox and Chrome/Edge/Safari to test.
[Fiddle Link](https://jsfiddle.net/13djwright/kxe6oqj0/)

## Explanation

- What is the behavior you expect?

To get the same bounding box from different browsers on elements that are hidden via .hide().

- What is happening instead?

I cannot seem to get a consistent example showing the few differences I have noticed with the .bbox() method in different browsers. In the current fiddle, Firefox is the only browser that calculates the bbox of the hidden element. I have come across a case where Safari and Firefox did not calculate it, but Chrome and Edge did.

- What error message are you getting?

There are no errors reported. I believe that I have seen the opposite also occur where Chrome and Edge are able to return the bounding box but Firefox and Safari do not, I just couldn't get that to show in the fiddle.

**Comment by Fuzzyma** [comment]
Getting bboxes of hidden elements is generally a bad idea.
Chrome might give you an empty box, Firefox just throws an error.
We worked around that in the library by cloning the hidden element into the dom and getting the bbox of it, when the call to the original element failed.
But when there was no error, we do not catch it.

So in short: Browser dont bother giving correct bboxes on hidden elements (not even in defs) so dont do it.

We do not check for empty boxes. Maybe thats worth catching, too. Might fix this problem.

**Comment by 13djwright** [comment]
Yea, it's no problem for me to just use bbox's of visible elements, I just wasn't sure if it was intended or not. 
Appreciate the quick response.
