### ISSUE TITLE
Does SVG.js support entities and internal references within SVG

### ISSUE THREAD

**Issue by williamBurgeson** [svgdotjs/svg.js#884]
I have an SVG file which is generated externally which I attempted to import using the SVG.svg(...) function. The styles and transforms defined within the SVG code are held as entity references, the references being defined at the top of the file, outside the svg tag but within an xml outer tag.

When attempting to load the document (as a string arg), the load fails.

**Comment by Fuzzyma** [comment]
We import svg by setting the inner html of a temporary dom element. xml does not work there. Thats  why this does not work. We have to remain the balance between perfect and maintainable (and supported) implementation. To solve your usecase we would need to use an xmlparser. However, svg.js is extendable so if you need that feature, you can implement it by yourself by overwriting the svg method on SVG.Element.

**Comment by saivan** [comment]
I'll close this, if you need any more help; let us know. Hope it all worked out well for you :)
