### ISSUE TITLE
Does SVG.js support multiple SVG documents in one HTML document?

### ISSUE THREAD

**Issue by williamBurgeson** [svgdotjs/svg.js#886]
From looking at the documentation, you instantiate the SVG "object" by calling `SVG([element_id])`, which returns an SVG doc. However, I note that to get an item within the SVG document you need to call `SVG.get([item_id])` rather than `doc.get([item_id])` - doc being the variable name of the returned SVG document in this case.

Also, when I type SVG in the console, it shows that the function is defined as 
```
ƒ (element) {
  if (SVG.supported) {
    element = new SVG.Doc(element)

    if(!SVG.parser.draw)
      SVG.prepare()

    return element
  }
}
```
which says to me that the doc returned is indeed a singleton and multiple SVGs are not supported.

Could somebody confirm the situation with this?

**Comment by Fuzzyma** [comment]
Thats wrong. As you can see in the code you posted, a new SVG.Doc is created and returned for everytime you call the function. Its totally fine to create multiple instances by calling SVG with different ids. Or you use the helper function which you know already `SVG.get()` or `SVG.select()`

**Comment by Fuzzyma** [comment]
The ids of one page are unique. They are generated by svgs id function which you can simply override if you want to. However, svg.js already ensures, that **NEW** generated content has a unique id. It does not account for code generated by the server. There you have to take care of that yourself

**Comment by Fuzzyma** [comment]
The ids of one page are unique. They are generated by svgs id function which you can simply override if you want to. However, svg.js already ensures, that **NEW** generated content has a unique id. It does not account for code generated by the server. There you have to take care of that yourself
