### ISSUE TITLE
Incorrect TypeScript declaration for Element.clone() function

### ISSUE THREAD

**Issue by edmundmaruhn** [svgdotjs/svg.js#887]
# Bug report

The `Element.clone()` function is incorrectly declared in that it does not allow for an optional parent as target element when used in TypeScript.

## Fiddle
Not applicable, because this is not a runtime problem but a compilation issue and jsfiddle seems to be fine with the code. However here is a [fiddle](https://jsfiddle.net/4fkv2uj0/28/) even if it does not add any value to the problem.

## Explanation

- What is the behaviour you expect?
The `Element.clone()` function accepts an optional parent to clone into when used in TypeScript.

- What is happening instead?
Getting a compilation error when trying to pass a parent element to the function.

- What error message are you getting?
**TS2554: Expected 0 arguments, but got 1.**

## Suggested fix
This is pretty simple. Change the declarations file `svg.js.d.ts` at line 250 (currently on master branch) to `clone(parent?: Parent): Element`

**Comment by Fuzzyma** [comment]
Please submit a pull request so that we can merge this in
