### ISSUE TITLE
How to scale externally imported svg

### ISSUE THREAD

**Issue by midnight1994** [svgdotjs/svg.js#889]
I would like to ask, if I introduce an external svg file via the draw.svg() method, how can I scale it? After I get the newly imported svg element with the get() method, I use the selectize() and resize() methods to scale it, but the result is not what I want. How can I scale this newly imported svg friendly? Thank you

**Comment by midnight1994** [comment]
Thanks for your answer, yes, I want to scale it manually, I tried using the svg.panzoom.js plugin, but when I import multiple external svgs they will scale at the same time. I just want to import any imported graphics and manually scale them. If svg can't be scaled, then I can put the path in the external svg into a new <g></g> to zoom. ? Is there no other way to fulfill my needs?

**Comment by Fuzzyma** [comment]
I dont think so. But svg.js is very extendable. You can come up with your own plugin for your issue and open source it!

**Comment by saivan** [comment]
Can you make a quick sketch of what exactly you're after. I'm not completely sure I understand what your intention is.

**Comment by saivan** [comment]
I'll close this due to inactivity, if you have any more input we will be happy to help you out :)
