### ISSUE TITLE
modify svg paths without translates

### ISSUE THREAD

**Issue by villanus** [svgdotjs/svg.js#890]
Hi.
Is it possible to use the following to recalculate svg paths instead of css translations ?
https://github.com/fontello/svgpath

Or does svg.js have this functionality now?

**Comment by saivan** [comment]
Questions like this should be directed to stackoverflow. If you read the [docs](svgjs.com) you should be able to get answers to these sorts of questions. [This plugin for svg.js](https://github.com/svgdotjs/svg.pathmorphing.js) should be able to do most of what you need, if not; let me know with a little more information about what you're trying to achieve :).

I'm going to close this for now unless there is a specific issue you need help with.
