### ISSUE TITLE
Cannot Clipping an image

### ISSUE THREAD

**Issue by barraaaa** [svgdotjs/svg.js#891]
I tried to do clippath using images, but my image didn't appear

**Comment by barraaaa** [comment]
![untitled-2](https://user-images.githubusercontent.com/42228561/43877420-e03b74d0-9bc3-11e8-93fe-6e833c5af042.jpg)

**Comment by barraaaa** [comment]
Here's my code

var draw = SVG('svgDiv');
  var rect = draw.polygon('168.5,13 118.5,35 79.5,56 66.5,69 39.5,142 16.5,190 56.5,223 100.5,229 107.5,211 117.5,273 99.5,373 94.5,426 176.5,456 282.5,456 358.5,426 345.5,329 339.5,256 340.5,206 346.5,223 396.5,214 431.5,188 400.5,121 376.5,61 335.5,38 300.5,23 270.5,13 275.5,26 246.5,55 219.5,71 185.5,50 163.5,27')
  rect.stroke('#f06').move(10, 20).fill('#f06')
  rect.stroke({ color: '#f06', width: 4, linecap: 'round', linejoin: 'round' })

  var image = draw.image('1.jpg')

  var clip = draw.clip()
  clip.add(image.center(105, 115).size(150, 150))

  rect.clipWith(clip)

  // or deepSelect
  rect.selectize({deepSelect:true});
  rect.resize();
  draw.viewbox(0, 0, 1100, 1600);

**Comment by barraaaa** [comment]
forget, I've found what I'm looking for
just misunderstanding
Thank you very much

**Comment by benjaminbours** [comment]
I'm facing the same issue, how did you solve it plz?

**Comment by benjaminbours** [comment]
Just for the other to know, you have to clip the image with the shape in order for it to work.

**Comment by adriano-tirloni** [comment]
Still could not make this work, could provide an example?
https://codepen.io/adrianotirloni/pen/poGpeZJ

![image](https://github.com/svgdotjs/svg.js/assets/6390605/5d6ebaba-6393-404e-ad40-410091347477)

**Comment by adriano-tirloni** [comment]
OK, got it.
It's the reverse:

```javascript
var draw = SVG().addTo('body').size(500, 500)

var image = draw.image('https://cdn.img42.com/4b6f5e63ac50c95fe147052d8a4db676.jpeg').size(100, 100).move(150, 50)

var circle = draw.circle(50).fill('#000').center(190, 200).fill("blue")

var rect = draw.rect(200, 200).move(10, 10)

var clip = draw.clip().add(rect)

circle.clipWith(clip)
image.clipWith(clip)
```
