### ISSUE TITLE
SVG.Set add should accept adding another Set

### ISSUE THREAD

**Issue by pjfsilva** [svgdotjs/svg.js#893]
It should be easy to modify the add method so that it checks if input are also a SVG.Set and in that case it adds all the members of that set.

In alternative we could also add a merge method to merge two SVG.Set but I like the first idea better.

**Comment by Fuzzyma** [comment]
Isnt there already a merge for svg box or am i mistaken?

**Comment by pjfsilva** [comment]
yes, for SVG.Box but that is completly different from this request since it applies to SVG.Set, it's just a way of adding a Set to a Set. Merge in this case means take Set A elements, join with Set B elements and return a new Set with A + B.

**Comment by saivan** [comment]
I do agree, this is actually a really sensible thing to do.
