### ISSUE TITLE
The plugins cannot find the global SVG in test environments.

### ISSUE THREAD

**Issue by junedchhipa** [svgdotjs/svg.js#894]
I am using Jest to do unit/integration testing.
In the browser, I do not get the SVG undefined error as it was fixed in this PR https://github.com/svgdotjs/svg.js/pull/883

But while testing, the plugins that rely on SVG.js - it throw the following errors

![screen shot 2018-08-13 at 7 50 56 pm](https://user-images.githubusercontent.com/17950663/44038018-6da01ba6-9f33-11e8-8fab-d1140c0aa9f5.png)

![screen shot 2018-08-13 at 7 59 26 pm](https://user-images.githubusercontent.com/17950663/44038033-73391f90-9f33-11e8-899d-7d25852fc264.png)

Is this related to the same issue https://github.com/svgdotjs/svg.js/issues/767 ?

**Comment by dotnetCarpenter** [comment]
Hi @junedchhipa  - I've been absence from this project for a while but yes, I believe it's related to #767, #659 and #660.

Unfortunately I don't know of any quick fix but as I said, I haven't been involved in this project for a while but do hope to come back and fix this for [version 3](https://github.com/svgdotjs/svg.js/blob/3.0.0/src/svg.js#L5) ;)

On second thought - you might be able to try some of the stuff discussed in #659

**Comment by junedchhipa** [comment]
@dotnetCarpenter Thanks for the quick response.

Tried the options discussed in the threads you mentioned, didn't work out for me.
Eagerly waiting for version 3 then :)
I migrated from SnapSVG as it is not maintained anymore, happy with the switch and glad to see there is still development going on in svg.js. Version 3 gives me hope!

**Comment by junedchhipa** [comment]
Turns out the issue was with Jest / jsdom and not particularly the undefined global SVG

As jsdom doesn't have support with SVG elements, this function was returning false in jest test
```javascript
SVG.supported = (function() {
    !!document.createElementNS &&
     !! document.createElementNS(SVG.ns,'svg').createSVGRect
})()
```

This JSDom pull request https://github.com/jsdom/jsdom/pull/2011 claims to improve support for SVG, but I don't know if it fixes all issues.

**Comment by saivan** [comment]
I'll also chime in for a moment here. Maybe its probably best if you don't mock svg in your tests. Perhaps its better to actually use a headless version of chrome (or just run them straight in the browser with some kind of test runner), if you plan to test code that supports SVG. That way you're not at the mercy of the svg implementation in your mocking library :P Just a suggestion haha

**Comment by junedchhipa** [comment]
@saivan I tried setting `automock: true` in my jest config with no luck.
I decided to use [puppeteer](https://github.com/GoogleChrome/puppeteer) to do the e2e tests later on which gives me a satisfaction that I'm testing the whole thing. A large part of unit tests can still not run - but anyways, I am trying to make the unit tests as much independent as I can.

Thanks for the input!
