### ISSUE TITLE
Add title to text element

### ISSUE THREAD

**Issue by Srinath007sag** [svgdotjs/svg.js#895]
I am not able to add title to text element . tried SVG.Title plugin as well ... No luck

**Comment by saivan** [comment]
Sorry its taken us so long to get to this issue. Since title tags aren't really drawn; I think this was overlooked in the original design of this library. I agree that this is potentially a useful feature; @Fuzzyma  what do you think?

**Comment by Fuzzyma** [comment]
There are a few elements missing in svg.js (title, desc...) but most of them can be easily replicated using the SVG.Bare element. You just go `draw.element('title')` and get back a title element which you can easily fill with the `words()` method. [The docs example about `SVG.Bare` uses title, too](http://svgjs.com/elements/#element-constructor).
So I dont see the need to add it to the core but on the other hand it certainly wouldnt make much of a difference.
