### ISSUE TITLE
svg.js not support "shadow"

### ISSUE THREAD

**Issue by libbGit** [svgdotjs/svg.js#896]
for example:
```js
//if i want to set "fill" for rect. the code as below:
rect.attr({ fill: '#f03' });

//what if i want to set "shadow" for rect, i can't find the "shadow" method.
// rect.shadow()
```

**Comment by Fuzzyma** [comment]
can you please link me to the documentation which states a shadow attribue so we can implement that in svg.js?

**Comment by libbGit** [comment]
[](http://svgjs.com/elements/   )
I think the all elements should have shadow method, such as SVG.rect, SVG.line and so on. then we can call it very convenient.
`var rect = draw.rect(100, 100).shadow(dx,dy,blur,color, opacity)`

**Comment by libbGit** [comment]
link as below:
http://svgjs.com/elements/

**Comment by libbGit** [comment]
I think i have found the solution, it's svg.js plugin, which is svg.filter.js
https://github.com/svgdotjs/svg.filter.js#drop-shadow

Thank you for help

**Comment by saivan** [comment]
Yes, thats right. You're looking for filters. We felt like it wasn't so great to have them as part of the core, because only a select group of users use them :) Be careful if using them with any animations, shadows are quite expensive in svg.
