### ISSUE TITLE
How to scale the multiple paths in <g></g>?

### ISSUE THREAD

**Issue by midnight1994** [svgdotjs/svg.js#897]
Please ask a question. If there are two <path></path> in a <g></g>, how can I scale this whole? I use selectize().resize() on <g></g> but it doesn't work. If you use select().resize() on each <path></path>, it will only work for itself. So, what can I do to achieve overall scaling?

**Comment by midnight1994** [comment]
Structure like this `<g><path></path><path></path></g>`

**Comment by saivan** [comment]
Sorry to be so slow to get back to you on this. But I must admit, I'm trying hard to understand the problem and I don't quite understand what you're trying to achieve. If you want to scale multiple elements, you can just loop through them and scale them individually as you seem to point out.

What is your intended outcome?
What do you want it to look like when you're done.

**Comment by saivan** [comment]
Okay, I'll go ahead and close this for now; when you have more information for us, we will open it back up :)
