### ISSUE TITLE
Change the depth of  objects.

### ISSUE THREAD

**Issue by Greensue** [svgdotjs/svg.js#901]
# Feature request
Hi, here's  the something that I reaaaaaally want:
Changing  the render order of svg objects. Recently, I have  a need to change the order of the objects created using the svg.js, I did't find anything like z-index in css or information about how to change the display order of objects. Now, I could only display the objects in their create order. 

## Example
I have a car and many other objects  in the SVG canvas. When I touched the car, the car should move follow the mouse and display up above all the other things in the canvas. When the car not  be touched, it should be rendered before some objects rendered.
So, I really hope there could be a simple API or function here to change the render oder of the objects in the SVG canvas.

## Need your help
There is only few things about the SVG.js, Maybe there's a mature method to achieve my need, if exist，please let me know, and I will reaaaaaaally appreciate it。

**Comment by Fuzzyma** [comment]
Try front() and back()

**Comment by Greensue** [comment]
You are a genius！！！How could you be so outstanding. How could you create so beautiful words??
"Try front() and back()", so concise and powerful. Thank you man. Thank you very much.
