### ISSUE TITLE
clear() causing memory leaks

### ISSUE THREAD

**Issue by manjiru** [svgdotjs/svg.js#903]
# Bug report
clear() causes memory leak if called on elements that have active animations, or event handlers ( and possibly with css classes added).

## Fiddle
here is a code pen generating 20 random squares and attaching animations to 10 of them, clearing the screen and repeating. Checking the heap you can see DetachedSVGRectElements is ever increasing (10 at a time only as only the ones with animations are left in the Detached tree)

https://codepen.io/manjiru/pen/zJjbMV

## Explanation
- What is the behaviour you expect?
calling draw.clear() should remove completely all elements

- What is happening instead?
elements are being duplicated into the detached tree instead of actually being removed

- What error message are you getting?
none - Memory leak
## Solution

I'm using a wrapper function like this to remove classes, animations, and events, then to flatten all groups, before calling clear. Leaves the Heap clean and leak free. Would be nice if clear() did similar natively.

function killall(draw){
    draw.each(function(i, children) {
		this.removeClass('*')
		this.off()
		this.stop()
	}, true)
	draw.ungroup()
	draw.clear()
}

**Comment by Fuzzyma** [comment]
I doublechecked this issue and came to the concusion, that we dont really have a memory leak here.
Animations can be done on detached elements, too. Thats totally valid and no bad thing.
If you remove the element while animating, the memory gets cleated, when the animation is finished.
However, when you use `loop()` the animation nevere finishes and therefore the element remains in the memory.

The fx module itself cannot know, if its element is not referenced from another point anymore. So it cannot stop automatically.

The best call is, to explicitely stop the animation when you loop infinitely when you plan on removing the element. So your way is in my opinion the correct way.

Should be mentioned in the docs!
