### ISSUE TITLE
<svg> element appended to end of body receives tab focus on IE11

### ISSUE THREAD

**Issue by kalexmills** [svgdotjs/svg.js#908]
# Bug report

There is a well-known IE11 issue regarding SVG elements receiving tab focus. Svg.js currently adds an extra svg tag to the bottom of the body, which receives this focus.

The fix is to add `focusable=false` to the `<svg>` tag with ID `SvgJsSvg1001`. Right now, we are having to wait for the library to inject this DOM and hack this attribute in ourselves. It would be great if users didn't have to do that.

## Fiddle

This behavior should be seen in the minimal example. 

## Explanation

- What is the behaviour you expect?

On IE11, when tabbing away from the last focusable element on the page, the browser should receive the next tab.

- What is happening instead?

An extra tab is needed, because the added `<svg>`  tag is receiving the focus inappropriately.

- What error message are you getting?

None.

**Comment by saivan** [comment]
Ah I see! Thats totally fair! 
Feel free to make a pr for this one, I don't have a working IE distro to test this on,
but I think we can merge this one without too many problems.
