### ISSUE TITLE
Duplicated defs when imported

### ISSUE THREAD

**Issue by vbartusevicius** [svgdotjs/svg.js#910]
# Bug report

In Codesandbox below you can see that importing SVG with `defs` creates duplicated `<defs>` with id `SvgjsDefs1002`:
```xml
<defs id="SvgjsDefs1002"></defs>
<defs id="SvgjsDefs1002">
	<circle id="SvgjsCircle1008" r="10" cx="10" cy="10" stroke="black" stroke-width="2"></circle>
</defs>
```
Furhter investigation showed that empty def tag gets removed when something is added to defs again.

## Fiddle

https://codesandbox.io/s/yky857kym1

**Comment by Fuzzyma** [comment]
According to the specs it is allowed to have multiple defs in one document. However I agree with you that this is mostly not desired. We might want to give an oppurtunity to avoid this...

**Comment by vbartusevicius** [comment]
@Fuzzyma - yes, but suppose their `id` should be different

**Comment by Fuzzyma** [comment]
Oh yes. We dont check for duplicated ids at import at the moment. Thanks for the headsup!

**Comment by Fuzzyma** [comment]
However this can get a problem. Maybe teh code relies on fixed ids in the imported svg so we cannot just replace everything... difficult...

**Comment by Fuzzyma** [comment]
Yes. The reference to the defs is not the problem. I was talking about the more general problem when you start assigning new id's on import.
When you only assign new id's to the defs it will work but there can be a lot of duplicate id's in the imported code. Replacing them could lead to wrong references.

Imagine in your example the targeted element had a duplicate ID and you replaced it on import. All of a sudden you would reference a wrong element
