### ISSUE TITLE
Implement export modifier for SVG.Element.svg()

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#915]
We would like to have export modifiers so the user gets the possibility to change the node before eporting it. This can be useful e.g. for rounding values on a node, filtering or replacing nodes.

The following examples should give you a brief overview what should be possible:

```js
// instance is the svg object and not the node itself
element.svg((instance) => {
  instance.round(2)
})
```

If you want to execute multiple modifier you can call these in your function:

```js
element.svg((instance) => {
  doThis(instance)
  doThat(instance)
})
```

If you want to replace the node with another node you can return this new node:

```js
element.svg((instance=> {
  var newInstance = new SVG.Rect()
  return newInstance 
})
```

If you want to drop this node from exporting you can return false explicitly:

```js
// drops every node
element.svg((instance=> {
  return false
})
```

**Note: Implementation has to be done on the 3.0 branch**
For all questions head over to our gitter chat: https://gitter.im/svgdotjs/svg.js

**Comment by nobuti** [comment]
Picking this, if you don't mind

**Comment by Fuzzyma** [comment]
Sure! Go ahead!
