### ISSUE TITLE
Implement rounding for nodes

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#916]
Sometimes svg.js produces unrounded values like `x="2.999999999999"` or similar which can take a bunch if space in your database when you save them. It also slows down the browser.

Thats why we want to introduce rounding of nodes.

As wout suggested this will work like the following examples:

>```js
>var svg = path.round(2).svg()
>```
>
>Or non-destructively:
>```js
>var clone = path.clone().round(3)
>var svg = clone.svg()
>clone.remove()
>```
>
>We can also provide deep rounding for elements inheriting from SVG.Parent. Something like:
>```js
>nested.round(2, true)
>```

**Note: Implementation has to be done on the 3.0 branch**
For all questions head over to our gitter chat: https://gitter.im/svgdotjs/svg.js

**Comment by JulianJason** [comment]
I'll work on this

**Comment by saivan** [comment]
Feel free to jump on gitter if you need help with anything :)

**Comment by Fuzzyma** [comment]
This was implemented in the latest commit
