### ISSUE TITLE
svgjs.com is not accessible through https

### ISSUE THREAD

**Issue by behrangsa** [svgdotjs/svg.js#918]
There are a handful of static hosting providers that allow you to host static pages on SSL protected domains for free.

I have personally started using Netlify and it is quite good.

**Comment by Fuzzyma** [comment]
We have the problem, that the domain svgjs.com is not ours. So we cannot easily switch hosts. However, we will look into that issue.

But all that beside, svgjs.com serves static content and no private informations are transfered ever. So https is not neccessary. Its only the Browsers who start complaining more and more.

**Comment by Fuzzyma** [comment]
So wout jumped in and solved that issue immediately. Cudos to him!

It can take some time until it takes effect though

**Comment by wout** [comment]
Just noticed some http:// urls are hard-coded in the source. I'll fix that as well.

**Comment by wout** [comment]
It's all fixed now.
