### ISSUE TITLE
(documentation request) update README.md for correctness

### ISSUE THREAD

**Issue by SKalt** [svgdotjs/svg.js#919]
I'd like to update the readme to:
(1) Swap svgdotjs.github.io for svgjs.com, which the former link redirects to.
(2) rename the  `Installation#Node` section to `Installation#Npm` since the section describes installing svg.js via npm, and yarn installs svg.js for node as well.
EDIT: PR created: #920

**Comment by Fuzzyma** [comment]
Thanks!
