### ISSUE TITLE
XMLNS:svgjs attribute is valid XHTML but invalid HTML

### ISSUE THREAD

**Issue by tmb-github** [svgdotjs/svg.js#926]
The attribute `xmlns:svgjs` is only allowed if the document type is XHTML. For HTML documents, that attribute should not appear on SVG elements. Please remove that attribute from SVG elements created by the library, or provide a configuration switch that allows the user to indicate the document type, which in turn triggers the inclusion or exclusion of that attribute. (The default could be HTML to avoid requiring users to employ the configuration switch at all, since most users of this library are presumably creating HTML documents.)

Many thanks!

**Comment by saivan** [comment]
Do you mind linking the documentation on this one for us. I'm struggling to find the name spacing rule you're referencing

**Comment by tmb-github** [comment]
Both https://validator.w3.org/ and https://validator.nu/ report "**Error: Attribute xmlns:svgjs not allowed here.**" and "**Warning: Attribute with the local name xmlns:svgjs is not serializable as XML 1.0.**" when I attempt to validate this code, which is generated with svg.js:

`<!doctype html>`
`<html lang="en-us">`
`<head>`
`<meta charset="utf-8">`
`<title>Test</title>`
`</head>`
`<body>`
`<div id="drawing">`
    `<svg id="SvgjsSvg1006" width="300" height="300" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs">`
        `<defs id="SvgjsDefs1007"></defs>`
        `<rect id="SvgjsRect1008" width="100" height="100" fill="#ff0066"></rect>`
    `</svg>`
    `<svg id="SvgjsSvg1001" width="2" height="0" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs" style="overflow: hidden; top: -100%; left: -100%; position: absolute; opacity: 0;">`
        `<defs id="SvgjsDefs1002"></defs>`
        `<polyline id="SvgjsPolyline1003" points="0,0"></polyline>`
        `<path id="SvgjsPath1004" d="M0 0 "></path>`
    `</svg>`
`</div>`
`</body>`
`</html>`

Notice that it validates the **xmlns** and **xmlns:xlink** attributes but reports the custom namespace **xmlns:svgjs** as invalid. Apparently, custom namespaces are only valid in XHTML documents. I've found documentation stating that they are *valid* in XHTML, but it doesn't explicitly state that they are invalid in HTML; the report by the w3 validator would seem to confirm this. I'll keep looking, but it's _prima facie_ invalid in the face of the w3 validator report.

**Comment by tmb-github** [comment]
Aha! Found it. See the concluding part of section 8.1.2.3 here: https://www.w3.org/TR/html5/syntax.html#attributes-0

See the concluding sentence following the table:

> When a foreign element has one of the namespaced attributes given by the local name and namespace of the first and second cells of a row from the following table, it must be written using the name given by the third cell from the same row.
> 
> Local name | Namespace | Attribute name
> -- | -- | --
> actuate | XLink namespace | xlink:actuate
> arcrole | XLink namespace | xlink:arcrole
> href | XLink namespace | xlink:href
> role | XLink namespace | xlink:role
> show | XLink namespace | xlink:show
> title | XLink namespace | xlink:title
> type | XLink namespace | xlink:type
> base | XML namespace | xml:base
> lang | XML namespace | xml:lang
> space | XML namespace | xml:space
> xmlns | XMLNS namespace | xmlns
> xlink | XMLNS namespace | xmlns:xlink
> 
> No other namespaced attribute can be expressed in the HTML syntax.
> 
>

**Comment by saivan** [comment]
Right, so do you think removing the svgjs namespace makes sense here - if we can just remove that namespace without negative consequences, I'm not against that. @Fuzzyma what do you think?

**Comment by Fuzzyma** [comment]
I started reading up on this when you opened the issue and jeah - it seems liks html allows onl certain "external" namespaces which it can handle by default (making the namespace pointless because it can be handled without it). Didnt know, that the w3c splitted so much from xml, that you cant even define your own namespaces anymore. So I am wondering why we even have `createElementNS` in the first place...

The problem what arises is, that other consumer of our svgs (Incscape, gimp, whatever...) might have a more strict xml parser - because afterall svg is a subset of xml (not like html). And this parser will complain.
In html5 we could just drop the namespace and go with a custom attribute which is allowed in html5 but not in svg. As soon as you export the svg and save it as a file, custom elements become invalid and you need a namespace.

In the specification is stated, that html parsers should be forgiving when encountering bad formed code so I tend to let it where it is because: 

- new browser ignore it
- old webpages serving xhtml need it
- xml parser need it

When it is only about the `xmlns:xlink="http://www.w3.org/1999/xlink"` you could overwrite the namespace function of the SVG.Doc element to get rid of that. Thats at least a quickfix...
Having extra logic to find out in which environment we are is a bit hacky imo

**Comment by tmb-github** [comment]
I have a couple of suggestions. 

First, note that the document declaration may be retrieved with `new XMLSerializer().serializeToString(document.doctype);`

With that info detected by svg.js itself, it would be great to have a configuration object that could optionally be passed to the constructor (e.g., `.constructorProps()`) that would fix the problem under discussion and another issue not yet discussed.

The constructor could:
* Indicate not to include the `xmlns:svgjs` attribute regardless
* Indicate not to include the `xmlns:svgjs` attribute only if the detected doctype is HTML5
* Create a `<title>` element as the first child of the `<svg>` element, which is good/necessary for accessibility, with the text for the title passed in as a parameter, etc.

Currently, I'm having to use a MutationObserver to detect when SVG elements are created and then strip `xmlns:svgjs` attributes from them if present and then add `<title>` elements as first children of those `<svg>` elements. If the svg.js library supported these things via custom constructor props object--which could be expanded to include things not yet considered--it would be much more powerful

**Comment by Fuzzyma** [comment]
It seems like you overcomplicated that a bit. As I said earlier you can just overwrite the namespace function of SVG.Doc. This can be done at the very start of your application. That way, no namespace is added ever.

```js
SVG.extend(SVG.Doc, {
  namespaces: function () {
    return this
      .attr({ xmlns: ns, version: '1.1' })
      .attr('xmlns:xlink', xlink, xmlns)
  }
}
```

Custom constructors are not desiarable. This libraray aims to be as fast as possible. When everyone wants his own constructor property implemented, we couldnt achieve that goal anymore. 
Adding a title to an svg document is as easy a doing `el.element('title').words('mytitle')`. Why would you put something like this into a constructor?

**Comment by tmb-github** [comment]
* Provided that most users of this library are creating HTML5 applications, you should provide an easy way to make the resulting code HTML valid and compliant. Please don't accept the fact that modern browsers can handle the invalidity without a problem. I understand the need for the custom namespace in XHTML, etc., but if most are writing HTML, there needs to be an easy means of ensuring non-compliant attributes are not included.

* `<title>` elements are required for accessibility as the first child of the `<svg>` element. If `<svg>` elements are being rendered *dynamically* within an application, the programmer must employ a `MutationObserver` to detect when an `<svg>` element has been created and then add the `<title>` element. If, on the other hand, svg.js were creating `<title>` elements by default or optionally (with operators for filling in their text, etc.), this would be unnecessary. It would not slow down the code at all.

* I've tried the solution you provided, but I cannot get it to work. Here is a complete, simple HTML that correctly calls and executes two SVG operations, but the `xmlns:svgjs` attributes are still created on the two elements; check the DOM. What have I done wrong here?

`<!DOCTYPE html>`
`<html lang=en-us>`
`<head>`
`	<meta charset=utf-8>`
`	<title>TEST</title>`
`</head>`
`<body>`
`	<div id=drawing>`
`	</div>`
`<script src=https://cdnjs.cloudflare.com/ajax/libs/svg.js/2.6.6/svg.min.js></script>`
`<script>`
`(function () {`
`	'use strict';`
`	SVG.extend(SVG.Doc, {`
`		namespaces: function () {`
`			return this`
`				.attr({xmlns: "http://www.w3.org/2000/svg", version: '1.1'})`
`				.attr('xmlns:xlink', "http://www.w3.org/1999/xlink", "http://www.w3.org/2000/xmlns");`
`		}`
`	});`
`	var draw = new SVG('drawing').size(300, 300);`
`	var rect = draw.rect(100, 100).attr({fill: '#f06'});`
`}());`
`</script>`
`</body>`
`</html>`

**Comment by Fuzzyma** [comment]
Well - as written in my post, its `namespace` not `namespaces`.
Works like a charm: https://jsfiddle.net/c9rm0w7b/

**Comment by Fuzzyma** [comment]
I am not sure why you are not just doing:

```js
SVG.get('idOfSVG').element('title').words('text')
// or
SVG.select('cssSelector').first().element('title').words('text')
```

For the invisiable svg you are not supposed to change that. Not even adding a title to it. It is not for the user. Afaik screenreaders do not even read invisible content.

**Comment by tmb-github** [comment]
I've doubled checked on the screen reader issue, and you're right: so long as it's not displayed, it's not going to be picked up by a screen reader.

On the other hand, using the methods you provide, I cannot add a title as the first child of the <svg> element. Using `.first().element('title').words('text')` on the `<svg>` element itself, for example, I get:

`<svg>`
`<defs></defs>`
`<rect></rect>`
`<title></title>`
`</svg>`

...where the `<title>` is the last child. Applying the same operators to the object returned by the SVG constructor places the `<title>` as the first child of the `<defs>`.

I'm shooting for:

`<svg>`
`<title></title>`
`<defs></defs>`
`<rect></rect>`
`</svg>`

...where the `<title>` is the first child of the `<svg>`.

**Comment by Fuzzyma** [comment]
Now we are at a point where the docs will help you. Just go call `back()` on the element and you are done

**Comment by tmb-github** [comment]
Aha! I didn't realize there was a facility to manipulating the SVG element children like that. For anyone else grappling with this, the solution that works for me is:

`var draw = new SVG('drawing').size(300, 300);`
`var rect = draw.rect(100, 100).attr({fill: '#f06'});`
`draw.element('title').words('Rectangle').back();`

This creates the title element as the first child of the svg element.
