### ISSUE TITLE
npm org and scoping

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#929]
For the 3.0 release I would like to create an npm organisiation so that we can prefix all our packages like `@svgdotjs/svg.js`.
That has several advantages:

- multiple users can be part of an org and can publish packages
- no name clashing with other packages
- every user sees directly which plugin is maintained by us and which not

Having all 3.0 ready plugins published as organisation also makes it easy for the user to know wether a plugin is (already) supported for 3.0.

Opinions? @wout @saivan @dotnetCarpenter

**Comment by saivan** [comment]
I like it! Are there any downsides?

**Comment by saivan** [comment]
I'm actually thinking @svgjs is a better organisation name though :P not loving the dot.

**Comment by Fuzzyma** [comment]
No downsides (well - the user needs to type more: `npm install @svgdotjs/svg.js`.

I would also prefer to have npm org and github org names as the same

**Comment by Fuzzyma** [comment]
Ok - I went ahead and created the @svgdotjs organisation on npm. I have to figure out how all of this works but it doesnt seem to be that hard :)

**Comment by saivan** [comment]
So this is done, lets close it
