### ISSUE TITLE
How can i remove all drawed elements on SVG?

### ISSUE THREAD

**Issue by tifDev** [svgdotjs/svg.js#930]
## Explanation

- What is the behaviour you expect?
I expect to run a function to clear the elements drawed/added on SVG

In my code I create an svg element with a background img:
```
    const drawHouseImg = SVG( 'houseImg' );
drawHouseImg .image( './images/house.jpg' );

```

Then i have a function that draws round points on the SVG:
```

function drawPoints( pX, pY)
{
    drawHouseImg .circle( 7 ).fill( '#00FF00' ).move( pX, pY );    
} 
```

The result of the element's HTML with some circle's drawed is like this:

```
<div id="shotNetSVGht" >
   <svg id="SvgjsSvg1019" width="100%" height="100%" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:svgjs="http://svgjs.com/svgjs">
      <defs id="SvgjsDefs1020"></defs>
      <image id="SvgjsImage1026" xlink:href="./images/net.jpg" width="630" height="265" x="0" y="0"></image>
      <circle id="SvgjsCircle1054" r="3.5" cx="481.5" cy="136.5" fill="#00ff00"></circle>
      <circle id="SvgjsCircle1056" r="3.5" cx="281.5" cy="36.5" fill="#00ff00"></circle>
   </svg>
</div>
```

**So i want to delete all the _circle_ elements generated dinamically , how can i do it?**

**Comment by Fuzzyma** [comment]
As you can see yourself, thats neither an issue not a feature request. So this is best asked in [stackoverflow](https://stackoverflow.com).

To delete elements you can use `delete()`. To delete the circled, save same in an array and delete them.
You can also select them dynamically and remove them together: `drawHouseImage.select('circle').remove()`

**Comment by tifDev** [comment]
Ok sorry for that, and thanks for your answer
