### ISSUE TITLE
Rename Doc to SVG

### ISSUE THREAD

**Issue by Fuzzyma** [svgdotjs/svg.js#932]
Currently the `Doc` object is representing the `<svg>` tag. Since `Nested` got removed, Doc is used for both. It would make sense to go with the normal naming scheme of the libraray and aname the object `Svg` instead. As I know  @saivan is a friend of this idea. So am I.

What do you think @wout @dotnetCarpenter ?

**Comment by wout** [comment]
Good for me. It's more in line with the rest of the class names and it's the ideal time to re-evaluate such inconsistencies.

**Comment by Fuzzyma** [comment]
Just pushed the change.

However, one more thought: does it make sense to rename the `doc()` method to `root()`?
I dont have a strong opinion to either of these. So if noone cares we just let it as it is

**Comment by wout** [comment]
I think it makes perfect sense!

**Comment by Fuzzyma** [comment]
Well in that case I will go ahead and change that, too

**Comment by saivan** [comment]
Yes pleaseeeeeeeeeeeeeee 😀
