### ISSUE TITLE
loop() missing in Animation interface

### ISSUE THREAD

**Issue by ivanriotlysocial** [svgdotjs/svg.js#934]
https://svgjs.com/docs/2.7/animating/#loop
Getting `TS2339: Property 'loop' does not exist on type 'Animation'.` while trying to use it:
`circle.attr('r', outterRadius).animate(2000, '<>').attr('r', outterRadius+20).loop();`
without `.loop()` animation works good.
versions tried: 2.6.6, 2.7.0

**Comment by Fuzzyma** [comment]
Are you talking about TypeScript?
If so, the typings for svg.js are not complete. Feel free to dive into the svg.d.ts file and add what you need.
Of course it would be great if you could open a Pull Request with the fixes!
