### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by danyill** [svgdotjs/svg.js#940]
In https://svgjs.com/docs/2.7/installation/

The download links:

* svg.js [for development] - lots of comments
* svg.min.js [for production] - ±16k when gzipped

Are both broken.

**Comment by Fuzzyma** [comment]
Thanks for the report. Yes the master branch changed yesterday. For now you have to download the files from the 2.x branch until we fix this.

However, we releases 3.0 yesterday. You can install it with npm. If you want to download it, take a look at the [3.0.0 Release](https://github.com/svgdotjs/svg.js/releases/tag/3.0.0). You can download a zip with all needed files there :)

**Comment by wout** [comment]
This has been fixed. 2.x files are now referenced from CDN.js.
