### ISSUE TITLE
Documentation landing page examples not working

### ISSUE THREAD

**Issue by jacobus** [svgdotjs/svg.js#941]
Hi, just letting you know that two of the examples in your docs landing page are not working.

https://svgjs.com/docs/2.7/

Cheers,
Jack

**Comment by saivan** [comment]
@Fuzzyma Do these docs always point at master perhaps?

**Comment by Fuzzyma** [comment]
Its because the fiddles with the example use rawgit as cdn to get the SVG Version. And rawgit never points to a specific version.
Rawgit is deprecated anyway. So we can swap it with cdn.js or jsdelivr

**Comment by wout** [comment]
I'll switch over to cdnjs. Did anyone already create a pull request for a 3.0 version there?

**Comment by wout** [comment]
@Fuzzyma Maybe even a section in the docs. I'll try to fix something today.
