### ISSUE TITLE
How to get new version? I see only 2.7.1 in my package.json

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.js#949]
I can't put version 3.0.5 in to my package.json. I get information that only 2.7.1 I can choose

![image](https://user-images.githubusercontent.com/13883511/50735290-effea180-11ac-11e9-9e5b-dcc8b83cbf6b.png)

**Comment by chenz24** [comment]
I installed v3.05.  but import SVG from '@svgdotjs/svg.js';  got error.  when I use v2.7 , it work fine.
when I switched to v3, import did not work properly. I don't know why

**Comment by Fuzzyma** [comment]
Without code I can't help much :/

**Comment by Fuzzyma** [comment]
Fixed with latest release
