### ISSUE TITLE
Cannot read property 'extract' of undefined on animation rotation

### ISSUE THREAD

**Issue by biandtlp** [svgdotjs/svg.js#950]
Hello,

i've tried to animate a wheel after stopped it inside a "during" callback:

this.animation.during(function(pos, morph, eased, situation) {

    if (pos >= 0.8 && numwin) {

      `numwin = (numwin * this.angleValue) * (-1);`

      self.groupGraph.stop(false, true);

      self.groupGraph.animate(2000, '>').rotate(numwin);
    }

and this cause this stack trace:

> Uncaught TypeError: Cannot read property 'extract' of undefined
>     at create.eachAt (svg.js:1962)
>     at create.step (svg.js:1866)
>     at create.<anonymous> (svg.js:1450)

If i try the same thing without "during" everything works fine.

Fiddle example: [http://jsfiddle.net/803yp4cw/1](url)

**Comment by Fuzzyma** [comment]
When you stop an animation in the during callback, we check that aber the callback is finished. However, you start the next animation right away and that I assume that leads to the error.

Let the code handle the stop first and delay the start of the next animation to the end of the event queue by using `setTimeout(fn, 0)` where fn is a function calling animate.

**Comment by biandtlp** [comment]
it worked! thank you so much Fuzzyma
