### ISSUE TITLE
Document how to use old plugins with 3.0

### ISSUE THREAD

**Issue by iongion** [svgdotjs/svg.js#952]
Because of a text bug, I need to use 3.0, but now, none of the plugins work because they need to find global object SVG, what can be done to overcome this ?

I have tried creating a wrapper:

```
import * as SVG from '@svgdotjs/svg.js/src/svg';

global.SVG = SVG;
window.SVG = SVG;

export default SVG;
```

But then, there is no `SVG.extend`

**Comment by Fuzzyma** [comment]
The file you are importing exports one default object: The object which was global in svg.js v2.
So a simple correction is everyhing you need:

```js
import SVG from '@svgdotjs/svg.js/src/svg';
```

That should work

**Comment by tingshuai** [comment]
I have got the same problem，
1,  that's how i import svg.js and the plugins;
![2d7ed9f7-1ce2-4add-bff6-fdb3a9eb7df9 bmp](https://user-images.githubusercontent.com/23158246/51750308-a985ce00-20ec-11e9-8738-d1f92c2960f1.jpg)
2. that's the errors
![2019-01-25 220313](https://user-images.githubusercontent.com/23158246/51750433-0c776500-20ed-11e9-87a8-83926552ba5c.jpg)

**Comment by Fuzzyma** [comment]
You could have copied code and error message. No need to send images.


Only the plug-ins which were uodated for 3.0 can be used as esm import. Draggable was updated. But you don't use the new version. Try `npm install @svgdotjs/svg.draggable.js`.

**Comment by Fuzzyma** [comment]
Important note: the draggable plugin was published under the old name by accident.
More Infos here: https://github.com/svgdotjs/svg.draggable.js/issues/103

**Comment by tingshuai** [comment]
thanks a lot;
I hava got that; so I installed the version 2.7.1 。
now, I installed the svg.draggable.js version of 2.2.2; it work well;
but unfortunately；I found that when i use svg.select.js at the same time; the draggable.js does'nt work and not report error;

this is code :
`var draw = SVG('app');`
`var rect = draw.rect(100,100);`
`rect.draggable()`
`rect.selectize();`

**Comment by Fuzzyma** [comment]
There is a css file in the svg.select.js dist folder. Include it and it should work

**Comment by tingshuai** [comment]
as you said ; it's ok now; 
thanks all of your help and my poor english; 
good night;

**Comment by bradleybeighton** [comment]
How would I implement svg.draw.js with @svgdotjs/svg.js 3.0.12?

**Comment by Fuzzyma** [comment]
You dont, it doesnt work. Yoou can update the plugin and make it work though

**Comment by bradleybeighton** [comment]
Thanks for the quick reply! Is the plan for it to work at some point in the future or is svg.draw.js no longer supported? If not is there a timeline for the plugins?

**Comment by Fuzzyma** [comment]
I cant give you a time. But at some point they surely will get an update

**Comment by hoangtd185** [comment]
Hello, I'm having the same error. Since I want to use svg.draw.js, svg.select.js, svg.resize.js and svg.draggable at the same time. So on the  svg.js version 3.0 I can't use svg.draw.js right ?

**Comment by Fuzzyma** [comment]
Exactly - as stated above

**Comment by JanMisker** [comment]
I had a look and it turned out the only real change was to use SVG.List instead of SVG.Set, so I made a PR: https://github.com/svgdotjs/svg.draw.js/pull/48
