### ISSUE TITLE
Not working on Safari and Firefox

### ISSUE THREAD

**Issue by LeonGatt** [svgdotjs/svg.js#955]
I've got a done animation and all working on Chrome( 72.0.3626.96 ), but it is not working on safari(12.0.2) and firefox(66.0b5). 
I'm using just
```
var el_01 = SVG.get('my_rotation_01')
    el_01.animate(400000, '-').rotate(-365, '50%', '50%').loop()
```
and here I'm getting 

```
<svg  id="my_rotation_01">
...
</svg>
```

On Chrome it works, but on safari is showing transform="matrix(...)" but it is showing a static SVG and on Firefox there is nothing going on. 
Can u give me please some tips?
Thank you!

**Comment by Fuzzyma** [comment]
Try using no percentages and instead absolute numbers. Also create a jsfiddle showing your issue.
