### ISSUE TITLE
loop or reverse does not work animating a relative scale trasform

### ISSUE THREAD

**Issue by clodprogea** [svgdotjs/svg.js#958]
for example the following code :

     control.animate(100).transform({ scale: 1.2, relative: true }).loop(1, true);

will scale the control up but it won't reverte it back with loop
Removing the 'relative' then it works : 

     control.animate(100).transform({ scale: 1.2 }).loop(1, true);

I need to use relative because the control can be scaled by other pieces of code

**Comment by Fuzzyma** [comment]
Which version do you use?

**Comment by clodprogea** [comment]
the latest, just downloaded and retested again

**Comment by Fuzzyma** [comment]
Pardon that I ask but what do you consider as the latest version?

**Comment by clodprogea** [comment]
svg.js v2.7.1

**Comment by clodprogea** [comment]
I'd like also to know if there is a way to revert an animation, I searched in the doc but I could't find a way, maybe I'm missing something. I would like to animate a element like : 

var animated = control.animate(100).transform({ scale: 1.2, relative: true });

and I miss something like : 

animated.revert();


thanks

**Comment by Fuzzyma** [comment]
2.7.1 is the last version of 2.x. However, we released 3.0 some time ago. Its installable via `npm i @svgdotjs/svg.js`. There your code should work.
In 2.x animating transformation properties always had some issues which cant be really fixed with the architecture of version 2. 

You can reverse the direction of an animation by calling reverse()

**Comment by clodprogea** [comment]
ok, I'm moving to version 3 but I've found some breaking changes, and the doc refers to version 2.7.1 as far as I understand... for example the SVG.select is not available anymore... is there any updated doc for versione 3 or a list or breaking changes ?

thanks

**Comment by Fuzzyma** [comment]
Unfortunately the documentation is not up to date yet. We are working on it. You can find a lot of examples on twitter where we posted code to show the new behavior. For all the changes you can also take a look into the changelog.

To your specific quuestion: `SVG.select()` was replaced with `find()`. It does the same thing but returns a new `SVG.List` which is far more consistend then the old `SVG.Set`. Everything you can do to an elemen you can also do to a list. Even when you get a value via a getter e.g. `id()` you get back a list with all ids

**Comment by clodprogea** [comment]
thank you for your support, after puzzling with no docs through the sources I've found a breaking change in version 3.
I use the find() to get some SVG elements, when find is used to return a SVG ForeignObject it returns a DOM object which cannot be animated. While with version 2.7.1 it was working

the adopter.js cannot adopt to any other elements since foreignobject is not in the available elements

**Comment by Fuzzyma** [comment]
ForeignObject is an own element, right? I know its not in the core but when you do: 

```js
import {Element, nodeOrNew, register} from `@svgdotjs/svg.js`

class ForeignObject extends Element {
  constructor (node) {
    super(noreOrNew(node, 'foreignObject))'
  }
}

register(ForeignObject)
```

It should be enough to make it work with `find` and `animate`.
However, **children** of the foreignObject are not svg elements and therefore covered by the `Dom` class which has no animation capability

**Comment by clodprogea** [comment]
ok, are you going to push sources with foreignobject ?

**Comment by Fuzzyma** [comment]
What do you mean by "push sources"?

**Comment by clodprogea** [comment]
It you are going to update the sources including this change of the foreignobject

**Comment by Fuzzyma** [comment]
Mh... good question. I think its worth to put it in the core. I dont know when I have time for that - hence the quickfix

**Comment by clodprogea** [comment]
I finally managed to move to version 3 and I can confirm the original issue : 

animate with relative does not work as : 
```
control.animate(100).transform({ scale: 1.2, relative: true }).loop(1, true);
```


Removing the 'relative' then it works :


```
 control.animate(100).transform({ scale: 1.2 }).loop(1, true);
```

**Comment by Fuzzyma** [comment]
I am not sure what you try to achieve. When you loop ONCE it will only do one cycle. Nothing more. What should happen there? 
I tried both versions of your code and they do exactly the same as I would expect:
https://jsfiddle.net/Fuzzy/adq9x15n/2/

**Comment by clodprogea** [comment]
ok, thanks for the sample, looping with 2 works as I expected : 

const canvas = SVG().addTo('body').size('100%', '100%')

const rect = canvas.rect(100, 100).move(100, 100)

rect.on('mouseover', function (e) {
	rect.animate(100).transform({ scale: 1.2, relative: true }).loop(2, true);
});



I'm also trying to figure out how to revert back an animation, I tried this : 

const canvas = SVG().addTo('body').size('100%', '100%')

const rect = canvas.rect(100, 100).move(100, 100)

var animate;

rect.on('mouseover', function (e) {
animate = rect.animate(100).transform({ scale: 1.2, relative: true });
});

rect.on('mouseout', function (e) {
animate.reverse();
});

what I would like is to apply an animation and then reverte it back when I need it to

**Comment by Fuzzyma** [comment]
What you want might be `reset()`

**Comment by clodprogea** [comment]
ok thanks
