### ISSUE TITLE
Line animation with plot and percentage values?

### ISSUE THREAD

**Issue by janstieler** [svgdotjs/svg.js#972]
Hi,
I don't really sure if this is a bug, but it looks like.

If I have a line with percentage positions I can't use plot to animate this line.
```
var lineXX = draw.line('32%', '14%', '25%', '30%').stroke({ width: 20 }).id('lineXX');
lineXX.animate(1500, '>', 2000).plot(50, 30, 100, 150);
```
also
```
var lineZZ = draw.line('32%', '14%', '25%', '30%').stroke({ width: 20 }).id('lineZZ');
lineZZ.animate(1500, '>', 2000).plot('60%', '14%', '35%', '50%');
```
produce the error values in the attributes `x1, y1, x2, y2` like `30%NAN`.
The lines for it self are drawn perfectly with the percentage values.

The only constellation what is working is
```
var lineYY = draw.line(50, 30, 100, 150).stroke({ width: 20 }).id('lineYY');
lineYY.animate(1500, '>', 2000).plot('32%', '14%', '25%', '30%');
```

https://jsfiddle.net/qeoLd49w/

Does anybody know if its really a bug or how can I use percentages on `.line()` and `.plot()`?

Cheers

**Comment by Fuzzyma** [comment]
Percentage values are tricky but they SHOULD be animatable. However it could be that the PointArray use them wrong which leads to this issue. Can you test if this issue arises with v3, too?

The code would be:

```js
lineZZ.animate(1500, 2000).ease('>').plot('60%', '14%', '35%', '50%');
```

**Comment by janstieler** [comment]
Hi,
with the v3 I have a lot of problems because I use the old version.
Here I get no SVG-Container drawn in my Div with the error `Cannot read property 'size' of null`.
But the svg libary is loaded.
https://jsfiddle.net/hrvamt4b/

Your `.ease()`is not referenced in the documentation. There are also for the v3 my writing style declared. Is it not updated yet?

**Comment by Fuzzyma** [comment]
I fixed the fiddle: https://jsfiddle.net/Fuzzy/v9c0q6yk/1/

However, it seems percentage values doesnt work anway. Hope we can fix that some day. Animations are onl done with numbers. It will be hard to make percentages and units in general work

**Comment by janstieler** [comment]
Hi,
thanks! 

Okay than I have to use px.

`SVG().addTo('#artboard')` is this now in v3 the standard notation?
Than it needs to update the docs under `Getting started`.
What I also noticed on the documentation is if you call https://svgjs.com its loaded the v2.7 manual and not the v3.0.

best

**Comment by Fuzzyma** [comment]
see #954 and #948 for that issue
