### ISSUE TITLE
how to create a blinking fill color animation

### ISSUE THREAD

**Issue by clodprogea** [svgdotjs/svg.js#975]
I'm trying to create an animation which blinks between two colors merging color1 to color2 

I tried for example : 
// create your example here
var rect = canvas.rect(100, 100);
rect.move(100, 100).fill('blue');

rect.animate(3000).fill('blue').fill('red').loop(true, true);

using version 3

**Comment by Fuzzyma** [comment]
Why do you fill blue AND red? You can only animate to one color. It takes the current color as a start.
Furthermore we cannot morph keywords, only values. So use hex colors here:

```js
rect.fill('#00f').animate(3000).fill('#f00').loop(true, true)

**Comment by clodprogea** [comment]
ok, I've prepared an example, it works with version 2.7.1, but it doesn't with version 3.0.12

https://jsfiddle.net/Fuzzy/s06mfv5u

**Comment by Fuzzyma** [comment]
Thats the wrong link ;)

**Comment by clodprogea** [comment]
hhooopss, sorry, 

https://jsfiddle.net/anm3rcz5/1/

**Comment by Fuzzyma** [comment]
https://jsfiddle.net/Fuzzy/xafz20Lb/

**Comment by clodprogea** [comment]
yup

**Comment by 0xNF** [comment]
> Furthermore we cannot morph keywords, only values. So use hex colors here:

I know I'm late to the comment thread on this one, but I wish this was more clear from the documentation. I spent days wondering why I could use `shape.fill("red")` but not `shape.animate().fill("red")` and only figured it out due to this thread.
