### ISSUE TITLE
textPath.track() is not a function

### ISSUE THREAD

**Issue by PiotrFr** [svgdotjs/svg.js#976]
# Bug report

## Fiddle

https://jsfiddle.net/Piotrf/bokg7tsj/

## Explanation

- What error message are you getting?
text.track is not a function

**Comment by Fuzzyma** [comment]
Thats actually not a bug. The `track()` method was moved from text to textPath. You get back the textPath when you call `text.path()`. Here is a working example: https://jsfiddle.net/Fuzzy/ugv29hL6/1/
