### ISSUE TITLE
 How to Make SVG Adaptive to Width and Height Based on Content ？

### ISSUE THREAD

**Issue by longboquan** [svgdotjs/svg.js#980]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.

**Comment by Fuzzyma** [comment]
You don't. An svg is an image with a size you define. Everything of its content which is bigger than that size is not shown. Of course you can change the size of the svg later after measuring the size of the content e.g. With bbox().

But why you didn't use stackoverflow? You even posted it. This is a question and not a bug or feature!

**Comment by longboquan** [comment]
Thanks very much ！
