### ISSUE TITLE
Property 'width' does not exist on type 'Animation'

### ISSUE THREAD

**Issue by thayesx** [svgdotjs/svg.js#981]
# Bug report

`rect.animate().width()` operates as expected, but is flagged in VSCode due to: "Property 'width' does not exist on type 'Animation'."

## Fiddle

https://jsfiddle.net/thayesx/0up2vLy9/

**Comment by Fuzzyma** [comment]
I guess thats due to a lack of it in the d.ts file. Feel free to open a PR to add it!

**Comment by thayesx** [comment]
Just realized that I'm actually using 2.7.1 instead of 3.x.x. Though I've tried importing 3.x.x into my Angular/TS project but am unable to get it working (seems like a known issue).

Are there any options for contributing to v2.7.1?

**Comment by Fuzzyma** [comment]
A known issue? No, not really. 3.x should work in an angular project.
Ofc you can contribute to 2.x. Just create a PR against the 2.x branch

**Comment by thayesx** [comment]
Never mind. Turns out the issue I was having was due to using `SVG('#id')` instead of `SVG().addTo()`, though the error message led me to think it was a ts issue.

Updating just that line in [the documentation](https://svgjs.com/docs/3.0/getting-started/#create-an-svg-document) would be a huge help. (reference: #954 )

I'm going to migrate up to 3.x so not going to submit a PR for the 2.x version right now. The 2.x bug does still exist

**Comment by Fuzzyma** [comment]
docs are updated now
