### ISSUE TITLE
The 'svg.foreignObject.js' plugin is out of date

### ISSUE THREAD

**Issue by HJWAJ** [svgdotjs/svg.js#982]
I have created a [pull request](https://github.com/memloom-development/svg.foreignobject.js/pull/6) to update the plugin, but it seems the author is no longer maintaining this repo, and he doesn't reply me till now. 

Could my changes be set [here](https://svgjs.com/docs/3.0/plugins/svg-foreignobject-js/) directly? What more should I do? Thanks very much!

**Comment by Fuzzyma** [comment]
Foreign object is already in the core of 3.x so no need to include it :)

**Comment by cr1t** [comment]
Is there some documentation on how to use the foreignObject now that it is part of the core svg.js

**Comment by Fuzzyma** [comment]
Not yet, but there is no magic in using it. Just call foreignObject(width, height) and add elements to it with add or put like for any other element

```js
canvas.foreignObject(100, 100).add(someNode).add('<input type="text">')...
```
