### ISSUE TITLE
SVG object with hsl-defined color is rendered black if animate is called

### ISSUE THREAD

**Issue by ctlaux** [svgdotjs/svg.js#983]
# Bug report

When defining an SVG object (e.g. a circle) with a stroke color given as HSL, and then animating a change of attributes, the object is initially painted black instead of the given color.

This is for svg.js version 2.7.1

## Fiddle

https://jsfiddle.net/m1stkg8z/

**Comment by Fuzzyma** [comment]
Neither 2.x nor 3.x can read hsl strings. But 3.x understands hsl. The fact, that it cant read the string is a failure of our site.

So you cannot do that in 2.x but in 3.x you can at least do something similar shown here:
https://jsfiddle.net/Fuzzy/Latepcgk/4/

Its important to note, that svg.js always animates in the colorspace you provided as the destination!

**Comment by ctlaux** [comment]
Ok, I didn't realise that, thanks. On a side note: how come 3.x is not available as an npm package? npm only lists version up to 2.7.1

**Comment by Fuzzyma** [comment]
Yes, thats because we moved to an org on npm. You have to type: `npm i @svgdotjs/npmjs`
