### ISSUE TITLE
svg.js is so good, but I cannot use it because of the version conflicts and few docs

### ISSUE THREAD

**Issue by agongdai** [svgdotjs/svg.js#984]
I really love svg.js. It's simple and exactly what I am looking for for a really long time.

The scenario I want to implement is: allow user to draw a rectangle on an image, then he can drag/resize/move/remove/tag it.

svg.js provides [a list of plugins](https://svgjs.com/docs/2.7/plugins/) which implement what I need separately. However, the version conflicts is driving me crazy.

Here are the svg.js versions these plugins require:

 - svg.draggable.js: >= v3.0.10 
 - svg.draw.js, svg.resize.js and svg.select.js: cannot work for version < 3.

There seems a big jump from version 2.x to 3.x. Even the base syntax is different (`new SVG('canvas')` => `SVG().addTo('#canvas')`), and I could not find this syntax before digging the GitHub issues.

I guess there is a migration moving the name space to `svg.select.js` to `@svgdotjs/svg.select.js`. But at this moment, I cannot use svg.js for my application.

If any developer can help to clarify the status of svg.js, that really helps me a lot. Thanks.

**Comment by Fuzzyma** [comment]
A jump from 2.x to 3.x is a major version change also called a **breaking change** which by definition can and most likely WILL break your old code. This is better described here: https://github.com/semver/semver/blob/master/semver.md

The plugins you specify can all together only be used with svg.js v2.x.
The single plugin on your list which was updated for use with svg.js v3.x is svg.draggable.js.

If you want a working setup use:

```
npm i svg.js svg.select.js svg.resize.js svg.draw.js svg.draggable.js svg.draggable.js@2.x
```

The last bit (@2.x) is duo to a mistake I made when publishing the plugin

**Comment by agongdai** [comment]
@Fuzzyma, great thanks for the clarifications.

Here https://github.com/svgdotjs/svg.draggable.js says:

 > This module requires svg.js >= v3.0.10

So i thought it's not supporting svg.js < 3.

**Comment by Fuzzyma** [comment]
Yes, the current master requires that. The readme is only valid for the current version. If you go back in time you will see that the readme changes

**Comment by merraysy** [comment]
Still the `svg.draggable.js@2.2.2` is incompatible with `svg.js@2.7.1`.

For example the v2.2.2 of the draggable plugin assumes that `Dom#parent` takes a type argument which is not the case in the v2.7.1
