### ISSUE TITLE
How does the official github demo work

### ISSUE THREAD

**Issue by crazyu** [svgdotjs/svg.js#986]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
How does the official github demo work? readme.md only introduce the command of download，please tell me

**Comment by Fuzzyma** [comment]
**For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
