### ISSUE TITLE
12/5000   Please make more examples for reference

### ISSUE THREAD

**Issue by crazyu** [svgdotjs/svg.js#987]
> **For support questions, please use [stackoverflow](https://stackoverflow.com/questions/tagged/svg.js) with the tag svg.js or head to our chat over at [gitter](https://gitter.im/svgdotjs/svg.js), if you have a bug report or feature request, use those templates**.
12/5000  
Please make more examples for reference

**Comment by Fuzzyma** [comment]
svgjs.com
