### ISSUE TITLE
 Angular 7-problem with the transition to prodaction

### ISSUE THREAD

**Issue by ssamikk** [svgdotjs/svg.js#989]
ng serve works great
But ng serve --prod gives the following error in the browser console

`core.js.pre-build-optimizer.js:15724 ERROR TypeError: Sn[e] is not a constructor`
`    at Tn (svg.min.js:2)`
`    at Mn (svg.min.js:2)`
`    at ur (svg.min.js:2)`
`   at e.value (svg.min.js:2)`
`  at e.<anonymous> (svg.min.js:2)`
` at e.image (svg.min.js:2)`

**Comment by Fuzzyma** [comment]
I have no idwa what these commands are supposed to do. I guess it's some kind of build system? Most likely your uglifier destroys variable names in production mode

**Comment by ssamikk** [comment]
https://stackoverflow.com/questions/55195643/svg-js-angular-7-3-build-in-production-mode-get-not-a-constructor

Here you offer to upgrade from the repository.

**Comment by Fuzzyma** [comment]
I guess in that case it's a different problem. But an angular error and angular commands don't help me to solve it.
Pretty sure it has something to do with the minifier. But beside that...

**Comment by ssamikk** [comment]
Thanks for the answer.

**Comment by ssamikk** [comment]
Solved the problem by adding a dependency in index.html instead of angular.json
