### ISSUE TITLE
SVG.get(id) is not a function

### ISSUE THREAD

**Issue by top-dev830** [svgdotjs/svg.js#991]
I'm using @svgdotjs/svg.js in Vue.js

I've imported svg.js like this.
import {SVG} from '@svgdotjs/svg.js';

This works fine
And I've added id for each elements I created.
I want to get SVGElement from the id with this code.

var element = SVG.get(id);

but this shows an error: 'Uncaught TypeError: _svgdotjs_svg_js__WEBPACK_IMPORTED_MODULE_4__.SVG.get is not a function'

I want someone help me.
Thanks.

**Comment by Fuzzyma** [comment]
Use `SVG('#myId')`

**Comment by top-dev830** [comment]
Thanks.

**Comment by top-dev830** [comment]
Sorry, this wasn't my solution.
This requires the id of html5 dom element, but I want to get SVG element which is created by SVG.js

**Comment by Fuzzyma** [comment]
I have no idea what you are talking about. SVG('#id') gives you back whatever element has this id

**Comment by top-dev830** [comment]
I've set id to svg element.
var group = this.canvas.group();
group.attr('id', id);

I want to get this group with id.

**Comment by Fuzzyma** [comment]
Did you even try the code I posted? Because that's what you need to do in order to achieve what you want!

**Comment by henriquegavabarreto** [comment]
I ran into the same issue using 3.0.
`SVG('#myId')` didn't work, but `SVG(document.getElementById('#myId'))` did.

**Comment by Fuzzyma** [comment]
Please post a jsfiddle showing the issue

**Comment by FrontSide** [comment]
> Use SVG('#myId')

How come this is not in the official documentation under "Referencing Elements". It seems such an important and basic functionality.

**Comment by Fuzzyma** [comment]
Its in the getting started section: https://svgjs.dev/docs/3.0/getting-started/
