### ISSUE TITLE
Run the bbox function on a group in nodejs, it sometimes returns a zero value.

### ISSUE THREAD

**Issue by leesc81** [svgdotjs/svg.js#993]
# Bug report

## Fiddle
https://jsfiddle.net/SooChangLee/9wck4v3z/

## Explanation
The problem does not appear in the browser, but in nodeJS, the result of the bbox function in the first group is zero.(The fiddle works fine.)

Run the bbox function on a group in nodejs, it sometimes returns a zero value.
I use svg.js 2.7.1, svgdom 0.0.20 on nodeJS.

run the bbox () function on a child group of an svg file, most groups return the correct result, but one group returns zero.

{
  w: 0,
  h: 0,
  x2: 0,
  y2: 0,
  cx: 0,
  cy: 0,
  x: 0,
  y: 0,
  width: 0,
  height: 0 
}

**Comment by Fuzzyma** [comment]
So that is an issue with svgdom and not svg.js and should be opened there.

To be able to debug this, I need an easy example where the bbox calculation is wrong.
I would say the files you are loading from amazon s3 are the exact opposite of easy :D.

**Comment by leesc81** [comment]
Thanks for the quick reply.
Sorry. I did not know where the problem was in the past.
Your answer is to upload the same content to svgdom github?

**Comment by leesc81** [comment]
I posted the same thing on svgdom github.

Thank you.

**Comment by Fuzzyma** [comment]
No, since I maintain both repositories it doesnt matter now. What I need is an easy example where this problem occurs and not a mega file where I get lost.
You have to know, that I need to do step by step debugging for this and I cannot step trough thousands and thousands of nodes only to miss the wrong one. Thats just not possible (believe me I tried).
So an easy svg  example would be great!

**Comment by Fuzzyma** [comment]
>I posted the same thing on svgdom github.
lol ok I was to late^^

**Comment by leesc81** [comment]
Thank you for your kind and quick reply.

okay
I closed the issue posted to svgdom, and I will continue talking here.

I wanted to reproduce the problem as simple as possible, but I could not reproduce it more easily than the source of fiddle.

Is there a problem loading images uploaded to awss3?

Let me tell you how to reproduce the problem.
There are 10 groups in the svg file.

Invoke the bbox () function on an individual group.

Only 9 of the groups is returning fine value, but f1 group is returning zero value.
**(The problem occurs in the first group)**

Sorry for my English.

**Comment by Fuzzyma** [comment]
Yes, but this first group consists of over 20000 Nodes!! No way I can debug that!

**Comment by leesc81** [comment]
Is the number of nodes a problem?
Do you know the cause?

So if divide the node into smaller pieces and merge it, will that solve the problem?

I'll try it ...

Thank you.

**Comment by Fuzzyma** [comment]
The bbox calculation of groups happens by going through all nodes in the group and calculate their bbox and transform them if needed. So theoretically it SHOUld be enough when you verify that the paths in the group have a zero box, too. But I actually do not think thats the cause. Nevertheless it has to be checked first. If these paths are all NOT zero then I have to figure out at which place the Box is nulled.

So simply said: Yes, having significantly less paths in the group helps. I would say a maximum would be 10. But maybe you can verify first, that these paths indeed have no zero box. That would help!
