### ISSUE TITLE
Example code in Getting Started is broken

### ISSUE THREAD

**Issue by broofa** [svgdotjs/svg.js#998]
https://svgjs.com/docs/3.0/getting-started/#create-an-svg-document

`var draw = SVG('drawing').size('100%', '100%')`

Should read ...

`var draw = SVG('#drawing').size('100%', '100%')`

**Comment by Fuzzyma** [comment]
Please search through the old issues first. The docs are not up to date and we are aware of that. Solutions are in said issues.

**Comment by broofa** [comment]
After a bit of searching I found https://github.com/svgdotjs/svg.js/issues/948#issuecomment-450647545, but expecting newcomers to find the right incantation for the _very first line of code they need to write_ in a comment in a closed issue is not very... uh... shall we say "friendly".

At a minimum, there should be an open issue for tracking the various tasks needed for updating the docs, and some sort of top-level comment about that in the README. "Docs are coming soon.  See issue #XXX for details".   Incorrect documentation is worse than no documentation.

My apologies if I'm being ungrateful.  Just trying to help by providing first-impression feedback.  Cheers.

**Comment by Fuzzyma** [comment]
That's Completely correct. Actually I wanted to wrote something like this into the Readme some time ago and forgot about it.
Will do that as soon as I find some time. Or create a PR for the Readme. That would be welcome too!
